var searchData=
[
  ['facing_20step_202d_0',['Facing Step 2D',['../examples.html#autotoc_md261',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md263',1,'Forward Facing Step (2D)']]],
  ['failed_1',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md630',1,'']]],
  ['fails_2',['Fails',['../troubleshooting.html#autotoc_md598',1,'Build Fails?'],['../troubleshooting.html#autotoc_md599',1,'Run Fails?'],['../troubleshooting.html#autotoc_md600',1,'Test Fails?']]],
  ['fails_20with_20gpu_20openacc_20errors_3',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md631',1,'']]],
  ['failure_20traps_4',['Silent-Failure Traps',['../gpuParallelization.html#silent-failure-traps',1,'']]],
  ['failures_5',['Failures',['../contributing.html#autotoc_md122',1,'Common CI Failures'],['../troubleshooting.html#autotoc_md620',1,'Understanding Test Failures']]],
  ['false_20preston07_6',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md167',1,'']]],
  ['families_7',['Parameter Families',['../parameters.html#autotoc_md421',1,'']]],
  ['fd_5forder_201_202_204_8',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md208',1,'']]],
  ['feature_20compatibility_9',['Feature Compatibility',['../case_constraints.html#feature-compatibility',1,'📊 Feature Compatibility'],['../case.html#autotoc_md19',1,'Feature Compatibility'],['../physics_constraints.html#autotoc_md525',1,'Feature Compatibility']]],
  ['fetching_20mfc_10',['Fetching MFC',['../getting-started.html#autotoc_md373',1,'']]],
  ['fewer_20ranks_11',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md613',1,'']]],
  ['fft_20output_12',['FFT Output',['../physics_constraints.html#autotoc_md547',1,'']]],
  ['field_20setup_13',['10. Velocity Field Setup',['../case.html#sec-velocity-field-setup',1,'']]],
  ['figure_20of_20merit_3a_20grind_20time_20performance_14',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md362',1,'']]],
  ['file_20parameters_15',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md553',1,'']]],
  ['files_16',['Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md15',1,'Case Files'],['../troubleshooting.html#autotoc_md619',1,'Regenerating Golden Files']]],
  ['files_17',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md643',1,'']]],
  ['files_20across_20a_20re_20run_18',['Probe files across a re-run',['../examples.html#autotoc_md292',1,'']]],
  ['final_20condition_19',['Final Condition',['../examples.html#autotoc_md268',1,'Final Condition'],['../examples.html#autotoc_md304',1,'Final Condition'],['../examples.html#autotoc_md316',1,'Final Condition'],['../examples.html#autotoc_md345',1,'Final Condition']]],
  ['final_20condition_20and_20linear_20theory_20',['Final Condition and Linear Theory',['../examples.html#autotoc_md302',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md314',1,'Final Condition and Linear Theory']]],
  ['final_20condition_20density_21',['Final Condition Density',['../examples.html#autotoc_md262',1,'Final Condition (Density)'],['../examples.html#autotoc_md264',1,'Final Condition (Density)']]],
  ['final_20conditions_22',['Density Initial and Final Conditions',['../examples.html#autotoc_md252',1,'']]],
  ['final_20time_23',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md343',1,'']]],
  ['find_20a_20fortran_20compiler_24',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md629',1,'']]],
  ['find_20mpi_25',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md628',1,'']]],
  ['finite_20differences_20fd_5forder_201_202_204_26',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md208',1,'']]],
  ['first_20blocks_20all_20other_20jobs_27',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['fits_20together_28',['How the Build Fits Together',['../contributing.html#autotoc_md89',1,'']]],
  ['five_20equation_20model_20model_5feqns_202_29',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['fix_30',['The fix',['../examples.html#autotoc_md294',1,'']]],
  ['flags_31',['Flags',['../cli-reference.html#autotoc_md79',1,'Build Configuration Flags'],['../troubleshooting.html#autotoc_md593',1,'Debugging Flags'],['../expectedPerformance.html#autotoc_md357',1,'Other Optimization Flags'],['../troubleshooting.html#autotoc_md594',1,'Profiling Flags']]],
  ['flang_20amdflang_20known_20issues_32',['AMD flang (amdflang) Known Issues',['../gpuParallelization.html#autotoc_md413',1,'']]],
  ['flow_33',['Flow',['../gpuParallelization.html#autotoc_md390',1,'Data Flow'],['../contributing.html#autotoc_md87',1,'Simulation Data Flow']]],
  ['flow_20parameters_20with_20bubbles_34',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['flow_20visualization_35',['Flow visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md647',1,'Flow visualization']]],
  ['fluid_20material_20s_36',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['fluid_20structure_20interaction_37',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md171',1,'']]],
  ['fluid_5fpp_38',['fluid_pp',['../parameters.html#fluid_pp',1,'']]],
  ['fluid_5fpp_20i_20k_5ftherm_39',['4a. Fourier Heat Conduction (&lt;span class=&quot;tt&quot;&gt;fluid_pp(i)%k_therm&lt;/span&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['fluid_5frho_40',['fluid_rho',['../parameters.html#fluid_rho',1,'']]],
  ['flux_20limiting_41',['18. Flux Limiting',['../equations.html#autotoc_md217',1,'']]],
  ['flux_5fwrt_42',['flux_wrt',['../parameters.html#flux_wrt',1,'']]],
  ['for_20gpus_43',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md403',1,'']]],
  ['for_20optimization_44',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md358',1,'']]],
  ['for_20portability_45',['For Portability',['../docker.html#autotoc_md134',1,'']]],
  ['for_20stiff_20bubble_20dynamics_46',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md206',1,'']]],
  ['force_20history_47',['Immersed-boundary force history',['../case.html#sec-ib-force-history',1,'']]],
  ['force_20on_20a_20thin_20plate_20issue_201849_48',['Immersed-boundary force on a thin plate (issue #1849)',['../examples.html#autotoc_md317',1,'']]],
  ['forces_49',['13. Body Forces',['../case.html#autotoc_md30',1,'']]],
  ['forces_20bf_5fx_20bf_5fy_20bf_5fz_50',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md188',1,'']]],
  ['forcing_51',['Synthetic Turbulence Forcing',['../physics_constraints.html#autotoc_md533',1,'']]],
  ['format_52',['format',['../cli-reference.html#format',1,'']]],
  ['format_20selection_53',['Format selection',['../visualization.html#autotoc_md660',1,'']]],
  ['formatted_20output_54',['7. Formatted Output',['../case.html#sec-formatted-output',1,'']]],
  ['fortran_20block_20constructs_20are_20silently_20dropped_55',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md415',1,'']]],
  ['fortran_20compiler_56',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md629',1,'']]],
  ['fortran_20module_57',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['forward_20facing_20step_202d_58',['Forward Facing Step (2D)',['../examples.html#autotoc_md263',1,'']]],
  ['found_59',['found',['../troubleshooting.html#autotoc_md641',1,'&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;'],['../troubleshooting.html#autotoc_md642',1,'&quot;Variable &apos;X&apos; not found&quot;']]],
  ['found_20on_20hpc_60',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md632',1,'']]],
  ['fourier_20conduction_20convergence_61',['Fourier conduction convergence',['../examples.html#autotoc_md219',1,'1D Fourier conduction convergence'],['../examples.html#autotoc_md241',1,'Axisymmetric Fourier conduction convergence']]],
  ['fourier_20conduction_20convergence_203d_20cylindrical_62',['Azimuthal Fourier conduction convergence (3D cylindrical)',['../examples.html#autotoc_md322',1,'']]],
  ['fourier_20heat_20conduction_63',['Fourier Heat Conduction',['../physics_constraints.html#autotoc_md540',1,'']]],
  ['fourier_20heat_20conduction_20fluid_5fpp_20i_20k_5ftherm_64',['4a. Fourier Heat Conduction (&lt;span class=&quot;tt&quot;&gt;fluid_pp(i)%k_therm&lt;/span&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['fraction_20sum_65',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md501',1,'']]],
  ['framework_66',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['fypp_20and_20gpu_67',['Fypp and GPU',['../contributing.html#autotoc_md105',1,'']]],
  ['fypp_20preprocessing_20failed_68',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md630',1,'']]]
];
