var searchData=
[
  ['s_0',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['safety_1',['Precision and Type Safety',['../contributing.html#autotoc_md95',1,'']]],
  ['sanity_20transformed_20gamma_2',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md397',1,'']]],
  ['saurel08_3',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md170',1,'']]],
  ['scales_4',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['scaling_5',['Scaling',['../examples.html#autotoc_md243',1,'Strong Scaling'],['../examples.html#autotoc_md242',1,'Weak Scaling']]],
  ['scaling_6',['scaling',['../expectedPerformance.html#autotoc_md288',1,'GPU weak scaling'],['../expectedPerformance.html#autotoc_md291',1,'Strong scaling'],['../expectedPerformance.html#autotoc_md287',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_7',['Scaling and Performance test',['../examples.html#autotoc_md241',1,'']]],
  ['scheduler_20notes_8',['Scheduler Notes',['../running.html#autotoc_md469',1,'']]],
  ['schemes_9',['Numerical Schemes',['../physics_constraints.html#autotoc_md431',1,'']]],
  ['schlieren_20at_20final_20time_10',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md216',1,'']]],
  ['schlieren_5falpha_11',['schlieren_alpha',['../parameters.html#schlieren_alpha',1,'']]],
  ['schmidmayer17_20wilfong26_20sec_204_201_208_12',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md175',1,'']]],
  ['script_13',['Step 2: Customizing the script',['../visualization.html#autotoc_md555',1,'']]],
  ['sec_202_202_14',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md148',1,'']]],
  ['sec_202_203_15',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md153',1,'']]],
  ['sec_204_201_16',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md155',1,'']]],
  ['sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md207',1,'']]],
  ['sec_204_201_2010_18',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md179',1,'']]],
  ['sec_204_201_203_19',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md169',1,'']]],
  ['sec_204_201_206_20',['Sec 4 1 6',['../equations.html#autotoc_md166',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md167',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)']]],
  ['sec_204_201_207_21',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md173',1,'']]],
  ['sec_204_201_208_22',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md175',1,'']]],
  ['sec_204_201_209_23',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md178',1,'']]],
  ['sec_204_202_204_24',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md209',1,'']]],
  ['selection_25',['Model Equation Selection',['../physics_constraints.html#autotoc_md413',1,'']]],
  ['selection_26',['selection',['../visualization.html#autotoc_md546',1,'Format selection'],['../visualization.html#autotoc_md538',1,'Timestep selection']]],
  ['selection_20t_20targets_27',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md77',1,'']]],
  ['serial_20data_20output_28',['Serial data output',['../visualization.html#autotoc_md552',1,'']]],
  ['serial_20test_20execution_29',['Serial Test Execution',['../troubleshooting.html#autotoc_md503',1,'']]],
  ['server_30',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md556',1,'']]],
  ['set_20up_31',['Getting Set Up',['../contributing.html#autotoc_md82',1,'']]],
  ['setting_20up_20your_20environment_32',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md554',1,'']]],
  ['setup_33',['Setup',['../case.html#sec-velocity-field-setup',1,'10. Velocity Field Setup'],['../running.html#autotoc_md458',1,'Environment Setup']]],
  ['sh_20viz_34',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md535',1,'']]],
  ['shell_35',['Interactive Shell',['../docker.html#autotoc_md129',1,'']]],
  ['shell_20completion_36',['Shell Completion',['../getting-started.html#autotoc_md309',1,'']]],
  ['shock_203d_37',['IBM Bow Shock (3D)',['../examples.html#autotoc_md250',1,'']]],
  ['shock_20droplet_202d_38',['Shock Droplet (2D)',['../examples.html#autotoc_md226',1,'']]],
  ['shock_20tube_39',['Shock Tube',['../examples.html#autotoc_md260',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md231',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_202d_40',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md252',1,'']]],
  ['shock_20tube_20problem_201d_41',['Lax shock tube problem (1D)',['../examples.html#autotoc_md217',1,'']]],
  ['shu_20osher_20problem_201d_42',['Shu-Osher problem (1D)',['../examples.html#autotoc_md223',1,'']]],
  ['silo_20hdf5_20files_43',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md529',1,'']]],
  ['silo_5fhdf5_20directory_20found_44',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md527',1,'']]],
  ['simple_20bcs_45',['16.1 Simple BCs',['../equations.html#autotoc_md205',1,'']]],
  ['simplex_5fparams_46',['simplex_params',['../parameters.html#simplex_params',1,'']]],
  ['simulation_20algorithm_47',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['simulation_20constraints_48',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md420',1,'']]],
  ['simulation_20data_20flow_49',['Simulation Data Flow',['../contributing.html#autotoc_md86',1,'']]],
  ['simulation_20loop_50',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['simulation_20parameter_51',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md104',1,'']]],
  ['singularity_52',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md128',1,'']]],
  ['six_20equation_20model_20model_5feqns_203_53',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['skeleton_54',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['slicing_55',['3D slicing',['../visualization.html#autotoc_md540',1,'']]],
  ['slurm_20job_56',['Slurm Job',['../docker.html#autotoc_md131',1,'']]],
  ['smoothing_57',['Elliptic Smoothing',['../case.html#autotoc_md23',1,'']]],
  ['soft_20guidelines_58',['Soft Guidelines',['../contributing.html#autotoc_md92',1,'']]],
  ['solver_20core_59',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['solvers_60',['Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md192',1,'15.2 Riemann Solvers']]],
  ['sound_20speed_61',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md428',1,'']]],
  ['source_62',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['sources_63',['Sources',['../physics_constraints.html#autotoc_md437',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md438',1,'Acoustic Sources']]],
  ['sources_20acoustic_5fsource_20true_64',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['spatial_20reconstruction_65',['15.1 Spatial Reconstruction',['../equations.html#autotoc_md188',1,'']]],
  ['specific_20tests_66',['Running Specific Tests',['../troubleshooting.html#autotoc_md502',1,'']]],
  ['speed_67',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md428',1,'']]],
  ['spelling_68',['spelling',['../cli-reference.html#spelling',1,'']]],
  ['splitting_20strang68_20for_20stiff_20bubble_20dynamics_69',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md200',1,'']]],
  ['src_20common_70',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md112',1,'']]],
  ['stage_71',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['standards_72',['Coding Standards',['../contributing.html#autotoc_md90',1,'']]],
  ['started_73',['Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md296',1,'Getting Started'],['../index.html#autotoc_md443',1,'Getting Started']]],
  ['startup_74',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['state_75',['State',['../equations.html#autotoc_md147',1,'3. Equations of State'],['../examples.html#autotoc_md222',1,'Evolved State'],['../examples.html#autotoc_md240',1,'Evolved State'],['../examples.html#autotoc_md254',1,'Evolved State'],['../examples.html#autotoc_md221',1,'Initial State'],['../examples.html#autotoc_md239',1,'Initial State'],['../examples.html#autotoc_md253',1,'Initial State']]],
  ['state_76',['Liutex visualization at transitional state',['../examples.html#autotoc_md237',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_77',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md554',1,'']]],
  ['step_202_3a_20customizing_20the_20script_78',['Step 2: Customizing the script',['../visualization.html#autotoc_md555',1,'']]],
  ['step_202d_79',['Step 2D',['../examples.html#autotoc_md258',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md274',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_80',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md556',1,'']]],
  ['stepping_81',['Stepping',['../case.html#autotoc_md26',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md25',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md434',1,'Time Stepping']]],
  ['stepping_20adap_5fdt_20true_82',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md199',1,'']]],
  ['stiff_20bubble_20dynamics_83',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md200',1,'']]],
  ['stiffened_20eos_20positivity_84',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md396',1,'']]],
  ['stiffened_20gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_85',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md148',1,'']]],
  ['stirred_20reactor_86',['Perfectly Stirred Reactor',['../examples.html#autotoc_md213',1,'']]],
  ['stored_20parameter_20conventions_87',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['strang_20splitting_20strang68_20for_20stiff_20bubble_20dynamics_88',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md200',1,'']]],
  ['strang68_20for_20stiff_20bubble_20dynamics_89',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md200',1,'']]],
  ['stress_20tensor_20viscous_20true_90',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md151',1,'']]],
  ['strong_20scaling_91',['Strong Scaling',['../examples.html#autotoc_md243',1,'']]],
  ['strong_20scaling_92',['Strong scaling',['../expectedPerformance.html#autotoc_md291',1,'']]],
  ['structure_93',['Tag Structure',['../docker.html#autotoc_md134',1,'']]],
  ['structure_20interaction_94',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md165',1,'']]],
  ['structures_95',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['styling_96',['Plot styling',['../visualization.html#autotoc_md545',1,'']]],
  ['sub_20grid_20bubble_20dynamics_20wilfong26_20sec_204_201_97',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md155',1,'']]],
  ['sub_20grid_20bubble_20models_98',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['submitting_20a_20pull_20request_99',['Submitting a Pull Request',['../contributing.html#autotoc_md120',1,'']]],
  ['suite_100',['Running the Test Suite',['../getting-started.html#autotoc_md302',1,'']]],
  ['sum_101',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md401',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_102',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md128',1,'']]],
  ['support_103',['Support',['../docker.html#autotoc_md136',1,'Architecture Support'],['../running.html#autotoc_md455',1,'Building with GPU Support']]],
  ['supported_20compilers_104',['Supported Compilers',['../running.html#autotoc_md457',1,'']]],
  ['supports_105',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['surface_20tension_106',['Surface Tension',['../physics_constraints.html#autotoc_md425',1,'']]],
  ['surface_20tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_107',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md175',1,'']]],
  ['surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_108',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md175',1,'']]],
  ['synchronization_20macros_109',['Synchronization Macros',['../gpuParallelization.html#autotoc_md320',1,'']]],
  ['system_110',['Working with the Precision System',['../contributing.html#autotoc_md109',1,'']]]
];
