var searchData=
[
  ['elasticity_0',['15. Elasticity',['../case.html#autotoc_md29',1,'']]],
  ['elliptic_20smoothing_1',['Elliptic Smoothing',['../case.html#autotoc_md12',1,'']]],
  ['ensemble_20averaged_20bubble_20model_2',['9.1 Ensemble-Averaged Bubble Model',['../case.html#autotoc_md22',1,'']]],
  ['enumerations_3',['Enumerations',['../case.html#autotoc_md32',1,'']]],
  ['environment_4',['Environment',['../getting-started.html#autotoc_md252',1,'Build Environment'],['../visualization.html#autotoc_md469',1,'Step 1: Setting up your Environment']]],
  ['environment_20setup_5',['Environment Setup',['../running.html#autotoc_md394',1,'']]],
  ['equations_6',['🔢 Model Equations',['../case_constraints.html#autotoc_md50',1,'']]],
  ['errors_7',['Errors',['../troubleshooting.html#autotoc_md449',1,'Common Build Errors'],['../troubleshooting.html#autotoc_md456',1,'Common Runtime Errors']]],
  ['errors_8',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md453',1,'']]],
  ['errors_20or_20hangs_9',['MPI errors or hangs',['../troubleshooting.html#autotoc_md460',1,'']]],
  ['evolved_20state_10',['Evolved State',['../examples.html#autotoc_md183',1,'Evolved State'],['../examples.html#autotoc_md199',1,'Evolved State'],['../examples.html#autotoc_md202',1,'Evolved State']]],
  ['example_11',['Example',['../examples.html#autotoc_md209',1,'2D Hardcodied IC Example'],['../examples.html#autotoc_md173',1,'Example']]],
  ['example_20case_12',['Running an Example Case',['../getting-started.html#autotoc_md256',1,'']]],
  ['example_20cases_13',['Example Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md166',1,'Example Cases']]],
  ['example_20runs_14',['Example Runs',['../running.html#autotoc_md409',1,'']]],
  ['example_20tags_15',['Example Tags',['../docker.html#autotoc_md164',1,'']]],
  ['examples_16',['Examples',['../case_constraints.html#autotoc_md43',1,'🔴 Advanced Examples'],['../case_constraints.html#autotoc_md42',1,'🟡 Intermediate Examples'],['../case_constraints.html#autotoc_md41',1,'🟢 Beginner Examples'],['../running.html#autotoc_md403',1,'Examples']]],
  ['examples_20visualization_17',['Examples &amp;amp; Visualization',['../index.html#autotoc_md380',1,'']]],
  ['examples_2emd_18',['examples.md',['../examples_8md.html',1,'']]],
  ['exchange_19',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]],
  ['execution_20',['Execution',['../running.html#autotoc_md400',1,'Batch Execution'],['../running.html#autotoc_md388',1,'Interactive Execution'],['../troubleshooting.html#autotoc_md439',1,'Serial Test Execution']]],
  ['expectedperformance_2emd_21',['expectedPerformance.md',['../expectedPerformance_8md.html',1,'']]],
  ['extend_20mpi_20halo_20exchange_22',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]]
];
