var searchData=
[
  ['backward_20facing_20step_202d_0',['Backward Facing Step (2D)',['../examples.html#autotoc_md255',1,'']]],
  ['base_20images_1',['Base Images',['../docker.html#autotoc_md131',1,'']]],
  ['basic_20skeleton_2',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../running.html#autotoc_md463',1,'']]],
  ['batch_20execution_4',['Batch Execution',['../running.html#autotoc_md462',1,'']]],
  ['batch_20options_5',['Batch Options',['../running.html#autotoc_md464',1,'']]],
  ['bc_5fx_6',['bc_x',['../parameters.html#bc_x',1,'']]],
  ['bc_5fx_20beg_205_20to_2012_7',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md204',1,'']]],
  ['bc_5fy_8',['bc_y',['../parameters.html#bc_y',1,'']]],
  ['bc_5fz_9',['bc_z',['../parameters.html#bc_z',1,'']]],
  ['bcs_10',['16.1 Simple BCs',['../equations.html#autotoc_md203',1,'']]],
  ['bcs_20thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_11',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md204',1,'']]],
  ['beg_205_20to_2012_12',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md204',1,'']]],
  ['beginner_20examples_13',['🟢 Beginner Examples',['../case_constraints.html#autotoc_md39',1,'']]],
  ['bench_14',['bench',['../cli-reference.html#bench',1,'']]],
  ['bench_5fdiff_15',['bench_diff',['../cli-reference.html#bench_diff',1,'']]],
  ['benchmark_20results_16',['Benchmark Results',['../expectedPerformance.html#autotoc_md282',1,'']]],
  ['bf_5fx_20bf_5fy_20bf_5fz_17',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['bf_5fy_20bf_5fz_18',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['bf_5fz_19',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['bibliography_20',['Bibliography',['../citelist.html',1,'']]],
  ['blocks_20all_20other_20jobs_21',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md114',1,'']]],
  ['body_20forces_22',['13. Body Forces',['../case.html#autotoc_md29',1,'']]],
  ['body_20forces_20bf_5fx_20bf_5fy_20bf_5fz_23',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['boundary_20condition_20compatibility_24',['Boundary Condition Compatibility',['../physics_constraints.html#autotoc_md414',1,'']]],
  ['boundary_20condition_20patches_25',['Boundary Condition Patches',['../case.html#boundary-condition-patches',1,'']]],
  ['boundary_20conditions_26',['Boundary Conditions',['../equations.html#autotoc_md202',1,'16. Boundary Conditions'],['../architecture.html#autotoc_md8',1,'Boundary Conditions'],['../physics_constraints.html#autotoc_md413',1,'Boundary Conditions']]],
  ['boundary_20conditions_27',['Boundary conditions',['../case.html#boundary-conditions',1,'Boundary conditions'],['../case.html#autotoc_md35',1,'Generalized Characteristic Boundary conditions']]],
  ['boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_28',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md205',1,'']]],
  ['boundary_20patch_20types_29',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['boundary_20patches_30',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['bounds_31',['Domain Bounds',['../physics_constraints.html#autotoc_md403',1,'']]],
  ['bounds_20and_20indexing_32',['Array Bounds and Indexing',['../contributing.html#autotoc_md92',1,'']]],
  ['bow_20shock_203d_33',['IBM Bow Shock (3D)',['../examples.html#autotoc_md247',1,'']]],
  ['bryngelson20_34',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['bub_5fpp_35',['bub_pp',['../parameters.html#bub_pp',1,'']]],
  ['bubble_20case_36',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['bubble_20dynamics_37',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['bubble_20dynamics_38',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md198',1,'']]],
  ['bubble_20dynamics_20wilfong26_20sec_204_201_39',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md153',1,'']]],
  ['bubble_20model_40',['Bubble Model',['../case.html#autotoc_md27',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md28',1,'9.2 Volume-Averaged Bubble Model'],['../physics_constraints.html#autotoc_md417',1,'Euler-Euler Bubble Model'],['../physics_constraints.html#autotoc_md419',1,'Euler-Lagrange Bubble Model']]],
  ['bubble_20models_41',['Bubble Models',['../case_constraints.html#bubble-models',1,'💧 Bubble Models'],['../case.html#sec-bubble-models',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#compat-bubble-models',1,'Bubble Models']]],
  ['bubble_20physics_42',['Bubble Physics',['../physics_constraints.html#autotoc_md416',1,'']]],
  ['bubble_20simulation_20constraints_43',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md418',1,'']]],
  ['bubble_20users_3a_20non_20dimensional_20framework_44',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['bubble_5fmodel_201_20gilmore52_45',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md158',1,'']]],
  ['bubble_5fmodel_202_20keller80_46',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['bubble_5fmodel_203_20rayleigh17_20plesset49_47',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['bubbles_48',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['bubbles_20bubbles_5feuler_20true_49',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md154',1,'']]],
  ['bubbles_20bubbles_5flagrange_20true_20maeda18_50',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['bubbles_5feuler_20true_51',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md154',1,'']]],
  ['bubbles_5flagrange_20true_20maeda18_52',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['build_53',['build',['../cli-reference.html#build',1,'']]],
  ['build_20and_20test_20matrix_54',['Build and Test Matrix',['../contributing.html#autotoc_md115',1,'']]],
  ['build_20configuration_20flags_55',['Build Configuration Flags',['../cli-reference.html#autotoc_md76',1,'']]],
  ['build_20debugging_56',['Build Debugging',['../troubleshooting.html#autotoc_md486',1,'']]],
  ['build_20environment_57',['Build Environment',['../getting-started.html#autotoc_md296',1,'']]],
  ['build_20errors_58',['Common Build Errors',['../troubleshooting.html#autotoc_md511',1,'']]],
  ['build_20fails_59',['Build Fails?',['../troubleshooting.html#autotoc_md482',1,'']]],
  ['build_20fails_20with_20gpu_20openacc_20errors_60',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md515',1,'']]],
  ['build_20toolchain_61',['Build Toolchain',['../contributing.html#autotoc_md85',1,'']]],
  ['building_20mfc_62',['Building MFC',['../getting-started.html#autotoc_md297',1,'']]],
  ['building_20with_20gpu_20support_63',['Building with GPU Support',['../running.html#autotoc_md453',1,'']]],
  ['builds_64',['Debug Builds',['../troubleshooting.html#autotoc_md488',1,'']]]
];
