var searchData=
[
  ['mach_20number_0',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['mach_20number_20corrections_20wilfong26_20sec_204_202_204_1',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md192',1,'']]],
  ['macos_2',['macOS',['../getting-started.html#autotoc_md280',1,'Install via Homebrew (macOS)'],['../running.html#autotoc_md382',1,'Using the Homebrew package (macOS)']]],
  ['macro_20api_20documentation_3',['Macro API Documentation',['../gpuParallelization.html#autotoc_md292',1,'']]],
  ['macros_4',['Macros',['../gpuParallelization.html#autotoc_md296',1,'Computation Macros'],['../gpuParallelization.html#autotoc_md298',1,'Data Control Macros'],['../gpuParallelization.html#autotoc_md302',1,'Miscellaneous Macros'],['../gpuParallelization.html#autotoc_md300',1,'Synchronization Macros']]],
  ['maeda18_5',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md146',1,'']]],
  ['magnetohydrodynamics_6',['11. Magnetohydrodynamics',['../equations.html#autotoc_md160',1,'']]],
  ['magnetohydrodynamics_20mhd_7',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md16',1,'']]],
  ['manage_20gpu_20arrays_8',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['material_20s_9',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['matrix_10',['Build and Test Matrix',['../contributing.html#autotoc_md101',1,'']]],
  ['maximum_20performance_11',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md260',1,'']]],
  ['meanings_12',['Data Type Meanings',['../gpuParallelization.html#autotoc_md293',1,'']]],
  ['memory_20and_20allocation_13',['Memory and Allocation',['../contributing.html#autotoc_md80',1,'']]],
  ['menikoff89_20lemetayer04_20wilfong26_20sec_202_202_14',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md131',1,'']]],
  ['merge_15',['Code Review and Merge',['../contributing.html#autotoc_md105',1,'']]],
  ['merit_3a_20grind_20time_20performance_16',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md268',1,'']]],
  ['meshkov_20instability_202d_17',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md202',1,'']]],
  ['messages_18',['Commit Messages',['../contributing.html#autotoc_md73',1,'']]],
  ['method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_19',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['method_20of_20classes_20commander89_20ando11_20',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md140',1,'']]],
  ['methods_21',['15. Numerical Methods',['../equations.html#autotoc_md170',1,'']]],
  ['mfc_22',['MFC',['../getting-started.html#autotoc_md282',1,'Building MFC'],['../contributing.html#autotoc_md65',1,'Contributing to MFC'],['../getting-started.html#autotoc_md279',1,'Fetching MFC']]],
  ['mfc_20documentation_23',['MFC Documentation',['../index.html',1,'']]],
  ['mfc_3a_20comprehensive_20equations_20reference_24',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md121',1,'']]],
  ['mhd_25',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md16',1,'']]],
  ['mhd_20mhd_20true_20wilfong26_20sec_204_201_209_26',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md161',1,'']]],
  ['mhd_20only_27',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md179',1,'']]],
  ['mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_28',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md162',1,'']]],
  ['mhd_20true_20wilfong26_20sec_204_201_209_29',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md161',1,'']]],
  ['mi250x_20gpu_30',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md270',1,'']]],
  ['miksis_20bubble_5fmodel_202_20keller80_31',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md142',1,'']]],
  ['miscellaneous_20macros_32',['Miscellaneous Macros',['../gpuParallelization.html#autotoc_md302',1,'']]],
  ['mittal05_20wilfong26_20sec_204_201_201_33',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['mixing_20layer_203d_34',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md218',1,'']]],
  ['model_35',['Model',['../case.html#sec-phase-change',1,'11. Phase Change Model'],['../case.html#autotoc_md13',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md14',1,'9.2 Volume-Averaged Bubble Model']]],
  ['model_20consistency_36',['Physics and Model Consistency',['../contributing.html#autotoc_md82',1,'']]],
  ['model_20equations_37',['🔢 Model Equations',['../case_constraints.html#model-equations',1,'']]],
  ['model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_38',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_39',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md149',1,'']]],
  ['model_20model_5feqns_202_40',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md126',1,'']]],
  ['model_20model_5feqns_203_41',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md127',1,'']]],
  ['model_20polytropic_20false_20preston07_42',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['model_20variants_43',['2.3 Other Model Variants',['../equations.html#autotoc_md128',1,'']]],
  ['model_5feqns_202_44',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md126',1,'']]],
  ['model_5feqns_203_45',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md127',1,'']]],
  ['models_46',['Models',['../case_constraints.html#bubble-models',1,'💧 Bubble Models'],['../case.html#sec-bubble-models',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#compat-bubble-models',1,'Bubble Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['modifying_20src_20common_47',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md96',1,'']]],
  ['module_48',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['module_20not_20found_20on_20hpc_49',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['mom_5fwrt_50',['mom_wrt',['../parameters.html#mom_wrt',1,'']]],
  ['moment_20transport_20qbmm_20true_20bryngelson20_51',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['mpi_52',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md446',1,'']]],
  ['mpi_20correctness_53',['MPI Correctness',['../contributing.html#autotoc_md81',1,'']]],
  ['mpi_20errors_20or_20hangs_54',['MPI errors or hangs',['../troubleshooting.html#autotoc_md456',1,'']]],
  ['mpi_20halo_20exchange_55',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['multi_20component_20inert_20shock_20tube_56',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md242',1,'']]],
  ['multi_20component_20reactive_20shock_20tube_57',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md213',1,'']]],
  ['muscl_20muscl_5forder_202_58',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md173',1,'']]],
  ['muscl_5forder_202_59',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md173',1,'']]]
];
