var searchData=
[
  ['a_20bubble_20case_0',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['a_20fortran_20compiler_1',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md590',1,'']]],
  ['a_20gpu_20parallel_20loop_2',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md108',1,'']]],
  ['a_20new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md351',1,'']]],
  ['a_20new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['a_20new_20simulation_20parameter_5',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md107',1,'']]],
  ['a_20post_20processing_20output_20variable_6',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['a_20pull_20request_7',['Submitting a Pull Request',['../contributing.html#autotoc_md124',1,'']]],
  ['a_20state_20dependent_20equation_20of_20state_8',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md461',1,'']]],
  ['a_20test_20case_9',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['about_10',['About',['../index.html#autotoc_md523',1,'']]],
  ['accepting_20command_20line_20arguments_11',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['achieving_20maximum_20performance_12',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md321',1,'']]],
  ['acoustic_13',['acoustic',['../parameters.html#acoustic',1,'']]],
  ['acoustic_20source_14',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['acoustic_20sources_15',['Acoustic Sources',['../physics_constraints.html#autotoc_md506',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md507',1,'Acoustic Sources']]],
  ['acoustic_20sources_20acoustic_5fsource_20true_16',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md188',1,'']]],
  ['acoustic_20supports_17',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['acoustic_5fsource_20true_18',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md188',1,'']]],
  ['adap_5fdt_20true_19',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md203',1,'']]],
  ['adaptive_20time_20stepping_20',['Adaptive Time-Stepping',['../case.html#autotoc_md27',1,'']]],
  ['adaptive_20time_20stepping_20adap_5fdt_20true_21',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md203',1,'']]],
  ['add_20a_20new_20simulation_20parameter_22',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md107',1,'']]],
  ['add_20a_20post_20processing_20output_20variable_23',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['add_20a_20test_20case_24',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['add_20an_20equation_20of_20state_25',['How to Add an Equation of State',['../contributing.html#autotoc_md110',1,'']]],
  ['adding_20new_20physics_26',['Adding New Physics',['../architecture.html#autotoc_md13',1,'']]],
  ['advanced_20examples_27',['🔴 Advanced Examples',['../case_constraints.html#autotoc_md45',1,'']]],
  ['advanced_20topics_28',['Advanced Topics',['../index.html#autotoc_md521',1,'']]],
  ['agnostic_20tools_29',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md370',1,'']]],
  ['air_20mc_201_205_30',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md227',1,'']]],
  ['algorithm_31',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['all_20other_20jobs_32',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['allocate_20and_20manage_20gpu_20arrays_33',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md109',1,'']]],
  ['allocation_34',['Memory and Allocation',['../contributing.html#autotoc_md98',1,'']]],
  ['alpha_20rho_20consistency_35',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['alpha_5frho_5fe_5fwrt_36',['alpha_rho_e_wrt',['../parameters.html#alpha_rho_e_wrt',1,'']]],
  ['alpha_5frho_5fwrt_37',['alpha_rho_wrt',['../parameters.html#alpha_rho_wrt',1,'']]],
  ['alpha_5fwrt_38',['alpha_wrt',['../parameters.html#alpha_wrt',1,'']]],
  ['alternative_20sound_20speed_39',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md495',1,'']]],
  ['amd_20flang_20amdflang_20known_20issues_40',['AMD flang (amdflang) Known Issues',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['amd_20gpu_20profiling_41',['AMD GPU Profiling',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['amd_20gpus_42',['AMD GPUs',['../running.html#autotoc_md537',1,'']]],
  ['amdflang_20known_20issues_43',['AMD flang (amdflang) Known Issues',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['an_20equation_20of_20state_44',['How to Add an Equation of State',['../contributing.html#autotoc_md110',1,'']]],
  ['an_20example_20case_45',['Running an Example Case',['../getting-started.html#autotoc_md346',1,'']]],
  ['analytic_20solution_46',['Analytic solution',['../examples.html#autotoc_md291',1,'']]],
  ['analytic_20solution_47',['analytic solution',['../examples.html#autotoc_md245',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md261',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md274',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md285',1,'Governing physics and analytic solution']]],
  ['analytical_20definition_20of_20primitive_20variables_48',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['and_20allocation_49',['Memory and Allocation',['../contributing.html#autotoc_md98',1,'']]],
  ['and_20analytic_20solution_50',['and analytic solution',['../examples.html#autotoc_md245',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md261',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md274',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md285',1,'Governing physics and analytic solution']]],
  ['and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_51',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md176',1,'']]],
  ['and_20dimensional_20consistency_52',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md476',1,'']]],
  ['and_20dimensions_53',['Units and Dimensions',['../getting-started.html#autotoc_md347',1,'']]],
  ['and_20execution_20pitfalls_54',['Selection and Execution Pitfalls',['../testing.html#selection-and-execution-pitfalls',1,'']]],
  ['and_20final_20conditions_55',['Density Initial and Final Conditions',['../examples.html#autotoc_md253',1,'']]],
  ['and_20geometry_56',['Domain and Geometry',['../physics_constraints.html#autotoc_md470',1,'']]],
  ['and_20gpu_57',['Fypp and GPU',['../contributing.html#autotoc_md105',1,'']]],
  ['and_20indexing_58',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['and_20linear_20theory_59',['and Linear Theory',['../examples.html#autotoc_md266',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md306',1,'Final Condition and Linear Theory']]],
  ['and_20manage_20gpu_20arrays_60',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md109',1,'']]],
  ['and_20merge_61',['Code Review and Merge',['../contributing.html#autotoc_md125',1,'']]],
  ['and_20model_20consistency_62',['Physics and Model Consistency',['../contributing.html#autotoc_md100',1,'']]],
  ['and_20non_20dimensionalization_63',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['and_20parameters_64',['and parameters',['../examples.html#autotoc_md290',1,'Geometry and parameters'],['../examples.html#autotoc_md244',1,'Regime and parameters'],['../examples.html#autotoc_md260',1,'Regime and parameters'],['../examples.html#autotoc_md273',1,'Regime and parameters'],['../examples.html#autotoc_md284',1,'Regime and parameters'],['../examples.html#autotoc_md301',1,'Regime and parameters']]],
  ['and_20performance_20test_65',['Scaling and Performance test',['../examples.html#autotoc_md233',1,'']]],
  ['and_20result_66',['Initial Condition and Result',['../examples.html#autotoc_md310',1,'']]],
  ['and_20startup_67',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['and_20test_20matrix_68',['Build and Test Matrix',['../contributing.html#autotoc_md121',1,'']]],
  ['and_20tips_20for_20gpus_69',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md369',1,'']]],
  ['and_20type_20safety_70',['Precision and Type Safety',['../contributing.html#autotoc_md97',1,'']]],
  ['ando11_71',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['api_20documentation_72',['Macro API Documentation',['../gpuParallelization.html#autotoc_md355',1,'']]],
  ['apptainer_20singularity_73',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md132',1,'']]],
  ['architecture_74',['Code Architecture',['../architecture.html',1,'']]],
  ['architecture_20notes_75',['Architecture Notes',['../contributing.html#autotoc_md104',1,'']]],
  ['architecture_20overview_76',['Architecture Overview',['../contributing.html#autotoc_md84',1,'']]],
  ['architecture_20support_77',['Architecture Support',['../docker.html#autotoc_md140',1,'']]],
  ['architecture_2emd_78',['architecture.md',['../architecture_8md.html',1,'']]],
  ['are_20silently_20dropped_79',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md381',1,'']]],
  ['arguments_80',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['around_20in_20the_20build_81',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md380',1,'']]],
  ['array_20bounds_20and_20indexing_82',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['arrays_83',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md109',1,'']]],
  ['artifacts_84',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md605',1,'']]],
  ['artificial_20mach_20number_85',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['at_20each_20stage_86',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['at_20final_20time_87',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md226',1,'']]],
  ['at_20transitional_20state_88',['Liutex visualization at transitional state',['../examples.html#autotoc_md279',1,'']]],
  ['authors_89',['Authors',['../authors.html',1,'Authors'],['../authors.html#autotoc_md14',1,'Authors']]],
  ['authors_2emd_90',['authors.md',['../authors_8md.html',1,'']]],
  ['available_20data_91',['Exploring available data',['../visualization.html#autotoc_md612',1,'']]],
  ['averaged_20bubble_20model_92',['Averaged Bubble Model',['../case.html#autotoc_md28',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md29',1,'9.2 Volume-Averaged Bubble Model']]]
];
