var searchData=
[
  ['d_20debug_20log_0',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md79',1,'']]],
  ['data_1',['Exploring available data',['../visualization.html#autotoc_md538',1,'']]],
  ['data_20control_20macros_2',['Data Control Macros',['../gpuParallelization.html#autotoc_md317',1,'']]],
  ['data_20flow_3',['Data Flow',['../gpuParallelization.html#autotoc_md313',1,'Data Flow'],['../contributing.html#autotoc_md85',1,'Simulation Data Flow']]],
  ['data_20in_20cylindrical_20coordinates_4',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md551',1,'']]],
  ['data_20output_5',['Serial data output',['../visualization.html#autotoc_md553',1,'']]],
  ['data_20structures_6',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['data_20type_20meanings_7',['Data Type Meanings',['../gpuParallelization.html#autotoc_md312',1,'']]],
  ['debug_20builds_8',['Debug Builds',['../troubleshooting.html#autotoc_md491',1,'']]],
  ['debug_20log_9',['Debug Log',['../troubleshooting.html#autotoc_md499',1,'']]],
  ['debug_20log_10',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md79',1,'']]],
  ['debug_20logging_20d_20debug_20log_11',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md79',1,'']]],
  ['debugging_12',['Debugging',['../troubleshooting.html#autotoc_md489',1,'Build Debugging'],['../contributing.html#autotoc_md112',1,'Debugging'],['../troubleshooting.html#autotoc_md496',1,'Runtime Debugging'],['../troubleshooting.html#autotoc_md502',1,'Test Debugging']]],
  ['debugging_20flags_13',['Debugging Flags',['../troubleshooting.html#autotoc_md480',1,'']]],
  ['debugging_20tools_20and_20tips_20for_20gpus_14',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md323',1,'']]],
  ['debugging_20workflow_15',['Debugging Workflow',['../troubleshooting.html#autotoc_md484',1,'']]],
  ['definition_20of_20primitive_20variables_16',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['density_17',['Density',['../examples.html#autotoc_md255',1,'Density'],['../examples.html#autotoc_md258',1,'Final Condition (Density)'],['../examples.html#autotoc_md274',1,'Final Condition (Density)']]],
  ['density_20initial_20and_20final_20conditions_18',['Density Initial and Final Conditions',['../examples.html#autotoc_md234',1,'']]],
  ['density_20norms_19',['Density Norms',['../examples.html#autotoc_md256',1,'']]],
  ['descriptions_20',['Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['design_20playbook_21',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['desktop_20gui_22',['Docker Desktop GUI',['../docker.html#autotoc_md123',1,'']]],
  ['details_23',['Tag Details',['../docker.html#autotoc_md131',1,'']]],
  ['details_20on_20running_20containers_24',['Details on Running Containers',['../docker.html#autotoc_md125',1,'']]],
  ['detected_25',['detected',['../troubleshooting.html#autotoc_md523',1,'&quot;NaN detected&quot;'],['../troubleshooting.html#autotoc_md524',1,'GPU not detected']]],
  ['detection_26',['Verifying GPU Detection',['../running.html#autotoc_md460',1,'']]],
  ['development_27',['Development',['../index.html#autotoc_md448',1,'']]],
  ['development_20commands_28',['Development Commands',['../cli-reference.html#autotoc_md62',1,'']]],
  ['development_20workflow_29',['Development Workflow',['../contributing.html#autotoc_md87',1,'']]],
  ['differences_20fd_5forder_201_202_204_30',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md201',1,'']]],
  ['different_20viscosity_20parameters_31',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['dimensional_20bubble_20dynamics_32',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dimensional_20consistency_33',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md410',1,'']]],
  ['dimensional_20framework_34',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['dimensional_20handling_35',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['dimensionality_36',['Dimensionality',['../physics_constraints.html#autotoc_md407',1,'']]],
  ['dimensionalization_37',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensionalization_20of_20input_20parameters_38',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['dimensionalizing_20a_20bubble_20case_39',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['dimensions_40',['Dimensions',['../getting-started.html#autotoc_md303',1,'Units and Dimensions'],['../physics_constraints.html#autotoc_md411',1,'Velocity Components in Inactive Dimensions']]],
  ['dimensions_20and_20non_20dimensionalization_41',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensions_20in_20dimensions_20out_42',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['dimensions_20out_43',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['directory_20found_44',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md528',1,'']]],
  ['directory_20layout_45',['Directory Layout',['../architecture.html#autotoc_md1',1,'Directory Layout'],['../contributing.html#autotoc_md84',1,'Directory Layout']]],
  ['docker_46',['Navigating Docker',['../docker.html#autotoc_md122',1,'']]],
  ['docker_20cli_47',['Docker CLI',['../docker.html#autotoc_md124',1,'']]],
  ['docker_20desktop_20gui_48',['Docker Desktop GUI',['../docker.html#autotoc_md123',1,'']]],
  ['docker_2emd_49',['docker.md',['../docker_8md.html',1,'']]],
  ['document_20physics_20constraints_50',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['documentation_51',['Documentation',['../gpuParallelization.html#autotoc_md333',1,'Compiler Documentation'],['../contributing.html#autotoc_md118',1,'Documentation'],['../gpuParallelization.html#autotoc_md311',1,'Macro API Documentation'],['../index.html',1,'MFC Documentation']]],
  ['domain_52',['Domain',['../case.html#sec-computational-domain',1,'2. Computational Domain'],['../physics_constraints.html#autotoc_md408',1,'Patch Within Domain']]],
  ['domain_20and_20geometry_53',['Domain and Geometry',['../physics_constraints.html#autotoc_md405',1,'']]],
  ['domain_20bounds_54',['Domain Bounds',['../physics_constraints.html#autotoc_md406',1,'']]],
  ['driven_20cavity_20problem_202d_55',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md268',1,'']]],
  ['droplet_202d_56',['Shock Droplet (2D)',['../examples.html#autotoc_md225',1,'']]],
  ['dt_202d_57',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md266',1,'']]],
  ['dynamics_58',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dynamics_59',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md199',1,'']]],
  ['dynamics_20wilfong26_20sec_204_201_60',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md154',1,'']]]
];
