var searchData=
[
  ['nan_20detected_0',['&quot;NaN detected&quot;',['../troubleshooting.html#autotoc_md532',1,'']]],
  ['navigating_20docker_1',['Navigating Docker',['../docker.html#autotoc_md152',1,'']]],
  ['new_2',['new',['../cli-reference.html#autotoc_md70',1,'']]],
  ['new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md333',1,'']]],
  ['new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['new_20simulation_20parameter_5',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md133',1,'']]],
  ['non_20polytropic_20thermal_20model_20polytropic_20false_20preston07_6',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;b&gt;[Preston07]&lt;/b&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['norms_7',['Density Norms',['../examples.html#autotoc_md284',1,'']]],
  ['not_20detected_8',['GPU not detected',['../troubleshooting.html#autotoc_md533',1,'']]],
  ['not_20find_20a_20fortran_20compiler_9',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['not_20find_20mpi_10',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md524',1,'']]],
  ['not_20found_20on_20hpc_11',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md528',1,'']]],
  ['notes_12',['Notes',['../contributing.html#autotoc_md130',1,'Architecture Notes'],['../running.html#autotoc_md479',1,'Scheduler Notes']]],
  ['number_13',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['number_20corrections_20wilfong26_20sec_204_202_204_14',['17. Low Mach Number Corrections (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.2.4)',['../equations.html#autotoc_md237',1,'']]],
  ['numerical_20methods_15',['15. Numerical Methods',['../equations.html#autotoc_md215',1,'']]],
  ['numerical_20schlieren_20at_20final_20time_16',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md243',1,'']]],
  ['numerics_17',['Numerics',['../case_constraints.html#autotoc_md48',1,'']]],
  ['nvhpc_20compiler_20options_18',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md355',1,'']]],
  ['nvhpc_20general_20options_19',['NVHPC General Options',['../gpuParallelization.html#autotoc_md356',1,'']]],
  ['nvhpc_20openacc_20options_20',['NVHPC OpenACC Options',['../gpuParallelization.html#autotoc_md357',1,'']]],
  ['nvhpc_20openmp_20options_21',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md358',1,'']]],
  ['nvidia_20gpu_20profiling_22',['NVIDIA GPU Profiling',['../troubleshooting.html#autotoc_md519',1,'']]],
  ['nvidia_20gpus_23',['NVIDIA GPUs',['../running.html#autotoc_md471',1,'']]],
  ['nvidia_20v100_20gpu_24',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md316',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md319',1,'NVIDIA V100 GPU']]]
];
