var searchData=
[
  ['o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['of_20classes_20commander89_20ando11_1',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['of_20input_20parameters_2',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['of_20merit_3a_20grind_20time_20performance_3',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md324',1,'']]],
  ['of_20primitive_20variables_4',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['of_20state_5',['of State',['../equations.html#autotoc_md150',1,'3. Equations of State'],['../contributing.html#autotoc_md109',1,'How to Add an Equation of State'],['../physics_constraints.html#autotoc_md455',1,'Initial States Inside a State-Dependent Equation of State']]],
  ['of_20state_20selector_6',['Equation of State Selector',['../physics_constraints.html#autotoc_md456',1,'']]],
  ['omega_5fwrt_7',['omega_wrt',['../parameters.html#omega_wrt',1,'']]],
  ['on_20gpus_8',['on GPUs',['../running.html#autotoc_md523',1,'Running on GPUs'],['../running.html#autotoc_md525',1,'Running on GPUs']]],
  ['on_20hpc_9',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md587',1,'']]],
  ['on_20non_20conservative_20term_20implementation_10',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['on_20pace_20phoenix_11',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md622',1,'']]],
  ['on_20running_20containers_12',['Details on Running Containers',['../docker.html#autotoc_md129',1,'']]],
  ['openacc_20errors_13',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['openacc_20options_14',['OpenACC Options',['../gpuParallelization.html#autotoc_md369',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md372',1,'NVHPC OpenACC Options']]],
  ['openmp_20options_15',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md373',1,'']]],
  ['openmp_20tools_16',['OpenMP tools',['../gpuParallelization.html#autotoc_md366',1,'']]],
  ['optimization_17',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md320',1,'']]],
  ['optimization_18',['When to use case optimization',['../expectedPerformance.html#autotoc_md318',1,'']]],
  ['optimization_20flags_19',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md319',1,'']]],
  ['optimization_20recommended_20',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md317',1,'']]],
  ['option_20reference_21',['Complete option reference',['../visualization.html#autotoc_md616',1,'']]],
  ['optional_20accepting_20command_20line_20arguments_22',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['options_23',['Options',['../running.html#autotoc_md535',1,'Batch Options'],['../cli-reference.html#autotoc_md77',1,'Common Options'],['../gpuParallelization.html#autotoc_md368',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md369',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md370',1,'NVHPC Compiler Options'],['../gpuParallelization.html#autotoc_md371',1,'NVHPC General Options'],['../gpuParallelization.html#autotoc_md372',1,'NVHPC OpenACC Options'],['../gpuParallelization.html#autotoc_md373',1,'NVHPC OpenMP Options']]],
  ['options_24',['Rendering options',['../visualization.html#autotoc_md608',1,'']]],
  ['or_20hangs_25',['MPI errors or hangs',['../troubleshooting.html#autotoc_md593',1,'']]],
  ['or_20has_20artifacts_26',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md599',1,'']]],
  ['or_20hypoelasticity_27',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md198',1,'']]],
  ['or_20silo_5fhdf5_20directory_20found_28',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md596',1,'']]],
  ['ordering_29',['Ordering',['../case.html#autotoc_md40',1,'Conservative Variables Ordering'],['../case.html#autotoc_md41',1,'Primitive Variables Ordering']]],
  ['osher_20problem_201d_30',['Shu-Osher problem (1D)',['../examples.html#autotoc_md232',1,'']]],
  ['other_20commands_31',['Other Commands',['../cli-reference.html#autotoc_md75',1,'']]],
  ['other_20jobs_32',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md119',1,'']]],
  ['other_20model_20variants_33',['2.3 Other Model Variants',['../equations.html#autotoc_md148',1,'']]],
  ['other_20optimization_20flags_34',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md319',1,'']]],
  ['out_35',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['output_36',['Output',['../case.html#sec-formatted-output',1,'7. Formatted Output'],['../physics_constraints.html#autotoc_md505',1,'FFT Output'],['../physics_constraints.html#autotoc_md504',1,'Vorticity Output']]],
  ['output_37',['Serial data output',['../visualization.html#autotoc_md621',1,'']]],
  ['output_20location_38',['Test Output Location',['../troubleshooting.html#autotoc_md573',1,'']]],
  ['output_20variable_39',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md114',1,'']]],
  ['overview_40',['Overview',['../equations.html#autotoc_md142',1,'1. Overview'],['../contributing.html#autotoc_md84',1,'Architecture Overview'],['../cli-reference.html#autotoc_md48',1,'Overview'],['../parameters.html#autotoc_md380',1,'Overview']]]
];
