var searchData=
[
  ['v_20verbose_0',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md108',1,'']]],
  ['v100_20gpu_1',['V100 GPU',['../expectedPerformance.html#autotoc_md242',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md245',1,'NVIDIA V100 GPU']]],
  ['validate_2',['validate',['../cli-reference.html#autotoc_md67',1,'']]],
  ['validation_3',['Case Validation',['../troubleshooting.html#autotoc_md432',1,'']]],
  ['variable_4',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md140',1,'']]],
  ['variables_5',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md9',1,'']]],
  ['variables_20ordering_6',['Variables Ordering',['../case.html#autotoc_md37',1,'Conservative Variables Ordering'],['../case.html#autotoc_md38',1,'Primitive Variables Ordering']]],
  ['vel_5fwrt_7',['vel_wrt',['../parameters.html#autotoc_md360',1,'']]],
  ['velocities_8',['Centerline Velocities',['../examples.html#autotoc_md224',1,'']]],
  ['velocity_20field_20setup_9',['10. Velocity Field Setup',['../case.html#autotoc_md24',1,'']]],
  ['verbose_10',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md108',1,'']]],
  ['verbose_20runs_11',['Verbose Runs',['../troubleshooting.html#autotoc_md433',1,'']]],
  ['verbosity_20levels_12',['Verbosity Levels',['../troubleshooting.html#autotoc_md425',1,'']]],
  ['verbosity_20v_20verbose_13',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md108',1,'']]],
  ['verifying_20gpu_20detection_14',['Verifying GPU Detection',['../running.html#autotoc_md395',1,'']]],
  ['via_20apptainer_20singularity_15',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md157',1,'']]],
  ['via_20homebrew_20macos_16',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md251',1,'']]],
  ['violations_17',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md457',1,'']]],
  ['viscous_20shock_20tube_202d_18',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md205',1,'']]],
  ['visit_19',['Visualizing with VisIt',['../visualization.html#autotoc_md466',1,'']]],
  ['visualization_20',['Examples &amp;amp; Visualization',['../index.html#autotoc_md380',1,'']]],
  ['visualization_21',['visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md463',1,'Flow visualization']]],
  ['visualization_20at_20transitional_20state_22',['Liutex visualization at transitional state',['../examples.html#autotoc_md190',1,'']]],
  ['visualization_20on_20pace_20phoenix_23',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md468',1,'']]],
  ['visualization_2emd_24',['visualization.md',['../visualization_8md.html',1,'']]],
  ['visualizing_20data_20in_20cylindrical_20coordinates_25',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md465',1,'']]],
  ['visualizing_20with_20paraview_26',['Visualizing with Paraview',['../visualization.html#autotoc_md464',1,'']]],
  ['visualizing_20with_20visit_27',['Visualizing with VisIt',['../visualization.html#autotoc_md466',1,'']]],
  ['volume_20averaged_20bubble_20model_28',['9.2 Volume-Averaged Bubble Model',['../case.html#autotoc_md23',1,'']]],
  ['vortex_203d_29',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md225',1,'']]],
  ['vortex_20problem_202d_30',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md208',1,'']]],
  ['vs_20correctness_31',['Performance vs Correctness',['../troubleshooting.html#autotoc_md447',1,'']]]
];
