var searchData=
[
  ['lag_5fparams_0',['lag_params',['../parameters.html#lag_params',1,'']]],
  ['lagrange_20bubble_20model_1',['Euler-Lagrange Bubble Model',['../physics_constraints.html#autotoc_md405',1,'']]],
  ['lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_2',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['lax_20shock_20tube_20problem_201d_3',['Lax shock tube problem (1D)',['../examples.html#autotoc_md200',1,'']]],
  ['layer_203d_4',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md219',1,'']]],
  ['layout_5',['Directory Layout',['../contributing.html#autotoc_md69',1,'']]],
  ['lemetayer04_20wilfong26_20sec_202_202_6',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md132',1,'']]],
  ['levels_7',['Verbosity Levels',['../troubleshooting.html#autotoc_md473',1,'']]],
  ['lid_20driven_20cavity_20problem_202d_8',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md252',1,'']]],
  ['limiting_9',['18. Flux Limiting',['../equations.html#autotoc_md195',1,'']]],
  ['line_20arguments_10',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['line_20reference_11',['Line Reference',['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md29',1,'Command Line Reference'],['../parameters.html#autotoc_md376',1,'Command Line Reference']]],
  ['linear_20theory_12',['Linear Theory',['../examples.html#autotoc_md213',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md247',1,'Final Condition and Linear Theory']]],
  ['lint_13',['lint',['../cli-reference.html#lint',1,'']]],
  ['lint_20gate_20runs_20first_20blocks_20all_20other_20jobs_14',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md100',1,'']]],
  ['liutex_20visualization_20at_20transitional_20state_15',['Liutex visualization at transitional state',['../examples.html#autotoc_md220',1,'']]],
  ['load_16',['load',['../cli-reference.html#load',1,'']]],
  ['location_17',['Test Output Location',['../troubleshooting.html#autotoc_md488',1,'']]],
  ['log_18',['Debug Log',['../troubleshooting.html#autotoc_md482',1,'']]],
  ['log_19',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md64',1,'']]],
  ['logging_20d_20debug_20log_20',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md64',1,'']]],
  ['lookup_21',['Parameter Lookup',['../getting-started.html#autotoc_md289',1,'']]],
  ['loop_22',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['low_20mach_20number_20corrections_20wilfong26_20sec_204_202_204_23',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md193',1,'']]]
];
