var searchData=
[
  ['s_0',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['safety_1',['Precision and Type Safety',['../contributing.html#autotoc_md93',1,'']]],
  ['sanity_20transformed_20gamma_2',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md395',1,'']]],
  ['saurel08_3',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['scales_4',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['scaling_5',['Scaling',['../examples.html#autotoc_md240',1,'Strong Scaling'],['../examples.html#autotoc_md239',1,'Weak Scaling']]],
  ['scaling_6',['scaling',['../expectedPerformance.html#autotoc_md285',1,'GPU weak scaling'],['../expectedPerformance.html#autotoc_md288',1,'Strong scaling'],['../expectedPerformance.html#autotoc_md284',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_7',['Scaling and Performance test',['../examples.html#autotoc_md238',1,'']]],
  ['scheduler_20notes_8',['Scheduler Notes',['../running.html#autotoc_md467',1,'']]],
  ['schemes_9',['Numerical Schemes',['../physics_constraints.html#autotoc_md429',1,'']]],
  ['schlieren_20at_20final_20time_10',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md213',1,'']]],
  ['schlieren_5falpha_11',['schlieren_alpha',['../parameters.html#schlieren_alpha',1,'']]],
  ['schmidmayer17_20wilfong26_20sec_204_201_208_12',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md173',1,'']]],
  ['script_13',['Step 2: Customizing the script',['../visualization.html#autotoc_md532',1,'']]],
  ['sec_202_202_14',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md146',1,'']]],
  ['sec_202_203_15',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md151',1,'']]],
  ['sec_204_201_16',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md153',1,'']]],
  ['sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md205',1,'']]],
  ['sec_204_201_2010_18',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md177',1,'']]],
  ['sec_204_201_203_19',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md167',1,'']]],
  ['sec_204_201_206_20',['Sec 4 1 6',['../equations.html#autotoc_md164',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md165',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)']]],
  ['sec_204_201_207_21',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md171',1,'']]],
  ['sec_204_201_208_22',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md173',1,'']]],
  ['sec_204_201_209_23',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md176',1,'']]],
  ['sec_204_202_204_24',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md207',1,'']]],
  ['selection_25',['Model Equation Selection',['../physics_constraints.html#autotoc_md411',1,'']]],
  ['selection_20t_20targets_26',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md75',1,'']]],
  ['serial_20data_20output_27',['Serial data output',['../visualization.html#autotoc_md529',1,'']]],
  ['serial_20test_20execution_28',['Serial Test Execution',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['server_29',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['set_20up_30',['Getting Set Up',['../contributing.html#autotoc_md80',1,'']]],
  ['setting_20up_20your_20environment_31',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md531',1,'']]],
  ['setup_32',['Setup',['../case.html#sec-velocity-field-setup',1,'10. Velocity Field Setup'],['../running.html#autotoc_md456',1,'Environment Setup']]],
  ['shell_33',['Interactive Shell',['../docker.html#autotoc_md127',1,'']]],
  ['shell_20completion_34',['Shell Completion',['../getting-started.html#autotoc_md305',1,'']]],
  ['shock_203d_35',['IBM Bow Shock (3D)',['../examples.html#autotoc_md247',1,'']]],
  ['shock_20droplet_202d_36',['Shock Droplet (2D)',['../examples.html#autotoc_md223',1,'']]],
  ['shock_20tube_37',['Shock Tube',['../examples.html#autotoc_md257',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md228',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_202d_38',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md249',1,'']]],
  ['shock_20tube_20problem_201d_39',['Lax shock tube problem (1D)',['../examples.html#autotoc_md214',1,'']]],
  ['shu_20osher_20problem_201d_40',['Shu-Osher problem (1D)',['../examples.html#autotoc_md220',1,'']]],
  ['simple_20bcs_41',['16.1 Simple BCs',['../equations.html#autotoc_md203',1,'']]],
  ['simplex_5fparams_42',['simplex_params',['../parameters.html#simplex_params',1,'']]],
  ['simulation_20algorithm_43',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['simulation_20constraints_44',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md418',1,'']]],
  ['simulation_20data_20flow_45',['Simulation Data Flow',['../contributing.html#autotoc_md84',1,'']]],
  ['simulation_20loop_46',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['simulation_20parameter_47',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md102',1,'']]],
  ['singularity_48',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md126',1,'']]],
  ['six_20equation_20model_20model_5feqns_203_49',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md142',1,'']]],
  ['skeleton_50',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['slurm_20job_51',['Slurm Job',['../docker.html#autotoc_md129',1,'']]],
  ['smoothing_52',['Elliptic Smoothing',['../case.html#autotoc_md23',1,'']]],
  ['soft_20guidelines_53',['Soft Guidelines',['../contributing.html#autotoc_md90',1,'']]],
  ['solver_20core_54',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['solvers_55',['Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md190',1,'15.2 Riemann Solvers']]],
  ['sound_20speed_56',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md426',1,'']]],
  ['source_57',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['sources_58',['Sources',['../physics_constraints.html#autotoc_md435',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md436',1,'Acoustic Sources']]],
  ['sources_20acoustic_5fsource_20true_59',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['spatial_20reconstruction_60',['15.1 Spatial Reconstruction',['../equations.html#autotoc_md186',1,'']]],
  ['specific_20tests_61',['Running Specific Tests',['../troubleshooting.html#autotoc_md500',1,'']]],
  ['speed_62',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md426',1,'']]],
  ['spelling_63',['spelling',['../cli-reference.html#spelling',1,'']]],
  ['splitting_20strang68_20for_20stiff_20bubble_20dynamics_64',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md198',1,'']]],
  ['src_20common_65',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md110',1,'']]],
  ['stage_66',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['standards_67',['Coding Standards',['../contributing.html#autotoc_md88',1,'']]],
  ['started_68',['Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md293',1,'Getting Started'],['../index.html#autotoc_md441',1,'Getting Started']]],
  ['startup_69',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['state_70',['State',['../equations.html#autotoc_md145',1,'3. Equations of State'],['../examples.html#autotoc_md219',1,'Evolved State'],['../examples.html#autotoc_md237',1,'Evolved State'],['../examples.html#autotoc_md251',1,'Evolved State'],['../examples.html#autotoc_md218',1,'Initial State'],['../examples.html#autotoc_md236',1,'Initial State'],['../examples.html#autotoc_md250',1,'Initial State']]],
  ['state_71',['Liutex visualization at transitional state',['../examples.html#autotoc_md234',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_72',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md531',1,'']]],
  ['step_202_3a_20customizing_20the_20script_73',['Step 2: Customizing the script',['../visualization.html#autotoc_md532',1,'']]],
  ['step_202d_74',['Step 2D',['../examples.html#autotoc_md255',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md271',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_75',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['stepping_76',['Stepping',['../case.html#autotoc_md26',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md25',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md432',1,'Time Stepping']]],
  ['stepping_20adap_5fdt_20true_77',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md197',1,'']]],
  ['stiff_20bubble_20dynamics_78',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md198',1,'']]],
  ['stiffened_20eos_20positivity_79',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md394',1,'']]],
  ['stiffened_20gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_80',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md146',1,'']]],
  ['stirred_20reactor_81',['Perfectly Stirred Reactor',['../examples.html#autotoc_md211',1,'']]],
  ['stored_20parameter_20conventions_82',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['strang_20splitting_20strang68_20for_20stiff_20bubble_20dynamics_83',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md198',1,'']]],
  ['strang68_20for_20stiff_20bubble_20dynamics_84',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md198',1,'']]],
  ['stress_20tensor_20viscous_20true_85',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md149',1,'']]],
  ['strong_20scaling_86',['Strong Scaling',['../examples.html#autotoc_md240',1,'']]],
  ['strong_20scaling_87',['Strong scaling',['../expectedPerformance.html#autotoc_md288',1,'']]],
  ['structure_88',['Tag Structure',['../docker.html#autotoc_md132',1,'']]],
  ['structure_20interaction_89',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md163',1,'']]],
  ['structures_90',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['sub_20grid_20bubble_20dynamics_20wilfong26_20sec_204_201_91',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md153',1,'']]],
  ['sub_20grid_20bubble_20models_92',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['submitting_20a_20pull_20request_93',['Submitting a Pull Request',['../contributing.html#autotoc_md118',1,'']]],
  ['suite_94',['Running the Test Suite',['../getting-started.html#autotoc_md299',1,'']]],
  ['sum_95',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md399',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_96',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md126',1,'']]],
  ['support_97',['Support',['../docker.html#autotoc_md134',1,'Architecture Support'],['../running.html#autotoc_md453',1,'Building with GPU Support']]],
  ['supported_20compilers_98',['Supported Compilers',['../running.html#autotoc_md455',1,'']]],
  ['supports_99',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['surface_20tension_100',['Surface Tension',['../physics_constraints.html#autotoc_md423',1,'']]],
  ['surface_20tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_101',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md173',1,'']]],
  ['surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_102',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md173',1,'']]],
  ['synchronization_20macros_103',['Synchronization Macros',['../gpuParallelization.html#autotoc_md316',1,'']]],
  ['system_104',['Working with the Precision System',['../contributing.html#autotoc_md107',1,'']]]
];
