var searchData=
[
  ['v_20verbose_0',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['v100_20gpu_1',['V100 GPU',['../expectedPerformance.html#autotoc_md271',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md274',1,'NVIDIA V100 GPU']]],
  ['validate_2',['validate',['../cli-reference.html#validate',1,'']]],
  ['validation_3',['Case Validation',['../troubleshooting.html#autotoc_md428',1,'']]],
  ['variable_4',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['variables_5',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md6',1,'']]],
  ['variables_20ordering_6',['Variables Ordering',['../case.html#autotoc_md22',1,'Conservative Variables Ordering'],['../case.html#autotoc_md23',1,'Primitive Variables Ordering']]],
  ['variants_7',['2.3 Other Model Variants',['../equations.html#autotoc_md128',1,'']]],
  ['vel_5fwrt_8',['vel_wrt',['../parameters.html#vel_wrt',1,'']]],
  ['velocities_9',['Centerline Velocities',['../examples.html#autotoc_md253',1,'']]],
  ['velocity_20field_20setup_10',['10. Velocity Field Setup',['../case.html#sec-velocity-field-setup',1,'']]],
  ['verbose_11',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['verbose_20runs_12',['Verbose Runs',['../troubleshooting.html#autotoc_md429',1,'']]],
  ['verbosity_20levels_13',['Verbosity Levels',['../troubleshooting.html#autotoc_md421',1,'']]],
  ['verbosity_20v_20verbose_14',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['verifying_20gpu_20detection_15',['Verifying GPU Detection',['../running.html#autotoc_md391',1,'']]],
  ['via_20apptainer_20singularity_16',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md112',1,'']]],
  ['via_20homebrew_20macos_17',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md280',1,'']]],
  ['violations_18',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md453',1,'']]],
  ['viscous_20shock_20tube_202d_19',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md234',1,'']]],
  ['viscous_20stress_20tensor_20viscous_20true_20',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md134',1,'']]],
  ['viscous_20true_21',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md134',1,'']]],
  ['visit_22',['Visualizing with VisIt',['../visualization.html#autotoc_md462',1,'']]],
  ['visualization_23',['Examples &amp;amp; Visualization',['../index.html#autotoc_md377',1,'']]],
  ['visualization_24',['visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md459',1,'Flow visualization']]],
  ['visualization_20at_20transitional_20state_25',['Liutex visualization at transitional state',['../examples.html#autotoc_md219',1,'']]],
  ['visualization_20on_20pace_20phoenix_26',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md464',1,'']]],
  ['visualization_2emd_27',['visualization.md',['../visualization_8md.html',1,'']]],
  ['visualizing_20data_20in_20cylindrical_20coordinates_28',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md461',1,'']]],
  ['visualizing_20with_20paraview_29',['Visualizing with Paraview',['../visualization.html#autotoc_md460',1,'']]],
  ['visualizing_20with_20visit_30',['Visualizing with VisIt',['../visualization.html#autotoc_md462',1,'']]],
  ['volume_20averaged_20bubble_20model_31',['9.2 Volume-Averaged Bubble Model',['../case.html#autotoc_md14',1,'']]],
  ['vortex_203d_32',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md254',1,'']]],
  ['vortex_20problem_202d_33',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md237',1,'']]],
  ['vs_20correctness_34',['Performance vs Correctness',['../troubleshooting.html#autotoc_md443',1,'']]]
];
