var searchData=
[
  ['pace_20paraview_20server_0',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md597',1,'']]],
  ['pace_20phoenix_1',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md594',1,'']]],
  ['pack_2',['packer pack',['../cli-reference.html#autotoc_md58',1,'']]],
  ['package_20macos_3',['Using the Homebrew package (macOS)',['../running.html#autotoc_md491',1,'']]],
  ['packer_4',['packer',['../cli-reference.html#packer',1,'']]],
  ['packer_20compare_5',['packer compare',['../cli-reference.html#autotoc_md59',1,'']]],
  ['packer_20pack_6',['packer pack',['../cli-reference.html#autotoc_md58',1,'']]],
  ['papers_7',['Papers',['../papers.html',1,'Papers'],['../papers.html#autotoc_md371',1,'Papers']]],
  ['papers_2emd_8',['papers.md',['../papers_8md.html',1,'']]],
  ['parallel_20loop_9',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md106',1,'']]],
  ['parallelization_10',['Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md346',1,'GPU Parallelization'],['../architecture.html#autotoc_md12',1,'MPI Parallelization']]],
  ['parameter_11',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md105',1,'']]],
  ['parameter_20constraint_20violations_12',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md562',1,'']]],
  ['parameter_20conventions_13',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['parameter_20descriptions_14',['Parameter Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['parameter_20families_15',['Parameter Families',['../parameters.html#autotoc_md374',1,'']]],
  ['parameter_20lookup_16',['Parameter Lookup',['../getting-started.html#autotoc_md343',1,'']]],
  ['parameter_20reference_17',['📖 Quick Parameter Reference',['../case_constraints.html#quick-parameter-reference',1,'']]],
  ['parameter_20sanity_20transformed_20gamma_18',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md437',1,'']]],
  ['parameters_19',['Parameters',['../parameters.html',1,'Case Parameters'],['../parameters.html#autotoc_md372',1,'Case Parameters'],['../equations.html#sec-nondim-inputs',1,'Non-Dimensionalization of Input Parameters'],['../case.html#autotoc_md18',1,'Parameters'],['../equations.html#sec-two-viscosities',1,'Two Different Viscosity Parameters']]],
  ['parameters_20',['parameters',['../examples.html#autotoc_md227',1,'Geometry and parameters'],['../examples.html#autotoc_md239',1,'Regime and parameters'],['../examples.html#autotoc_md245',1,'Regime and parameters'],['../examples.html#autotoc_md251',1,'Regime and parameters'],['../examples.html#autotoc_md270',1,'Regime and parameters'],['../examples.html#autotoc_md293',1,'Regime and parameters']]],
  ['parameters_20with_20bubbles_21',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['parameters_2emd_22',['parameters.md',['../parameters_8md.html',1,'']]],
  ['params_23',['params',['../cli-reference.html#params',1,'']]],
  ['paraview_24',['Visualizing with ParaView',['../visualization.html#autotoc_md590',1,'']]],
  ['paraview_20server_25',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md597',1,'']]],
  ['particle_5fcloud_26',['particle_cloud',['../parameters.html#particle_cloud',1,'']]],
  ['patch_20initial_20condition_20constraints_27',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md438',1,'']]],
  ['patch_20types_28',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['patch_20types_29',['Patch types',['../case.html#patch-types',1,'']]],
  ['patch_20within_20domain_30',['Patch Within Domain',['../physics_constraints.html#autotoc_md447',1,'']]],
  ['patch_5fbc_31',['patch_bc',['../parameters.html#patch_bc',1,'']]],
  ['patch_5fib_32',['patch_ib',['../parameters.html#patch_ib',1,'']]],
  ['patch_5ficpp_33',['patch_icpp',['../parameters.html#patch_icpp',1,'']]],
  ['patches_34',['Patches',['../case.html#sec-patches',1,'3. Patches'],['../case.html#sec-immersed-boundary-patches',1,'4. Immersed Boundary Patches'],['../case.html#boundary-condition-patches',1,'Boundary Condition Patches'],['../case.html#autotoc_md21',1,'Hard Coded Patches']]],
  ['patterns_35',['Patterns',['../case_constraints.html#common-configuration-patterns',1,'🚀 Common Configuration Patterns'],['../parameters.html#autotoc_md376',1,'Patterns'],['../parameters.html#autotoc_md378',1,'Patterns'],['../parameters.html#autotoc_md380',1,'Patterns'],['../parameters.html#autotoc_md382',1,'Patterns'],['../parameters.html#autotoc_md384',1,'Patterns'],['../parameters.html#autotoc_md386',1,'Patterns'],['../parameters.html#autotoc_md388',1,'Patterns'],['../parameters.html#autotoc_md390',1,'Patterns'],['../parameters.html#autotoc_md392',1,'Patterns'],['../parameters.html#autotoc_md394',1,'Patterns'],['../parameters.html#autotoc_md396',1,'Patterns'],['../parameters.html#autotoc_md398',1,'Patterns'],['../parameters.html#autotoc_md403',1,'Patterns'],['../parameters.html#autotoc_md405',1,'Patterns'],['../parameters.html#autotoc_md407',1,'Patterns'],['../parameters.html#autotoc_md409',1,'Patterns'],['../parameters.html#autotoc_md411',1,'Patterns'],['../parameters.html#autotoc_md413',1,'Patterns'],['../parameters.html#autotoc_md417',1,'Patterns'],['../parameters.html#autotoc_md419',1,'Patterns'],['../parameters.html#autotoc_md421',1,'Patterns'],['../parameters.html#autotoc_md423',1,'Patterns']]],
  ['pdes_36',['2. Governing PDEs',['../equations.html#autotoc_md143',1,'']]],
  ['perfectly_20stirred_20reactor_37',['Perfectly Stirred Reactor',['../examples.html#autotoc_md258',1,'']]],
  ['performance_38',['Performance',['../expectedPerformance.html#autotoc_md314',1,'Achieving Maximum Performance'],['../expectedPerformance.html',1,'Performance'],['../expectedPerformance.html#autotoc_md312',1,'Performance']]],
  ['performance_39',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md322',1,'']]],
  ['performance_20checklist_40',['Performance Checklist',['../expectedPerformance.html#autotoc_md319',1,'']]],
  ['performance_20nvidia_20uvm_41',['20. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md35',1,'']]],
  ['performance_20profiling_42',['Performance Profiling',['../troubleshooting.html#autotoc_md549',1,'']]],
  ['performance_20test_43',['Scaling and Performance test',['../examples.html#autotoc_md281',1,'']]],
  ['performance_20vs_20correctness_44',['Performance vs Correctness',['../troubleshooting.html#autotoc_md552',1,'']]],
  ['phase_20change_45',['Phase Change',['../physics_constraints.html#autotoc_md467',1,'']]],
  ['phase_20change_20model_46',['11. Phase Change Model',['../case.html#sec-phase-change',1,'']]],
  ['phase_20change_20relax_20true_20wilfong26_20sec_204_201_203_47',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md170',1,'']]],
  ['phase_20pipeline_48',['Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md85',1,'Three-Phase Pipeline']]],
  ['phoenix_49',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md594',1,'']]],
  ['physics_50',['Physics',['../architecture.html#autotoc_md13',1,'Adding New Physics'],['../physics_constraints.html#autotoc_md458',1,'Bubble Physics']]],
  ['physics_51',['Governing physics',['../examples.html#autotoc_md271',1,'']]],
  ['physics_20and_20analytic_20solution_52',['physics and analytic solution',['../examples.html#autotoc_md240',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md246',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md252',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md294',1,'Governing physics and analytic solution']]],
  ['physics_20and_20model_20consistency_53',['Physics and Model Consistency',['../contributing.html#autotoc_md99',1,'']]],
  ['physics_20constraints_54',['Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'How to Document Physics Constraints'],['../physics_constraints.html',1,'Physics Constraints']]],
  ['physics_20constraints_20reference_55',['Physics Constraints Reference',['../physics_constraints.html#autotoc_md433',1,'']]],
  ['physics_20models_56',['Physics Models',['../architecture.html#autotoc_md7',1,'Physics Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['physics_20warnings_57',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['physics_5fconstraints_2emd_58',['physics_constraints.md',['../physics__constraints_8md.html',1,'']]],
  ['pipeline_59',['Pipeline',['../contributing.html#autotoc_md116',1,'CI Pipeline'],['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md85',1,'Three-Phase Pipeline']]],
  ['pitfalls_60',['Common Pitfalls',['../contributing.html#autotoc_md94',1,'']]],
  ['playbook_61',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_62',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['plesset49_63',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['plot_20styling_64',['Plot styling',['../visualization.html#autotoc_md586',1,'']]],
  ['point_202d_65',['2D Triple Point (2D)',['../examples.html#autotoc_md304',1,'']]],
  ['points_66',['Points',['../expectedPerformance.html#autotoc_md329',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md330',1,'64M Grid Points']]],
  ['poiseuille_20channel_67',['Poiseuille Channel',['../examples.html#autotoc_md238',1,'2D Bingham (Yield-Stress) Poiseuille Channel'],['../examples.html#autotoc_md292',1,'2D General Herschel-Bulkley Poiseuille Channel'],['../examples.html#autotoc_md226',1,'2D IBM-Walled Power-Law Poiseuille Channel'],['../examples.html#autotoc_md244',1,'2D Power-Law (Shear-Thickening) Poiseuille Channel'],['../examples.html#autotoc_md250',1,'2D Power-Law (Shear-Thinning) Poiseuille Channel']]],
  ['polytropic_20false_20preston07_68',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['polytropic_20thermal_20model_20polytropic_20false_20preston07_69',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['portability_70',['Portability',['../contributing.html#autotoc_md101',1,'Compiler Portability'],['../docker.html#autotoc_md131',1,'For Portability'],['../docker.html#autotoc_md128',1,'Portability']]],
  ['positivity_71',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md436',1,'']]],
  ['post_20process_72',['Testing Post Process',['../testing.html#autotoc_md517',1,'']]],
  ['post_20processing_73',['Post-Processing',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['post_20processing_20output_20variable_74',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md112',1,'']]],
  ['power_20law_20poiseuille_20channel_75',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md226',1,'']]],
  ['power_20law_20shear_20thickening_20poiseuille_20channel_76',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md244',1,'']]],
  ['power_20law_20shear_20thinning_20poiseuille_20channel_77',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md250',1,'']]],
  ['power9_20cpu_78',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md331',1,'']]],
  ['power9_20cpu_20historical_79',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md326',1,'']]],
  ['pre_20process_80',['Pre-Process',['../architecture.html#autotoc_md11',1,'']]],
  ['precheck_81',['precheck',['../cli-reference.html#precheck',1,'']]],
  ['precision_20and_20type_20safety_82',['Precision and Type Safety',['../contributing.html#autotoc_md96',1,'']]],
  ['precision_20system_83',['Working with the Precision System',['../contributing.html#autotoc_md110',1,'']]],
  ['preprocessing_20failed_84',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md557',1,'']]],
  ['preston07_85',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['primitive_20variables_86',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['primitive_20variables_20ordering_87',['Primitive Variables Ordering',['../case.html#autotoc_md39',1,'']]],
  ['probe_88',['probe',['../parameters.html#probe',1,'']]],
  ['problem_201d_89',['problem 1D',['../examples.html#autotoc_md306',1,'Lax shock tube problem (1D)'],['../examples.html#autotoc_md223',1,'Shu-Osher problem (1D)'],['../examples.html#autotoc_md264',1,'Titarev-Toro problem (1D)']]],
  ['problem_202d_90',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md232',1,'']]],
  ['problem_202d_91',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md287',1,'']]],
  ['process_92',['Process',['../architecture.html#autotoc_md11',1,'Pre-Process'],['../testing.html#autotoc_md517',1,'Testing Post Process']]],
  ['processing_93',['Post-Processing',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['processing_20output_20variable_94',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md112',1,'']]],
  ['profiling_95',['Profiling',['../troubleshooting.html#autotoc_md551',1,'AMD GPU Profiling'],['../running.html#autotoc_md501',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md550',1,'NVIDIA GPU Profiling'],['../troubleshooting.html#autotoc_md549',1,'Performance Profiling']]],
  ['profiling_20flags_96',['Profiling Flags',['../troubleshooting.html#autotoc_md521',1,'']]],
  ['profiling_20for_20optimization_97',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md318',1,'']]],
  ['pt_20relaxation_20relax_5fmodel_205_20saurel08_98',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['ptg_20relaxation_20relax_5fmodel_206_20zein10_99',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['pull_20request_100',['Submitting a Pull Request',['../contributing.html#autotoc_md121',1,'']]],
  ['python_20toolchain_101',['Python Toolchain',['../contributing.html#autotoc_md100',1,'']]]
];
