var searchData=
[
  ['case_0',['Running an Example Case',['../md_getting-started.html#autotoc_md150',1,'']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../md_case__constraints.html',1,'']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../md_case__constraints.html#autotoc_md39',1,'']]],
  ['case_20files_3',['Case Files',['../md_case.html',1,'']]],
  ['case_2emd_4',['case.md',['../case_8md.html',1,'']]],
  ['case_5fconstraints_2emd_5',['case_constraints.md',['../case__constraints_8md.html',1,'']]],
  ['cases_6',['Cases',['../md_examples.html',1,'Example Cases'],['../md_running.html#autotoc_md188',1,'Restarting Cases']]],
  ['cavity_20problem_202d_7',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md97',1,'']]],
  ['centerline_20velocities_8',['Centerline Velocities',['../md_examples.html#autotoc_md99',1,'']]],
  ['cfl_20dt_202d_9',['2D IBM CFL dt (2D)',['../md_examples.html#autotoc_md79',1,'']]],
  ['change_20model_10',['11. Phase Change Model',['../md_case.html#autotoc_md25',1,'']]],
  ['characteristic_20boundary_20conditions_11',['Generalized Characteristic Boundary conditions',['../md_case.html#autotoc_md33',1,'']]],
  ['cli_12',['Docker CLI',['../md_docker.html#autotoc_md57',1,'']]],
  ['clusters_20via_20apptainer_20singularity_13',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md60',1,'']]],
  ['code_20api_20documentation_14',['Code/API Documentation',['../md_readme.html#autotoc_md179',1,'']]],
  ['coded_20patches_15',['Hard Coded Patches',['../md_case.html#autotoc_md10',1,'']]],
  ['command_20line_20arguments_16',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md3',1,'']]],
  ['common_20configuration_20patterns_17',['🚀 Common Configuration Patterns',['../md_case__constraints.html#autotoc_md43',1,'']]],
  ['compatibility_18',['Compatibility',['../md_case__constraints.html#autotoc_md44',1,'📊 Feature Compatibility'],['../md_case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['compiler_20agnostic_20tools_19',['Compiler agnostic tools',['../md_gpuParallelization.html#autotoc_md166',1,'']]],
  ['compiler_20documentation_20',['Compiler Documentation',['../md_gpuParallelization.html#autotoc_md175',1,'']]],
  ['compiler_20options_21',['NVHPC Compiler Options',['../md_gpuParallelization.html#autotoc_md171',1,'']]],
  ['compiler_20tools_22',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md168',1,'']]],
  ['component_20inert_20shock_20tube_23',['1D Multi-Component Inert Shock Tube',['../md_examples.html#autotoc_md127',1,'']]],
  ['component_20reactive_20shock_20tube_24',['1D Multi-Component Reactive Shock Tube',['../md_examples.html#autotoc_md89',1,'']]],
  ['computation_20macros_25',['Computation Macros',['../md_gpuParallelization.html#autotoc_md157',1,'']]],
  ['computational_20domain_26',['2. Computational Domain',['../md_case.html#autotoc_md7',1,'']]],
  ['condition_27',['Condition',['../md_examples.html#autotoc_md88',1,'Final Condition'],['../md_examples.html#autotoc_md98',1,'Final Condition'],['../md_examples.html#autotoc_md120',1,'Final Condition'],['../md_examples.html#autotoc_md131',1,'Final Condition'],['../md_examples.html#autotoc_md71',1,'Initial Condition'],['../md_examples.html#autotoc_md82',1,'Initial Condition'],['../md_examples.html#autotoc_md90',1,'Initial Condition'],['../md_examples.html#autotoc_md110',1,'Initial Condition'],['../md_examples.html#autotoc_md117',1,'Initial Condition'],['../md_examples.html#autotoc_md128',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_28',['Condition and Linear Theory',['../md_examples.html#autotoc_md78',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md122',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_29',['Initial Condition and Result',['../md_examples.html#autotoc_md113',1,'']]],
  ['condition_20density_30',['Condition Density',['../md_examples.html#autotoc_md93',1,'Final Condition (Density)'],['../md_examples.html#autotoc_md115',1,'Final Condition (Density)']]],
  ['condition_20patches_31',['Boundary Condition Patches',['../md_case.html#autotoc_md17',1,'']]],
  ['conditions_32',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md95',1,'']]],
  ['conditions_33',['conditions',['../md_case.html#autotoc_md32',1,'Boundary conditions'],['../md_case.html#autotoc_md33',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20patterns_34',['🚀 Common Configuration Patterns',['../md_case__constraints.html#autotoc_md43',1,'']]],
  ['conservative_20variables_20ordering_35',['Conservative Variables Ordering',['../md_case.html#autotoc_md36',1,'']]],
  ['constant_20time_20stepping_36',['Constant Time-Stepping',['../md_case.html#autotoc_md18',1,'']]],
  ['containers_37',['Containers',['../md_docker.html',1,'Containers'],['../md_docker.html#autotoc_md58',1,'Details on Running Containers'],['../md_getting-started.html#autotoc_md148',1,'Using Containers']]],
  ['control_20macros_38',['Data Control Macros',['../md_gpuParallelization.html#autotoc_md159',1,'']]],
  ['coordinates_39',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['coordinates_40',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md195',1,'']]],
  ['cpu_41',['CPU',['../md_expectedPerformance.html#autotoc_md137',1,'IBM Power9 CPU'],['../md_expectedPerformance.html#autotoc_md142',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_42',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md168',1,'']]],
  ['cray_20general_20options_43',['Cray General Options',['../md_gpuParallelization.html#autotoc_md169',1,'']]],
  ['cray_20openacc_20options_44',['Cray OpenACC Options',['../md_gpuParallelization.html#autotoc_md170',1,'']]],
  ['creating_20tests_45',['Creating Tests',['../md_testing.html#autotoc_md191',1,'']]],
  ['creator_20guide_46',['Case Creator Guide',['../md_case__constraints.html',1,'']]],
  ['customizing_20the_20script_47',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md200',1,'']]],
  ['cylindrical_20coordinates_48',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['cylindrical_20coordinates_49',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md195',1,'']]]
];
