var searchData=
[
  ['of_20classes_20commander89_20ando11_0',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md141',1,'']]],
  ['of_20input_20parameters_1',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['of_20merit_3a_20grind_20time_20performance_2',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md269',1,'']]],
  ['of_20primitive_20variables_3',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md6',1,'']]],
  ['of_20state_4',['3. Equations of State',['../equations.html#autotoc_md131',1,'']]],
  ['omega_5fwrt_5',['omega_wrt',['../parameters.html#omega_wrt',1,'']]],
  ['on_20gpus_6',['on GPUs',['../running.html#autotoc_md438',1,'Running on GPUs'],['../running.html#autotoc_md440',1,'Running on GPUs']]],
  ['on_20hpc_7',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md502',1,'']]],
  ['on_20pace_20phoenix_8',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md516',1,'']]],
  ['on_20running_20containers_9',['Details on Running Containers',['../docker.html#autotoc_md110',1,'']]],
  ['only_10',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md180',1,'']]],
  ['openacc_20errors_11',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['openacc_20options_12',['OpenACC Options',['../gpuParallelization.html#autotoc_md311',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md314',1,'NVHPC OpenACC Options']]],
  ['openmp_20options_13',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md315',1,'']]],
  ['openmp_20tools_14',['OpenMP tools',['../gpuParallelization.html#autotoc_md308',1,'']]],
  ['optimization_15',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md265',1,'']]],
  ['optimization_16',['When to use case optimization',['../expectedPerformance.html#autotoc_md263',1,'']]],
  ['optimization_20flags_17',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md264',1,'']]],
  ['optimization_20recommended_18',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md262',1,'']]],
  ['optional_20accepting_20command_20line_20arguments_19',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['options_20',['Options',['../running.html#autotoc_md450',1,'Batch Options'],['../cli-reference.html#autotoc_md60',1,'Common Options'],['../gpuParallelization.html#autotoc_md310',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md311',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md312',1,'NVHPC Compiler Options'],['../gpuParallelization.html#autotoc_md313',1,'NVHPC General Options'],['../gpuParallelization.html#autotoc_md314',1,'NVHPC OpenACC Options'],['../gpuParallelization.html#autotoc_md315',1,'NVHPC OpenMP Options']]],
  ['or_20hangs_21',['MPI errors or hangs',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['ordering_22',['Ordering',['../case.html#autotoc_md22',1,'Conservative Variables Ordering'],['../case.html#autotoc_md23',1,'Primitive Variables Ordering']]],
  ['osher_20problem_201d_23',['Shu-Osher problem (1D)',['../examples.html#autotoc_md206',1,'']]],
  ['other_20commands_24',['Other Commands',['../cli-reference.html#autotoc_md57',1,'']]],
  ['other_20jobs_25',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md100',1,'']]],
  ['other_20model_20variants_26',['2.3 Other Model Variants',['../equations.html#autotoc_md129',1,'']]],
  ['other_20optimization_20flags_27',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md264',1,'']]],
  ['out_28',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['output_29',['Output',['../case.html#sec-formatted-output',1,'7. Formatted Output'],['../physics_constraints.html#autotoc_md426',1,'FFT Output'],['../physics_constraints.html#autotoc_md425',1,'Vorticity Output']]],
  ['output_30',['Serial data output',['../visualization.html#autotoc_md515',1,'']]],
  ['output_20location_31',['Test Output Location',['../troubleshooting.html#autotoc_md488',1,'']]],
  ['output_20variable_32',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['overview_33',['Overview',['../equations.html#autotoc_md123',1,'1. Overview'],['../contributing.html#autotoc_md67',1,'Architecture Overview'],['../cli-reference.html#autotoc_md30',1,'Overview'],['../parameters.html#autotoc_md319',1,'Overview']]]
];
