var searchData=
[
  ['case_0',['Running an Example Case',['../md_getting-started.html#autotoc_md151',1,'']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../md_case__constraints.html',1,'']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../md_case__constraints.html#autotoc_md40',1,'']]],
  ['case_20files_3',['Case Files',['../md_case.html',1,'']]],
  ['case_2emd_4',['case.md',['../case_8md.html',1,'']]],
  ['case_5fconstraints_2emd_5',['case_constraints.md',['../case__constraints_8md.html',1,'']]],
  ['cases_6',['Cases',['../md_examples.html',1,'Example Cases'],['../md_running.html#autotoc_md189',1,'Restarting Cases']]],
  ['cavity_20problem_202d_7',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md98',1,'']]],
  ['centerline_20velocities_8',['Centerline Velocities',['../md_examples.html#autotoc_md100',1,'']]],
  ['cfl_20dt_202d_9',['2D IBM CFL dt (2D)',['../md_examples.html#autotoc_md80',1,'']]],
  ['change_20model_10',['11. Phase Change Model',['../md_case.html#autotoc_md25',1,'']]],
  ['characteristic_20boundary_20conditions_11',['Generalized Characteristic Boundary conditions',['../md_case.html#autotoc_md34',1,'']]],
  ['chemistry_12',['17. Chemistry',['../md_case.html#autotoc_md31',1,'']]],
  ['cli_13',['Docker CLI',['../md_docker.html#autotoc_md58',1,'']]],
  ['clusters_20via_20apptainer_20singularity_14',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md61',1,'']]],
  ['code_20api_20documentation_15',['Code/API Documentation',['../md_readme.html#autotoc_md180',1,'']]],
  ['coded_20patches_16',['Hard Coded Patches',['../md_case.html#autotoc_md10',1,'']]],
  ['command_20line_20arguments_17',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md3',1,'']]],
  ['common_20configuration_20patterns_18',['🚀 Common Configuration Patterns',['../md_case__constraints.html#autotoc_md44',1,'']]],
  ['compatibility_19',['Compatibility',['../md_case__constraints.html#autotoc_md45',1,'📊 Feature Compatibility'],['../md_case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['compiler_20agnostic_20tools_20',['Compiler agnostic tools',['../md_gpuParallelization.html#autotoc_md167',1,'']]],
  ['compiler_20documentation_21',['Compiler Documentation',['../md_gpuParallelization.html#autotoc_md176',1,'']]],
  ['compiler_20options_22',['NVHPC Compiler Options',['../md_gpuParallelization.html#autotoc_md172',1,'']]],
  ['compiler_20tools_23',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md169',1,'']]],
  ['component_20inert_20shock_20tube_24',['1D Multi-Component Inert Shock Tube',['../md_examples.html#autotoc_md128',1,'']]],
  ['component_20reactive_20shock_20tube_25',['1D Multi-Component Reactive Shock Tube',['../md_examples.html#autotoc_md90',1,'']]],
  ['computation_20macros_26',['Computation Macros',['../md_gpuParallelization.html#autotoc_md158',1,'']]],
  ['computational_20domain_27',['2. Computational Domain',['../md_case.html#autotoc_md7',1,'']]],
  ['condition_28',['Condition',['../md_examples.html#autotoc_md89',1,'Final Condition'],['../md_examples.html#autotoc_md99',1,'Final Condition'],['../md_examples.html#autotoc_md121',1,'Final Condition'],['../md_examples.html#autotoc_md132',1,'Final Condition'],['../md_examples.html#autotoc_md72',1,'Initial Condition'],['../md_examples.html#autotoc_md83',1,'Initial Condition'],['../md_examples.html#autotoc_md91',1,'Initial Condition'],['../md_examples.html#autotoc_md111',1,'Initial Condition'],['../md_examples.html#autotoc_md118',1,'Initial Condition'],['../md_examples.html#autotoc_md129',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_29',['Condition and Linear Theory',['../md_examples.html#autotoc_md79',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md123',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_30',['Initial Condition and Result',['../md_examples.html#autotoc_md114',1,'']]],
  ['condition_20density_31',['Condition Density',['../md_examples.html#autotoc_md94',1,'Final Condition (Density)'],['../md_examples.html#autotoc_md116',1,'Final Condition (Density)']]],
  ['condition_20patches_32',['Boundary Condition Patches',['../md_case.html#autotoc_md17',1,'']]],
  ['conditions_33',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md96',1,'']]],
  ['conditions_34',['conditions',['../md_case.html#autotoc_md33',1,'Boundary conditions'],['../md_case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20patterns_35',['🚀 Common Configuration Patterns',['../md_case__constraints.html#autotoc_md44',1,'']]],
  ['conservative_20variables_20ordering_36',['Conservative Variables Ordering',['../md_case.html#autotoc_md37',1,'']]],
  ['constant_20time_20stepping_37',['Constant Time-Stepping',['../md_case.html#autotoc_md18',1,'']]],
  ['containers_38',['Containers',['../md_docker.html',1,'Containers'],['../md_docker.html#autotoc_md59',1,'Details on Running Containers'],['../md_getting-started.html#autotoc_md149',1,'Using Containers']]],
  ['control_20macros_39',['Data Control Macros',['../md_gpuParallelization.html#autotoc_md160',1,'']]],
  ['coordinates_40',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['coordinates_41',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md196',1,'']]],
  ['cpu_42',['CPU',['../md_expectedPerformance.html#autotoc_md138',1,'IBM Power9 CPU'],['../md_expectedPerformance.html#autotoc_md143',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_43',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md169',1,'']]],
  ['cray_20general_20options_44',['Cray General Options',['../md_gpuParallelization.html#autotoc_md170',1,'']]],
  ['cray_20openacc_20options_45',['Cray OpenACC Options',['../md_gpuParallelization.html#autotoc_md171',1,'']]],
  ['creating_20tests_46',['Creating Tests',['../md_testing.html#autotoc_md192',1,'']]],
  ['creator_20guide_47',['Case Creator Guide',['../md_case__constraints.html',1,'']]],
  ['customizing_20the_20script_48',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md201',1,'']]],
  ['cylindrical_20coordinates_49',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['cylindrical_20coordinates_50',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md196',1,'']]]
];
