var searchData=
[
  ['warnings_0',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['weak_20scaling_1',['Weak Scaling',['../examples.html#autotoc_md242',1,'']]],
  ['weak_20scaling_2',['Weak scaling',['../expectedPerformance.html#autotoc_md287',1,'']]],
  ['weak_20scaling_3',['GPU weak scaling',['../expectedPerformance.html#autotoc_md288',1,'']]],
  ['weno_20reconstruction_4',['WENO Reconstruction',['../physics_constraints.html#autotoc_md432',1,'']]],
  ['weno_20weno_5forder_203_205_207_5',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['weno_5forder_203_205_207_6',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['what_20happens_20at_20each_20stage_7',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['when_20to_20use_20case_20optimization_8',['When to use case optimization',['../expectedPerformance.html#autotoc_md280',1,'']]],
  ['wilfong25a_9',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['wilfong26_20sec_202_202_10',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md148',1,'']]],
  ['wilfong26_20sec_202_203_11',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md153',1,'']]],
  ['wilfong26_20sec_204_201_12',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md155',1,'']]],
  ['wilfong26_20sec_204_201_201_13',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md207',1,'']]],
  ['wilfong26_20sec_204_201_2010_14',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md179',1,'']]],
  ['wilfong26_20sec_204_201_203_15',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md169',1,'']]],
  ['wilfong26_20sec_204_201_206_16',['Wilfong26 Sec 4 1 6',['../equations.html#autotoc_md166',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md167',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)']]],
  ['wilfong26_20sec_204_201_207_17',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md173',1,'']]],
  ['wilfong26_20sec_204_201_208_18',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md175',1,'']]],
  ['wilfong26_20sec_204_201_209_19',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md178',1,'']]],
  ['wilfong26_20sec_204_202_204_20',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md209',1,'']]],
  ['with_20bubbles_21',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['with_20fewer_20ranks_22',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md499',1,'']]],
  ['with_20gpu_20openacc_20errors_23',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md517',1,'']]],
  ['with_20gpu_20support_24',['Building with GPU Support',['../running.html#autotoc_md455',1,'']]],
  ['with_20mfc_20sh_20viz_25',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md535',1,'']]],
  ['with_20paraview_26',['Visualizing with ParaView',['../visualization.html#autotoc_md549',1,'']]],
  ['with_20the_20precision_20system_27',['Working with the Precision System',['../contributing.html#autotoc_md109',1,'']]],
  ['with_20visit_28',['Visualizing with VisIt',['../visualization.html#autotoc_md551',1,'']]],
  ['within_20domain_29',['Patch Within Domain',['../physics_constraints.html#autotoc_md407',1,'']]],
  ['worked_20examples_30',['Worked Examples',['../equations.html#sec-nondim-example',1,'']]],
  ['workflow_31',['Workflow',['../troubleshooting.html#autotoc_md483',1,'Debugging Workflow'],['../contributing.html#autotoc_md88',1,'Development Workflow']]],
  ['working_20with_20the_20precision_20system_32',['Working with the Precision System',['../contributing.html#autotoc_md109',1,'']]],
  ['write_20a_20gpu_20parallel_20loop_33',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md105',1,'']]],
  ['wrong_20or_20has_20artifacts_34',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md530',1,'']]]
];
