var searchData=
[
  ['a_20fortran_20compiler_0',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md497',1,'']]],
  ['a_20gpu_20parallel_20loop_1',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['a_20new_20case_2',['Creating a New Case',['../getting-started.html#autotoc_md288',1,'']]],
  ['a_20new_20fortran_20module_3',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['a_20new_20simulation_20parameter_4',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['a_20post_20processing_20output_20variable_5',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['a_20pull_20request_6',['Submitting a Pull Request',['../contributing.html#autotoc_md104',1,'']]],
  ['a_20test_20case_7',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['about_8',['About',['../index.html#autotoc_md430',1,'']]],
  ['accepting_20command_20line_20arguments_9',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['achieving_20maximum_20performance_10',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md260',1,'']]],
  ['acoustic_11',['acoustic',['../parameters.html#acoustic',1,'']]],
  ['acoustic_20source_12',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['acoustic_20sources_13',['Acoustic Sources',['../physics_constraints.html#autotoc_md419',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md420',1,'Acoustic Sources']]],
  ['acoustic_20sources_20acoustic_5fsource_20true_14',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['acoustic_20supports_15',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['acoustic_5fsource_20true_16',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['adap_5fdt_20true_17',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['adaptive_20time_20stepping_18',['Adaptive Time-Stepping',['../case.html#autotoc_md12',1,'']]],
  ['adaptive_20time_20stepping_20adap_5fdt_20true_19',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['add_20a_20new_20simulation_20parameter_20',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['add_20a_20post_20processing_20output_20variable_21',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['add_20a_20test_20case_22',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['advanced_20examples_23',['🔴 Advanced Examples',['../case_constraints.html#autotoc_md27',1,'']]],
  ['advanced_20topics_24',['Advanced Topics',['../index.html#autotoc_md428',1,'']]],
  ['agnostic_20tools_25',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md305',1,'']]],
  ['algorithm_26',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['all_20other_20jobs_27',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md100',1,'']]],
  ['allocate_20and_20manage_20gpu_20arrays_28',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['allocation_29',['Memory and Allocation',['../contributing.html#autotoc_md80',1,'']]],
  ['alpha_20rho_20consistency_30',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md384',1,'']]],
  ['alpha_5frho_5fe_5fwrt_31',['alpha_rho_e_wrt',['../parameters.html#alpha_rho_e_wrt',1,'']]],
  ['alpha_5frho_5fwrt_32',['alpha_rho_wrt',['../parameters.html#alpha_rho_wrt',1,'']]],
  ['alpha_5fwrt_33',['alpha_wrt',['../parameters.html#alpha_wrt',1,'']]],
  ['alternative_20sound_20speed_34',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md410',1,'']]],
  ['amd_20gpu_20profiling_35',['AMD GPU Profiling',['../troubleshooting.html#autotoc_md492',1,'']]],
  ['amd_20gpus_36',['AMD GPUs',['../running.html#autotoc_md444',1,'']]],
  ['amd_20mi250x_20gpu_37',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md270',1,'']]],
  ['an_20example_20case_38',['Running an Example Case',['../getting-started.html#autotoc_md285',1,'']]],
  ['analytical_20definition_20of_20primitive_20variables_39',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md6',1,'']]],
  ['and_20allocation_40',['Memory and Allocation',['../contributing.html#autotoc_md80',1,'']]],
  ['and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_41',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md156',1,'']]],
  ['and_20dimensional_20consistency_42',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md391',1,'']]],
  ['and_20final_20conditions_43',['Density Initial and Final Conditions',['../examples.html#autotoc_md217',1,'']]],
  ['and_20geometry_44',['Domain and Geometry',['../physics_constraints.html#autotoc_md386',1,'']]],
  ['and_20gpu_45',['Fypp and GPU',['../contributing.html#autotoc_md86',1,'']]],
  ['and_20indexing_46',['Array Bounds and Indexing',['../contributing.html#autotoc_md78',1,'']]],
  ['and_20linear_20theory_47',['and Linear Theory',['../examples.html#autotoc_md212',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md246',1,'Final Condition and Linear Theory']]],
  ['and_20manage_20gpu_20arrays_48',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['and_20merge_49',['Code Review and Merge',['../contributing.html#autotoc_md105',1,'']]],
  ['and_20model_20consistency_50',['Physics and Model Consistency',['../contributing.html#autotoc_md82',1,'']]],
  ['and_20performance_20test_51',['Scaling and Performance test',['../examples.html#autotoc_md223',1,'']]],
  ['and_20result_52',['Initial Condition and Result',['../examples.html#autotoc_md248',1,'']]],
  ['and_20test_20matrix_53',['Build and Test Matrix',['../contributing.html#autotoc_md101',1,'']]],
  ['and_20tips_20for_20gpus_54',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['and_20type_20safety_55',['Precision and Type Safety',['../contributing.html#autotoc_md79',1,'']]],
  ['ando11_56',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md140',1,'']]],
  ['api_20documentation_57',['Macro API Documentation',['../gpuParallelization.html#autotoc_md292',1,'']]],
  ['apptainer_20singularity_58',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md112',1,'']]],
  ['architecture_20notes_59',['Architecture Notes',['../contributing.html#autotoc_md85',1,'']]],
  ['architecture_20overview_60',['Architecture Overview',['../contributing.html#autotoc_md67',1,'']]],
  ['architecture_20support_61',['Architecture Support',['../docker.html#autotoc_md120',1,'']]],
  ['arguments_62',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['array_20bounds_20and_20indexing_63',['Array Bounds and Indexing',['../contributing.html#autotoc_md78',1,'']]],
  ['arrays_64',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['artificial_20mach_20number_65',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['at_20final_20time_66',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md198',1,'']]],
  ['at_20transitional_20state_67',['Liutex visualization at transitional state',['../examples.html#autotoc_md219',1,'']]],
  ['authors_68',['Authors',['../authors.html',1,'Authors'],['../authors.html#autotoc_md0',1,'Authors']]],
  ['authors_2emd_69',['authors.md',['../authors_8md.html',1,'']]],
  ['averaged_20bubble_20model_70',['Averaged Bubble Model',['../case.html#autotoc_md13',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md14',1,'9.2 Volume-Averaged Bubble Model']]]
];
