var searchData=
[
  ['ranks_0',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md435',1,'']]],
  ['rayleigh_20taylor_20instability_202d_1',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md182',1,'']]],
  ['rayleigh_20taylor_20instability_203d_2',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md216',1,'']]],
  ['reactive_20shock_20tube_3',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md184',1,'']]],
  ['reactor_4',['Perfectly Stirred Reactor',['../examples.html#autotoc_md167',1,'']]],
  ['readme_2emd_5',['readme.md',['../readme_8md.html',1,'']]],
  ['rebuild_6',['Clean Rebuild',['../troubleshooting.html#autotoc_md429',1,'']]],
  ['recommended_7',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md232',1,'']]],
  ['reference_8',['Reference',['../case_constraints.html#autotoc_md53',1,'📖 Quick Parameter Reference'],['../parameters.html',1,'Case Parameters Reference'],['../parameters.html#autotoc_md287',1,'Case Parameters Reference'],['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md55',1,'Command Line Reference'],['../parameters.html#autotoc_md377',1,'Command Line Reference'],['../cli-reference.html#autotoc_md57',1,'Quick Reference'],['../troubleshooting.html#autotoc_md414',1,'Quick Reference'],['../index.html#autotoc_md379',1,'Reference']]],
  ['references_9',['References',['../references.html',1,'References'],['../references.html#autotoc_md384',1,'References']]],
  ['references_2emd_10',['references.md',['../references_8md.html',1,'']]],
  ['regenerating_20golden_20files_11',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md441',1,'']]],
  ['remote_20visualization_20on_20pace_20phoenix_12',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md468',1,'']]],
  ['request_13',['Submitting a Pull Request',['../contributing.html#autotoc_md149',1,'']]],
  ['restarting_20cases_14',['Restarting Cases',['../running.html#autotoc_md407',1,'']]],
  ['result_15',['Result',['../examples.html#autotoc_md219',1,'Initial Condition and Result'],['../examples.html#autotoc_md172',1,'Result'],['../examples.html#autotoc_md178',1,'Result'],['../examples.html#autotoc_md181',1,'Result'],['../examples.html#autotoc_md200',1,'Result'],['../examples.html#autotoc_md221',1,'Result']]],
  ['results_16',['Results',['../expectedPerformance.html#autotoc_md238',1,'Benchmark Results'],['../examples.html#autotoc_md186',1,'Results'],['../examples.html#autotoc_md215',1,'Results']]],
  ['review_20and_20merge_17',['Code Review and Merge',['../contributing.html#autotoc_md150',1,'']]],
  ['richtmyer_20meshkov_20instability_202d_18',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md173',1,'']]],
  ['riemann_20solvers_19',['⚙️ Riemann Solvers',['../case_constraints.html#autotoc_md51',1,'']]],
  ['riemann_20test_202d_20',['2D Riemann Test (2D)',['../examples.html#autotoc_md187',1,'']]],
  ['rules_21',['Hard Rules',['../contributing.html#autotoc_md120',1,'']]],
  ['run_22',['run',['../cli-reference.html#autotoc_md61',1,'']]],
  ['run_20fails_23',['Run Fails?',['../troubleshooting.html#autotoc_md421',1,'']]],
  ['running_24',['Running',['../running.html',1,'Running'],['../running.html#autotoc_md385',1,'Running']]],
  ['running_20an_20example_20case_25',['Running an Example Case',['../getting-started.html#autotoc_md256',1,'']]],
  ['running_20containers_26',['Details on Running Containers',['../docker.html#autotoc_md155',1,'']]],
  ['running_20on_20gpus_27',['Running on GPUs',['../running.html#autotoc_md390',1,'Running on GPUs'],['../running.html#autotoc_md392',1,'Running on GPUs']]],
  ['running_20pace_20paraview_20server_28',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md471',1,'']]],
  ['running_20specific_20tests_29',['Running Specific Tests',['../troubleshooting.html#autotoc_md438',1,'']]],
  ['running_20the_20test_20suite_30',['Running the Test Suite',['../getting-started.html#autotoc_md255',1,'']]],
  ['running_20with_20fewer_20ranks_31',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md435',1,'']]],
  ['running_2emd_32',['running.md',['../running_8md.html',1,'']]],
  ['runs_33',['Runs',['../running.html#autotoc_md409',1,'Example Runs'],['../troubleshooting.html#autotoc_md433',1,'Verbose Runs']]],
  ['runs_20first_20blocks_20all_20other_20jobs_34',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['runtime_35',['1. Runtime',['../case.html#autotoc_md6',1,'']]],
  ['runtime_20debugging_36',['Runtime Debugging',['../troubleshooting.html#autotoc_md431',1,'']]],
  ['runtime_20errors_37',['Common Runtime Errors',['../troubleshooting.html#autotoc_md456',1,'']]]
];
