var searchData=
[
  ['h5py_20is_20required_20to_20read_20silo_20hdf5_20files_0',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md530',1,'']]],
  ['halo_20exchange_1',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md109',1,'']]],
  ['handling_2',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['hangs_3',['MPI errors or hangs',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['happens_20at_20each_20stage_4',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['hard_20coded_20patches_5',['Hard Coded Patches',['../case.html#autotoc_md21',1,'']]],
  ['hard_20rules_6',['Hard Rules',['../contributing.html#autotoc_md90',1,'']]],
  ['hardcodied_20ic_20example_7',['2D Hardcodied IC Example',['../examples.html#autotoc_md264',1,'']]],
  ['harten83_8',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md192',1,'']]],
  ['has_20artifacts_9',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md531',1,'']]],
  ['hdf5_20files_10',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md530',1,'']]],
  ['helmholtz_20instability_202d_11',['Kelvin-Helmholtz Instability (2D)',['../examples.html#autotoc_md237',1,'']]],
  ['help_12',['Getting Help',['../troubleshooting.html#autotoc_md533',1,'']]],
  ['help_13',['help',['../cli-reference.html#help',1,'']]],
  ['helpful_20tools_14',['Helpful Tools',['../getting-started.html#autotoc_md305',1,'']]],
  ['historical_15',['historical',['../expectedPerformance.html#autotoc_md289',1,'IBM Power9 CPU (historical)'],['../expectedPerformance.html#autotoc_md288',1,'NVIDIA V100 GPU (historical)']]],
  ['hll_20riemann_5fsolver_201_20harten83_16',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md192',1,'']]],
  ['hllc_20riemann_5fsolver_202_20toro94_17',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md193',1,'']]],
  ['hlld_20riemann_5fsolver_204_20mhd_20only_18',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md195',1,'']]],
  ['homebrew_20macos_19',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md297',1,'']]],
  ['homebrew_20package_20macos_20',['Using the Homebrew package (macOS)',['../running.html#autotoc_md451',1,'']]],
  ['how_20to_20add_20a_20new_20simulation_20parameter_21',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md103',1,'']]],
  ['how_20to_20add_20a_20post_20processing_20output_20variable_22',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md110',1,'']]],
  ['how_20to_20add_20a_20test_20case_23',['How to Add a Test Case',['../contributing.html#autotoc_md106',1,'']]],
  ['how_20to_20allocate_20and_20manage_20gpu_20arrays_24',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md105',1,'']]],
  ['how_20to_20create_20a_20new_20fortran_20module_25',['How to Create a New Fortran Module',['../contributing.html#autotoc_md107',1,'']]],
  ['how_20to_20document_20physics_20constraints_26',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['how_20to_20extend_20mpi_20halo_20exchange_27',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md109',1,'']]],
  ['how_20to_20guides_28',['How-To Guides',['../contributing.html#autotoc_md102',1,'']]],
  ['how_20to_20write_20a_20gpu_20parallel_20loop_29',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md104',1,'']]],
  ['hpc_30',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md519',1,'']]],
  ['hyperelastic_20model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_31',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md166',1,'']]],
  ['hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_32',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md166',1,'']]],
  ['hypoelastic_20model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_33',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md165',1,'']]],
  ['hypoelasticity_34',['Hypoelasticity',['../physics_constraints.html#autotoc_md427',1,'']]],
  ['hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_35',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md165',1,'']]]
];
