var searchData=
[
  ['d_20debug_20log_0',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['damage_20cont_5fdamage_20true_20cao19_20spratt24_20sec_204_201_202_1',['7.2 Continuum Damage (&lt;span class=&quot;tt&quot;&gt;cont_damage = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_cao19&quot;&gt;[10]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_spratt24&quot;&gt;[48]&lt;/a&gt; Sec. 4.1.2)',['../equations.html#autotoc_md171',1,'']]],
  ['data_2',['Exploring available data',['../visualization.html#autotoc_md622',1,'']]],
  ['data_20control_20macros_3',['Data Control Macros',['../gpuParallelization.html#autotoc_md370',1,'']]],
  ['data_20flow_4',['Data Flow',['../gpuParallelization.html#autotoc_md366',1,'Data Flow'],['../contributing.html#autotoc_md87',1,'Simulation Data Flow']]],
  ['data_20in_20cylindrical_20coordinates_5',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md635',1,'']]],
  ['data_20output_6',['Serial data output',['../visualization.html#autotoc_md637',1,'']]],
  ['data_20structures_7',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['data_20type_20meanings_8',['Data Type Meanings',['../gpuParallelization.html#autotoc_md365',1,'']]],
  ['debug_20builds_9',['Debug Builds',['../troubleshooting.html#autotoc_md575',1,'']]],
  ['debug_20log_10',['Debug Log',['../troubleshooting.html#autotoc_md583',1,'']]],
  ['debug_20log_11',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['debug_20logging_20d_20debug_20log_12',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['debugging_13',['Debugging',['../troubleshooting.html#autotoc_md573',1,'Build Debugging'],['../contributing.html#autotoc_md117',1,'Debugging'],['../troubleshooting.html#autotoc_md580',1,'Runtime Debugging'],['../troubleshooting.html#autotoc_md586',1,'Test Debugging']]],
  ['debugging_20flags_14',['Debugging Flags',['../troubleshooting.html#autotoc_md564',1,'']]],
  ['debugging_20tools_20and_20tips_20for_20gpus_15',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md378',1,'']]],
  ['debugging_20workflow_16',['Debugging Workflow',['../troubleshooting.html#autotoc_md568',1,'']]],
  ['definition_20of_20primitive_20variables_17',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['density_18',['Density',['../examples.html#autotoc_md286',1,'Density'],['../examples.html#autotoc_md218',1,'Final Condition (Density)'],['../examples.html#autotoc_md263',1,'Final Condition (Density)']]],
  ['density_20initial_20and_20final_20conditions_19',['Density Initial and Final Conditions',['../examples.html#autotoc_md258',1,'']]],
  ['density_20norms_20',['Density Norms',['../examples.html#autotoc_md287',1,'']]],
  ['dependent_20equation_20of_20state_21',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md470',1,'']]],
  ['descriptions_22',['Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['design_20playbook_23',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['desktop_20gui_24',['Docker Desktop GUI',['../docker.html#autotoc_md128',1,'']]],
  ['details_25',['Tag Details',['../docker.html#autotoc_md136',1,'']]],
  ['details_20on_20running_20containers_26',['Details on Running Containers',['../docker.html#autotoc_md130',1,'']]],
  ['detected_27',['detected',['../troubleshooting.html#autotoc_md607',1,'&quot;NaN detected&quot;'],['../troubleshooting.html#autotoc_md608',1,'GPU not detected']]],
  ['detection_28',['Verifying GPU Detection',['../running.html#autotoc_md544',1,'']]],
  ['developer_20notes_20on_20non_20conservative_20term_20implementation_29',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md200',1,'']]],
  ['development_30',['Development',['../index.html#autotoc_md532',1,'']]],
  ['development_20commands_31',['Development Commands',['../cli-reference.html#autotoc_md65',1,'']]],
  ['development_20workflow_32',['Development Workflow',['../contributing.html#autotoc_md90',1,'']]],
  ['device_20codegen_20instability_20worked_20around_20in_20the_20build_33',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md389',1,'']]],
  ['device_20helpers_34',['Writing GPU_ROUTINE Device Helpers',['../gpuParallelization.html#autotoc_md376',1,'']]],
  ['differences_20fd_5forder_201_202_204_35',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md206',1,'']]],
  ['different_20viscosity_20parameters_36',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['dimensional_20bubble_20dynamics_37',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dimensional_20consistency_38',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md485',1,'']]],
  ['dimensional_20framework_39',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['dimensional_20handling_40',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['dimensionality_41',['Dimensionality',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['dimensionality_42',['Boundary-condition patch geometry has to match the dimensionality',['../examples.html#autotoc_md303',1,'']]],
  ['dimensionalization_43',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensionalization_20of_20input_20parameters_44',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['dimensionalizing_20a_20bubble_20case_45',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['dimensions_46',['Dimensions',['../getting-started.html#autotoc_md356',1,'Units and Dimensions'],['../physics_constraints.html#autotoc_md486',1,'Velocity Components in Inactive Dimensions']]],
  ['dimensions_20and_20non_20dimensionalization_47',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensions_20in_20dimensions_20out_48',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['dimensions_20out_49',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['directory_20found_50',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md612',1,'']]],
  ['directory_20layout_51',['Directory Layout',['../architecture.html#autotoc_md1',1,'Directory Layout'],['../contributing.html#autotoc_md86',1,'Directory Layout']]],
  ['docker_52',['Navigating Docker',['../docker.html#autotoc_md127',1,'']]],
  ['docker_20cli_53',['Docker CLI',['../docker.html#autotoc_md129',1,'']]],
  ['docker_20desktop_20gui_54',['Docker Desktop GUI',['../docker.html#autotoc_md128',1,'']]],
  ['docker_2emd_55',['docker.md',['../docker_8md.html',1,'']]],
  ['document_20physics_20constraints_56',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['documentation_57',['Documentation',['../gpuParallelization.html#autotoc_md392',1,'Compiler Documentation'],['../contributing.html#autotoc_md123',1,'Documentation'],['../gpuParallelization.html#autotoc_md364',1,'Macro API Documentation'],['../index.html',1,'MFC Documentation']]],
  ['domain_58',['Domain',['../case.html#sec-computational-domain',1,'2. Computational Domain'],['../physics_constraints.html#autotoc_md483',1,'Patch Within Domain']]],
  ['domain_20and_20geometry_59',['Domain and Geometry',['../physics_constraints.html#autotoc_md479',1,'']]],
  ['domain_20bounds_60',['Domain Bounds',['../physics_constraints.html#autotoc_md480',1,'']]],
  ['domain_20extents_20specified_61',['Domain Extents Specified',['../physics_constraints.html#autotoc_md482',1,'']]],
  ['driven_20cavity_62',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md309',1,'']]],
  ['driven_20cavity_20problem_202d_63',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md272',1,'']]],
  ['droplet_202d_64',['Shock Droplet (2D)',['../examples.html#autotoc_md325',1,'']]],
  ['dropped_65',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md390',1,'']]],
  ['dt_202d_66',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md231',1,'']]],
  ['dynamics_67',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dynamics_68',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md204',1,'']]],
  ['dynamics_20wilfong26_20sec_204_201_69',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md159',1,'']]]
];
