var searchData=
[
  ['halo_20exchange_0',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['handling_1',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['hangs_2',['MPI errors or hangs',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['hard_20coded_20patches_3',['Hard Coded Patches',['../case.html#autotoc_md7',1,'']]],
  ['hard_20rules_4',['Hard Rules',['../contributing.html#autotoc_md75',1,'']]],
  ['hardcodied_20ic_20example_5',['2D Hardcodied IC Example',['../examples.html#autotoc_md248',1,'']]],
  ['harten83_6',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['helmholtz_20instability_202d_7',['Kelvin-Helmholtz Instability (2D)',['../examples.html#autotoc_md221',1,'']]],
  ['help_8',['Getting Help',['../troubleshooting.html#autotoc_md510',1,'']]],
  ['help_9',['help',['../cli-reference.html#help',1,'']]],
  ['helpful_20tools_10',['Helpful Tools',['../getting-started.html#autotoc_md288',1,'']]],
  ['hll_20riemann_5fsolver_201_20harten83_11',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['hllc_20riemann_5fsolver_202_20toro94_12',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md178',1,'']]],
  ['hlld_20riemann_5fsolver_204_20mhd_20only_13',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md180',1,'']]],
  ['homebrew_20macos_14',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md281',1,'']]],
  ['homebrew_20package_20macos_15',['Using the Homebrew package (macOS)',['../running.html#autotoc_md434',1,'']]],
  ['how_20to_20add_20a_20new_20simulation_20parameter_16',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['how_20to_20add_20a_20post_20processing_20output_20variable_17',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['how_20to_20add_20a_20test_20case_18',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['how_20to_20allocate_20and_20manage_20gpu_20arrays_19',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['how_20to_20create_20a_20new_20fortran_20module_20',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['how_20to_20document_20physics_20constraints_21',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['how_20to_20extend_20mpi_20halo_20exchange_22',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['how_20to_20guides_23',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]],
  ['how_20to_20write_20a_20gpu_20parallel_20loop_24',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['hpc_25',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md502',1,'']]],
  ['hyperelastic_20model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_26',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md151',1,'']]],
  ['hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_27',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md151',1,'']]],
  ['hypoelastic_20model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_28',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['hypoelasticity_29',['Hypoelasticity',['../physics_constraints.html#autotoc_md410',1,'']]],
  ['hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_30',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]]
];
