var searchData=
[
  ['ranks_0',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md540',1,'']]],
  ['rayleigh_20plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_1',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['rayleigh_20taylor_20instability_202d_2',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md285',1,'']]],
  ['rayleigh_20taylor_20instability_203d_3',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md290',1,'']]],
  ['rayleigh17_20plesset49_4',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['reactive_20shock_20tube_5',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md301',1,'']]],
  ['reactor_6',['Perfectly Stirred Reactor',['../examples.html#autotoc_md258',1,'']]],
  ['read_20silo_20hdf5_20files_7',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['readme_2emd_8',['readme.md',['../readme_8md.html',1,'']]],
  ['rebuild_9',['Clean Rebuild',['../troubleshooting.html#autotoc_md534',1,'']]],
  ['recommended_10',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md315',1,'']]],
  ['reconstruction_11',['Reconstruction',['../equations.html#autotoc_md189',1,'15.1 Spatial Reconstruction'],['../equations.html#autotoc_md192',1,'IGR Reconstruction'],['../physics_constraints.html#autotoc_md474',1,'MUSCL Reconstruction'],['../physics_constraints.html#autotoc_md473',1,'WENO Reconstruction']]],
  ['reference_12',['Reference',['../case_constraints.html#quick-parameter-reference',1,'📖 Quick Parameter Reference'],['../cli-reference.html',1,'CLI Reference'],['../cli-reference.html#autotoc_md45',1,'CLI Reference'],['../parameters.html#autotoc_md432',1,'CLI Reference'],['../equations.html#autotoc_md138',1,'MFC: Comprehensive Equations Reference'],['../physics_constraints.html#autotoc_md433',1,'Physics Constraints Reference'],['../cli-reference.html#autotoc_md47',1,'Quick Reference'],['../troubleshooting.html#autotoc_md519',1,'Quick Reference'],['../index.html#autotoc_md485',1,'Reference']]],
  ['reference_13',['Complete option reference',['../visualization.html#autotoc_md588',1,'']]],
  ['reference_20scales_14',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['references_15',['References',['../examples.html#autotoc_md231',1,'References'],['../examples.html#autotoc_md243',1,'References'],['../examples.html#autotoc_md249',1,'References'],['../examples.html#autotoc_md255',1,'References'],['../examples.html#autotoc_md273',1,'References'],['../examples.html#autotoc_md297',1,'References']]],
  ['regenerating_20golden_20files_16',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md546',1,'']]],
  ['regime_20and_20parameters_17',['Regime and parameters',['../examples.html#autotoc_md239',1,'Regime and parameters'],['../examples.html#autotoc_md245',1,'Regime and parameters'],['../examples.html#autotoc_md251',1,'Regime and parameters'],['../examples.html#autotoc_md270',1,'Regime and parameters'],['../examples.html#autotoc_md293',1,'Regime and parameters']]],
  ['regularization_20igr_20true_20wilfong25a_18',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['relativistic_20mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_19',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md180',1,'']]],
  ['relativity_20true_20wilfong26_20sec_204_201_2010_20',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md180',1,'']]],
  ['relax_20true_20wilfong26_20sec_204_201_203_21',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md170',1,'']]],
  ['relax_5fmodel_205_20saurel08_22',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['relax_5fmodel_206_20zein10_23',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['relaxation_20relax_5fmodel_205_20saurel08_24',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['relaxation_20relax_5fmodel_206_20zein10_25',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['remote_20visualization_20on_20pace_20phoenix_26',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md594',1,'']]],
  ['rendering_27',['Tiled 1D rendering',['../visualization.html#autotoc_md583',1,'']]],
  ['rendering_20options_28',['Rendering options',['../visualization.html#autotoc_md580',1,'']]],
  ['request_29',['Submitting a Pull Request',['../contributing.html#autotoc_md121',1,'']]],
  ['required_20to_20read_20silo_20hdf5_20files_30',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['restarting_20cases_31',['Restarting Cases',['../running.html#autotoc_md512',1,'']]],
  ['result_32',['Result',['../examples.html#autotoc_md215',1,'Initial Condition and Result'],['../examples.html#autotoc_md225',1,'Result'],['../examples.html#autotoc_md266',1,'Result'],['../examples.html#autotoc_md268',1,'Result'],['../examples.html#autotoc_md308',1,'Result'],['../examples.html#autotoc_md311',1,'Result']]],
  ['result_33',['result',['../examples.html#autotoc_md242',1,'Validation result'],['../examples.html#autotoc_md248',1,'Validation result'],['../examples.html#autotoc_md254',1,'Validation result'],['../examples.html#autotoc_md296',1,'Validation result']]],
  ['results_34',['Results',['../expectedPerformance.html#autotoc_md321',1,'Benchmark Results'],['../examples.html#autotoc_md300',1,'Results'],['../examples.html#autotoc_md303',1,'Results'],['../getting-started.html#autotoc_md341',1,'Visualizing Results']]],
  ['results_35',['Validation results',['../examples.html#autotoc_md230',1,'']]],
  ['review_20and_20merge_36',['Code Review and Merge',['../contributing.html#autotoc_md122',1,'']]],
  ['rho_20consistency_37',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md442',1,'']]],
  ['richtmyer_20meshkov_20instability_202d_38',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md274',1,'']]],
  ['riemann_20igr_39',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md469',1,'']]],
  ['riemann_20solvers_40',['Riemann Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md193',1,'15.2 Riemann Solvers']]],
  ['riemann_20test_202d_41',['2D Riemann Test (2D)',['../examples.html#autotoc_md219',1,'']]],
  ['riemann_5fsolver_201_20harten83_42',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md194',1,'']]],
  ['riemann_5fsolver_202_20toro94_43',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[51]&lt;/a&gt;)',['../equations.html#autotoc_md195',1,'']]],
  ['riemann_5fsolver_203_44',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['riemann_5fsolver_204_20mhd_20only_45',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md197',1,'']]],
  ['rodriguez19_20wilfong26_20sec_204_201_206_46',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md167',1,'']]],
  ['rules_47',['Hard Rules',['../contributing.html#autotoc_md92',1,'']]],
  ['run_48',['run',['../examples.html#autotoc_md229',1,'How to run'],['../examples.html#autotoc_md241',1,'How to run'],['../examples.html#autotoc_md247',1,'How to run'],['../examples.html#autotoc_md253',1,'How to run'],['../examples.html#autotoc_md272',1,'How to run'],['../examples.html#autotoc_md295',1,'How to run'],['../cli-reference.html#run',1,'run']]],
  ['run_20fails_49',['Run Fails?',['../troubleshooting.html#autotoc_md526',1,'']]],
  ['runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_50',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md199',1,'']]],
  ['running_51',['Running',['../running.html',1,'Running'],['../running.html#autotoc_md490',1,'Running']]],
  ['running_20an_20example_20case_52',['Running an Example Case',['../getting-started.html#autotoc_md339',1,'']]],
  ['running_20containers_53',['Details on Running Containers',['../docker.html#autotoc_md127',1,'']]],
  ['running_20on_20gpus_54',['Running on GPUs',['../running.html#autotoc_md495',1,'Running on GPUs'],['../running.html#autotoc_md497',1,'Running on GPUs']]],
  ['running_20pace_20paraview_20server_55',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md597',1,'']]],
  ['running_20specific_20tests_56',['Running Specific Tests',['../troubleshooting.html#autotoc_md543',1,'']]],
  ['running_20the_20test_20suite_57',['Running the Test Suite',['../getting-started.html#autotoc_md338',1,'']]],
  ['running_20with_20fewer_20ranks_58',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md540',1,'']]],
  ['running_2emd_59',['running.md',['../running_8md.html',1,'']]],
  ['runs_60',['Runs',['../running.html#autotoc_md514',1,'Example Runs'],['../troubleshooting.html#autotoc_md538',1,'Verbose Runs']]],
  ['runs_20first_20blocks_20all_20other_20jobs_61',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md117',1,'']]],
  ['runtime_62',['1. Runtime',['../case.html#sec-runtime',1,'']]],
  ['runtime_20debugging_63',['Runtime Debugging',['../troubleshooting.html#autotoc_md536',1,'']]],
  ['runtime_20errors_64',['Common Runtime Errors',['../troubleshooting.html#autotoc_md561',1,'']]]
];
