var searchData=
[
  ['case_0',['Case',['../getting-started.html#autotoc_md308',1,'Creating a New Case'],['../equations.html#sec-bubble-example',1,'Example: Non-Dimensionalizing a Bubble Case'],['../contributing.html#autotoc_md107',1,'How to Add a Test Case'],['../getting-started.html#autotoc_md303',1,'Running an Example Case']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['case_20files_3',['Case Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md15',1,'Case Files']]],
  ['case_20optimization_4',['When to use case optimization',['../expectedPerformance.html#autotoc_md280',1,'']]],
  ['case_20optimization_20recommended_5',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md279',1,'']]],
  ['case_20parameter_20constraint_20violations_6',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md521',1,'']]],
  ['case_20parameters_7',['Case Parameters',['../parameters.html',1,'Case Parameters'],['../parameters.html#autotoc_md336',1,'Case Parameters']]],
  ['case_20validation_8',['Case Validation',['../troubleshooting.html#autotoc_md496',1,'']]],
  ['case_2emd_9',['case.md',['../case_8md.html',1,'']]],
  ['case_5fconstraints_2emd_10',['case_constraints.md',['../case__constraints_8md.html',1,'']]],
  ['cases_11',['Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md212',1,'Example Cases'],['../running.html#autotoc_md471',1,'Restarting Cases']]],
  ['cavity_20problem_202d_12',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md242',1,'']]],
  ['centerline_20velocities_13',['Centerline Velocities',['../examples.html#autotoc_md244',1,'']]],
  ['cfl_20condition_14',['15.4 CFL Condition',['../equations.html#autotoc_md201',1,'']]],
  ['cfl_20dt_202d_15',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md224',1,'']]],
  ['change_16',['Phase Change',['../physics_constraints.html#autotoc_md427',1,'']]],
  ['change_20model_17',['11. Phase Change Model',['../case.html#sec-phase-change',1,'']]],
  ['change_20relax_20true_20wilfong26_20sec_204_201_203_18',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md169',1,'']]],
  ['characteristic_20bcs_20thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_19',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md206',1,'']]],
  ['characteristic_20boundary_20conditions_20',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md36',1,'']]],
  ['checklist_21',['Performance Checklist',['../expectedPerformance.html#autotoc_md283',1,'']]],
  ['chem_5fparams_22',['chem_params',['../parameters.html#chem_params',1,'']]],
  ['chem_5fwrt_5fy_23',['chem_wrt_Y',['../parameters.html#chem_wrt_Y',1,'']]],
  ['chemistry_24',['17. Chemistry',['../case.html#autotoc_md33',1,'']]],
  ['chemistry_20and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_25',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md173',1,'']]],
  ['chemistry_20chemistry_20true_26',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md149',1,'']]],
  ['chemistry_20true_27',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md149',1,'']]],
  ['chemistry_20true_20wilfong26_20sec_204_201_207_28',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md173',1,'']]],
  ['ci_20commands_29',['CI Commands',['../cli-reference.html#autotoc_md70',1,'']]],
  ['ci_20failures_30',['Common CI Failures',['../contributing.html#autotoc_md118',1,'']]],
  ['ci_20pipeline_31',['CI Pipeline',['../contributing.html#autotoc_md115',1,'']]],
  ['classes_20commander89_20ando11_32',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['clean_33',['clean',['../cli-reference.html#clean',1,'']]],
  ['clean_20rebuild_34',['Clean Rebuild',['../troubleshooting.html#autotoc_md493',1,'']]],
  ['cli_35',['Docker CLI',['../docker.html#autotoc_md125',1,'']]],
  ['cli_20reference_36',['CLI Reference',['../cli-reference.html',1,'CLI Reference'],['../cli-reference.html#autotoc_md44',1,'CLI Reference'],['../parameters.html#autotoc_md392',1,'CLI Reference']]],
  ['cli_2dreference_2emd_37',['cli-reference.md',['../cli-reference_8md.html',1,'']]],
  ['clusters_20via_20apptainer_20singularity_38',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md128',1,'']]],
  ['cmake_20could_20not_20find_20a_20fortran_20compiler_39',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md515',1,'']]],
  ['cmake_20could_20not_20find_20mpi_40',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md514',1,'']]],
  ['code_20architecture_41',['Code Architecture',['../architecture.html',1,'']]],
  ['code_20coverage_42',['Code Coverage',['../troubleshooting.html#autotoc_md491',1,'']]],
  ['code_20review_20and_20merge_43',['Code Review and Merge',['../contributing.html#autotoc_md121',1,'']]],
  ['coded_20patches_44',['Hard Coded Patches',['../case.html#autotoc_md21',1,'']]],
  ['coding_20standards_45',['Coding Standards',['../contributing.html#autotoc_md90',1,'']]],
  ['combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_46',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md173',1,'']]],
  ['command_20line_20arguments_47',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['commander89_20ando11_48',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['commands_49',['Commands',['../cli-reference.html#autotoc_md70',1,'CI Commands'],['../cli-reference.html#autotoc_md47',1,'Commands'],['../cli-reference.html#autotoc_md63',1,'Development Commands'],['../cli-reference.html#autotoc_md73',1,'Other Commands'],['../troubleshooting.html#autotoc_md481',1,'Useful Commands'],['../cli-reference.html#autotoc_md53',1,'Utility Commands']]],
  ['commit_20messages_50',['Commit Messages',['../contributing.html#autotoc_md89',1,'']]],
  ['common_51',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md112',1,'']]],
  ['common_20build_20errors_52',['Common Build Errors',['../troubleshooting.html#autotoc_md513',1,'']]],
  ['common_20ci_20failures_53',['Common CI Failures',['../contributing.html#autotoc_md118',1,'']]],
  ['common_20configuration_20patterns_54',['🚀 Common Configuration Patterns',['../case_constraints.html#common-configuration-patterns',1,'']]],
  ['common_20material_20values_55',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['common_20options_56',['Common Options',['../cli-reference.html#autotoc_md76',1,'']]],
  ['common_20pitfalls_57',['Common Pitfalls',['../contributing.html#autotoc_md93',1,'']]],
  ['common_20runtime_20errors_58',['Common Runtime Errors',['../troubleshooting.html#autotoc_md520',1,'']]],
  ['compare_59',['packer compare',['../cli-reference.html#autotoc_md58',1,'']]],
  ['compatibility_60',['Compatibility',['../case_constraints.html#feature-compatibility',1,'📊 Feature Compatibility'],['../physics_constraints.html#autotoc_md416',1,'Boundary Condition Compatibility'],['../case.html#autotoc_md19',1,'Feature Compatibility'],['../physics_constraints.html#autotoc_md423',1,'Feature Compatibility']]],
  ['compiler_61',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md515',1,'']]],
  ['compiler_20agnostic_20tools_62',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md325',1,'']]],
  ['compiler_20documentation_63',['Compiler Documentation',['../gpuParallelization.html#autotoc_md334',1,'']]],
  ['compiler_20options_64',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md330',1,'']]],
  ['compiler_20portability_65',['Compiler Portability',['../contributing.html#autotoc_md100',1,'']]],
  ['compiler_20tools_66',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md327',1,'']]],
  ['compilers_67',['Supported Compilers',['../running.html#autotoc_md457',1,'']]],
  ['complete_20option_20reference_68',['Complete option reference',['../visualization.html#autotoc_md547',1,'']]],
  ['completion_69',['Shell Completion',['../getting-started.html#autotoc_md309',1,'']]],
  ['completion_70',['completion',['../cli-reference.html#completion',1,'']]],
  ['component_20inert_20shock_20tube_71',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md271',1,'']]],
  ['component_20reactive_20shock_20tube_72',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md247',1,'']]],
  ['components_20in_20inactive_20dimensions_73',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md410',1,'']]],
  ['comprehensive_20equations_20reference_74',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md137',1,'']]],
  ['computation_20macros_75',['Computation Macros',['../gpuParallelization.html#autotoc_md316',1,'']]],
  ['computational_20domain_76',['2. Computational Domain',['../case.html#sec-computational-domain',1,'']]],
  ['computer_20templates_77',['Computer Templates',['../running.html#autotoc_md468',1,'']]],
  ['condition_78',['Condition',['../equations.html#autotoc_md201',1,'15.4 CFL Condition'],['../examples.html#autotoc_md214',1,'Final Condition'],['../examples.html#autotoc_md223',1,'Final Condition'],['../examples.html#autotoc_md231',1,'Final Condition'],['../examples.html#autotoc_md243',1,'Final Condition'],['../examples.html#autotoc_md235',1,'Initial Condition'],['../examples.html#autotoc_md238',1,'Initial Condition'],['../examples.html#autotoc_md248',1,'Initial Condition'],['../examples.html#autotoc_md253',1,'Initial Condition'],['../examples.html#autotoc_md266',1,'Initial Condition'],['../examples.html#autotoc_md272',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_79',['Condition and Linear Theory',['../examples.html#autotoc_md219',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md275',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_80',['Initial Condition and Result',['../examples.html#autotoc_md221',1,'']]],
  ['condition_20compatibility_81',['Boundary Condition Compatibility',['../physics_constraints.html#autotoc_md416',1,'']]],
  ['condition_20constraints_82',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md398',1,'']]],
  ['condition_20density_83',['Condition Density',['../examples.html#autotoc_md241',1,'Final Condition (Density)'],['../examples.html#autotoc_md259',1,'Final Condition (Density)']]],
  ['condition_20patches_84',['Boundary Condition Patches',['../case.html#boundary-condition-patches',1,'']]],
  ['conditions_85',['Conditions',['../equations.html#autotoc_md204',1,'16. Boundary Conditions'],['../architecture.html#autotoc_md8',1,'Boundary Conditions'],['../physics_constraints.html#autotoc_md415',1,'Boundary Conditions'],['../examples.html#autotoc_md246',1,'Density Initial and Final Conditions']]],
  ['conditions_86',['conditions',['../case.html#boundary-conditions',1,'Boundary conditions'],['../case.html#autotoc_md36',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20flags_87',['Build Configuration Flags',['../cli-reference.html#autotoc_md78',1,'']]],
  ['configuration_20patterns_88',['🚀 Common Configuration Patterns',['../case_constraints.html#common-configuration-patterns',1,'']]],
  ['conservative_20variables_20ordering_89',['Conservative Variables Ordering',['../case.html#autotoc_md37',1,'']]],
  ['consistency_90',['Consistency',['../physics_constraints.html#autotoc_md402',1,'Alpha-Rho Consistency'],['../contributing.html#autotoc_md98',1,'Physics and Model Consistency'],['../equations.html#sec-unit-consistency',1,'Unit Consistency'],['../physics_constraints.html#autotoc_md409',1,'Velocity and Dimensional Consistency']]],
  ['constant_20time_20stepping_91',['Constant Time-Stepping',['../case.html#autotoc_md25',1,'']]],
  ['constraint_20violations_92',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md521',1,'']]],
  ['constraints_93',['Constraints',['../physics_constraints.html#autotoc_md420',1,'Bubble Simulation Constraints'],['../contributing.html#how-to-document-physics-constraints',1,'How to Document Physics Constraints'],['../physics_constraints.html#autotoc_md400',1,'Mixture Constraints'],['../physics_constraints.html#autotoc_md398',1,'Patch Initial Condition Constraints'],['../physics_constraints.html',1,'Physics Constraints'],['../physics_constraints.html#autotoc_md395',1,'Thermodynamic Constraints']]],
  ['constraints_20reference_94',['Physics Constraints Reference',['../physics_constraints.html#autotoc_md393',1,'']]],
  ['containers_95',['Containers',['../docker.html',1,'Containers'],['../docker.html#autotoc_md122',1,'Containers'],['../docker.html#autotoc_md126',1,'Details on Running Containers'],['../getting-started.html#autotoc_md301',1,'Using Containers']]],
  ['contributing_96',['Contributing',['../contributing.html',1,'']]],
  ['contributing_20to_20mfc_97',['Contributing to MFC',['../contributing.html#autotoc_md81',1,'']]],
  ['contributing_2emd_98',['contributing.md',['../contributing_8md.html',1,'']]],
  ['control_20macros_99',['Data Control Macros',['../gpuParallelization.html#autotoc_md318',1,'']]],
  ['conventions_100',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['coordinates_101',['16. Cylindrical Coordinates',['../case.html#autotoc_md32',1,'']]],
  ['coordinates_102',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md550',1,'']]],
  ['coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_103',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md153',1,'']]],
  ['core_104',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['corrections_20wilfong26_20sec_204_202_204_105',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md209',1,'']]],
  ['correctness_106',['Correctness',['../contributing.html#autotoc_md97',1,'MPI Correctness'],['../troubleshooting.html#autotoc_md511',1,'Performance vs Correctness']]],
  ['could_20not_20find_20a_20fortran_20compiler_107',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md515',1,'']]],
  ['could_20not_20find_20mpi_108',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md514',1,'']]],
  ['count_109',['count',['../cli-reference.html#count',1,'']]],
  ['count_5fdiff_110',['count_diff',['../cli-reference.html#count_diff',1,'']]],
  ['coverage_111',['Code Coverage',['../troubleshooting.html#autotoc_md491',1,'']]],
  ['cpu_112',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md295',1,'']]],
  ['cpu_20historical_113',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md290',1,'']]],
  ['cray_20compiler_20tools_114',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md327',1,'']]],
  ['cray_20general_20options_115',['Cray General Options',['../gpuParallelization.html#autotoc_md328',1,'']]],
  ['cray_20openacc_20options_116',['Cray OpenACC Options',['../gpuParallelization.html#autotoc_md329',1,'']]],
  ['create_20a_20new_20fortran_20module_117',['How to Create a New Fortran Module',['../contributing.html#autotoc_md108',1,'']]],
  ['creating_20a_20new_20case_118',['Creating a New Case',['../getting-started.html#autotoc_md308',1,'']]],
  ['creating_20tests_119',['Creating Tests',['../testing.html#autotoc_md475',1,'']]],
  ['creator_20guide_120',['Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['customizing_20the_20script_121',['Step 2: Customizing the script',['../visualization.html#autotoc_md555',1,'']]],
  ['cyl_5fcoord_20true_20wilfong26_20sec_202_203_122',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md153',1,'']]],
  ['cylindrical_20coordinates_123',['16. Cylindrical Coordinates',['../case.html#autotoc_md32',1,'']]],
  ['cylindrical_20coordinates_124',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md550',1,'']]],
  ['cylindrical_20coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_125',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md153',1,'']]]
];
