var searchData=
[
  ['elasticity_0',['15. Elasticity',['../case.html#autotoc_md29',1,'']]],
  ['elliptic_20smoothing_1',['Elliptic Smoothing',['../case.html#autotoc_md12',1,'']]],
  ['ensemble_20averaged_20bubble_20model_2',['9.1 Ensemble-Averaged Bubble Model',['../case.html#autotoc_md22',1,'']]],
  ['enumerations_3',['Enumerations',['../case.html#autotoc_md32',1,'']]],
  ['environment_4',['Environment',['../getting-started.html#autotoc_md326',1,'Build Environment'],['../visualization.html#autotoc_md543',1,'Step 1: Setting up your Environment']]],
  ['environment_20setup_5',['Environment Setup',['../running.html#autotoc_md468',1,'']]],
  ['eos_20chemistry_20chemistry_20true_6',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_7',['3.1 Stiffened Gas EOS (&lt;b&gt;[Menikoff89]&lt;/b&gt;; &lt;b&gt;[LeMetayer04]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.2)',['../equations.html#autotoc_md176',1,'']]],
  ['equation_20model_20model_5feqns_202_8',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['equation_20model_20model_5feqns_203_9',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['equations_10',['Equations',['../case_constraints.html#autotoc_md50',1,'🔢 Model Equations'],['../equations.html',1,'Equations']]],
  ['equations_20of_20state_11',['3. Equations of State',['../equations.html#autotoc_md175',1,'']]],
  ['equations_20reference_12',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md166',1,'']]],
  ['equations_2emd_13',['equations.md',['../equations_8md.html',1,'']]],
  ['errors_14',['Errors',['../troubleshooting.html#autotoc_md523',1,'Common Build Errors'],['../troubleshooting.html#autotoc_md530',1,'Common Runtime Errors']]],
  ['errors_15',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md527',1,'']]],
  ['errors_20or_20hangs_16',['MPI errors or hangs',['../troubleshooting.html#autotoc_md534',1,'']]],
  ['euler_20bubbles_20bubbles_5feuler_20true_17',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['euler_20euler_20bubbles_20bubbles_5feuler_20true_18',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['euler_20lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_19',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;b&gt;[Maeda18]&lt;/b&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['evolved_20state_20',['Evolved State',['../examples.html#autotoc_md249',1,'Evolved State'],['../examples.html#autotoc_md267',1,'Evolved State'],['../examples.html#autotoc_md281',1,'Evolved State']]],
  ['exact_20riemann_5fsolver_203_21',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md223',1,'']]],
  ['example_22',['Example',['../examples.html#autotoc_md292',1,'2D Hardcodied IC Example'],['../examples.html#autotoc_md271',1,'Example']]],
  ['example_20case_23',['Running an Example Case',['../getting-started.html#autotoc_md330',1,'']]],
  ['example_20cases_24',['Example Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md240',1,'Example Cases']]],
  ['example_20runs_25',['Example Runs',['../running.html#autotoc_md483',1,'']]],
  ['example_20tags_26',['Example Tags',['../docker.html#autotoc_md164',1,'']]],
  ['examples_27',['Examples',['../case_constraints.html#autotoc_md43',1,'🔴 Advanced Examples'],['../case_constraints.html#autotoc_md42',1,'🟡 Intermediate Examples'],['../case_constraints.html#autotoc_md41',1,'🟢 Beginner Examples'],['../running.html#autotoc_md477',1,'Examples']]],
  ['examples_20visualization_28',['Examples &amp;amp; Visualization',['../index.html#autotoc_md454',1,'']]],
  ['examples_2emd_29',['examples.md',['../examples_8md.html',1,'']]],
  ['exchange_30',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]],
  ['execution_31',['Execution',['../running.html#autotoc_md474',1,'Batch Execution'],['../running.html#autotoc_md462',1,'Interactive Execution'],['../troubleshooting.html#autotoc_md513',1,'Serial Test Execution']]],
  ['expectedperformance_2emd_32',['expectedPerformance.md',['../expectedPerformance_8md.html',1,'']]],
  ['extend_20mpi_20halo_20exchange_33',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]]
];
