var searchData=
[
  ['lag_5fparams_0',['lag_params',['../parameters.html#lag_params',1,'']]],
  ['lagrange_20bubble_20model_1',['Euler-Lagrange Bubble Model',['../physics_constraints.html#autotoc_md523',1,'']]],
  ['lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_2',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[31]&lt;/a&gt;)',['../equations.html#autotoc_md169',1,'']]],
  ['law_20poiseuille_20channel_3',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md235',1,'']]],
  ['law_20shear_20thickening_20poiseuille_20channel_4',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md286',1,'']]],
  ['law_20shear_20thinning_20poiseuille_20channel_5',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md328',1,'']]],
  ['lax_20shock_20tube_20problem_201d_6',['Lax shock tube problem (1D)',['../examples.html#autotoc_md346',1,'']]],
  ['layer_203d_7',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md265',1,'']]],
  ['layer_20h2_20n2_20air_20mc_201_205_8',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md272',1,'']]],
  ['layer_20initial_20conditions_9',['Mixing-layer initial conditions',['../thermochemistry.html#autotoc_md589',1,'']]],
  ['layout_10',['Layout',['../architecture.html#autotoc_md1',1,'Directory Layout'],['../contributing.html#autotoc_md86',1,'Directory Layout']]],
  ['lemetayer04_20wilfong26_20sec_202_202_11',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md152',1,'']]],
  ['levels_12',['Verbosity Levels',['../troubleshooting.html#autotoc_md603',1,'']]],
  ['lid_20driven_20cavity_13',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md296',1,'']]],
  ['lid_20driven_20cavity_20problem_202d_14',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md303',1,'']]],
  ['limiting_15',['18. Flux Limiting',['../equations.html#autotoc_md217',1,'']]],
  ['line_20arguments_16',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['linear_20theory_17',['Linear Theory',['../examples.html#autotoc_md302',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md314',1,'Final Condition and Linear Theory']]],
  ['lint_18',['lint',['../cli-reference.html#lint',1,'']]],
  ['lint_20gate_20runs_20first_20blocks_20all_20other_20jobs_19',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['liutex_20visualization_20at_20transitional_20state_20',['Liutex visualization at transitional state',['../examples.html#autotoc_md266',1,'']]],
  ['load_21',['load',['../cli-reference.html#load',1,'']]],
  ['location_22',['Test Output Location',['../troubleshooting.html#autotoc_md618',1,'']]],
  ['log_23',['Debug Log',['../troubleshooting.html#autotoc_md612',1,'']]],
  ['log_24',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['logging_20d_20debug_20log_25',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['looks_20wrong_20or_20has_20artifacts_26',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md644',1,'']]],
  ['lookup_27',['Parameter Lookup',['../getting-started.html#autotoc_md383',1,'']]],
  ['loop_28',['Loop',['../contributing.html#autotoc_md108',1,'How to Write a GPU Parallel Loop'],['../architecture.html#autotoc_md3',1,'The Simulation Loop']]],
  ['low_20mach_20number_20corrections_20wilfong26_20sec_204_202_204_29',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md215',1,'']]]
];
