var searchData=
[
  ['i_20o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_1',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['ib_5fairfoil_2',['ib_airfoil',['../parameters.html#ib_airfoil',1,'']]],
  ['ibm_20bow_20shock_203d_3',['IBM Bow Shock (3D)',['../examples.html#autotoc_md306',1,'']]],
  ['ibm_20cfl_20dt_202d_4',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md230',1,'']]],
  ['ibm_20power9_20cpu_5',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md337',1,'']]],
  ['ibm_20power9_20cpu_20historical_6',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md332',1,'']]],
  ['ibm_20walled_20power_20law_20poiseuille_20channel_7',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md288',1,'']]],
  ['ic_20example_8',['2D Hardcodied IC Example',['../examples.html#autotoc_md308',1,'']]],
  ['ic_20extrusion_9',['IC Extrusion',['../physics_constraints.html#autotoc_md514',1,'']]],
  ['ic_20extrusion_20file_20parameters_10',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md515',1,'']]],
  ['ideal_20gas_20eos_20chemistry_20chemistry_20true_11',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md152',1,'']]],
  ['ideal_20mhd_20mhd_20true_20wilfong26_20sec_204_201_209_12',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['igr_13',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md494',1,'']]],
  ['igr_20reconstruction_14',['IGR Reconstruction',['../equations.html#autotoc_md193',1,'']]],
  ['igr_20true_20wilfong25a_15',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['image_20device_20codegen_20instability_20worked_20around_20in_20the_20build_16',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['images_17',['Base Images',['../docker.html#autotoc_md136',1,'']]],
  ['immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_18',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['immersed_20boundary_20patch_20types_19',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['immersed_20boundary_20patches_20',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['implementation_21',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['in_20cylindrical_20coordinates_22',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md623',1,'']]],
  ['in_20dimensions_20out_23',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['in_20inactive_20dimensions_24',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md475',1,'']]],
  ['in_20the_20build_25',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['inactive_20dimensions_26',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md475',1,'']]],
  ['indexing_27',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['inert_20shock_20tube_28',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md218',1,'']]],
  ['information_20geometric_20regularization_20igr_20true_20wilfong25a_29',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['infrastructure_30',['Infrastructure',['../architecture.html#autotoc_md10',1,'']]],
  ['initial_20and_20final_20conditions_31',['Density Initial and Final Conditions',['../examples.html#autotoc_md252',1,'']]],
  ['initial_20condition_32',['Initial Condition',['../examples.html#autotoc_md219',1,'Initial Condition'],['../examples.html#autotoc_md222',1,'Initial Condition'],['../examples.html#autotoc_md237',1,'Initial Condition'],['../examples.html#autotoc_md254',1,'Initial Condition'],['../examples.html#autotoc_md295',1,'Initial Condition'],['../examples.html#autotoc_md316',1,'Initial Condition']]],
  ['initial_20condition_33',['Initial condition',['../examples.html#autotoc_md228',1,'']]],
  ['initial_20condition_20and_20result_34',['Initial Condition and Result',['../examples.html#autotoc_md309',1,'']]],
  ['initial_20condition_20constraints_35',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md462',1,'']]],
  ['initial_20state_36',['Initial State',['../examples.html#autotoc_md240',1,'Initial State'],['../examples.html#autotoc_md249',1,'Initial State'],['../examples.html#autotoc_md311',1,'Initial State']]],
  ['initial_20states_20inside_20a_20state_20dependent_20equation_20of_20state_37',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['input_20parameters_38',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['inside_20a_20state_20dependent_20equation_20of_20state_39',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['inside_20fortran_20block_20constructs_20are_20silently_20dropped_40',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md380',1,'']]],
  ['instability_202d_41',['Instability 2D',['../examples.html#autotoc_md239',1,'Kelvin-Helmholtz Instability (2D)'],['../examples.html#autotoc_md304',1,'Rayleigh-Taylor Instability (2D)'],['../examples.html#autotoc_md310',1,'Richtmyer-Meshkov Instability (2D)']]],
  ['instability_203d_42',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md264',1,'']]],
  ['instability_20worked_20around_20in_20the_20build_43',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['install_20via_20homebrew_20macos_44',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md340',1,'']]],
  ['integration_45',['15.3 Time Integration',['../equations.html#autotoc_md200',1,'']]],
  ['interaction_46',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md168',1,'']]],
  ['interactive_20execution_47',['Interactive Execution',['../running.html#autotoc_md525',1,'']]],
  ['interactive_20mode_48',['Interactive mode',['../visualization.html#autotoc_md616',1,'']]],
  ['interactive_20shell_49',['Interactive Shell',['../docker.html#autotoc_md132',1,'']]],
  ['intermediate_20examples_50',['🟡 Intermediate Examples',['../case_constraints.html#autotoc_md44',1,'']]],
  ['is_20required_20to_20read_20silo_20hdf5_20files_51',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md602',1,'']]],
  ['isentropic_20vortex_20problem_202d_52',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md279',1,'']]],
  ['isolating_20issues_53',['Isolating Issues',['../troubleshooting.html#autotoc_md565',1,'']]],
  ['issues_54',['Issues',['../gpuParallelization.html#autotoc_md378',1,'AMD flang (amdflang) Known Issues'],['../troubleshooting.html#autotoc_md565',1,'Isolating Issues'],['../troubleshooting.html#autotoc_md599',1,'Visualization Issues']]],
  ['iterative_20generalized_20riemann_20igr_55',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md494',1,'']]]
];
