var searchData=
[
  ['nan_20detected_0',['&quot;NaN detected&quot;',['../troubleshooting.html#autotoc_md458',1,'']]],
  ['navigating_20docker_1',['Navigating Docker',['../docker.html#autotoc_md152',1,'']]],
  ['new_2',['new',['../cli-reference.html#autotoc_md70',1,'']]],
  ['new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md259',1,'']]],
  ['new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['new_20simulation_20parameter_5',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md133',1,'']]],
  ['norms_6',['Density Norms',['../examples.html#autotoc_md210',1,'']]],
  ['not_20detected_7',['GPU not detected',['../troubleshooting.html#autotoc_md459',1,'']]],
  ['not_20find_20a_20fortran_20compiler_8',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['not_20find_20mpi_9',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['not_20found_20on_20hpc_10',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md454',1,'']]],
  ['notes_11',['Notes',['../contributing.html#autotoc_md130',1,'Architecture Notes'],['../running.html#autotoc_md405',1,'Scheduler Notes']]],
  ['number_12',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['numerical_20schlieren_20at_20final_20time_13',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md169',1,'']]],
  ['numerics_14',['Numerics',['../case_constraints.html#autotoc_md48',1,'']]],
  ['nvhpc_20compiler_20options_15',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md281',1,'']]],
  ['nvhpc_20general_20options_16',['NVHPC General Options',['../gpuParallelization.html#autotoc_md282',1,'']]],
  ['nvhpc_20openacc_20options_17',['NVHPC OpenACC Options',['../gpuParallelization.html#autotoc_md283',1,'']]],
  ['nvhpc_20openmp_20options_18',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md284',1,'']]],
  ['nvidia_20gpu_20profiling_19',['NVIDIA GPU Profiling',['../troubleshooting.html#autotoc_md445',1,'']]],
  ['nvidia_20gpus_20',['NVIDIA GPUs',['../running.html#autotoc_md397',1,'']]],
  ['nvidia_20v100_20gpu_21',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md242',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md245',1,'NVIDIA V100 GPU']]]
];
