var searchData=
[
  ['gamma_0',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md452',1,'']]],
  ['gas_20eos_20chemistry_20chemistry_20true_1',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_2',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md152',1,'']]],
  ['gas_20jet_202d_3',['Gas Jet (2D)',['../examples.html#autotoc_md224',1,'']]],
  ['gate_20runs_20first_20blocks_20all_20other_20jobs_4',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['general_5',['general',['../parameters.html#general',1,'']]],
  ['general_20herschel_20bulkley_20poiseuille_20channel_6',['2D General Herschel-Bulkley Poiseuille Channel',['../examples.html#autotoc_md295',1,'']]],
  ['general_20options_7',['General Options',['../gpuParallelization.html#autotoc_md369',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md372',1,'NVHPC General Options']]],
  ['general_20users_3a_20dimensional_20handling_8',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['generalized_20characteristic_20boundary_20conditions_9',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md39',1,'']]],
  ['generalized_20riemann_20igr_10',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md484',1,'']]],
  ['generate_11',['generate',['../cli-reference.html#generate',1,'']]],
  ['generation_12',['Video generation',['../visualization.html#autotoc_md600',1,'']]],
  ['geometric_20regularization_20igr_20true_20wilfong25a_13',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['geometry_14',['Geometry',['../physics_constraints.html#autotoc_md459',1,'Domain and Geometry'],['../case_constraints.html#compat-geometry',1,'Geometry']]],
  ['geometry_20and_20parameters_15',['Geometry and parameters',['../examples.html#autotoc_md230',1,'']]],
  ['getting_20help_16',['Getting Help',['../troubleshooting.html#autotoc_md591',1,'']]],
  ['getting_20set_20up_17',['Getting Set Up',['../contributing.html#autotoc_md85',1,'']]],
  ['getting_20started_18',['Getting Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md335',1,'Getting Started'],['../index.html#autotoc_md502',1,'Getting Started']]],
  ['getting_2dstarted_2emd_19',['getting-started.md',['../getting-started_8md.html',1,'']]],
  ['gilmore_20bubble_5fmodel_201_20gilmore52_20',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['gilmore52_21',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['golden_20files_22',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md564',1,'']]],
  ['gottlieb98_23',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['governing_20pdes_24',['2. Governing PDEs',['../equations.html#autotoc_md146',1,'']]],
  ['governing_20physics_25',['Governing physics',['../examples.html#autotoc_md274',1,'']]],
  ['governing_20physics_20and_20analytic_20solution_26',['Governing physics and analytic solution',['../examples.html#autotoc_md243',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md249',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md255',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md297',1,'Governing physics and analytic solution']]],
  ['gpu_27',['GPU',['../contributing.html#autotoc_md106',1,'Fypp and GPU'],['../expectedPerformance.html#autotoc_md331',1,'NVIDIA V100 GPU']]],
  ['gpu_20arrays_28',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md110',1,'']]],
  ['gpu_20detection_29',['Verifying GPU Detection',['../running.html#autotoc_md518',1,'']]],
  ['gpu_20historical_30',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md328',1,'']]],
  ['gpu_20not_20detected_31',['GPU not detected',['../troubleshooting.html#autotoc_md582',1,'']]],
  ['gpu_20openacc_20errors_32',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md576',1,'']]],
  ['gpu_20parallel_20loop_33',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md109',1,'']]],
  ['gpu_20parallelization_34',['GPU Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md349',1,'GPU Parallelization']]],
  ['gpu_20performance_20nvidia_20uvm_35',['20. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md36',1,'']]],
  ['gpu_20profiling_36',['GPU Profiling',['../troubleshooting.html#autotoc_md569',1,'AMD GPU Profiling'],['../running.html#autotoc_md519',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md568',1,'NVIDIA GPU Profiling']]],
  ['gpu_20support_37',['Building with GPU Support',['../running.html#autotoc_md514',1,'']]],
  ['gpu_20weak_20scaling_38',['GPU weak scaling',['../expectedPerformance.html#autotoc_md327',1,'']]],
  ['gpu_5froutine_20device_20helpers_39',['Writing GPU_ROUTINE Device Helpers',['../gpuParallelization.html#autotoc_md363',1,'']]],
  ['gpuparallelization_2emd_40',['gpuParallelization.md',['../gpuParallelization_8md.html',1,'']]],
  ['gpus_41',['GPUs',['../running.html#autotoc_md521',1,'AMD GPUs'],['../gpuParallelization.html#autotoc_md365',1,'Debugging Tools and Tips for GPUs'],['../running.html#autotoc_md520',1,'NVIDIA GPUs'],['../running.html#autotoc_md513',1,'Running on GPUs'],['../running.html#autotoc_md515',1,'Running on GPUs']]],
  ['green_20vortex_203d_42',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md265',1,'']]],
  ['grid_20bubble_20dynamics_20wilfong26_20sec_204_201_43',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md159',1,'']]],
  ['grid_20bubble_20models_44',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['grid_20points_45',['Grid Points',['../expectedPerformance.html#autotoc_md332',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md333',1,'64M Grid Points']]],
  ['grind_20time_20performance_46',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md325',1,'']]],
  ['gui_47',['Docker Desktop GUI',['../docker.html#autotoc_md128',1,'']]],
  ['guide_48',['Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md42',1,'Case Creator Guide'],['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md536',1,'Troubleshooting Guide']]],
  ['guidelines_49',['Soft Guidelines',['../contributing.html#autotoc_md96',1,'']]],
  ['guides_50',['How-To Guides',['../contributing.html#autotoc_md107',1,'']]]
];
