var searchData=
[
  ['accepting_20command_20line_20arguments_0',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md3',1,'']]],
  ['acoustic_20source_1',['8. Acoustic Source',['../md_case.html#acoustic-source',1,'']]],
  ['acoustic_20supports_2',['Acoustic Supports',['../md_case.html#acoustic-supports',1,'']]],
  ['adaptive_20time_20stepping_3',['Adaptive Time-Stepping',['../md_case.html#autotoc_md18',1,'']]],
  ['agnostic_20tools_4',['Compiler agnostic tools',['../md_gpuParallelization.html#autotoc_md123',1,'']]],
  ['algorithm_5',['6. Simulation Algorithm',['../md_case.html#autotoc_md15',1,'']]],
  ['amd_20gpus_6',['AMD GPUs',['../md_running.html#autotoc_md143',1,'']]],
  ['amd_20mi250x_20gpu_7',['AMD MI250X GPU',['../md_expectedPerformance.html#autotoc_md94',1,'']]],
  ['an_20example_20case_8',['Running an Example Case',['../md_getting-started.html#autotoc_md107',1,'']]],
  ['analytical_20definition_20of_20primitive_20variables_9',['Analytical Definition of Primitive Variables',['../md_case.html#autotoc_md8',1,'']]],
  ['and_20final_20conditions_10',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md68',1,'']]],
  ['and_20linear_20theory_11',['and Linear Theory',['../md_examples.html#autotoc_md44',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md75',1,'Final Condition and Linear Theory']]],
  ['and_20result_12',['Initial Condition and Result',['../md_examples.html#autotoc_md50',1,'']]],
  ['and_20tips_20for_20gpus_13',['Debugging Tools and Tips for GPUs',['../md_gpuParallelization.html#autotoc_md122',1,'']]],
  ['api_20documentation_14',['API Documentation',['../md_readme.html#autotoc_md136',1,'Code/API Documentation'],['../md_gpuParallelization.html#autotoc_md110',1,'Macro API Documentation']]],
  ['arguments_15',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md3',1,'']]],
  ['artificial_20mach_20number_16',['12. Artificial Mach Number',['../md_case.html#autotoc_md25',1,'']]],
  ['at_20final_20time_17',['Numerical Schlieren at Final Time',['../md_examples.html#autotoc_md63',1,'']]],
  ['at_20transitional_20state_18',['Liutex visualization at transitional state',['../md_examples.html#autotoc_md84',1,'']]],
  ['authors_19',['Authors',['../md_authors.html',1,'']]],
  ['authors_2emd_20',['authors.md',['../authors_8md.html',1,'']]],
  ['averaged_20bubble_20model_21',['Averaged Bubble Model',['../md_case.html#autotoc_md21',1,'9.1 Ensemble-Averaged Bubble Model'],['../md_case.html#autotoc_md22',1,'9.2 Volume-Averaged Bubble Model']]]
];
