var searchData=
[
  ['h5py_20is_20required_20to_20read_20silo_20hdf5_20files_0',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['halo_20exchange_1',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md111',1,'']]],
  ['handling_2',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['hangs_3',['MPI errors or hangs',['../troubleshooting.html#autotoc_md565',1,'']]],
  ['happens_20at_20each_20stage_4',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['hard_20coded_20patches_5',['Hard Coded Patches',['../case.html#autotoc_md21',1,'']]],
  ['hard_20rules_6',['Hard Rules',['../contributing.html#autotoc_md92',1,'']]],
  ['hardcodied_20ic_20example_7',['2D Hardcodied IC Example',['../examples.html#autotoc_md214',1,'']]],
  ['harten83_8',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md194',1,'']]],
  ['has_20artifacts_9',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md571',1,'']]],
  ['hdf5_20files_10',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['helmholtz_20instability_202d_11',['Kelvin-Helmholtz Instability (2D)',['../examples.html#autotoc_md216',1,'']]],
  ['help_12',['Getting Help',['../troubleshooting.html#autotoc_md573',1,'']]],
  ['help_13',['help',['../cli-reference.html#help',1,'']]],
  ['helpful_20tools_14',['Helpful Tools',['../getting-started.html#autotoc_md342',1,'']]],
  ['herschel_20bulkley_20poiseuille_20channel_15',['2D General Herschel-Bulkley Poiseuille Channel',['../examples.html#autotoc_md292',1,'']]],
  ['herschel_20bulkley_20viscosity_16',['Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md470',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['historical_17',['historical',['../expectedPerformance.html#autotoc_md326',1,'IBM Power9 CPU (historical)'],['../expectedPerformance.html#autotoc_md325',1,'NVIDIA V100 GPU (historical)']]],
  ['hll_20riemann_5fsolver_201_20harten83_18',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md194',1,'']]],
  ['hllc_20riemann_5fsolver_202_20toro94_19',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[51]&lt;/a&gt;)',['../equations.html#autotoc_md195',1,'']]],
  ['hlld_20riemann_5fsolver_204_20mhd_20only_20',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md197',1,'']]],
  ['homebrew_20macos_21',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md334',1,'']]],
  ['homebrew_20package_20macos_22',['Using the Homebrew package (macOS)',['../running.html#autotoc_md491',1,'']]],
  ['how_20to_20add_20a_20new_20simulation_20parameter_23',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md105',1,'']]],
  ['how_20to_20add_20a_20post_20processing_20output_20variable_24',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md112',1,'']]],
  ['how_20to_20add_20a_20test_20case_25',['How to Add a Test Case',['../contributing.html#autotoc_md108',1,'']]],
  ['how_20to_20allocate_20and_20manage_20gpu_20arrays_26',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md107',1,'']]],
  ['how_20to_20create_20a_20new_20fortran_20module_27',['How to Create a New Fortran Module',['../contributing.html#autotoc_md109',1,'']]],
  ['how_20to_20document_20physics_20constraints_28',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['how_20to_20extend_20mpi_20halo_20exchange_29',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md111',1,'']]],
  ['how_20to_20guides_30',['How-To Guides',['../contributing.html#autotoc_md104',1,'']]],
  ['how_20to_20run_31',['How to run',['../examples.html#autotoc_md229',1,'How to run'],['../examples.html#autotoc_md241',1,'How to run'],['../examples.html#autotoc_md247',1,'How to run'],['../examples.html#autotoc_md253',1,'How to run'],['../examples.html#autotoc_md272',1,'How to run'],['../examples.html#autotoc_md295',1,'How to run']]],
  ['how_20to_20write_20a_20gpu_20parallel_20loop_32',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md106',1,'']]],
  ['hpc_33',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md559',1,'']]],
  ['hyperelastic_20model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_34',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md168',1,'']]],
  ['hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_35',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md168',1,'']]],
  ['hypoelastic_20model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_36',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md167',1,'']]],
  ['hypoelasticity_37',['Hypoelasticity',['../physics_constraints.html#autotoc_md466',1,'']]],
  ['hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_38',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md167',1,'']]]
];
