var searchData=
[
  ['i_20o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_1',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['ib_5fairfoil_2',['ib_airfoil',['../parameters.html#ib_airfoil',1,'']]],
  ['ibm_20bow_20shock_203d_3',['IBM Bow Shock (3D)',['../examples.html#autotoc_md232',1,'']]],
  ['ibm_20cfl_20dt_202d_4',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md284',1,'']]],
  ['ibm_20power9_20cpu_5',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md333',1,'']]],
  ['ibm_20power9_20cpu_20historical_6',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md328',1,'']]],
  ['ibm_20walled_20power_20law_20poiseuille_20channel_7',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md308',1,'']]],
  ['ic_20example_8',['2D Hardcodied IC Example',['../examples.html#autotoc_md276',1,'']]],
  ['ic_20extrusion_9',['IC Extrusion',['../physics_constraints.html#autotoc_md505',1,'']]],
  ['ic_20extrusion_20file_20parameters_10',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md506',1,'']]],
  ['ideal_20gas_20eos_20chemistry_20chemistry_20true_11',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['ideal_20mhd_20mhd_20true_20wilfong26_20sec_204_201_209_12',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['igr_13',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md486',1,'']]],
  ['igr_20reconstruction_14',['IGR Reconstruction',['../equations.html#autotoc_md193',1,'']]],
  ['igr_20true_20wilfong25a_15',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[58]&lt;/a&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['images_16',['Base Images',['../docker.html#autotoc_md137',1,'']]],
  ['immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['immersed_20boundary_20patch_20types_18',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['immersed_20boundary_20patches_19',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['implementation_20',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['in_20cylindrical_20coordinates_21',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md614',1,'']]],
  ['in_20dimensions_20out_22',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['in_20inactive_20dimensions_23',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md467',1,'']]],
  ['inactive_20dimensions_24',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md467',1,'']]],
  ['indexing_25',['Array Bounds and Indexing',['../contributing.html#autotoc_md98',1,'']]],
  ['inert_20shock_20tube_26',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md240',1,'']]],
  ['information_20geometric_20regularization_20igr_20true_20wilfong25a_27',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[58]&lt;/a&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['infrastructure_28',['Infrastructure',['../architecture.html#autotoc_md10',1,'']]],
  ['initial_20and_20final_20conditions_29',['Density Initial and Final Conditions',['../examples.html#autotoc_md231',1,'']]],
  ['initial_20condition_30',['Initial Condition',['../examples.html#autotoc_md222',1,'Initial Condition'],['../examples.html#autotoc_md225',1,'Initial Condition'],['../examples.html#autotoc_md241',1,'Initial Condition'],['../examples.html#autotoc_md261',1,'Initial Condition'],['../examples.html#autotoc_md290',1,'Initial Condition'],['../examples.html#autotoc_md304',1,'Initial Condition']]],
  ['initial_20condition_20and_20result_31',['Initial Condition and Result',['../examples.html#autotoc_md277',1,'']]],
  ['initial_20condition_20constraints_32',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md455',1,'']]],
  ['initial_20state_33',['Initial State',['../examples.html#autotoc_md217',1,'Initial State'],['../examples.html#autotoc_md287',1,'Initial State'],['../examples.html#autotoc_md301',1,'Initial State']]],
  ['input_20parameters_34',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['instability_202d_35',['Instability 2D',['../examples.html#autotoc_md286',1,'Kelvin-Helmholtz Instability (2D)'],['../examples.html#autotoc_md258',1,'Rayleigh-Taylor Instability (2D)'],['../examples.html#autotoc_md300',1,'Richtmyer-Meshkov Instability (2D)']]],
  ['instability_203d_36',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md243',1,'']]],
  ['install_20via_20homebrew_20macos_37',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md336',1,'']]],
  ['integral_38',['integral',['../parameters.html#integral',1,'']]],
  ['integration_39',['15.3 Time Integration',['../equations.html#autotoc_md200',1,'']]],
  ['interaction_40',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md169',1,'']]],
  ['interactive_41',['interactive',['../cli-reference.html#interactive',1,'']]],
  ['interactive_20execution_42',['Interactive Execution',['../running.html#autotoc_md516',1,'']]],
  ['interactive_20mode_43',['Interactive mode',['../visualization.html#autotoc_md607',1,'']]],
  ['interactive_20shell_44',['Interactive Shell',['../docker.html#autotoc_md133',1,'']]],
  ['intermediate_20examples_45',['🟡 Intermediate Examples',['../case_constraints.html#autotoc_md44',1,'']]],
  ['is_20required_20to_20read_20silo_20hdf5_20files_46',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md593',1,'']]],
  ['isentropic_20vortex_20problem_202d_47',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md255',1,'']]],
  ['isolating_20issues_48',['Isolating Issues',['../troubleshooting.html#autotoc_md556',1,'']]],
  ['issues_49',['Issues',['../troubleshooting.html#autotoc_md556',1,'Isolating Issues'],['../troubleshooting.html#autotoc_md590',1,'Visualization Issues']]],
  ['iterative_20generalized_20riemann_20igr_50',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md486',1,'']]]
];
