var searchData=
[
  ['gamma_0',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md397',1,'']]],
  ['gas_20eos_20chemistry_20chemistry_20true_1',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md149',1,'']]],
  ['gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_2',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md148',1,'']]],
  ['gas_20jet_202d_3',['Gas Jet (2D)',['../examples.html#autotoc_md248',1,'']]],
  ['gate_20runs_20first_20blocks_20all_20other_20jobs_4',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md116',1,'']]],
  ['general_5',['general',['../parameters.html#general',1,'']]],
  ['general_20options_6',['General Options',['../gpuParallelization.html#autotoc_md328',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md331',1,'NVHPC General Options']]],
  ['general_20users_3a_20dimensional_20handling_7',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['generalized_20characteristic_20boundary_20conditions_8',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md36',1,'']]],
  ['generalized_20riemann_20igr_9',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md429',1,'']]],
  ['generate_10',['generate',['../cli-reference.html#generate',1,'']]],
  ['generation_11',['Video generation',['../visualization.html#autotoc_md541',1,'']]],
  ['geometric_20regularization_20igr_20true_20wilfong25a_12',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['geometry_13',['Geometry',['../physics_constraints.html#autotoc_md404',1,'Domain and Geometry'],['../case_constraints.html#compat-geometry',1,'Geometry']]],
  ['getting_20help_14',['Getting Help',['../troubleshooting.html#autotoc_md532',1,'']]],
  ['getting_20set_20up_15',['Getting Set Up',['../contributing.html#autotoc_md82',1,'']]],
  ['getting_20started_16',['Getting Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md296',1,'Getting Started'],['../index.html#autotoc_md443',1,'Getting Started']]],
  ['getting_2dstarted_2emd_17',['getting-started.md',['../getting-started_8md.html',1,'']]],
  ['gilmore_20bubble_5fmodel_201_20gilmore52_18',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['gilmore52_19',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['golden_20files_20',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md505',1,'']]],
  ['gottlieb98_21',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md198',1,'']]],
  ['governing_20pdes_22',['2. Governing PDEs',['../equations.html#autotoc_md142',1,'']]],
  ['gpu_23',['GPU',['../contributing.html#autotoc_md102',1,'Fypp and GPU'],['../expectedPerformance.html#autotoc_md292',1,'NVIDIA V100 GPU']]],
  ['gpu_20arrays_24',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md106',1,'']]],
  ['gpu_20detection_25',['Verifying GPU Detection',['../running.html#autotoc_md459',1,'']]],
  ['gpu_20historical_26',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md289',1,'']]],
  ['gpu_20not_20detected_27',['GPU not detected',['../troubleshooting.html#autotoc_md523',1,'']]],
  ['gpu_20openacc_20errors_28',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md517',1,'']]],
  ['gpu_20parallel_20loop_29',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md105',1,'']]],
  ['gpu_20parallelization_30',['GPU Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md310',1,'GPU Parallelization']]],
  ['gpu_20performance_20nvidia_20uvm_31',['18. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md34',1,'']]],
  ['gpu_20profiling_32',['GPU Profiling',['../troubleshooting.html#autotoc_md510',1,'AMD GPU Profiling'],['../running.html#autotoc_md460',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md509',1,'NVIDIA GPU Profiling']]],
  ['gpu_20support_33',['Building with GPU Support',['../running.html#autotoc_md455',1,'']]],
  ['gpu_20weak_20scaling_34',['GPU weak scaling',['../expectedPerformance.html#autotoc_md288',1,'']]],
  ['gpuparallelization_2emd_35',['gpuParallelization.md',['../gpuParallelization_8md.html',1,'']]],
  ['gpus_36',['GPUs',['../running.html#autotoc_md462',1,'AMD GPUs'],['../gpuParallelization.html#autotoc_md324',1,'Debugging Tools and Tips for GPUs'],['../running.html#autotoc_md461',1,'NVIDIA GPUs'],['../running.html#autotoc_md454',1,'Running on GPUs'],['../running.html#autotoc_md456',1,'Running on GPUs']]],
  ['green_20vortex_203d_37',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md272',1,'']]],
  ['grid_20bubble_20dynamics_20wilfong26_20sec_204_201_38',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md155',1,'']]],
  ['grid_20bubble_20models_39',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['grid_20points_40',['Grid Points',['../expectedPerformance.html#autotoc_md293',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md294',1,'64M Grid Points']]],
  ['grind_20time_20performance_41',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md286',1,'']]],
  ['gui_42',['Docker Desktop GUI',['../docker.html#autotoc_md124',1,'']]],
  ['guide_43',['Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide'],['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md477',1,'Troubleshooting Guide']]],
  ['guidelines_44',['Soft Guidelines',['../contributing.html#autotoc_md92',1,'']]],
  ['guides_45',['How-To Guides',['../contributing.html#autotoc_md103',1,'']]]
];
