var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md116',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md118',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md119',1,'']]],
  ['target_20selection_20t_20targets_4',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['taylor_20green_20vortex_203d_6',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md254',1,'']]],
  ['taylor_20instability_202d_7',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md211',1,'']]],
  ['taylor_20instability_203d_8',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md245',1,'']]],
  ['templates_9',['Computer Templates',['../running.html#autotoc_md400',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_10',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md158',1,'']]],
  ['tensor_20viscous_20true_11',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md134',1,'']]],
  ['test_12',['test',['../examples.html#autotoc_md223',1,'Scaling and Performance test'],['../cli-reference.html#test',1,'test']]],
  ['test_202d_13',['2D Riemann Test (2D)',['../examples.html#autotoc_md216',1,'']]],
  ['test_20case_14',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['test_20debugging_15',['Test Debugging',['../troubleshooting.html#autotoc_md433',1,'']]],
  ['test_20execution_16',['Serial Test Execution',['../troubleshooting.html#autotoc_md435',1,'']]],
  ['test_20fails_17',['Test Fails?',['../troubleshooting.html#autotoc_md418',1,'']]],
  ['test_20failures_18',['Understanding Test Failures',['../troubleshooting.html#autotoc_md438',1,'']]],
  ['test_20matrix_19',['Build and Test Matrix',['../contributing.html#autotoc_md101',1,'']]],
  ['test_20output_20location_20',['Test Output Location',['../troubleshooting.html#autotoc_md436',1,'']]],
  ['test_20suite_21',['Running the Test Suite',['../getting-started.html#autotoc_md284',1,'']]],
  ['testing_22',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md98',1,'Testing'],['../testing.html#autotoc_md406',1,'Testing']]],
  ['testing_20post_20process_23',['Testing Post Process',['../testing.html#autotoc_md408',1,'']]],
  ['testing_2emd_24',['testing.md',['../testing_8md.html',1,'']]],
  ['tests_25',['Tests',['../testing.html#autotoc_md407',1,'Creating Tests'],['../troubleshooting.html#autotoc_md434',1,'Running Specific Tests']]],
  ['the_20homebrew_20package_20macos_26',['Using the Homebrew package (macOS)',['../running.html#autotoc_md382',1,'']]],
  ['the_20precision_20system_27',['Working with the Precision System',['../contributing.html#autotoc_md93',1,'']]],
  ['the_20script_28',['Step 2: Customizing the script',['../visualization.html#autotoc_md466',1,'']]],
  ['the_20test_20suite_29',['Running the Test Suite',['../getting-started.html#autotoc_md284',1,'']]],
  ['theory_30',['Theory',['../examples.html#autotoc_md212',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md246',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_31',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['thompson87_20thompson90_20bc_5fxbeg_205_20to_2012_32',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['thompson90_20bc_5fxbeg_205_20to_2012_33',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['three_20phase_20pipeline_34',['Three-Phase Pipeline',['../contributing.html#autotoc_md68',1,'']]],
  ['time_35',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md198',1,'']]],
  ['time_20integration_36',['15.3 Time Integration',['../equations.html#autotoc_md180',1,'']]],
  ['time_20performance_37',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md268',1,'']]],
  ['time_20stepping_38',['Time Stepping',['../case.html#autotoc_md12',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md11',1,'Constant Time-Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_39',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_40',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['tips_20for_20gpus_41',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['titarev_20toro_20problem_201d_42',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md227',1,'']]],
  ['to_2012_43',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_44',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_45',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['to_20add_20a_20test_20case_46',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_47',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_48',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_49',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['to_20guides_50',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]],
  ['to_20mfc_51',['Contributing to MFC',['../contributing.html#autotoc_md65',1,'']]],
  ['to_20use_20case_20optimization_52',['When to use case optimization',['../expectedPerformance.html#autotoc_md262',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_53',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['toolchain_54',['Toolchain',['../contributing.html#autotoc_md71',1,'Build Toolchain'],['../contributing.html#autotoc_md83',1,'Python Toolchain']]],
  ['tools_55',['Tools',['../gpuParallelization.html#autotoc_md307',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md286',1,'Helpful Tools']]],
  ['tools_56',['tools',['../gpuParallelization.html#autotoc_md305',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md306',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_57',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['topics_58',['Advanced Topics',['../index.html#autotoc_md378',1,'']]],
  ['toro_20problem_201d_59',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md227',1,'']]],
  ['toro94_60',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['transitional_20state_61',['Liutex visualization at transitional state',['../examples.html#autotoc_md219',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_62',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['triple_20point_202d_63',['2D Triple Point (2D)',['../examples.html#autotoc_md197',1,'']]],
  ['troubleshooting_20guide_64',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md409',1,'Troubleshooting Guide']]],
  ['troubleshooting_2emd_65',['troubleshooting.md',['../troubleshooting_8md.html',1,'']]],
  ['true_66',['true',['../equations.html#autotoc_md168',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md132',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md134',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md139',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md182',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_67',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['true_20kamrin12_20wilfong26_20sec_204_201_206_68',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['true_20maeda18_69',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md146',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_70',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md149',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_71',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md158',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_72',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['true_20wilfong25a_73',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['true_20wilfong26_20sec_202_203_74',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md136',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_75',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md162',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_76',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md152',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_77',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md156',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_78',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md161',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_79',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['tube_80',['Tube',['../examples.html#autotoc_md242',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md213',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_81',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md234',1,'']]],
  ['tube_20problem_201d_82',['Lax shock tube problem (1D)',['../examples.html#autotoc_md199',1,'']]],
  ['turbulent_20mixing_20layer_203d_83',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md218',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_84',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['type_20meanings_85',['Data Type Meanings',['../gpuParallelization.html#autotoc_md293',1,'']]],
  ['type_20safety_86',['Precision and Type Safety',['../contributing.html#autotoc_md79',1,'']]],
  ['types_87',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['types_88',['Patch types',['../case.html#patch-types',1,'']]]
];
