var searchData=
[
  ['elasticity_0',['15. Elasticity',['../case.html#autotoc_md17',1,'']]],
  ['elliptic_20smoothing_1',['Elliptic Smoothing',['../case.html#autotoc_md9',1,'']]],
  ['ensemble_20averaged_20bubble_20model_2',['9.1 Ensemble-Averaged Bubble Model',['../case.html#autotoc_md13',1,'']]],
  ['enumerations_3',['Enumerations',['../case.html#autotoc_md20',1,'']]],
  ['environment_4',['Environment',['../getting-started.html#autotoc_md282',1,'Build Environment'],['../visualization.html#autotoc_md517',1,'Step 1: Setting up your Environment']]],
  ['environment_20setup_5',['Environment Setup',['../running.html#autotoc_md442',1,'']]],
  ['eos_20chemistry_20chemistry_20true_6',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md133',1,'']]],
  ['eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_7',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md132',1,'']]],
  ['eos_20parameter_20sanity_20transformed_20gamma_8',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md381',1,'']]],
  ['eos_20positivity_9',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md380',1,'']]],
  ['equation_20model_20model_5feqns_202_10',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md127',1,'']]],
  ['equation_20model_20model_5feqns_203_11',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md128',1,'']]],
  ['equation_20selection_12',['Model Equation Selection',['../physics_constraints.html#autotoc_md397',1,'']]],
  ['equations_13',['Equations',['../case_constraints.html#model-equations',1,'🔢 Model Equations'],['../equations.html',1,'Equations'],['../physics_constraints.html#autotoc_md396',1,'Model Equations']]],
  ['equations_20of_20state_14',['3. Equations of State',['../equations.html#autotoc_md131',1,'']]],
  ['equations_20reference_15',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md121',1,'']]],
  ['equations_2emd_16',['equations.md',['../equations_8md.html',1,'']]],
  ['errors_17',['Errors',['../troubleshooting.html#autotoc_md497',1,'Common Build Errors'],['../troubleshooting.html#autotoc_md504',1,'Common Runtime Errors']]],
  ['errors_18',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['errors_20or_20hangs_19',['MPI errors or hangs',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['euler_20bubble_20model_20',['Euler-Euler Bubble Model',['../physics_constraints.html#autotoc_md403',1,'']]],
  ['euler_20bubbles_20bubbles_5feuler_20true_21',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md140',1,'']]],
  ['euler_20euler_20bubble_20model_22',['Euler-Euler Bubble Model',['../physics_constraints.html#autotoc_md403',1,'']]],
  ['euler_20euler_20bubbles_20bubbles_5feuler_20true_23',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md140',1,'']]],
  ['euler_20lagrange_20bubble_20model_24',['Euler-Lagrange Bubble Model',['../physics_constraints.html#autotoc_md405',1,'']]],
  ['euler_20lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_25',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['evolved_20state_26',['Evolved State',['../examples.html#autotoc_md205',1,'Evolved State'],['../examples.html#autotoc_md223',1,'Evolved State'],['../examples.html#autotoc_md237',1,'Evolved State']]],
  ['exact_20riemann_5fsolver_203_27',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md179',1,'']]],
  ['example_28',['Example',['../examples.html#autotoc_md248',1,'2D Hardcodied IC Example'],['../examples.html#autotoc_md227',1,'Example']]],
  ['example_20case_29',['Running an Example Case',['../getting-started.html#autotoc_md286',1,'']]],
  ['example_20cases_30',['Example Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md196',1,'Example Cases']]],
  ['example_20runs_31',['Example Runs',['../running.html#autotoc_md457',1,'']]],
  ['example_20tags_32',['Example Tags',['../docker.html#autotoc_md119',1,'']]],
  ['example_3a_20non_20dimensionalizing_20a_20bubble_20case_33',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['examples_34',['Examples',['../case_constraints.html#autotoc_md27',1,'🔴 Advanced Examples'],['../case_constraints.html#autotoc_md26',1,'🟡 Intermediate Examples'],['../case_constraints.html#autotoc_md25',1,'🟢 Beginner Examples'],['../running.html#autotoc_md451',1,'Examples'],['../equations.html#sec-nondim-example',1,'Worked Examples']]],
  ['examples_20visualization_35',['Examples &amp;amp; Visualization',['../index.html#autotoc_md429',1,'']]],
  ['examples_2emd_36',['examples.md',['../examples_8md.html',1,'']]],
  ['exchange_37',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['execution_38',['Execution',['../running.html#autotoc_md448',1,'Batch Execution'],['../running.html#autotoc_md436',1,'Interactive Execution'],['../troubleshooting.html#autotoc_md487',1,'Serial Test Execution']]],
  ['expectedperformance_2emd_39',['expectedPerformance.md',['../expectedPerformance_8md.html',1,'']]],
  ['extend_20mpi_20halo_20exchange_40',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]]
];
