var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md106',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md161',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md163',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md164',1,'']]],
  ['target_20selection_20t_20targets_4',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md106',1,'']]],
  ['targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md106',1,'']]],
  ['taylor_20green_20vortex_203d_6',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md299',1,'']]],
  ['taylor_20instability_202d_7',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md256',1,'']]],
  ['taylor_20instability_203d_8',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md290',1,'']]],
  ['templates_9',['Computer Templates',['../running.html#autotoc_md478',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_10',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;b&gt;[Schmidmayer17]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.8)',['../equations.html#autotoc_md203',1,'']]],
  ['tensor_20viscous_20true_11',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md179',1,'']]],
  ['test_12',['test',['../examples.html#autotoc_md268',1,'Scaling and Performance test'],['../cli-reference.html#autotoc_md63',1,'test']]],
  ['test_202d_13',['2D Riemann Test (2D)',['../examples.html#autotoc_md261',1,'']]],
  ['test_20case_14',['How to Add a Test Case',['../contributing.html#autotoc_md136',1,'']]],
  ['test_20debugging_15',['Test Debugging',['../troubleshooting.html#autotoc_md511',1,'']]],
  ['test_20execution_16',['Serial Test Execution',['../troubleshooting.html#autotoc_md513',1,'']]],
  ['test_20fails_17',['Test Fails?',['../troubleshooting.html#autotoc_md496',1,'']]],
  ['test_20failures_18',['Understanding Test Failures',['../troubleshooting.html#autotoc_md516',1,'']]],
  ['test_20matrix_19',['Build and Test Matrix',['../contributing.html#autotoc_md146',1,'']]],
  ['test_20output_20location_20',['Test Output Location',['../troubleshooting.html#autotoc_md514',1,'']]],
  ['test_20suite_21',['Running the Test Suite',['../getting-started.html#autotoc_md329',1,'']]],
  ['testing_22',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md143',1,'Testing'],['../testing.html#autotoc_md484',1,'Testing']]],
  ['testing_20post_20process_23',['Testing Post Process',['../testing.html#autotoc_md486',1,'']]],
  ['testing_2emd_24',['testing.md',['../testing_8md.html',1,'']]],
  ['tests_25',['Tests',['../testing.html#autotoc_md485',1,'Creating Tests'],['../troubleshooting.html#autotoc_md512',1,'Running Specific Tests']]],
  ['the_20homebrew_20package_20macos_26',['Using the Homebrew package (macOS)',['../running.html#autotoc_md460',1,'']]],
  ['the_20precision_20system_27',['Working with the Precision System',['../contributing.html#autotoc_md138',1,'']]],
  ['the_20script_28',['Step 2: Customizing the script',['../visualization.html#autotoc_md544',1,'']]],
  ['the_20test_20suite_29',['Running the Test Suite',['../getting-started.html#autotoc_md329',1,'']]],
  ['theory_30',['Theory',['../examples.html#autotoc_md257',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md291',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_31',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;b&gt;[Preston07]&lt;/b&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['thompson87_20thompson90_20bc_5fxbeg_205_20to_2012_32',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['thompson90_20bc_5fxbeg_205_20to_2012_33',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['three_20phase_20pipeline_34',['Three-Phase Pipeline',['../contributing.html#autotoc_md113',1,'']]],
  ['time_35',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md243',1,'']]],
  ['time_20integration_36',['15.3 Time Integration',['../equations.html#autotoc_md225',1,'']]],
  ['time_20performance_37',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md313',1,'']]],
  ['time_20stepping_38',['Time Stepping',['../case.html#autotoc_md19',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md18',1,'Constant Time-Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_39',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md227',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_40',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;b&gt;[Gottlieb98]&lt;/b&gt;)',['../equations.html#autotoc_md226',1,'']]],
  ['tips_20for_20gpus_41',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md349',1,'']]],
  ['titarev_20toro_20problem_201d_42',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md272',1,'']]],
  ['to_2012_43',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_44',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md133',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_45',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md140',1,'']]],
  ['to_20add_20a_20test_20case_46',['How to Add a Test Case',['../contributing.html#autotoc_md136',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_47',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_48',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_49',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]],
  ['to_20guides_50',['How-To Guides',['../contributing.html#autotoc_md132',1,'']]],
  ['to_20mfc_51',['Contributing to MFC',['../contributing.html#autotoc_md110',1,'']]],
  ['to_20use_20case_20optimization_52',['When to use case optimization',['../expectedPerformance.html#autotoc_md307',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_53',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md134',1,'']]],
  ['toolchain_54',['Toolchain',['../contributing.html#autotoc_md116',1,'Build Toolchain'],['../contributing.html#autotoc_md128',1,'Python Toolchain']]],
  ['tools_55',['Tools',['../gpuParallelization.html#autotoc_md352',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md331',1,'Helpful Tools']]],
  ['tools_56',['tools',['../gpuParallelization.html#autotoc_md350',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md351',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_57',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md349',1,'']]],
  ['topics_58',['Advanced Topics',['../index.html#autotoc_md455',1,'']]],
  ['toro_20problem_201d_59',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md272',1,'']]],
  ['toro94_60',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;b&gt;[Toro94]&lt;/b&gt;)',['../equations.html#autotoc_md222',1,'']]],
  ['transitional_20state_61',['Liutex visualization at transitional state',['../examples.html#autotoc_md264',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_62',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;b&gt;[Bryngelson20]&lt;/b&gt;)',['../equations.html#autotoc_md190',1,'']]],
  ['triple_20point_202d_63',['2D Triple Point (2D)',['../examples.html#autotoc_md242',1,'']]],
  ['troubleshooting_20guide_64',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md487',1,'Troubleshooting Guide']]],
  ['troubleshooting_2emd_65',['troubleshooting.md',['../troubleshooting_8md.html',1,'']]],
  ['true_66',['true',['../equations.html#autotoc_md213',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md177',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md179',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md184',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md227',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_67',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;b&gt;[Bryngelson20]&lt;/b&gt;)',['../equations.html#autotoc_md190',1,'']]],
  ['true_20kamrin12_20wilfong26_20sec_204_201_206_68',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;b&gt;[Kamrin12]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.6)',['../equations.html#autotoc_md195',1,'']]],
  ['true_20maeda18_69',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;b&gt;[Maeda18]&lt;/b&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_70',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;b&gt;[Rodriguez19]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.6)',['../equations.html#autotoc_md194',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_71',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;b&gt;[Schmidmayer17]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.8)',['../equations.html#autotoc_md203',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_72',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;b&gt;[Tseng03]&lt;/b&gt;; &lt;b&gt;[Mittal05]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.1)',['../equations.html#autotoc_md235',1,'']]],
  ['true_20wilfong25a_73',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong25a]&lt;/b&gt;)',['../equations.html#autotoc_md209',1,'']]],
  ['true_20wilfong26_20sec_202_203_74',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.3)',['../equations.html#autotoc_md181',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_75',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.10)',['../equations.html#autotoc_md207',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_76',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.3)',['../equations.html#autotoc_md197',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_77',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.7)',['../equations.html#autotoc_md201',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_78',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.9)',['../equations.html#autotoc_md206',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_79',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;b&gt;[Tseng03]&lt;/b&gt;; &lt;b&gt;[Mittal05]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.1)',['../equations.html#autotoc_md235',1,'']]],
  ['tube_80',['Tube',['../examples.html#autotoc_md287',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md258',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_81',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md279',1,'']]],
  ['tube_20problem_201d_82',['Lax shock tube problem (1D)',['../examples.html#autotoc_md244',1,'']]],
  ['turbulent_20mixing_20layer_203d_83',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md263',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_84',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;b&gt;[Gottlieb98]&lt;/b&gt;)',['../equations.html#autotoc_md226',1,'']]],
  ['type_20meanings_85',['Data Type Meanings',['../gpuParallelization.html#autotoc_md338',1,'']]],
  ['type_20safety_86',['Precision and Type Safety',['../contributing.html#autotoc_md124',1,'']]],
  ['types_87',['Immersed Boundary Patch Types',['../case.html#autotoc_md36',1,'']]],
  ['types_88',['Patch types',['../case.html#autotoc_md35',1,'']]]
];
