var searchData=
[
  ['backward_20facing_20step_202d_0',['Backward Facing Step (2D)',['../examples.html#autotoc_md211',1,'']]],
  ['base_20images_1',['Base Images',['../docker.html#autotoc_md162',1,'']]],
  ['basic_20skeleton_2',['Basic Skeleton',['../case.html#autotoc_md2',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../running.html#autotoc_md401',1,'']]],
  ['batch_20execution_4',['Batch Execution',['../running.html#autotoc_md400',1,'']]],
  ['batch_20options_5',['Batch Options',['../running.html#autotoc_md402',1,'']]],
  ['bc_5fx_6',['bc_x',['../parameters.html#autotoc_md312',1,'']]],
  ['bc_5fy_7',['bc_y',['../parameters.html#autotoc_md315',1,'']]],
  ['bc_5fz_8',['bc_z',['../parameters.html#autotoc_md318',1,'']]],
  ['beginner_20examples_9',['🟢 Beginner Examples',['../case_constraints.html#autotoc_md41',1,'']]],
  ['bench_10',['bench',['../cli-reference.html#autotoc_md96',1,'']]],
  ['bench_5fdiff_11',['bench_diff',['../cli-reference.html#autotoc_md98',1,'']]],
  ['benchmark_20results_12',['Benchmark Results',['../expectedPerformance.html#autotoc_md238',1,'']]],
  ['blocks_20all_20other_20jobs_13',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['body_20forces_14',['13. Body Forces',['../case.html#autotoc_md27',1,'']]],
  ['boundary_20condition_20patches_15',['Boundary Condition Patches',['../case.html#autotoc_md17',1,'']]],
  ['boundary_20conditions_16',['Boundary conditions',['../case.html#autotoc_md33',1,'Boundary conditions'],['../case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['boundary_20patch_20types_17',['Immersed Boundary Patch Types',['../case.html#autotoc_md36',1,'']]],
  ['boundary_20patches_18',['4. Immersed Boundary Patches',['../case.html#autotoc_md13',1,'']]],
  ['bounds_20and_20indexing_19',['Array Bounds and Indexing',['../contributing.html#autotoc_md123',1,'']]],
  ['bow_20shock_203d_20',['IBM Bow Shock (3D)',['../examples.html#autotoc_md203',1,'']]],
  ['bub_5fpp_21',['bub_pp',['../parameters.html#autotoc_md327',1,'']]],
  ['bubble_20model_22',['Bubble Model',['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]],
  ['bubble_20models_23',['Bubble Models',['../case_constraints.html#autotoc_md52',1,'💧 Bubble Models'],['../case.html#autotoc_md21',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#autotoc_md47',1,'Bubble Models']]],
  ['build_24',['build',['../cli-reference.html#autotoc_md59',1,'']]],
  ['build_20and_20test_20matrix_25',['Build and Test Matrix',['../contributing.html#autotoc_md146',1,'']]],
  ['build_20configuration_20flags_26',['Build Configuration Flags',['../cli-reference.html#autotoc_md107',1,'']]],
  ['build_20debugging_27',['Build Debugging',['../troubleshooting.html#autotoc_md424',1,'']]],
  ['build_20environment_28',['Build Environment',['../getting-started.html#autotoc_md252',1,'']]],
  ['build_20errors_29',['Common Build Errors',['../troubleshooting.html#autotoc_md449',1,'']]],
  ['build_20fails_30',['Build Fails?',['../troubleshooting.html#autotoc_md420',1,'']]],
  ['build_20fails_20with_20gpu_20openacc_20errors_31',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md453',1,'']]],
  ['build_20toolchain_32',['Build Toolchain',['../contributing.html#autotoc_md116',1,'']]],
  ['building_20mfc_33',['Building MFC',['../getting-started.html#autotoc_md253',1,'']]],
  ['building_20with_20gpu_20support_34',['Building with GPU Support',['../running.html#autotoc_md391',1,'']]],
  ['builds_35',['Debug Builds',['../troubleshooting.html#autotoc_md426',1,'']]]
];
