var searchData=
[
  ['scaling_0',['Scaling',['../md_examples.html#autotoc_md60',1,'Strong Scaling'],['../md_examples.html#autotoc_md59',1,'Weak Scaling']]],
  ['scaling_1',['scaling',['../md_expectedPerformance.html#autotoc_md97',1,'Strong scaling'],['../md_examples.html#autotoc_md58',1,'Strong- &amp; Weak-scaling'],['../md_expectedPerformance.html#autotoc_md93',1,'Weak scaling']]],
  ['schlieren_20at_20final_20time_2',['Numerical Schlieren at Final Time',['../md_examples.html#autotoc_md46',1,'']]],
  ['script_3',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md156',1,'']]],
  ['serial_20data_20output_4',['Serial data output',['../md_visualization.html#autotoc_md153',1,'']]],
  ['server_5',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md157',1,'']]],
  ['setting_20up_20your_20environment_6',['Step 1: Setting up your Environment',['../md_visualization.html#autotoc_md155',1,'']]],
  ['setup_7',['10. Velocity Field Setup',['../md_case.html#autotoc_md23',1,'']]],
  ['shock_203d_8',['IBM Bow Shock (3D)',['../md_examples.html#autotoc_md87',1,'']]],
  ['shock_20droplet_202d_9',['Shock Droplet (2D)',['../md_examples.html#autotoc_md41',1,'']]],
  ['shock_20tube_10',['Shock Tube',['../md_examples.html#autotoc_md38',1,'1D Multi-Component Inert Shock Tube'],['../md_examples.html#autotoc_md84',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_20problem_201d_11',['Lax shock tube problem (1D)',['../md_examples.html#autotoc_md81',1,'']]],
  ['shu_20osher_20problem_201d_12',['Shu-Osher problem (1D)',['../md_examples.html#autotoc_md47',1,'']]],
  ['simulation_20algorithm_13',['6. Simulation Algorithm',['../md_case.html#autotoc_md15',1,'']]],
  ['skeleton_14',['Basic Skeleton',['../md_case.html#autotoc_md2',1,'']]],
  ['smoothing_15',['Elliptic Smoothing',['../md_case.html#autotoc_md11',1,'']]],
  ['source_16',['8. Acoustic Source',['../md_case.html#acoustic-source',1,'']]],
  ['started_17',['Getting Started',['../md_getting-started.html',1,'']]],
  ['state_18',['Liutex visualization at transitional state',['../md_examples.html#autotoc_md73',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_19',['Step 1: Setting up your Environment',['../md_visualization.html#autotoc_md155',1,'']]],
  ['step_202_3a_20customizing_20the_20script_20',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md156',1,'']]],
  ['step_202d_21',['Step 2D',['../md_examples.html#autotoc_md62',1,'Backward Facing Step (2D)'],['../md_examples.html#autotoc_md64',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_22',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md157',1,'']]],
  ['stepping_23',['Stepping',['../md_case.html#autotoc_md18',1,'Adaptive Time-Stepping'],['../md_case.html#autotoc_md17',1,'Constant Time-Stepping']]],
  ['stirred_20reactor_24',['Perfectly Stirred Reactor',['../md_examples.html#autotoc_md44',1,'']]],
  ['strong_20scaling_25',['Strong Scaling',['../md_examples.html#autotoc_md60',1,'']]],
  ['strong_20scaling_26',['Strong scaling',['../md_expectedPerformance.html#autotoc_md97',1,'']]],
  ['strong_20weak_20scaling_27',['Strong- &amp; Weak-scaling',['../md_examples.html#autotoc_md58',1,'']]],
  ['sub_20grid_20bubble_20models_28',['9. Sub-grid Bubble Models',['../md_case.html#autotoc_md20',1,'']]],
  ['suite_29',['Running the Test Suite',['../md_getting-started.html#autotoc_md106',1,'']]],
  ['supports_30',['Acoustic Supports',['../md_case.html#acoustic-supports',1,'']]],
  ['synchronization_20macros_31',['Synchronization Macros',['../md_gpuParallelization.html#autotoc_md118',1,'']]]
];
