var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md116',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md118',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md119',1,'']]],
  ['target_20selection_20t_20targets_4',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md61',1,'']]],
  ['taylor_20green_20vortex_203d_6',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md254',1,'']]],
  ['taylor_20instability_202d_7',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md211',1,'']]],
  ['taylor_20instability_203d_8',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md245',1,'']]],
  ['templates_9',['Computer Templates',['../running.html#autotoc_md450',1,'']]],
  ['tension_10',['Surface Tension',['../physics_constraints.html#autotoc_md407',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_11',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md158',1,'']]],
  ['tensor_20viscous_20true_12',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md134',1,'']]],
  ['test_13',['test',['../examples.html#autotoc_md223',1,'Scaling and Performance test'],['../cli-reference.html#test',1,'test']]],
  ['test_202d_14',['2D Riemann Test (2D)',['../examples.html#autotoc_md216',1,'']]],
  ['test_20case_15',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['test_20debugging_16',['Test Debugging',['../troubleshooting.html#autotoc_md483',1,'']]],
  ['test_20execution_17',['Serial Test Execution',['../troubleshooting.html#autotoc_md485',1,'']]],
  ['test_20fails_18',['Test Fails?',['../troubleshooting.html#autotoc_md468',1,'']]],
  ['test_20failures_19',['Understanding Test Failures',['../troubleshooting.html#autotoc_md488',1,'']]],
  ['test_20matrix_20',['Build and Test Matrix',['../contributing.html#autotoc_md101',1,'']]],
  ['test_20output_20location_21',['Test Output Location',['../troubleshooting.html#autotoc_md486',1,'']]],
  ['test_20suite_22',['Running the Test Suite',['../getting-started.html#autotoc_md284',1,'']]],
  ['testing_23',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md98',1,'Testing'],['../testing.html#autotoc_md456',1,'Testing']]],
  ['testing_20post_20process_24',['Testing Post Process',['../testing.html#autotoc_md458',1,'']]],
  ['testing_2emd_25',['testing.md',['../testing_8md.html',1,'']]],
  ['tests_26',['Tests',['../testing.html#autotoc_md457',1,'Creating Tests'],['../troubleshooting.html#autotoc_md484',1,'Running Specific Tests']]],
  ['the_20homebrew_20package_20macos_27',['Using the Homebrew package (macOS)',['../running.html#autotoc_md432',1,'']]],
  ['the_20precision_20system_28',['Working with the Precision System',['../contributing.html#autotoc_md93',1,'']]],
  ['the_20script_29',['Step 2: Customizing the script',['../visualization.html#autotoc_md516',1,'']]],
  ['the_20test_20suite_30',['Running the Test Suite',['../getting-started.html#autotoc_md284',1,'']]],
  ['theory_31',['Theory',['../examples.html#autotoc_md212',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md246',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_32',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['thermodynamic_20constraints_33',['Thermodynamic Constraints',['../physics_constraints.html#autotoc_md377',1,'']]],
  ['thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_34',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['thompson90_20bc_5fx_20beg_205_20to_2012_35',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['three_20phase_20pipeline_36',['Three-Phase Pipeline',['../contributing.html#autotoc_md68',1,'']]],
  ['time_37',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md198',1,'']]],
  ['time_20integration_38',['15.3 Time Integration',['../equations.html#autotoc_md180',1,'']]],
  ['time_20performance_39',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md268',1,'']]],
  ['time_20stepping_40',['Time Stepping',['../case.html#autotoc_md12',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md11',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md416',1,'Time Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_41',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_42',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['tips_20for_20gpus_43',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['titarev_20toro_20problem_201d_44',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md227',1,'']]],
  ['to_2012_45',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[47]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[48]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_46',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_47',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['to_20add_20a_20test_20case_48',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_49',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_50',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['to_20document_20physics_20constraints_51',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_52',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['to_20guides_53',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]],
  ['to_20mfc_54',['Contributing to MFC',['../contributing.html#autotoc_md65',1,'']]],
  ['to_20use_20case_20optimization_55',['When to use case optimization',['../expectedPerformance.html#autotoc_md262',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_56',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['toolchain_57',['Toolchain',['../contributing.html#autotoc_md71',1,'Build Toolchain'],['../contributing.html#autotoc_md83',1,'Python Toolchain']]],
  ['tools_58',['Tools',['../gpuParallelization.html#autotoc_md307',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md286',1,'Helpful Tools']]],
  ['tools_59',['tools',['../gpuParallelization.html#autotoc_md305',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md306',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_60',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['topics_61',['Advanced Topics',['../index.html#autotoc_md428',1,'']]],
  ['toro_20problem_201d_62',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md227',1,'']]],
  ['toro94_63',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['transformed_20gamma_64',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md379',1,'']]],
  ['transitional_20state_65',['Liutex visualization at transitional state',['../examples.html#autotoc_md219',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_66',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['triple_20point_202d_67',['2D Triple Point (2D)',['../examples.html#autotoc_md197',1,'']]],
  ['troubleshooting_20guide_68',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md459',1,'Troubleshooting Guide']]],
  ['troubleshooting_2emd_69',['troubleshooting.md',['../troubleshooting_8md.html',1,'']]],
  ['true_70',['true',['../equations.html#autotoc_md168',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md132',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md134',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md139',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md182',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_71',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['true_20kamrin12_20wilfong26_20sec_204_201_206_72',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['true_20maeda18_73',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md146',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_74',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md149',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_75',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md158',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_76',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['true_20wilfong25a_77',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['true_20wilfong26_20sec_202_203_78',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md136',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_79',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md162',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_80',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md152',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_81',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md156',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_82',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md161',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_83',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md190',1,'']]],
  ['tube_84',['Tube',['../examples.html#autotoc_md242',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md213',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_85',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md234',1,'']]],
  ['tube_20problem_201d_86',['Lax shock tube problem (1D)',['../examples.html#autotoc_md199',1,'']]],
  ['turbulent_20mixing_20layer_203d_87',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md218',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_88',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['type_20meanings_89',['Data Type Meanings',['../gpuParallelization.html#autotoc_md293',1,'']]],
  ['type_20safety_90',['Precision and Type Safety',['../contributing.html#autotoc_md79',1,'']]],
  ['types_91',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['types_92',['Patch types',['../case.html#patch-types',1,'']]]
];
