var searchData=
[
  ['facing_20step_202d_0',['Facing Step 2D',['../examples.html#autotoc_md282',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md280',1,'Forward Facing Step (2D)']]],
  ['failed_1',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md575',1,'']]],
  ['fails_2',['Fails',['../troubleshooting.html#autotoc_md543',1,'Build Fails?'],['../troubleshooting.html#autotoc_md544',1,'Run Fails?'],['../troubleshooting.html#autotoc_md545',1,'Test Fails?']]],
  ['fails_20with_20gpu_20openacc_20errors_3',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md576',1,'']]],
  ['failures_4',['Failures',['../contributing.html#autotoc_md122',1,'Common CI Failures'],['../troubleshooting.html#autotoc_md565',1,'Understanding Test Failures']]],
  ['false_20preston07_5',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['families_6',['Parameter Families',['../parameters.html#autotoc_md379',1,'']]],
  ['fd_5forder_201_202_204_7',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md206',1,'']]],
  ['feature_20compatibility_8',['Feature Compatibility',['../case_constraints.html#feature-compatibility',1,'📊 Feature Compatibility'],['../case.html#autotoc_md19',1,'Feature Compatibility'],['../physics_constraints.html#autotoc_md478',1,'Feature Compatibility']]],
  ['fetching_20mfc_9',['Fetching MFC',['../getting-started.html#autotoc_md336',1,'']]],
  ['fewer_20ranks_10',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md558',1,'']]],
  ['fft_20output_11',['FFT Output',['../physics_constraints.html#autotoc_md498',1,'']]],
  ['field_20setup_12',['10. Velocity Field Setup',['../case.html#sec-velocity-field-setup',1,'']]],
  ['figure_20of_20merit_3a_20grind_20time_20performance_13',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md325',1,'']]],
  ['file_20parameters_14',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md501',1,'']]],
  ['files_15',['Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md15',1,'Case Files'],['../troubleshooting.html#autotoc_md564',1,'Regenerating Golden Files']]],
  ['files_16',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md588',1,'']]],
  ['final_20condition_17',['Final Condition',['../examples.html#autotoc_md225',1,'Final Condition'],['../examples.html#autotoc_md236',1,'Final Condition'],['../examples.html#autotoc_md264',1,'Final Condition'],['../examples.html#autotoc_md266',1,'Final Condition']]],
  ['final_20condition_20and_20linear_20theory_18',['Final Condition and Linear Theory',['../examples.html#autotoc_md289',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md294',1,'Final Condition and Linear Theory']]],
  ['final_20condition_20density_19',['Final Condition Density',['../examples.html#autotoc_md281',1,'Final Condition (Density)'],['../examples.html#autotoc_md283',1,'Final Condition (Density)']]],
  ['final_20conditions_20',['Density Initial and Final Conditions',['../examples.html#autotoc_md223',1,'']]],
  ['final_20time_21',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md308',1,'']]],
  ['find_20a_20fortran_20compiler_22',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md574',1,'']]],
  ['find_20mpi_23',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md573',1,'']]],
  ['finite_20differences_20fd_5forder_201_202_204_24',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md206',1,'']]],
  ['first_20blocks_20all_20other_20jobs_25',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['fits_20together_26',['How the Build Fits Together',['../contributing.html#autotoc_md91',1,'']]],
  ['five_20equation_20model_20model_5feqns_202_27',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['flags_28',['Flags',['../cli-reference.html#autotoc_md81',1,'Build Configuration Flags'],['../troubleshooting.html#autotoc_md538',1,'Debugging Flags'],['../expectedPerformance.html#autotoc_md320',1,'Other Optimization Flags'],['../troubleshooting.html#autotoc_md539',1,'Profiling Flags']]],
  ['flow_29',['Flow',['../gpuParallelization.html#autotoc_md353',1,'Data Flow'],['../contributing.html#autotoc_md89',1,'Simulation Data Flow']]],
  ['flow_20parameters_20with_20bubbles_30',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['flow_20visualization_31',['Flow visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md592',1,'Flow visualization']]],
  ['fluid_20material_20s_32',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['fluid_20structure_20interaction_33',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md169',1,'']]],
  ['fluid_5fpp_34',['fluid_pp',['../parameters.html#fluid_pp',1,'']]],
  ['fluid_5frho_35',['fluid_rho',['../parameters.html#fluid_rho',1,'']]],
  ['flux_20limiting_36',['18. Flux Limiting',['../equations.html#autotoc_md215',1,'']]],
  ['flux_5fwrt_37',['flux_wrt',['../parameters.html#flux_wrt',1,'']]],
  ['for_20gpus_38',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md365',1,'']]],
  ['for_20optimization_39',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md321',1,'']]],
  ['for_20portability_40',['For Portability',['../docker.html#autotoc_md134',1,'']]],
  ['for_20stiff_20bubble_20dynamics_41',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md204',1,'']]],
  ['forces_42',['13. Body Forces',['../case.html#autotoc_md30',1,'']]],
  ['forces_20bf_5fx_20bf_5fy_20bf_5fz_43',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['format_44',['format',['../cli-reference.html#format',1,'']]],
  ['format_20selection_45',['Format selection',['../visualization.html#autotoc_md605',1,'']]],
  ['formatted_20output_46',['7. Formatted Output',['../case.html#sec-formatted-output',1,'']]],
  ['fortran_20compiler_47',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md574',1,'']]],
  ['fortran_20module_48',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['forward_20facing_20step_202d_49',['Forward Facing Step (2D)',['../examples.html#autotoc_md280',1,'']]],
  ['found_50',['found',['../troubleshooting.html#autotoc_md586',1,'&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;'],['../troubleshooting.html#autotoc_md587',1,'&quot;Variable &apos;X&apos; not found&quot;']]],
  ['found_20on_20hpc_51',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md577',1,'']]],
  ['fraction_20sum_52',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md456',1,'']]],
  ['framework_53',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['fypp_20and_20gpu_54',['Fypp and GPU',['../contributing.html#autotoc_md106',1,'']]],
  ['fypp_20preprocessing_20failed_55',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md575',1,'']]]
];
