var searchData=
[
  ['walled_20power_20law_20poiseuille_20channel_0',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md226',1,'']]],
  ['warnings_1',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['weak_20scaling_2',['Weak Scaling',['../examples.html#autotoc_md282',1,'']]],
  ['weak_20scaling_3',['Weak scaling',['../expectedPerformance.html#autotoc_md323',1,'']]],
  ['weak_20scaling_4',['GPU weak scaling',['../expectedPerformance.html#autotoc_md324',1,'']]],
  ['weno_20reconstruction_5',['WENO Reconstruction',['../physics_constraints.html#autotoc_md473',1,'']]],
  ['weno_20weno_5forder_203_205_207_6',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md190',1,'']]],
  ['weno_5forder_203_205_207_7',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md190',1,'']]],
  ['what_20happens_20at_20each_20stage_8',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['when_20to_20use_20case_20optimization_9',['When to use case optimization',['../expectedPerformance.html#autotoc_md316',1,'']]],
  ['wilfong25a_10',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['wilfong26_20sec_202_202_11',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md149',1,'']]],
  ['wilfong26_20sec_202_203_12',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md154',1,'']]],
  ['wilfong26_20sec_204_201_13',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md156',1,'']]],
  ['wilfong26_20sec_204_201_201_14',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md208',1,'']]],
  ['wilfong26_20sec_204_201_2010_15',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md180',1,'']]],
  ['wilfong26_20sec_204_201_203_16',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md170',1,'']]],
  ['wilfong26_20sec_204_201_206_17',['Wilfong26 Sec 4 1 6',['../equations.html#autotoc_md167',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md168',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)']]],
  ['wilfong26_20sec_204_201_207_18',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md174',1,'']]],
  ['wilfong26_20sec_204_201_208_19',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md176',1,'']]],
  ['wilfong26_20sec_204_201_209_20',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md179',1,'']]],
  ['wilfong26_20sec_204_202_204_21',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md210',1,'']]],
  ['with_20bubbles_22',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['with_20fewer_20ranks_23',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md540',1,'']]],
  ['with_20gpu_20openacc_20errors_24',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md558',1,'']]],
  ['with_20gpu_20support_25',['Building with GPU Support',['../running.html#autotoc_md496',1,'']]],
  ['with_20mfc_20sh_20viz_26',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md576',1,'']]],
  ['with_20paraview_27',['Visualizing with ParaView',['../visualization.html#autotoc_md590',1,'']]],
  ['with_20the_20precision_20system_28',['Working with the Precision System',['../contributing.html#autotoc_md110',1,'']]],
  ['with_20visit_29',['Visualizing with VisIt',['../visualization.html#autotoc_md592',1,'']]],
  ['within_20domain_30',['Patch Within Domain',['../physics_constraints.html#autotoc_md447',1,'']]],
  ['worked_20examples_31',['Worked Examples',['../equations.html#sec-nondim-example',1,'']]],
  ['workflow_32',['Workflow',['../troubleshooting.html#autotoc_md524',1,'Debugging Workflow'],['../contributing.html#autotoc_md89',1,'Development Workflow']]],
  ['working_20with_20the_20precision_20system_33',['Working with the Precision System',['../contributing.html#autotoc_md110',1,'']]],
  ['write_20a_20gpu_20parallel_20loop_34',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md106',1,'']]],
  ['wrong_20or_20has_20artifacts_35',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md571',1,'']]]
];
