var searchData=
[
  ['warnings_0',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['weak_20scaling_1',['Weak Scaling',['../examples.html#autotoc_md225',1,'']]],
  ['weak_20scaling_2',['Weak scaling',['../expectedPerformance.html#autotoc_md270',1,'']]],
  ['weno_20reconstruction_3',['WENO Reconstruction',['../physics_constraints.html#autotoc_md416',1,'']]],
  ['weno_20weno_5forder_203_205_207_4',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md173',1,'']]],
  ['weno_5forder_203_205_207_5',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md173',1,'']]],
  ['when_20to_20use_20case_20optimization_6',['When to use case optimization',['../expectedPerformance.html#autotoc_md263',1,'']]],
  ['wilfong25a_7',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['wilfong26_20sec_202_202_8',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md132',1,'']]],
  ['wilfong26_20sec_202_203_9',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md137',1,'']]],
  ['wilfong26_20sec_204_201_10',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md139',1,'']]],
  ['wilfong26_20sec_204_201_201_11',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md191',1,'']]],
  ['wilfong26_20sec_204_201_2010_12',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md163',1,'']]],
  ['wilfong26_20sec_204_201_203_13',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md153',1,'']]],
  ['wilfong26_20sec_204_201_206_14',['Wilfong26 Sec 4 1 6',['../equations.html#autotoc_md150',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md151',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)']]],
  ['wilfong26_20sec_204_201_207_15',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md157',1,'']]],
  ['wilfong26_20sec_204_201_208_16',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md159',1,'']]],
  ['wilfong26_20sec_204_201_209_17',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md162',1,'']]],
  ['wilfong26_20sec_204_202_204_18',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md193',1,'']]],
  ['with_20bubbles_19',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['with_20fewer_20ranks_20',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md483',1,'']]],
  ['with_20gpu_20openacc_20errors_21',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['with_20gpu_20support_22',['Building with GPU Support',['../running.html#autotoc_md439',1,'']]],
  ['with_20paraview_23',['Visualizing with Paraview',['../visualization.html#autotoc_md512',1,'']]],
  ['with_20the_20precision_20system_24',['Working with the Precision System',['../contributing.html#autotoc_md93',1,'']]],
  ['with_20visit_25',['Visualizing with VisIt',['../visualization.html#autotoc_md514',1,'']]],
  ['within_20domain_26',['Patch Within Domain',['../physics_constraints.html#autotoc_md391',1,'']]],
  ['worked_20examples_27',['Worked Examples',['../equations.html#sec-nondim-example',1,'']]],
  ['workflow_28',['Workflow',['../troubleshooting.html#autotoc_md467',1,'Debugging Workflow'],['../contributing.html#autotoc_md72',1,'Development Workflow']]],
  ['working_20with_20the_20precision_20system_29',['Working with the Precision System',['../contributing.html#autotoc_md93',1,'']]],
  ['write_20a_20gpu_20parallel_20loop_30',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]]
];
