var searchData=
[
  ['mach_20number_0',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['macos_1',['macOS',['../getting-started.html#autotoc_md251',1,'Install via Homebrew (macOS)'],['../running.html#autotoc_md386',1,'Using the Homebrew package (macOS)']]],
  ['macro_20api_20documentation_2',['Macro API Documentation',['../gpuParallelization.html#autotoc_md263',1,'']]],
  ['macros_3',['Macros',['../gpuParallelization.html#autotoc_md267',1,'Computation Macros'],['../gpuParallelization.html#autotoc_md269',1,'Data Control Macros'],['../gpuParallelization.html#autotoc_md273',1,'Miscellaneous Macros'],['../gpuParallelization.html#autotoc_md271',1,'Synchronization Macros']]],
  ['magnetohydrodynamics_20mhd_4',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md28',1,'']]],
  ['manage_20gpu_20arrays_5',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['material’s_6',['5. Fluid Material’s',['../case.html#autotoc_md15',1,'']]],
  ['matrix_7',['Build and Test Matrix',['../contributing.html#autotoc_md146',1,'']]],
  ['maximum_20performance_8',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md231',1,'']]],
  ['meanings_9',['Data Type Meanings',['../gpuParallelization.html#autotoc_md264',1,'']]],
  ['memory_20and_20allocation_10',['Memory and Allocation',['../contributing.html#autotoc_md125',1,'']]],
  ['merge_11',['Code Review and Merge',['../contributing.html#autotoc_md150',1,'']]],
  ['merit_3a_20grind_20time_20performance_12',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md239',1,'']]],
  ['meshkov_20instability_202d_13',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md197',1,'']]],
  ['messages_14',['Commit Messages',['../contributing.html#autotoc_md118',1,'']]],
  ['mfc_15',['MFC',['../getting-started.html#autotoc_md253',1,'Building MFC'],['../contributing.html#autotoc_md110',1,'Contributing to MFC'],['../getting-started.html#autotoc_md250',1,'Fetching MFC']]],
  ['mfc_20documentation_16',['MFC Documentation',['../index.html',1,'']]],
  ['mhd_17',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md28',1,'']]],
  ['mi250x_20gpu_18',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md241',1,'']]],
  ['miscellaneous_20macros_19',['Miscellaneous Macros',['../gpuParallelization.html#autotoc_md273',1,'']]],
  ['mixing_20layer_203d_20',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md222',1,'']]],
  ['model_21',['Model',['../case.html#autotoc_md25',1,'11. Phase Change Model'],['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]],
  ['model_20consistency_22',['Physics and Model Consistency',['../contributing.html#autotoc_md127',1,'']]],
  ['model_20equations_23',['🔢 Model Equations',['../case_constraints.html#autotoc_md50',1,'']]],
  ['models_24',['Models',['../case_constraints.html#autotoc_md52',1,'💧 Bubble Models'],['../case.html#autotoc_md21',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#autotoc_md47',1,'Bubble Models'],['../case_constraints.html#autotoc_md46',1,'Physics Models']]],
  ['modifying_20src_20common_25',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md141',1,'']]],
  ['module_26',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['module_20not_20found_20on_20hpc_27',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md454',1,'']]],
  ['mom_5fwrt_28',['mom_wrt',['../parameters.html#autotoc_md354',1,'']]],
  ['mpi_29',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['mpi_20correctness_30',['MPI Correctness',['../contributing.html#autotoc_md126',1,'']]],
  ['mpi_20errors_20or_20hangs_31',['MPI errors or hangs',['../troubleshooting.html#autotoc_md460',1,'']]],
  ['mpi_20halo_20exchange_32',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md139',1,'']]],
  ['multi_20component_20inert_20shock_20tube_33',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md224',1,'']]],
  ['multi_20component_20reactive_20shock_20tube_34',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md186',1,'']]]
];
