var searchData=
[
  ['i_20o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_1',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['ib_5fairfoil_2',['ib_airfoil',['../parameters.html#ib_airfoil',1,'']]],
  ['ibm_20bow_20shock_203d_3',['IBM Bow Shock (3D)',['../examples.html#autotoc_md311',1,'']]],
  ['ibm_20cfl_20dt_202d_4',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md231',1,'']]],
  ['ibm_20power9_20cpu_5',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md342',1,'']]],
  ['ibm_20power9_20cpu_20historical_6',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md337',1,'']]],
  ['ibm_20walled_20power_20law_20poiseuille_20channel_7',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md289',1,'']]],
  ['ic_20example_8',['2D Hardcodied IC Example',['../examples.html#autotoc_md313',1,'']]],
  ['ic_20extrusion_9',['IC Extrusion',['../physics_constraints.html#autotoc_md521',1,'']]],
  ['ic_20extrusion_20file_20parameters_10',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md522',1,'']]],
  ['ideal_20gas_20eos_20chemistry_20chemistry_20true_11',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['ideal_20mhd_20mhd_20true_20wilfong26_20sec_204_201_209_12',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md181',1,'']]],
  ['igr_13',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md501',1,'']]],
  ['igr_20reconstruction_14',['IGR Reconstruction',['../equations.html#autotoc_md194',1,'']]],
  ['igr_20true_20wilfong25a_15',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['image_20device_20codegen_20instability_20worked_20around_20in_20the_20build_16',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md384',1,'']]],
  ['images_17',['Base Images',['../docker.html#autotoc_md137',1,'']]],
  ['immersed_20boundary_20force_20history_18',['Immersed-boundary force history',['../case.html#sec-ib-force-history',1,'']]],
  ['immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_19',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['immersed_20boundary_20patch_20types_20',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['immersed_20boundary_20patches_21',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['implementation_22',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md200',1,'']]],
  ['in_20cylindrical_20coordinates_23',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md630',1,'']]],
  ['in_20dimensions_20out_24',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['in_20inactive_20dimensions_25',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['in_20the_20build_26',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md384',1,'']]],
  ['in_20the_20same_20corner_27',['A second trap in the same corner',['../examples.html#autotoc_md300',1,'']]],
  ['inactive_20dimensions_28',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['indexing_29',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['inert_20shock_20tube_30',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md219',1,'']]],
  ['inflow_20ramp_31',['GRCBC Inflow Ramp',['../physics_constraints.html#autotoc_md487',1,'']]],
  ['information_20geometric_20regularization_20igr_20true_20wilfong25a_32',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['infrastructure_33',['Infrastructure',['../architecture.html#autotoc_md10',1,'']]],
  ['initial_20and_20final_20conditions_34',['Density Initial and Final Conditions',['../examples.html#autotoc_md253',1,'']]],
  ['initial_20condition_35',['Initial Condition',['../examples.html#autotoc_md220',1,'Initial Condition'],['../examples.html#autotoc_md223',1,'Initial Condition'],['../examples.html#autotoc_md238',1,'Initial Condition'],['../examples.html#autotoc_md255',1,'Initial Condition'],['../examples.html#autotoc_md296',1,'Initial Condition'],['../examples.html#autotoc_md321',1,'Initial Condition']]],
  ['initial_20condition_36',['Initial condition',['../examples.html#autotoc_md229',1,'']]],
  ['initial_20condition_20and_20result_37',['Initial Condition and Result',['../examples.html#autotoc_md314',1,'']]],
  ['initial_20condition_20constraints_38',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['initial_20state_39',['Initial State',['../examples.html#autotoc_md241',1,'Initial State'],['../examples.html#autotoc_md250',1,'Initial State'],['../examples.html#autotoc_md316',1,'Initial State']]],
  ['initial_20states_20inside_20a_20state_20dependent_20equation_20of_20state_40',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md465',1,'']]],
  ['input_20parameters_41',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['inside_20a_20state_20dependent_20equation_20of_20state_42',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md465',1,'']]],
  ['inside_20fortran_20block_20constructs_20are_20silently_20dropped_43',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md385',1,'']]],
  ['instability_202d_44',['Instability 2D',['../examples.html#autotoc_md240',1,'Kelvin-Helmholtz Instability (2D)'],['../examples.html#autotoc_md309',1,'Rayleigh-Taylor Instability (2D)'],['../examples.html#autotoc_md315',1,'Richtmyer-Meshkov Instability (2D)']]],
  ['instability_203d_45',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md265',1,'']]],
  ['instability_20worked_20around_20in_20the_20build_46',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md384',1,'']]],
  ['install_20via_20homebrew_20macos_47',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md345',1,'']]],
  ['integration_48',['15.3 Time Integration',['../equations.html#autotoc_md201',1,'']]],
  ['interaction_49',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md169',1,'']]],
  ['interactive_20execution_50',['Interactive Execution',['../running.html#autotoc_md532',1,'']]],
  ['interactive_20mode_51',['Interactive mode',['../visualization.html#autotoc_md623',1,'']]],
  ['interactive_20shell_52',['Interactive Shell',['../docker.html#autotoc_md133',1,'']]],
  ['intermediate_20examples_53',['🟡 Intermediate Examples',['../case_constraints.html#autotoc_md44',1,'']]],
  ['is_20required_20to_20read_20silo_20hdf5_20files_54',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md609',1,'']]],
  ['isentropic_20vortex_20problem_202d_55',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md280',1,'']]],
  ['isolating_20issues_56',['Isolating Issues',['../troubleshooting.html#autotoc_md572',1,'']]],
  ['issues_57',['Issues',['../gpuParallelization.html#autotoc_md383',1,'AMD flang (amdflang) Known Issues'],['../troubleshooting.html#autotoc_md572',1,'Isolating Issues'],['../troubleshooting.html#autotoc_md606',1,'Visualization Issues']]],
  ['it_58',['Running it',['../examples.html#autotoc_md299',1,'']]],
  ['iterative_20generalized_20riemann_20igr_59',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md501',1,'']]]
];
