var searchData=
[
  ['nan_20detected_0',['&quot;NaN detected&quot;',['../troubleshooting.html#autotoc_md584',1,'']]],
  ['navigating_20docker_1',['Navigating Docker',['../docker.html#autotoc_md127',1,'']]],
  ['new_2',['new',['../cli-reference.html#new',1,'']]],
  ['new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md346',1,'']]],
  ['new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['new_20physics_5',['Adding New Physics',['../architecture.html#autotoc_md13',1,'']]],
  ['new_20simulation_20parameter_6',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md108',1,'']]],
  ['newtonian_20herschel_20bulkley_20viscosity_7',['Newtonian Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md485',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['no_20binary_20or_20silo_5fhdf5_20directory_20found_8',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md589',1,'']]],
  ['non_20conservative_20term_20implementation_9',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['non_20dimensional_20bubble_20dynamics_10',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['non_20dimensional_20framework_11',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['non_20dimensionalization_12',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['non_20dimensionalization_20of_20input_20parameters_13',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['non_20dimensionalizing_20a_20bubble_20case_14',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['non_20newtonian_20herschel_20bulkley_20viscosity_15',['Non Newtonian Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md485',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['non_20polytropic_20thermal_20model_20polytropic_20false_20preston07_16',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['norms_17',['Density Norms',['../examples.html#autotoc_md257',1,'']]],
  ['not_20detected_18',['GPU not detected',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['not_20find_20a_20fortran_20compiler_19',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md577',1,'']]],
  ['not_20find_20mpi_20',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md576',1,'']]],
  ['not_20found_21',['&quot;Variable &apos;X&apos; not found&quot;',['../troubleshooting.html#autotoc_md590',1,'']]],
  ['not_20found_20on_20hpc_22',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md580',1,'']]],
  ['notes_23',['Notes',['../contributing.html#autotoc_md105',1,'Architecture Notes'],['../running.html#autotoc_md531',1,'Scheduler Notes']]],
  ['notes_20on_20non_20conservative_20term_20implementation_24',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['number_25',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['number_20corrections_20wilfong26_20sec_204_202_204_26',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md212',1,'']]],
  ['numerical_20methods_27',['15. Numerical Methods',['../equations.html#autotoc_md189',1,'']]],
  ['numerical_20schemes_28',['Numerical Schemes',['../physics_constraints.html#autotoc_md487',1,'']]],
  ['numerical_20schlieren_20at_20final_20time_29',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md264',1,'']]],
  ['numerics_30',['Numerics',['../case_constraints.html#compat-numerics',1,'']]],
  ['nvhpc_20compiler_20options_31',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md370',1,'']]],
  ['nvhpc_20general_20options_32',['NVHPC General Options',['../gpuParallelization.html#autotoc_md371',1,'']]],
  ['nvhpc_20openacc_20options_33',['NVHPC OpenACC Options',['../gpuParallelization.html#autotoc_md372',1,'']]],
  ['nvhpc_20openmp_20options_34',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md373',1,'']]],
  ['nvidia_20gpu_20profiling_35',['NVIDIA GPU Profiling',['../troubleshooting.html#autotoc_md571',1,'']]],
  ['nvidia_20gpus_36',['NVIDIA GPUs',['../running.html#autotoc_md523',1,'']]],
  ['nvidia_20uvm_37',['20. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md36',1,'']]],
  ['nvidia_20v100_20gpu_38',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md330',1,'']]],
  ['nvidia_20v100_20gpu_20historical_39',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md327',1,'']]]
];
