var searchData=
[
  ['ramp_0',['GRCBC Inflow Ramp',['../physics_constraints.html#autotoc_md516',1,'']]],
  ['ranks_1',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md609',1,'']]],
  ['ranks_20are_20not_20cubes_2',['Automatic &lt;span class=&quot;tt&quot;&gt;ib_neighborhood_radius&lt;/span&gt; when ranks are not cubes',['../examples.html#autotoc_md338',1,'']]],
  ['rayleigh_20plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_3',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[29]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['rayleigh_20taylor_20instability_202d_4',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md329',1,'']]],
  ['rayleigh_20taylor_20instability_203d_5',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md280',1,'']]],
  ['rayleigh17_20plesset49_6',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[29]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['rburn_7',['rburn',['../parameters.html#rburn',1,'']]],
  ['re_20run_8',['Probe files across a re-run',['../examples.html#autotoc_md268',1,'']]],
  ['reacting_20mixing_20layer_20h2_20n2_20air_20mc_201_205_9',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md229',1,'']]],
  ['reactive_20burn_10',['Condensed-Phase Reactive Burn',['../physics_constraints.html#autotoc_md549',1,'']]],
  ['reactive_20shock_20tube_11',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md224',1,'']]],
  ['reactor_12',['Perfectly Stirred Reactor',['../examples.html#autotoc_md285',1,'']]],
  ['read_20silo_20hdf5_20files_13',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md639',1,'']]],
  ['rebuild_14',['Clean Rebuild',['../troubleshooting.html#autotoc_md603',1,'']]],
  ['recommended_15',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md355',1,'']]],
  ['reconstruction_16',['Reconstruction',['../equations.html#autotoc_md193',1,'15.1 Spatial Reconstruction'],['../equations.html#autotoc_md196',1,'IGR Reconstruction'],['../physics_constraints.html#autotoc_md536',1,'MUSCL Reconstruction'],['../physics_constraints.html#autotoc_md535',1,'WENO Reconstruction']]],
  ['reference_17',['Reference',['../case_constraints.html#quick-parameter-reference',1,'📖 Quick Parameter Reference'],['../cli-reference.html',1,'CLI Reference'],['../cli-reference.html#autotoc_md47',1,'CLI Reference'],['../parameters.html#autotoc_md489',1,'CLI Reference'],['../equations.html#autotoc_md141',1,'MFC: Comprehensive Equations Reference'],['../physics_constraints.html#autotoc_md490',1,'Physics Constraints Reference'],['../cli-reference.html#autotoc_md49',1,'Quick Reference'],['../troubleshooting.html#autotoc_md588',1,'Quick Reference'],['../index.html#autotoc_md554',1,'Reference']]],
  ['reference_18',['Complete option reference',['../visualization.html#autotoc_md657',1,'']]],
  ['reference_20check_20is_20not_20available_20here_19',['Why a zero-reference check is not available here',['../examples.html#autotoc_md242',1,'']]],
  ['reference_20scales_20',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['references_21',['References',['../examples.html#autotoc_md259',1,'References'],['../examples.html#autotoc_md279',1,'References'],['../examples.html#autotoc_md292',1,'References'],['../examples.html#autotoc_md308',1,'References'],['../examples.html#autotoc_md314',1,'References'],['../examples.html#autotoc_md328',1,'References']]],
  ['regenerating_20golden_20files_22',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md615',1,'']]],
  ['regime_20and_20parameters_23',['Regime and parameters',['../examples.html#autotoc_md255',1,'Regime and parameters'],['../examples.html#autotoc_md275',1,'Regime and parameters'],['../examples.html#autotoc_md288',1,'Regime and parameters'],['../examples.html#autotoc_md304',1,'Regime and parameters'],['../examples.html#autotoc_md325',1,'Regime and parameters']]],
  ['regions_20inside_20fortran_20block_20constructs_20are_20silently_20dropped_24',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['regularization_20igr_20true_20wilfong25a_25',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['related_26',['Related',['../examples.html#autotoc_md243',1,'']]],
  ['relativistic_20mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_27',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md184',1,'']]],
  ['relativity_20true_20wilfong26_20sec_204_201_2010_28',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md184',1,'']]],
  ['relax_20true_20wilfong26_20sec_204_201_203_29',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md174',1,'']]],
  ['relax_5fmodel_205_20saurel08_30',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[44]&lt;/a&gt;)',['../equations.html#autotoc_md175',1,'']]],
  ['relax_5fmodel_206_20zein10_31',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[61]&lt;/a&gt;)',['../equations.html#autotoc_md176',1,'']]],
  ['relaxation_20relax_5fmodel_205_20saurel08_32',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[44]&lt;/a&gt;)',['../equations.html#autotoc_md175',1,'']]],
  ['relaxation_20relax_5fmodel_206_20zein10_33',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[61]&lt;/a&gt;)',['../equations.html#autotoc_md176',1,'']]],
  ['remote_20visualization_20on_20pace_20phoenix_34',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md663',1,'']]],
  ['rendering_35',['Tiled 1D rendering',['../visualization.html#autotoc_md652',1,'']]],
  ['rendering_20options_36',['Rendering options',['../visualization.html#autotoc_md649',1,'']]],
  ['reproducing_37',['Reproducing',['../examples.html#autotoc_md269',1,'']]],
  ['request_38',['Submitting a Pull Request',['../contributing.html#autotoc_md124',1,'']]],
  ['required_20to_20read_20silo_20hdf5_20files_39',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md639',1,'']]],
  ['restarting_20cases_40',['Restarting Cases',['../running.html#autotoc_md581',1,'']]],
  ['result_41',['Result',['../examples.html#autotoc_md334',1,'Initial Condition and Result'],['../examples.html#autotoc_md238',1,'Result'],['../examples.html#autotoc_md250',1,'Result'],['../examples.html#autotoc_md267',1,'Result'],['../examples.html#autotoc_md317',1,'Result'],['../examples.html#autotoc_md347',1,'Result']]],
  ['result_42',['result',['../examples.html#autotoc_md258',1,'Validation result'],['../examples.html#autotoc_md278',1,'Validation result'],['../examples.html#autotoc_md291',1,'Validation result'],['../examples.html#autotoc_md307',1,'Validation result']]],
  ['results_43',['Results',['../expectedPerformance.html#autotoc_md361',1,'Benchmark Results'],['../examples.html#autotoc_md223',1,'Results'],['../examples.html#autotoc_md226',1,'Results'],['../getting-started.html#autotoc_md381',1,'Visualizing Results']]],
  ['results_44',['results',['../examples.html#autotoc_md236',1,'Observed results'],['../examples.html#autotoc_md302',1,'Observed results'],['../examples.html#autotoc_md313',1,'Validation results']]],
  ['review_20and_20merge_45',['Code Review and Merge',['../contributing.html#autotoc_md125',1,'']]],
  ['rho_20consistency_46',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md501',1,'']]],
  ['richtmyer_20meshkov_20instability_202d_47',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md335',1,'']]],
  ['riemann_20igr_48',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md530',1,'']]],
  ['riemann_20solvers_49',['Riemann Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md197',1,'15.2 Riemann Solvers']]],
  ['riemann_20test_202d_50',['2D Riemann Test (2D)',['../examples.html#autotoc_md263',1,'']]],
  ['riemann_5fsolver_201_20harten83_51',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[21]&lt;/a&gt;)',['../equations.html#autotoc_md198',1,'']]],
  ['riemann_5fsolver_202_20toro94_52',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md199',1,'']]],
  ['riemann_5fsolver_203_53',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md200',1,'']]],
  ['riemann_5fsolver_204_20mhd_20or_20hypoelasticity_54',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md201',1,'']]],
  ['rodriguez19_20wilfong26_20sec_204_201_206_55',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md172',1,'']]],
  ['rules_56',['Hard Rules',['../contributing.html#autotoc_md93',1,'']]],
  ['run_57',['run',['../examples.html#autotoc_md257',1,'How to run'],['../examples.html#autotoc_md277',1,'How to run'],['../examples.html#autotoc_md290',1,'How to run'],['../examples.html#autotoc_md306',1,'How to run'],['../examples.html#autotoc_md312',1,'How to run'],['../examples.html#autotoc_md327',1,'How to run'],['../examples.html#autotoc_md268',1,'Probe files across a re-run'],['../cli-reference.html#run',1,'run']]],
  ['run_20fails_58',['Run Fails?',['../troubleshooting.html#autotoc_md595',1,'']]],
  ['runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_59',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md204',1,'']]],
  ['running_60',['Running',['../running.html',1,'Running'],['../examples.html#autotoc_md232',1,'Running'],['../examples.html#autotoc_md235',1,'Running'],['../examples.html#autotoc_md301',1,'Running'],['../examples.html#autotoc_md350',1,'Running'],['../running.html#autotoc_md559',1,'Running']]],
  ['running_20an_20example_20case_61',['Running an Example Case',['../getting-started.html#autotoc_md379',1,'']]],
  ['running_20containers_62',['Details on Running Containers',['../docker.html#autotoc_md130',1,'']]],
  ['running_20it_63',['Running it',['../examples.html#autotoc_md319',1,'Running it'],['../examples.html#autotoc_md340',1,'Running it']]],
  ['running_20on_20gpus_64',['Running on GPUs',['../running.html#autotoc_md564',1,'Running on GPUs'],['../running.html#autotoc_md566',1,'Running on GPUs']]],
  ['running_20pace_20paraview_20server_65',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md666',1,'']]],
  ['running_20specific_20tests_66',['Running Specific Tests',['../troubleshooting.html#autotoc_md612',1,'']]],
  ['running_20the_20sweep_67',['Running the sweep',['../examples.html#autotoc_md240',1,'']]],
  ['running_20the_20test_20suite_68',['Running the Test Suite',['../getting-started.html#autotoc_md378',1,'']]],
  ['running_20with_20fewer_20ranks_69',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md609',1,'']]],
  ['runs_70',['Runs',['../running.html#autotoc_md583',1,'Example Runs'],['../troubleshooting.html#autotoc_md607',1,'Verbose Runs']]],
  ['runs_20first_20blocks_20all_20other_20jobs_71',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md120',1,'']]],
  ['runtime_72',['1. Runtime',['../case.html#sec-runtime',1,'']]],
  ['runtime_20debugging_73',['Runtime Debugging',['../troubleshooting.html#autotoc_md605',1,'']]],
  ['runtime_20errors_74',['Common Runtime Errors',['../troubleshooting.html#autotoc_md630',1,'']]]
];
