var searchData=
[
  ['mach_20number_0',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['mach_20number_20corrections_20wilfong26_20sec_204_202_204_1',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md212',1,'']]],
  ['macos_2',['macOS',['../getting-started.html#autotoc_md336',1,'Install via Homebrew (macOS)'],['../running.html#autotoc_md512',1,'Using the Homebrew package (macOS)']]],
  ['macro_20api_20documentation_3',['Macro API Documentation',['../gpuParallelization.html#autotoc_md350',1,'']]],
  ['macros_4',['Macros',['../gpuParallelization.html#autotoc_md354',1,'Computation Macros'],['../gpuParallelization.html#autotoc_md356',1,'Data Control Macros'],['../gpuParallelization.html#autotoc_md360',1,'Miscellaneous Macros'],['../gpuParallelization.html#autotoc_md358',1,'Synchronization Macros']]],
  ['maeda18_5',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[31]&lt;/a&gt;)',['../equations.html#autotoc_md167',1,'']]],
  ['magnetohydrodynamics_6',['11. Magnetohydrodynamics',['../equations.html#autotoc_md179',1,'']]],
  ['magnetohydrodynamics_20mhd_7',['Magnetohydrodynamics MHD',['../case.html#autotoc_md31',1,'14. Magnetohydrodynamics (MHD)'],['../physics_constraints.html#autotoc_md479',1,'Magnetohydrodynamics (MHD)']]],
  ['manage_20gpu_20arrays_8',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md110',1,'']]],
  ['map_9',['Module Map',['../architecture.html#autotoc_md5',1,'']]],
  ['material_20s_10',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['material_20values_11',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['matrix_12',['Build and Test Matrix',['../contributing.html#autotoc_md121',1,'']]],
  ['maximum_20performance_13',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md316',1,'']]],
  ['meanings_14',['Data Type Meanings',['../gpuParallelization.html#autotoc_md351',1,'']]],
  ['memory_20and_20allocation_15',['Memory and Allocation',['../contributing.html#autotoc_md100',1,'']]],
  ['menikoff89_20lemetayer04_20wilfong26_20sec_202_202_16',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md152',1,'']]],
  ['merge_17',['Code Review and Merge',['../contributing.html#autotoc_md125',1,'']]],
  ['merit_3a_20grind_20time_20performance_18',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md324',1,'']]],
  ['meshkov_20instability_202d_19',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md300',1,'']]],
  ['messages_20',['Commit Messages',['../contributing.html#autotoc_md93',1,'']]],
  ['method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_21',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['method_20of_20classes_20commander89_20ando11_22',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['methods_23',['15. Numerical Methods',['../equations.html#autotoc_md189',1,'']]],
  ['mfc_24',['MFC',['../getting-started.html#autotoc_md338',1,'Building MFC'],['../contributing.html#autotoc_md84',1,'Contributing to MFC'],['../getting-started.html#autotoc_md335',1,'Fetching MFC']]],
  ['mfc_20documentation_25',['MFC Documentation',['../index.html',1,'']]],
  ['mfc_20sh_20viz_26',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md597',1,'']]],
  ['mfc_3a_20comprehensive_20equations_20reference_27',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md141',1,'']]],
  ['mhd_28',['MHD',['../case.html#autotoc_md31',1,'14. Magnetohydrodynamics (MHD)'],['../physics_constraints.html#autotoc_md479',1,'Magnetohydrodynamics (MHD)']]],
  ['mhd_20mhd_20true_20wilfong26_20sec_204_201_209_29',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['mhd_20or_20hypoelasticity_30',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md198',1,'']]],
  ['mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_31',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md181',1,'']]],
  ['mhd_20true_20wilfong26_20sec_204_201_209_32',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['miksis_20bubble_5fmodel_202_20keller80_33',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md163',1,'']]],
  ['miscellaneous_20macros_34',['Miscellaneous Macros',['../gpuParallelization.html#autotoc_md360',1,'']]],
  ['mittal05_20wilfong26_20sec_204_201_201_35',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['mixing_20layer_203d_36',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md278',1,'']]],
  ['mixture_20constraints_37',['Mixture Constraints',['../physics_constraints.html#autotoc_md455',1,'']]],
  ['mode_38',['Interactive mode',['../visualization.html#autotoc_md605',1,'']]],
  ['model_39',['Model',['../case.html#sec-phase-change',1,'11. Phase Change Model'],['../case.html#autotoc_md28',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md29',1,'9.2 Volume-Averaged Bubble Model'],['../physics_constraints.html#autotoc_md474',1,'Euler-Euler Bubble Model'],['../physics_constraints.html#autotoc_md476',1,'Euler-Lagrange Bubble Model']]],
  ['model_20consistency_40',['Physics and Model Consistency',['../contributing.html#autotoc_md102',1,'']]],
  ['model_20equation_20selection_41',['Model Equation Selection',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['model_20equations_42',['Model Equations',['../case_constraints.html#model-equations',1,'🔢 Model Equations'],['../physics_constraints.html#autotoc_md467',1,'Model Equations']]],
  ['model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_43',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]],
  ['model_20model_5feqns_202_44',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['model_20model_5feqns_203_45',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md148',1,'']]],
  ['model_20polytropic_20false_20preston07_46',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['model_20variants_47',['2.3 Other Model Variants',['../equations.html#autotoc_md149',1,'']]],
  ['model_5feqns_202_48',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['model_5feqns_203_49',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md148',1,'']]],
  ['models_50',['Models',['../case_constraints.html#bubble-models',1,'💧 Bubble Models'],['../case.html#sec-bubble-models',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#compat-bubble-models',1,'Bubble Models'],['../architecture.html#autotoc_md7',1,'Physics Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['modifying_20src_20common_51',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md116',1,'']]],
  ['module_52',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['module_20map_53',['Module Map',['../architecture.html#autotoc_md5',1,'']]],
  ['module_20not_20found_20on_20hpc_54',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md580',1,'']]],
  ['mom_5fwrt_55',['mom_wrt',['../parameters.html#mom_wrt',1,'']]],
  ['moment_20transport_20qbmm_20true_20bryngelson20_56',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['mpi_57',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md576',1,'']]],
  ['mpi_20correctness_58',['MPI Correctness',['../contributing.html#autotoc_md101',1,'']]],
  ['mpi_20errors_20or_20hangs_59',['MPI errors or hangs',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['mpi_20halo_20exchange_60',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['mpi_20parallelization_61',['MPI Parallelization',['../architecture.html#autotoc_md12',1,'']]],
  ['multi_20component_20inert_20shock_20tube_62',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md240',1,'']]],
  ['multi_20component_20reactive_20shock_20tube_63',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md224',1,'']]],
  ['muscl_20muscl_5forder_202_64',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md192',1,'']]],
  ['muscl_20reconstruction_65',['MUSCL Reconstruction',['../physics_constraints.html#autotoc_md489',1,'']]],
  ['muscl_5forder_202_66',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md192',1,'']]]
];
