var searchData=
[
  ['case_0',['Case',['../getting-started.html#autotoc_md259',1,'Creating a New Case'],['../contributing.html#autotoc_md136',1,'How to Add a Test Case'],['../getting-started.html#autotoc_md256',1,'Running an Example Case']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../case_constraints.html#autotoc_md40',1,'']]],
  ['case_20files_3',['Case Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md1',1,'Case Files']]],
  ['case_20optimization_4',['When to use case optimization',['../expectedPerformance.html#autotoc_md233',1,'']]],
  ['case_20optimization_20recommended_5',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md232',1,'']]],
  ['case_20parameter_20constraint_20violations_6',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md457',1,'']]],
  ['case_20parameters_20reference_7',['Case Parameters Reference',['../parameters.html',1,'Case Parameters Reference'],['../parameters.html#autotoc_md287',1,'Case Parameters Reference']]],
  ['case_20validation_8',['Case Validation',['../troubleshooting.html#autotoc_md432',1,'']]],
  ['cases_9',['Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md166',1,'Example Cases'],['../running.html#autotoc_md407',1,'Restarting Cases']]],
  ['cavity_20problem_202d_10',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md194',1,'']]],
  ['centerline_20velocities_11',['Centerline Velocities',['../examples.html#autotoc_md196',1,'']]],
  ['cfl_20dt_202d_12',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md176',1,'']]],
  ['change_20model_13',['11. Phase Change Model',['../case.html#autotoc_md25',1,'']]],
  ['characteristic_20boundary_20conditions_14',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md34',1,'']]],
  ['checklist_15',['Performance Checklist',['../expectedPerformance.html#autotoc_md236',1,'']]],
  ['chem_5fparams_16',['chem_params',['../parameters.html#autotoc_md349',1,'']]],
  ['chem_5fwrt_5fy_17',['chem_wrt_Y',['../parameters.html#autotoc_md306',1,'']]],
  ['chemistry_18',['17. Chemistry',['../case.html#autotoc_md31',1,'']]],
  ['ci_20commands_19',['CI Commands',['../cli-reference.html#autotoc_md95',1,'']]],
  ['ci_20failures_20',['Common CI Failures',['../contributing.html#autotoc_md147',1,'']]],
  ['ci_20pipeline_21',['CI Pipeline',['../contributing.html#autotoc_md144',1,'']]],
  ['clean_22',['clean',['../cli-reference.html#autotoc_md65',1,'']]],
  ['clean_20rebuild_23',['Clean Rebuild',['../troubleshooting.html#autotoc_md429',1,'']]],
  ['cli_24',['Docker CLI',['../docker.html#autotoc_md154',1,'']]],
  ['clusters_20via_20apptainer_20singularity_25',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md157',1,'']]],
  ['cmake_20could_20not_20find_20a_20fortran_20compiler_26',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['cmake_20could_20not_20find_20mpi_27',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['code_20coverage_28',['Code Coverage',['../troubleshooting.html#autotoc_md427',1,'']]],
  ['code_20review_20and_20merge_29',['Code Review and Merge',['../contributing.html#autotoc_md150',1,'']]],
  ['coded_20patches_30',['Hard Coded Patches',['../case.html#autotoc_md10',1,'']]],
  ['coding_20standards_31',['Coding Standards',['../contributing.html#autotoc_md119',1,'']]],
  ['command_20line_20arguments_32',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['command_20line_20reference_33',['Command Line Reference',['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md55',1,'Command Line Reference'],['../parameters.html#autotoc_md377',1,'Command Line Reference']]],
  ['commands_34',['Commands',['../cli-reference.html#autotoc_md95',1,'CI Commands'],['../cli-reference.html#autotoc_md58',1,'Commands'],['../cli-reference.html#autotoc_md84',1,'Development Commands'],['../cli-reference.html#autotoc_md100',1,'Other Commands'],['../troubleshooting.html#autotoc_md417',1,'Useful Commands'],['../cli-reference.html#autotoc_md69',1,'Utility Commands']]],
  ['commit_20messages_35',['Commit Messages',['../contributing.html#autotoc_md118',1,'']]],
  ['common_36',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md141',1,'']]],
  ['common_20build_20errors_37',['Common Build Errors',['../troubleshooting.html#autotoc_md449',1,'']]],
  ['common_20ci_20failures_38',['Common CI Failures',['../contributing.html#autotoc_md147',1,'']]],
  ['common_20configuration_20patterns_39',['🚀 Common Configuration Patterns',['../case_constraints.html#autotoc_md44',1,'']]],
  ['common_20options_40',['Common Options',['../cli-reference.html#autotoc_md105',1,'']]],
  ['common_20pitfalls_41',['Common Pitfalls',['../contributing.html#autotoc_md122',1,'']]],
  ['common_20runtime_20errors_42',['Common Runtime Errors',['../troubleshooting.html#autotoc_md456',1,'']]],
  ['compare_43',['packer compare',['../cli-reference.html#autotoc_md76',1,'']]],
  ['compatibility_44',['Compatibility',['../case_constraints.html#autotoc_md45',1,'📊 Feature Compatibility'],['../case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['compiler_45',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['compiler_20agnostic_20tools_46',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md276',1,'']]],
  ['compiler_20documentation_47',['Compiler Documentation',['../gpuParallelization.html#autotoc_md285',1,'']]],
  ['compiler_20options_48',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md281',1,'']]],
  ['compiler_20portability_49',['Compiler Portability',['../contributing.html#autotoc_md129',1,'']]],
  ['compiler_20tools_50',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md278',1,'']]],
  ['compilers_51',['Supported Compilers',['../running.html#autotoc_md393',1,'']]],
  ['completion_52',['Shell Completion',['../getting-started.html#autotoc_md260',1,'']]],
  ['completion_53',['completion',['../cli-reference.html#autotoc_md78',1,'']]],
  ['component_20inert_20shock_20tube_54',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md224',1,'']]],
  ['component_20reactive_20shock_20tube_55',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md186',1,'']]],
  ['computation_20macros_56',['Computation Macros',['../gpuParallelization.html#autotoc_md267',1,'']]],
  ['computational_20domain_57',['2. Computational Domain',['../case.html#autotoc_md7',1,'']]],
  ['computer_20templates_58',['Computer Templates',['../running.html#autotoc_md404',1,'']]],
  ['condition_59',['Condition',['../examples.html#autotoc_md185',1,'Final Condition'],['../examples.html#autotoc_md195',1,'Final Condition'],['../examples.html#autotoc_md217',1,'Final Condition'],['../examples.html#autotoc_md228',1,'Final Condition'],['../examples.html#autotoc_md168',1,'Initial Condition'],['../examples.html#autotoc_md179',1,'Initial Condition'],['../examples.html#autotoc_md187',1,'Initial Condition'],['../examples.html#autotoc_md207',1,'Initial Condition'],['../examples.html#autotoc_md214',1,'Initial Condition'],['../examples.html#autotoc_md225',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_60',['Condition and Linear Theory',['../examples.html#autotoc_md175',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md219',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_61',['Initial Condition and Result',['../examples.html#autotoc_md210',1,'']]],
  ['condition_20density_62',['Condition Density',['../examples.html#autotoc_md190',1,'Final Condition (Density)'],['../examples.html#autotoc_md212',1,'Final Condition (Density)']]],
  ['condition_20patches_63',['Boundary Condition Patches',['../case.html#autotoc_md17',1,'']]],
  ['conditions_64',['Density Initial and Final Conditions',['../examples.html#autotoc_md192',1,'']]],
  ['conditions_65',['conditions',['../case.html#autotoc_md33',1,'Boundary conditions'],['../case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20flags_66',['Build Configuration Flags',['../cli-reference.html#autotoc_md107',1,'']]],
  ['configuration_20patterns_67',['🚀 Common Configuration Patterns',['../case_constraints.html#autotoc_md44',1,'']]],
  ['conservative_20variables_20ordering_68',['Conservative Variables Ordering',['../case.html#autotoc_md37',1,'']]],
  ['consistency_69',['Physics and Model Consistency',['../contributing.html#autotoc_md127',1,'']]],
  ['constant_20time_20stepping_70',['Constant Time-Stepping',['../case.html#autotoc_md18',1,'']]],
  ['constraint_20violations_71',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md457',1,'']]],
  ['containers_72',['Containers',['../docker.html',1,'Containers'],['../docker.html#autotoc_md151',1,'Containers'],['../docker.html#autotoc_md155',1,'Details on Running Containers'],['../getting-started.html#autotoc_md254',1,'Using Containers']]],
  ['contributing_73',['Contributing',['../contributing.html',1,'']]],
  ['contributing_20to_20mfc_74',['Contributing to MFC',['../contributing.html#autotoc_md110',1,'']]],
  ['control_20macros_75',['Data Control Macros',['../gpuParallelization.html#autotoc_md269',1,'']]],
  ['coordinates_76',['16. Cylindrical Coordinates',['../case.html#autotoc_md30',1,'']]],
  ['coordinates_77',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md465',1,'']]],
  ['correctness_78',['Correctness',['../contributing.html#autotoc_md126',1,'MPI Correctness'],['../troubleshooting.html#autotoc_md447',1,'Performance vs Correctness']]],
  ['could_20not_20find_20a_20fortran_20compiler_79',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['could_20not_20find_20mpi_80',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['count_81',['count',['../cli-reference.html#autotoc_md91',1,'']]],
  ['count_5fdiff_82',['count_diff',['../cli-reference.html#autotoc_md93',1,'']]],
  ['coverage_83',['Code Coverage',['../troubleshooting.html#autotoc_md427',1,'']]],
  ['cpu_84',['CPU',['../expectedPerformance.html#autotoc_md243',1,'IBM Power9 CPU'],['../expectedPerformance.html#autotoc_md248',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_85',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md278',1,'']]],
  ['cray_20general_20options_86',['Cray General Options',['../gpuParallelization.html#autotoc_md279',1,'']]],
  ['cray_20openacc_20options_87',['Cray OpenACC Options',['../gpuParallelization.html#autotoc_md280',1,'']]],
  ['create_20a_20new_20fortran_20module_88',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['creating_20a_20new_20case_89',['Creating a New Case',['../getting-started.html#autotoc_md259',1,'']]],
  ['creating_20tests_90',['Creating Tests',['../testing.html#autotoc_md411',1,'']]],
  ['creator_20guide_91',['Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['customizing_20the_20script_92',['Step 2: Customizing the script',['../visualization.html#autotoc_md470',1,'']]],
  ['cylindrical_20coordinates_93',['16. Cylindrical Coordinates',['../case.html#autotoc_md30',1,'']]],
  ['cylindrical_20coordinates_94',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md465',1,'']]]
];
