var searchData=
[
  ['nan_20detected_0',['&quot;NaN detected&quot;',['../troubleshooting.html#autotoc_md454',1,'']]],
  ['navigating_20docker_1',['Navigating Docker',['../docker.html#autotoc_md107',1,'']]],
  ['new_2',['new',['../cli-reference.html#new',1,'']]],
  ['new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md288',1,'']]],
  ['new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['new_20simulation_20parameter_5',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['non_20polytropic_20thermal_20model_20polytropic_20false_20preston07_6',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['norms_7',['Density Norms',['../examples.html#autotoc_md239',1,'']]],
  ['not_20detected_8',['GPU not detected',['../troubleshooting.html#autotoc_md455',1,'']]],
  ['not_20find_20a_20fortran_20compiler_9',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md447',1,'']]],
  ['not_20find_20mpi_10',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md446',1,'']]],
  ['not_20found_20on_20hpc_11',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['notes_12',['Notes',['../contributing.html#autotoc_md85',1,'Architecture Notes'],['../running.html#autotoc_md401',1,'Scheduler Notes']]],
  ['number_13',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['number_20corrections_20wilfong26_20sec_204_202_204_14',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md192',1,'']]],
  ['numerical_20methods_15',['15. Numerical Methods',['../equations.html#autotoc_md170',1,'']]],
  ['numerical_20schlieren_20at_20final_20time_16',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md198',1,'']]],
  ['numerics_17',['Numerics',['../case_constraints.html#compat-numerics',1,'']]],
  ['nvhpc_20compiler_20options_18',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md310',1,'']]],
  ['nvhpc_20general_20options_19',['NVHPC General Options',['../gpuParallelization.html#autotoc_md311',1,'']]],
  ['nvhpc_20openacc_20options_20',['NVHPC OpenACC Options',['../gpuParallelization.html#autotoc_md312',1,'']]],
  ['nvhpc_20openmp_20options_21',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md313',1,'']]],
  ['nvidia_20gpu_20profiling_22',['NVIDIA GPU Profiling',['../troubleshooting.html#autotoc_md441',1,'']]],
  ['nvidia_20gpus_23',['NVIDIA GPUs',['../running.html#autotoc_md393',1,'']]],
  ['nvidia_20v100_20gpu_24',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md271',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md274',1,'NVIDIA V100 GPU']]]
];
