var searchData=
[
  ['a_20bubble_20case_0',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['a_20fortran_20compiler_1',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md588',1,'']]],
  ['a_20gpu_20parallel_20loop_2',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md107',1,'']]],
  ['a_20new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md350',1,'']]],
  ['a_20new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md111',1,'']]],
  ['a_20new_20simulation_20parameter_5',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md106',1,'']]],
  ['a_20post_20processing_20output_20variable_6',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md114',1,'']]],
  ['a_20pull_20request_7',['Submitting a Pull Request',['../contributing.html#autotoc_md123',1,'']]],
  ['a_20state_20dependent_20equation_20of_20state_8',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['a_20test_20case_9',['How to Add a Test Case',['../contributing.html#autotoc_md110',1,'']]],
  ['about_10',['About',['../index.html#autotoc_md521',1,'']]],
  ['accepting_20command_20line_20arguments_11',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['achieving_20maximum_20performance_12',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md320',1,'']]],
  ['acoustic_13',['acoustic',['../parameters.html#acoustic',1,'']]],
  ['acoustic_20source_14',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['acoustic_20sources_15',['Acoustic Sources',['../physics_constraints.html#autotoc_md504',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md505',1,'Acoustic Sources']]],
  ['acoustic_20sources_20acoustic_5fsource_20true_16',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['acoustic_20supports_17',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['acoustic_5fsource_20true_18',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['adap_5fdt_20true_19',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['adaptive_20time_20stepping_20',['Adaptive Time-Stepping',['../case.html#autotoc_md27',1,'']]],
  ['adaptive_20time_20stepping_20adap_5fdt_20true_21',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['add_20a_20new_20simulation_20parameter_22',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md106',1,'']]],
  ['add_20a_20post_20processing_20output_20variable_23',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md114',1,'']]],
  ['add_20a_20test_20case_24',['How to Add a Test Case',['../contributing.html#autotoc_md110',1,'']]],
  ['add_20an_20equation_20of_20state_25',['How to Add an Equation of State',['../contributing.html#autotoc_md109',1,'']]],
  ['adding_20new_20physics_26',['Adding New Physics',['../architecture.html#autotoc_md13',1,'']]],
  ['advanced_20examples_27',['🔴 Advanced Examples',['../case_constraints.html#autotoc_md45',1,'']]],
  ['advanced_20topics_28',['Advanced Topics',['../index.html#autotoc_md519',1,'']]],
  ['agnostic_20tools_29',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md369',1,'']]],
  ['air_20mc_201_205_30',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md226',1,'']]],
  ['algorithm_31',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['all_20other_20jobs_32',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md119',1,'']]],
  ['allocate_20and_20manage_20gpu_20arrays_33',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md108',1,'']]],
  ['allocation_34',['Memory and Allocation',['../contributing.html#autotoc_md98',1,'']]],
  ['alpha_20rho_20consistency_35',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md466',1,'']]],
  ['alpha_5frho_5fe_5fwrt_36',['alpha_rho_e_wrt',['../parameters.html#alpha_rho_e_wrt',1,'']]],
  ['alpha_5frho_5fwrt_37',['alpha_rho_wrt',['../parameters.html#alpha_rho_wrt',1,'']]],
  ['alpha_5fwrt_38',['alpha_wrt',['../parameters.html#alpha_wrt',1,'']]],
  ['alternative_20sound_20speed_39',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md493',1,'']]],
  ['amd_20flang_20amdflang_20known_20issues_40',['AMD flang (amdflang) Known Issues',['../gpuParallelization.html#autotoc_md378',1,'']]],
  ['amd_20gpu_20profiling_41',['AMD GPU Profiling',['../troubleshooting.html#autotoc_md583',1,'']]],
  ['amd_20gpus_42',['AMD GPUs',['../running.html#autotoc_md535',1,'']]],
  ['amdflang_20known_20issues_43',['AMD flang (amdflang) Known Issues',['../gpuParallelization.html#autotoc_md378',1,'']]],
  ['an_20equation_20of_20state_44',['How to Add an Equation of State',['../contributing.html#autotoc_md109',1,'']]],
  ['an_20example_20case_45',['Running an Example Case',['../getting-started.html#autotoc_md345',1,'']]],
  ['analytic_20solution_46',['Analytic solution',['../examples.html#autotoc_md290',1,'']]],
  ['analytic_20solution_47',['analytic solution',['../examples.html#autotoc_md244',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md260',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md273',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md284',1,'Governing physics and analytic solution']]],
  ['analytical_20definition_20of_20primitive_20variables_48',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['and_20allocation_49',['Memory and Allocation',['../contributing.html#autotoc_md98',1,'']]],
  ['and_20analytic_20solution_50',['and analytic solution',['../examples.html#autotoc_md244',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md260',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md273',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md284',1,'Governing physics and analytic solution']]],
  ['and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_51',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['and_20dimensional_20consistency_52',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md474',1,'']]],
  ['and_20dimensions_53',['Units and Dimensions',['../getting-started.html#autotoc_md346',1,'']]],
  ['and_20final_20conditions_54',['Density Initial and Final Conditions',['../examples.html#autotoc_md252',1,'']]],
  ['and_20geometry_55',['Domain and Geometry',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['and_20gpu_56',['Fypp and GPU',['../contributing.html#autotoc_md104',1,'']]],
  ['and_20indexing_57',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['and_20linear_20theory_58',['and Linear Theory',['../examples.html#autotoc_md265',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md305',1,'Final Condition and Linear Theory']]],
  ['and_20manage_20gpu_20arrays_59',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md108',1,'']]],
  ['and_20merge_60',['Code Review and Merge',['../contributing.html#autotoc_md124',1,'']]],
  ['and_20model_20consistency_61',['Physics and Model Consistency',['../contributing.html#autotoc_md100',1,'']]],
  ['and_20non_20dimensionalization_62',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['and_20parameters_63',['and parameters',['../examples.html#autotoc_md289',1,'Geometry and parameters'],['../examples.html#autotoc_md243',1,'Regime and parameters'],['../examples.html#autotoc_md259',1,'Regime and parameters'],['../examples.html#autotoc_md272',1,'Regime and parameters'],['../examples.html#autotoc_md283',1,'Regime and parameters'],['../examples.html#autotoc_md300',1,'Regime and parameters']]],
  ['and_20performance_20test_64',['Scaling and Performance test',['../examples.html#autotoc_md232',1,'']]],
  ['and_20result_65',['Initial Condition and Result',['../examples.html#autotoc_md309',1,'']]],
  ['and_20startup_66',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['and_20test_20matrix_67',['Build and Test Matrix',['../contributing.html#autotoc_md120',1,'']]],
  ['and_20tips_20for_20gpus_68',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md368',1,'']]],
  ['and_20type_20safety_69',['Precision and Type Safety',['../contributing.html#autotoc_md97',1,'']]],
  ['ando11_70',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['api_20documentation_71',['Macro API Documentation',['../gpuParallelization.html#autotoc_md354',1,'']]],
  ['apptainer_20singularity_72',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md131',1,'']]],
  ['architecture_73',['Code Architecture',['../architecture.html',1,'']]],
  ['architecture_20notes_74',['Architecture Notes',['../contributing.html#autotoc_md103',1,'']]],
  ['architecture_20overview_75',['Architecture Overview',['../contributing.html#autotoc_md84',1,'']]],
  ['architecture_20support_76',['Architecture Support',['../docker.html#autotoc_md139',1,'']]],
  ['are_20silently_20dropped_77',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md380',1,'']]],
  ['arguments_78',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['around_20in_20the_20build_79',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md379',1,'']]],
  ['array_20bounds_20and_20indexing_80',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['arrays_81',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md108',1,'']]],
  ['artifacts_82',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md603',1,'']]],
  ['artificial_20mach_20number_83',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['at_20each_20stage_84',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['at_20final_20time_85',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md225',1,'']]],
  ['at_20transitional_20state_86',['Liutex visualization at transitional state',['../examples.html#autotoc_md278',1,'']]],
  ['authors_87',['Authors',['../authors.html',1,'Authors'],['../authors.html#autotoc_md14',1,'Authors']]],
  ['available_20data_88',['Exploring available data',['../visualization.html#autotoc_md610',1,'']]],
  ['averaged_20bubble_20model_89',['Averaged Bubble Model',['../case.html#autotoc_md28',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md29',1,'9.2 Volume-Averaged Bubble Model']]]
];
