var searchData=
[
  ['pace_20paraview_20server_0',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['pace_20phoenix_1',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md530',1,'']]],
  ['pack_2',['packer pack',['../cli-reference.html#autotoc_md55',1,'']]],
  ['package_20macos_3',['Using the Homebrew package (macOS)',['../running.html#autotoc_md448',1,'']]],
  ['packer_4',['packer',['../cli-reference.html#packer',1,'']]],
  ['packer_20compare_5',['packer compare',['../cli-reference.html#autotoc_md56',1,'']]],
  ['packer_20pack_6',['packer pack',['../cli-reference.html#autotoc_md55',1,'']]],
  ['papers_7',['Papers',['../papers.html',1,'Papers'],['../papers.html#autotoc_md331',1,'Papers']]],
  ['parallel_20loop_8',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md103',1,'']]],
  ['parallelization_9',['Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md306',1,'GPU Parallelization'],['../architecture.html#autotoc_md12',1,'MPI Parallelization']]],
  ['parameter_10',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md102',1,'']]],
  ['parameter_20constraint_20violations_11',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md519',1,'']]],
  ['parameter_20conventions_12',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['parameter_20descriptions_13',['Parameter Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['parameter_20families_14',['Parameter Families',['../parameters.html#autotoc_md334',1,'']]],
  ['parameter_20lookup_15',['Parameter Lookup',['../getting-started.html#autotoc_md303',1,'']]],
  ['parameter_20reference_16',['📖 Quick Parameter Reference',['../case_constraints.html#quick-parameter-reference',1,'']]],
  ['parameter_20sanity_20transformed_20gamma_17',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md395',1,'']]],
  ['parameters_18',['Parameters',['../parameters.html',1,'Case Parameters'],['../parameters.html#autotoc_md332',1,'Case Parameters'],['../equations.html#sec-nondim-inputs',1,'Non-Dimensionalization of Input Parameters'],['../case.html#autotoc_md18',1,'Parameters'],['../equations.html#sec-two-viscosities',1,'Two Different Viscosity Parameters']]],
  ['parameters_20with_20bubbles_19',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['params_20',['params',['../cli-reference.html#params',1,'']]],
  ['paraview_21',['Visualizing with Paraview',['../visualization.html#autotoc_md526',1,'']]],
  ['paraview_20server_22',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['patch_20initial_20condition_20constraints_23',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md396',1,'']]],
  ['patch_20types_24',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['patch_20types_25',['Patch types',['../case.html#patch-types',1,'']]],
  ['patch_20within_20domain_26',['Patch Within Domain',['../physics_constraints.html#autotoc_md405',1,'']]],
  ['patch_5fbc_27',['patch_bc',['../parameters.html#patch_bc',1,'']]],
  ['patch_5fib_28',['patch_ib',['../parameters.html#patch_ib',1,'']]],
  ['patch_5ficpp_29',['patch_icpp',['../parameters.html#patch_icpp',1,'']]],
  ['patches_30',['Patches',['../case.html#sec-patches',1,'3. Patches'],['../case.html#sec-immersed-boundary-patches',1,'4. Immersed Boundary Patches'],['../case.html#boundary-condition-patches',1,'Boundary Condition Patches'],['../case.html#autotoc_md21',1,'Hard Coded Patches']]],
  ['patterns_31',['Patterns',['../case_constraints.html#common-configuration-patterns',1,'🚀 Common Configuration Patterns'],['../parameters.html#autotoc_md336',1,'Patterns'],['../parameters.html#autotoc_md338',1,'Patterns'],['../parameters.html#autotoc_md340',1,'Patterns'],['../parameters.html#autotoc_md342',1,'Patterns'],['../parameters.html#autotoc_md344',1,'Patterns'],['../parameters.html#autotoc_md346',1,'Patterns'],['../parameters.html#autotoc_md348',1,'Patterns'],['../parameters.html#autotoc_md350',1,'Patterns'],['../parameters.html#autotoc_md352',1,'Patterns'],['../parameters.html#autotoc_md354',1,'Patterns'],['../parameters.html#autotoc_md356',1,'Patterns'],['../parameters.html#autotoc_md358',1,'Patterns'],['../parameters.html#autotoc_md362',1,'Patterns'],['../parameters.html#autotoc_md364',1,'Patterns'],['../parameters.html#autotoc_md366',1,'Patterns'],['../parameters.html#autotoc_md368',1,'Patterns'],['../parameters.html#autotoc_md370',1,'Patterns'],['../parameters.html#autotoc_md372',1,'Patterns'],['../parameters.html#autotoc_md375',1,'Patterns'],['../parameters.html#autotoc_md377',1,'Patterns'],['../parameters.html#autotoc_md379',1,'Patterns'],['../parameters.html#autotoc_md381',1,'Patterns']]],
  ['pdes_32',['2. Governing PDEs',['../equations.html#autotoc_md140',1,'']]],
  ['perfectly_20stirred_20reactor_33',['Perfectly Stirred Reactor',['../examples.html#autotoc_md237',1,'']]],
  ['performance_34',['Performance',['../expectedPerformance.html#autotoc_md275',1,'Achieving Maximum Performance'],['../expectedPerformance.html',1,'Performance'],['../expectedPerformance.html#autotoc_md273',1,'Performance']]],
  ['performance_35',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md283',1,'']]],
  ['performance_20checklist_36',['Performance Checklist',['../expectedPerformance.html#autotoc_md280',1,'']]],
  ['performance_20profiling_37',['Performance Profiling',['../troubleshooting.html#autotoc_md506',1,'']]],
  ['performance_20test_38',['Scaling and Performance test',['../examples.html#autotoc_md214',1,'']]],
  ['performance_20vs_20correctness_39',['Performance vs Correctness',['../troubleshooting.html#autotoc_md509',1,'']]],
  ['phase_20change_40',['Phase Change',['../physics_constraints.html#autotoc_md425',1,'']]],
  ['phase_20change_20model_41',['11. Phase Change Model',['../case.html#sec-phase-change',1,'']]],
  ['phase_20change_20relax_20true_20wilfong26_20sec_204_201_203_42',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md167',1,'']]],
  ['phase_20pipeline_43',['Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md82',1,'Three-Phase Pipeline']]],
  ['phoenix_44',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md530',1,'']]],
  ['physics_45',['Physics',['../architecture.html#autotoc_md13',1,'Adding New Physics'],['../physics_constraints.html#autotoc_md416',1,'Bubble Physics']]],
  ['physics_20and_20model_20consistency_46',['Physics and Model Consistency',['../contributing.html#autotoc_md96',1,'']]],
  ['physics_20constraints_47',['Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'How to Document Physics Constraints'],['../physics_constraints.html',1,'Physics Constraints']]],
  ['physics_20constraints_20reference_48',['Physics Constraints Reference',['../physics_constraints.html#autotoc_md391',1,'']]],
  ['physics_20models_49',['Physics Models',['../architecture.html#autotoc_md7',1,'Physics Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['physics_20warnings_50',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['pipeline_51',['Pipeline',['../contributing.html#autotoc_md113',1,'CI Pipeline'],['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md82',1,'Three-Phase Pipeline']]],
  ['pitfalls_52',['Common Pitfalls',['../contributing.html#autotoc_md91',1,'']]],
  ['playbook_53',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_54',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['plesset49_55',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['point_202d_56',['2D Triple Point (2D)',['../examples.html#autotoc_md264',1,'']]],
  ['points_57',['Points',['../expectedPerformance.html#autotoc_md290',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md291',1,'64M Grid Points']]],
  ['polytropic_20false_20preston07_58',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['polytropic_20thermal_20model_20polytropic_20false_20preston07_59',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['portability_60',['Portability',['../contributing.html#autotoc_md98',1,'Compiler Portability'],['../docker.html#autotoc_md128',1,'For Portability'],['../docker.html#autotoc_md125',1,'Portability']]],
  ['positivity_61',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md394',1,'']]],
  ['post_20process_62',['Testing Post Process',['../testing.html#autotoc_md474',1,'']]],
  ['post_20processing_63',['Post-Processing',['../physics_constraints.html#autotoc_md438',1,'']]],
  ['post_20processing_20output_20variable_64',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md109',1,'']]],
  ['power9_20cpu_65',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md292',1,'']]],
  ['power9_20cpu_20historical_66',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md287',1,'']]],
  ['pre_20process_67',['Pre-Process',['../architecture.html#autotoc_md11',1,'']]],
  ['precheck_68',['precheck',['../cli-reference.html#precheck',1,'']]],
  ['precision_20and_20type_20safety_69',['Precision and Type Safety',['../contributing.html#autotoc_md93',1,'']]],
  ['precision_20system_70',['Working with the Precision System',['../contributing.html#autotoc_md107',1,'']]],
  ['preprocessing_20failed_71',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md514',1,'']]],
  ['preston07_72',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['primitive_20variables_73',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['primitive_20variables_20ordering_74',['Primitive Variables Ordering',['../case.html#autotoc_md37',1,'']]],
  ['probe_75',['probe',['../parameters.html#probe',1,'']]],
  ['problem_201d_76',['problem 1D',['../examples.html#autotoc_md211',1,'Lax shock tube problem (1D)'],['../examples.html#autotoc_md222',1,'Shu-Osher problem (1D)'],['../examples.html#autotoc_md250',1,'Titarev-Toro problem (1D)']]],
  ['problem_202d_77',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md238',1,'']]],
  ['problem_202d_78',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md247',1,'']]],
  ['process_79',['Process',['../architecture.html#autotoc_md11',1,'Pre-Process'],['../testing.html#autotoc_md474',1,'Testing Post Process']]],
  ['processing_80',['Post-Processing',['../physics_constraints.html#autotoc_md438',1,'']]],
  ['processing_20output_20variable_81',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md109',1,'']]],
  ['profiling_82',['Profiling',['../troubleshooting.html#autotoc_md508',1,'AMD GPU Profiling'],['../running.html#autotoc_md458',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md507',1,'NVIDIA GPU Profiling'],['../troubleshooting.html#autotoc_md506',1,'Performance Profiling']]],
  ['profiling_20flags_83',['Profiling Flags',['../troubleshooting.html#autotoc_md478',1,'']]],
  ['profiling_20for_20optimization_84',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md279',1,'']]],
  ['pt_20relaxation_20relax_5fmodel_205_20saurel08_85',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['ptg_20relaxation_20relax_5fmodel_206_20zein10_86',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[55]&lt;/a&gt;)',['../equations.html#autotoc_md169',1,'']]],
  ['pull_20request_87',['Submitting a Pull Request',['../contributing.html#autotoc_md118',1,'']]],
  ['python_20toolchain_88',['Python Toolchain',['../contributing.html#autotoc_md97',1,'']]]
];
