var searchData=
[
  ['gamma_0',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md381',1,'']]],
  ['gas_20eos_20chemistry_20chemistry_20true_1',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md133',1,'']]],
  ['gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_2',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md132',1,'']]],
  ['gas_20jet_202d_3',['Gas Jet (2D)',['../examples.html#autotoc_md231',1,'']]],
  ['gate_20runs_20first_20blocks_20all_20other_20jobs_4',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md100',1,'']]],
  ['general_5',['general',['../parameters.html#general',1,'']]],
  ['general_20options_6',['General Options',['../gpuParallelization.html#autotoc_md310',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md313',1,'NVHPC General Options']]],
  ['general_20users_3a_20dimensional_20handling_7',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['generalized_20characteristic_20boundary_20conditions_8',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md21',1,'']]],
  ['generalized_20riemann_20igr_9',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md413',1,'']]],
  ['generate_10',['generate',['../cli-reference.html#generate',1,'']]],
  ['geometric_20regularization_20igr_20true_20wilfong25a_11',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['geometry_12',['Geometry',['../physics_constraints.html#autotoc_md388',1,'Domain and Geometry'],['../case_constraints.html#compat-geometry',1,'Geometry']]],
  ['getting_20help_13',['Getting Help',['../troubleshooting.html#autotoc_md510',1,'']]],
  ['getting_20set_20up_14',['Getting Set Up',['../contributing.html#autotoc_md66',1,'']]],
  ['getting_20started_15',['Getting Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md279',1,'Getting Started'],['../index.html#autotoc_md427',1,'Getting Started']]],
  ['gilmore_20bubble_5fmodel_201_20gilmore52_16',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['gilmore52_17',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md144',1,'']]],
  ['golden_20files_18',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md489',1,'']]],
  ['gottlieb98_19',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md182',1,'']]],
  ['governing_20pdes_20',['2. Governing PDEs',['../equations.html#autotoc_md126',1,'']]],
  ['gpu_21',['GPU',['../expectedPerformance.html#autotoc_md271',1,'AMD MI250X GPU'],['../contributing.html#autotoc_md86',1,'Fypp and GPU'],['../expectedPerformance.html#autotoc_md272',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md275',1,'NVIDIA V100 GPU']]],
  ['gpu_20arrays_22',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['gpu_20detection_23',['Verifying GPU Detection',['../running.html#autotoc_md443',1,'']]],
  ['gpu_20not_20detected_24',['GPU not detected',['../troubleshooting.html#autotoc_md507',1,'']]],
  ['gpu_20openacc_20errors_25',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['gpu_20parallel_20loop_26',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['gpu_20parallelization_27',['GPU Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md292',1,'GPU Parallelization']]],
  ['gpu_20profiling_28',['GPU Profiling',['../troubleshooting.html#autotoc_md494',1,'AMD GPU Profiling'],['../running.html#autotoc_md444',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md493',1,'NVIDIA GPU Profiling']]],
  ['gpu_20support_29',['Building with GPU Support',['../running.html#autotoc_md439',1,'']]],
  ['gpus_30',['GPUs',['../running.html#autotoc_md446',1,'AMD GPUs'],['../gpuParallelization.html#autotoc_md306',1,'Debugging Tools and Tips for GPUs'],['../running.html#autotoc_md445',1,'NVIDIA GPUs'],['../running.html#autotoc_md438',1,'Running on GPUs'],['../running.html#autotoc_md440',1,'Running on GPUs']]],
  ['green_20vortex_203d_31',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md255',1,'']]],
  ['grid_20bubble_20dynamics_20wilfong26_20sec_204_201_32',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md139',1,'']]],
  ['grid_20bubble_20models_33',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['grid_20points_34',['Grid Points',['../expectedPerformance.html#autotoc_md276',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md277',1,'64M Grid Points']]],
  ['grind_20time_20performance_35',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md269',1,'']]],
  ['gui_36',['Docker Desktop GUI',['../docker.html#autotoc_md108',1,'']]],
  ['guide_37',['Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md24',1,'Case Creator Guide'],['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md461',1,'Troubleshooting Guide']]],
  ['guidelines_38',['Soft Guidelines',['../contributing.html#autotoc_md76',1,'']]],
  ['guides_39',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]]
];
