var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md136',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md138',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md139',1,'']]],
  ['target_20regions_20inside_20fortran_20block_20constructs_20are_20silently_20dropped_4',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md390',1,'']]],
  ['target_20selection_20t_20targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['targets_6',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['taylor_20green_20vortex_203d_7',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md323',1,'']]],
  ['taylor_20instability_202d_8',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md314',1,'']]],
  ['taylor_20instability_203d_9',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md270',1,'']]],
  ['templates_10',['Computer Templates',['../running.html#autotoc_md553',1,'']]],
  ['temporal_20reacting_20mixing_20layer_20h2_20n2_20air_20mc_201_205_11',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md227',1,'']]],
  ['tension_12',['Surface Tension',['../physics_constraints.html#autotoc_md502',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_13',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md178',1,'']]],
  ['tensor_20viscous_20true_14',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md155',1,'']]],
  ['term_20implementation_15',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md200',1,'']]],
  ['terminal_20ui_20tui_16',['Terminal UI (TUI)',['../visualization.html#autotoc_md629',1,'']]],
  ['test_17',['test',['../examples.html#autotoc_md238',1,'Scaling and Performance test'],['../cli-reference.html#test',1,'test']]],
  ['test_202d_18',['2D Riemann Test (2D)',['../examples.html#autotoc_md257',1,'']]],
  ['test_20case_19',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['test_20debugging_20',['Test Debugging',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['test_20execution_21',['Serial Test Execution',['../troubleshooting.html#autotoc_md588',1,'']]],
  ['test_20fails_22',['Test Fails?',['../troubleshooting.html#autotoc_md571',1,'']]],
  ['test_20failures_23',['Understanding Test Failures',['../troubleshooting.html#autotoc_md591',1,'']]],
  ['test_20matrix_24',['Build and Test Matrix',['../contributing.html#autotoc_md121',1,'']]],
  ['test_20output_20location_25',['Test Output Location',['../troubleshooting.html#autotoc_md589',1,'']]],
  ['test_20suite_26',['Running the Test Suite',['../getting-started.html#autotoc_md354',1,'']]],
  ['testing_27',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md118',1,'Testing'],['../testing.html#autotoc_md559',1,'Testing']]],
  ['testing_20post_20process_28',['Testing Post Process',['../testing.html#autotoc_md561',1,'']]],
  ['tests_29',['Tests',['../testing.html#autotoc_md560',1,'Creating Tests'],['../troubleshooting.html#autotoc_md587',1,'Running Specific Tests']]],
  ['the_20build_30',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md389',1,'']]],
  ['the_20build_20fits_20together_31',['How the Build Fits Together',['../contributing.html#autotoc_md89',1,'']]],
  ['the_20dimensionality_32',['Boundary-condition patch geometry has to match the dimensionality',['../examples.html#autotoc_md303',1,'']]],
  ['the_20homebrew_20package_20macos_33',['Using the Homebrew package (macOS)',['../running.html#autotoc_md535',1,'']]],
  ['the_20precision_20system_34',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['the_20same_20corner_35',['A second trap in the same corner',['../examples.html#autotoc_md305',1,'']]],
  ['the_20script_36',['Step 2: Customizing the script',['../visualization.html#autotoc_md640',1,'']]],
  ['the_20simulation_20loop_37',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['the_20sweep_38',['Running the sweep',['../examples.html#autotoc_md234',1,'']]],
  ['the_20sweep_20shows_39',['What the sweep shows',['../examples.html#autotoc_md235',1,'']]],
  ['the_20test_20suite_40',['Running the Test Suite',['../getting-started.html#autotoc_md354',1,'']]],
  ['theory_41',['Theory',['../examples.html#autotoc_md271',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md315',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_42',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['thermodynamic_20constraints_43',['Thermodynamic Constraints',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['thickening_20poiseuille_20channel_44',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md277',1,'']]],
  ['thin_20plate_20issue_201849_45',['Immersed-boundary force on a thin plate (issue #1849)',['../examples.html#autotoc_md233',1,'']]],
  ['thinning_20lid_20driven_20cavity_46',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md309',1,'']]],
  ['thinning_20poiseuille_20channel_47',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md264',1,'']]],
  ['thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_48',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[53]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[54]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['thompson90_20bc_5fx_20beg_205_20to_2012_49',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[53]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[54]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['three_20phase_20pipeline_50',['Three Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md85',1,'Three-Phase Pipeline']]],
  ['tiled_201d_20rendering_51',['Tiled 1D rendering',['../visualization.html#autotoc_md627',1,'']]],
  ['time_52',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md226',1,'']]],
  ['time_20integration_53',['15.3 Time Integration',['../equations.html#autotoc_md201',1,'']]],
  ['time_20performance_54',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md338',1,'']]],
  ['time_20stepping_55',['Time Stepping',['../case.html#autotoc_md27',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md26',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md513',1,'Time Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_56',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md203',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_57',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['timestep_20selection_58',['Timestep selection',['../visualization.html#autotoc_md623',1,'']]],
  ['tips_20for_20gpus_59',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md378',1,'']]],
  ['titarev_20toro_20problem_201d_60',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md259',1,'']]],
  ['to_2012_61',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[53]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[54]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_62',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md107',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_63',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['to_20add_20a_20test_20case_64',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['to_20add_20an_20equation_20of_20state_65',['How to Add an Equation of State',['../contributing.html#autotoc_md110',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_66',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md109',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_67',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['to_20document_20physics_20constraints_68',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_69',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['to_20guides_70',['How-To Guides',['../contributing.html#autotoc_md106',1,'']]],
  ['to_20match_20the_20dimensionality_71',['Boundary-condition patch geometry has to match the dimensionality',['../examples.html#autotoc_md303',1,'']]],
  ['to_20mfc_72',['Contributing to MFC',['../contributing.html#autotoc_md82',1,'']]],
  ['to_20read_20silo_20hdf5_20files_73',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md614',1,'']]],
  ['to_20run_74',['to run',['../examples.html#autotoc_md251',1,'How to run'],['../examples.html#autotoc_md267',1,'How to run'],['../examples.html#autotoc_md280',1,'How to run'],['../examples.html#autotoc_md291',1,'How to run'],['../examples.html#autotoc_md297',1,'How to run'],['../examples.html#autotoc_md312',1,'How to run']]],
  ['to_20use_20case_20optimization_75',['When to use case optimization',['../expectedPerformance.html#autotoc_md332',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_76',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md108',1,'']]],
  ['together_77',['How the Build Fits Together',['../contributing.html#autotoc_md89',1,'']]],
  ['toolchain_78',['Toolchain',['../contributing.html#autotoc_md88',1,'Build Toolchain'],['../contributing.html#autotoc_md101',1,'Python Toolchain']]],
  ['tools_79',['Tools',['../gpuParallelization.html#autotoc_md381',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md358',1,'Helpful Tools']]],
  ['tools_80',['tools',['../gpuParallelization.html#autotoc_md379',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md380',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_81',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md378',1,'']]],
  ['topics_82',['Advanced Topics',['../index.html#autotoc_md531',1,'']]],
  ['toro_20problem_201d_83',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md259',1,'']]],
  ['toro94_84',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md197',1,'']]],
  ['transformed_20gamma_85',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md472',1,'']]],
  ['transitional_20state_86',['Liutex visualization at transitional state',['../examples.html#autotoc_md284',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_87',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['trap_20in_20the_20same_20corner_88',['A second trap in the same corner',['../examples.html#autotoc_md305',1,'']]],
  ['traps_89',['Silent-Failure Traps',['../gpuParallelization.html#silent-failure-traps',1,'']]],
  ['triple_20point_202d_90',['2D Triple Point (2D)',['../examples.html#autotoc_md225',1,'']]],
  ['troubleshooting_20guide_91',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md562',1,'Troubleshooting Guide']]],
  ['true_92',['true',['../equations.html#autotoc_md188',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md153',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md155',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md160',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md203',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_93',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['true_20cao19_20spratt24_20sec_204_201_202_94',['7.2 Continuum Damage (&lt;span class=&quot;tt&quot;&gt;cont_damage = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_cao19&quot;&gt;[10]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_spratt24&quot;&gt;[48]&lt;/a&gt; Sec. 4.1.2)',['../equations.html#autotoc_md171',1,'']]],
  ['true_20maeda18_95',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[31]&lt;/a&gt;)',['../equations.html#autotoc_md167',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_96',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_97',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md178',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_98',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['true_20wilfong25a_99',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['true_20wilfong26_20sec_202_203_100',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_101',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md182',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_102',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md172',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_103',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md176',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_104',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md181',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_105',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['tube_106',['Tube',['../examples.html#autotoc_md219',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md222',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_107',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md254',1,'']]],
  ['tube_20problem_201d_108',['Lax shock tube problem (1D)',['../examples.html#autotoc_md300',1,'']]],
  ['tui_109',['Terminal UI (TUI)',['../visualization.html#autotoc_md629',1,'']]],
  ['turb_5fpos_110',['turb_pos',['../parameters.html#turb_pos',1,'']]],
  ['turbulence_111',['20. Synthetic Turbulence',['../case.html#autotoc_md37',1,'']]],
  ['turbulence_20forcing_112',['Synthetic Turbulence Forcing',['../physics_constraints.html#autotoc_md508',1,'']]],
  ['turbulent_20mixing_20layer_203d_113',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md283',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_114',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['two_20different_20viscosity_20parameters_115',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['type_20meanings_116',['Data Type Meanings',['../gpuParallelization.html#autotoc_md365',1,'']]],
  ['type_20safety_117',['Precision and Type Safety',['../contributing.html#autotoc_md97',1,'']]],
  ['types_118',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['types_119',['Patch types',['../case.html#patch-types',1,'']]]
];
