var searchData=
[
  ['s_0',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['safety_1',['Precision and Type Safety',['../contributing.html#autotoc_md97',1,'']]],
  ['sanity_20transformed_20gamma_2',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md461',1,'']]],
  ['saurel08_3',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[44]&lt;/a&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['scales_4',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['scaling_5',['Scaling',['../examples.html#autotoc_md234',1,'Strong Scaling'],['../examples.html#autotoc_md233',1,'Weak Scaling']]],
  ['scaling_6',['scaling',['../expectedPerformance.html#autotoc_md330',1,'GPU weak scaling'],['../expectedPerformance.html#autotoc_md333',1,'Strong scaling'],['../expectedPerformance.html#autotoc_md329',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_7',['Scaling and Performance test',['../examples.html#autotoc_md232',1,'']]],
  ['scheduler_20notes_8',['Scheduler Notes',['../running.html#autotoc_md542',1,'']]],
  ['schemes_9',['Numerical Schemes',['../physics_constraints.html#autotoc_md498',1,'']]],
  ['schlieren_20at_20final_20time_10',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md225',1,'']]],
  ['schlieren_5falpha_11',['schlieren_alpha',['../parameters.html#schlieren_alpha',1,'']]],
  ['schmidmayer17_20wilfong26_20sec_204_201_208_12',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['script_13',['Step 2: Customizing the script',['../visualization.html#autotoc_md628',1,'']]],
  ['sec_202_202_14',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md151',1,'']]],
  ['sec_202_203_15',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md156',1,'']]],
  ['sec_204_201_16',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md158',1,'']]],
  ['sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['sec_204_201_2010_18',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md181',1,'']]],
  ['sec_204_201_202_19',['7.2 Continuum Damage (&lt;span class=&quot;tt&quot;&gt;cont_damage = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_cao19&quot;&gt;[10]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_spratt24&quot;&gt;[48]&lt;/a&gt; Sec. 4.1.2)',['../equations.html#autotoc_md170',1,'']]],
  ['sec_204_201_203_20',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md171',1,'']]],
  ['sec_204_201_206_21',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md169',1,'']]],
  ['sec_204_201_207_22',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['sec_204_201_208_23',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['sec_204_201_209_24',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['sec_204_202_204_25',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md212',1,'']]],
  ['selection_26',['Model Equation Selection',['../physics_constraints.html#autotoc_md478',1,'']]],
  ['selection_27',['selection',['../visualization.html#autotoc_md619',1,'Format selection'],['../visualization.html#autotoc_md611',1,'Timestep selection']]],
  ['selection_20t_20targets_28',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['selector_29',['Equation of State Selector',['../physics_constraints.html#autotoc_md460',1,'']]],
  ['serial_20data_20output_30',['Serial data output',['../visualization.html#autotoc_md625',1,'']]],
  ['serial_20test_20execution_31',['Serial Test Execution',['../troubleshooting.html#autotoc_md576',1,'']]],
  ['server_32',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md629',1,'']]],
  ['set_20up_33',['Getting Set Up',['../contributing.html#autotoc_md83',1,'']]],
  ['setting_20up_20your_20environment_34',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md627',1,'']]],
  ['setup_35',['Setup',['../case.html#sec-velocity-field-setup',1,'10. Velocity Field Setup'],['../running.html#autotoc_md531',1,'Environment Setup']]],
  ['sh_20viz_36',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md608',1,'']]],
  ['shear_20thickening_20poiseuille_20channel_37',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md271',1,'']]],
  ['shear_20thinning_20lid_20driven_20cavity_38',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md299',1,'']]],
  ['shear_20thinning_20poiseuille_20channel_39',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md258',1,'']]],
  ['shell_40',['Interactive Shell',['../docker.html#autotoc_md132',1,'']]],
  ['shell_20completion_41',['Shell Completion',['../getting-started.html#autotoc_md351',1,'']]],
  ['shock_203d_42',['IBM Bow Shock (3D)',['../examples.html#autotoc_md306',1,'']]],
  ['shock_20droplet_202d_43',['Shock Droplet (2D)',['../examples.html#autotoc_md315',1,'']]],
  ['shock_20tube_44',['Shock Tube',['../examples.html#autotoc_md218',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md221',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_202d_45',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md248',1,'']]],
  ['shock_20tube_20problem_201d_46',['Lax shock tube problem (1D)',['../examples.html#autotoc_md294',1,'']]],
  ['shu_20osher_20problem_201d_47',['Shu-Osher problem (1D)',['../examples.html#autotoc_md236',1,'']]],
  ['silently_20dropped_48',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md380',1,'']]],
  ['silo_20hdf5_20files_49',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md602',1,'']]],
  ['silo_5fhdf5_20directory_20found_50',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md600',1,'']]],
  ['simple_20bcs_51',['16.1 Simple BCs',['../equations.html#autotoc_md208',1,'']]],
  ['simplex_5fparams_52',['simplex_params',['../parameters.html#simplex_params',1,'']]],
  ['simulation_20algorithm_53',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['simulation_20constraints_54',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md485',1,'']]],
  ['simulation_20data_20flow_55',['Simulation Data Flow',['../contributing.html#autotoc_md87',1,'']]],
  ['simulation_20loop_56',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['simulation_20parameter_57',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md106',1,'']]],
  ['singularity_58',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md131',1,'']]],
  ['six_20equation_20model_20model_5feqns_203_59',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['skeleton_60',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['slicing_61',['3D slicing',['../visualization.html#autotoc_md613',1,'']]],
  ['slurm_20job_62',['Slurm Job',['../docker.html#autotoc_md134',1,'']]],
  ['smoothing_63',['Elliptic Smoothing',['../case.html#autotoc_md23',1,'']]],
  ['soft_20guidelines_64',['Soft Guidelines',['../contributing.html#autotoc_md94',1,'']]],
  ['solution_65',['solution',['../examples.html#autotoc_md290',1,'Analytic solution'],['../examples.html#autotoc_md244',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md260',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md273',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md284',1,'Governing physics and analytic solution']]],
  ['solver_20core_66',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['solvers_67',['Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md194',1,'15.2 Riemann Solvers']]],
  ['sound_20speed_68',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md493',1,'']]],
  ['source_69',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['sources_70',['Sources',['../physics_constraints.html#autotoc_md504',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md505',1,'Acoustic Sources']]],
  ['sources_20acoustic_5fsource_20true_71',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['spatial_20reconstruction_72',['15.1 Spatial Reconstruction',['../equations.html#autotoc_md190',1,'']]],
  ['spatial_5fbf_73',['spatial_bf',['../parameters.html#spatial_bf',1,'']]],
  ['specific_20boundary_20conditions_74',['18. Chemistry-Specific Boundary Conditions',['../case.html#autotoc_md35',1,'']]],
  ['specific_20tests_75',['Running Specific Tests',['../troubleshooting.html#autotoc_md575',1,'']]],
  ['specified_76',['Domain Extents Specified',['../physics_constraints.html#autotoc_md471',1,'']]],
  ['speed_77',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md493',1,'']]],
  ['spelling_78',['spelling',['../cli-reference.html#spelling',1,'']]],
  ['splitting_20strang68_20for_20stiff_20bubble_20dynamics_79',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md203',1,'']]],
  ['spratt24_20sec_204_201_202_80',['7.2 Continuum Damage (&lt;span class=&quot;tt&quot;&gt;cont_damage = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_cao19&quot;&gt;[10]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_spratt24&quot;&gt;[48]&lt;/a&gt; Sec. 4.1.2)',['../equations.html#autotoc_md170',1,'']]],
  ['src_20common_81',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md115',1,'']]],
  ['stage_82',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['standards_83',['Coding Standards',['../contributing.html#autotoc_md92',1,'']]],
  ['started_84',['Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md338',1,'Getting Started'],['../index.html#autotoc_md516',1,'Getting Started']]],
  ['startup_85',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['state_86',['State',['../equations.html#autotoc_md150',1,'3. Equations of State'],['../examples.html#autotoc_md241',1,'Evolved State'],['../examples.html#autotoc_md250',1,'Evolved State'],['../examples.html#autotoc_md312',1,'Evolved State'],['../contributing.html#autotoc_md109',1,'How to Add an Equation of State'],['../examples.html#autotoc_md240',1,'Initial State'],['../examples.html#autotoc_md249',1,'Initial State'],['../examples.html#autotoc_md311',1,'Initial State'],['../physics_constraints.html#autotoc_md459',1,'Initial States Inside a State-Dependent Equation of State']]],
  ['state_87',['Liutex visualization at transitional state',['../examples.html#autotoc_md278',1,'']]],
  ['state_20dependent_20equation_20of_20state_88',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['state_20selector_89',['Equation of State Selector',['../physics_constraints.html#autotoc_md460',1,'']]],
  ['states_20inside_20a_20state_20dependent_20equation_20of_20state_90',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_91',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md627',1,'']]],
  ['step_202_3a_20customizing_20the_20script_92',['Step 2: Customizing the script',['../visualization.html#autotoc_md628',1,'']]],
  ['step_202d_93',['Step 2D',['../examples.html#autotoc_md216',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md256',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_94',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md629',1,'']]],
  ['stepping_95',['Stepping',['../case.html#autotoc_md27',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md26',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md501',1,'Time Stepping']]],
  ['stepping_20adap_5fdt_20true_96',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['stiff_20bubble_20dynamics_97',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md203',1,'']]],
  ['stiffened_20eos_20positivity_98',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md458',1,'']]],
  ['stiffened_20gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_99',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md151',1,'']]],
  ['stirred_20reactor_100',['Perfectly Stirred Reactor',['../examples.html#autotoc_md269',1,'']]],
  ['stl_5fmodels_101',['stl_models',['../parameters.html#stl_models',1,'']]],
  ['stored_20parameter_20conventions_102',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['strang_20splitting_20strang68_20for_20stiff_20bubble_20dynamics_103',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md203',1,'']]],
  ['strang68_20for_20stiff_20bubble_20dynamics_104',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[50]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md203',1,'']]],
  ['stress_20poiseuille_20channel_105',['2D Bingham (Yield-Stress) Poiseuille Channel',['../examples.html#autotoc_md282',1,'']]],
  ['stress_20tensor_20viscous_20true_106',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md154',1,'']]],
  ['strong_20scaling_107',['Strong Scaling',['../examples.html#autotoc_md234',1,'']]],
  ['strong_20scaling_108',['Strong scaling',['../expectedPerformance.html#autotoc_md333',1,'']]],
  ['structure_109',['Tag Structure',['../docker.html#autotoc_md137',1,'']]],
  ['structure_20interaction_110',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md168',1,'']]],
  ['structures_111',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['styling_112',['Plot styling',['../visualization.html#autotoc_md618',1,'']]],
  ['sub_20grid_20bubble_20dynamics_20wilfong26_20sec_204_201_113',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md158',1,'']]],
  ['sub_20grid_20bubble_20models_114',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['submitting_20a_20pull_20request_115',['Submitting a Pull Request',['../contributing.html#autotoc_md123',1,'']]],
  ['suite_116',['Running the Test Suite',['../getting-started.html#autotoc_md344',1,'']]],
  ['sum_117',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md465',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_118',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md131',1,'']]],
  ['support_119',['Support',['../docker.html#autotoc_md139',1,'Architecture Support'],['../running.html#autotoc_md528',1,'Building with GPU Support']]],
  ['supported_20compilers_120',['Supported Compilers',['../running.html#autotoc_md530',1,'']]],
  ['supports_121',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['surface_20tension_122',['Surface Tension',['../physics_constraints.html#autotoc_md490',1,'']]],
  ['surface_20tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_123',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_124',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['synchronization_20macros_125',['Synchronization Macros',['../gpuParallelization.html#autotoc_md362',1,'']]],
  ['synth_5famp_5fshell_126',['synth_amp_shell',['../parameters.html#synth_amp_shell',1,'']]],
  ['synth_5fk_5fshell_127',['synth_k_shell',['../parameters.html#synth_k_shell',1,'']]],
  ['synth_5fl_128',['synth_L',['../parameters.html#synth_L',1,'']]],
  ['synth_5fn_5fwaves_5fper_5fshell_129',['synth_n_waves_per_shell',['../parameters.html#synth_n_waves_per_shell',1,'']]],
  ['synthetic_20turbulence_130',['20. Synthetic Turbulence',['../case.html#autotoc_md37',1,'']]],
  ['synthetic_20turbulence_20forcing_131',['Synthetic Turbulence Forcing',['../physics_constraints.html#autotoc_md496',1,'']]],
  ['system_132',['Working with the Precision System',['../contributing.html#autotoc_md112',1,'']]]
];
