var searchData=
[
  ['backward_20facing_20step_202d_0',['Backward Facing Step (2D)',['../examples.html#autotoc_md285',1,'']]],
  ['base_20images_1',['Base Images',['../docker.html#autotoc_md162',1,'']]],
  ['basic_20skeleton_2',['Basic Skeleton',['../case.html#autotoc_md2',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../running.html#autotoc_md475',1,'']]],
  ['batch_20execution_4',['Batch Execution',['../running.html#autotoc_md474',1,'']]],
  ['batch_20options_5',['Batch Options',['../running.html#autotoc_md476',1,'']]],
  ['bc_5fx_6',['bc_x',['../parameters.html#autotoc_md386',1,'']]],
  ['bc_5fxbeg_205_20to_2012_7',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['bc_5fy_8',['bc_y',['../parameters.html#autotoc_md389',1,'']]],
  ['bc_5fz_9',['bc_z',['../parameters.html#autotoc_md392',1,'']]],
  ['bcs_10',['16.1 Simple BCs',['../equations.html#autotoc_md233',1,'']]],
  ['bcs_20thompson87_20thompson90_20bc_5fxbeg_205_20to_2012_11',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['beginner_20examples_12',['🟢 Beginner Examples',['../case_constraints.html#autotoc_md41',1,'']]],
  ['bench_13',['bench',['../cli-reference.html#autotoc_md96',1,'']]],
  ['bench_5fdiff_14',['bench_diff',['../cli-reference.html#autotoc_md98',1,'']]],
  ['benchmark_20results_15',['Benchmark Results',['../expectedPerformance.html#autotoc_md312',1,'']]],
  ['bf_5fx_20bf_5fy_20bf_5fz_16',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md211',1,'']]],
  ['bf_5fy_20bf_5fz_17',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md211',1,'']]],
  ['bf_5fz_18',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md211',1,'']]],
  ['bibliography_19',['Bibliography',['../citelist.html',1,'']]],
  ['blocks_20all_20other_20jobs_20',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['body_20forces_21',['13. Body Forces',['../case.html#autotoc_md27',1,'']]],
  ['body_20forces_20bf_5fx_20bf_5fy_20bf_5fz_22',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md211',1,'']]],
  ['boundary_20condition_20patches_23',['Boundary Condition Patches',['../case.html#autotoc_md17',1,'']]],
  ['boundary_20conditions_24',['16. Boundary Conditions',['../equations.html#autotoc_md232',1,'']]],
  ['boundary_20conditions_25',['Boundary conditions',['../case.html#autotoc_md33',1,'Boundary conditions'],['../case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_26',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;b&gt;[Tseng03]&lt;/b&gt;; &lt;b&gt;[Mittal05]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.1)',['../equations.html#autotoc_md235',1,'']]],
  ['boundary_20patch_20types_27',['Immersed Boundary Patch Types',['../case.html#autotoc_md36',1,'']]],
  ['boundary_20patches_28',['4. Immersed Boundary Patches',['../case.html#autotoc_md13',1,'']]],
  ['bounds_20and_20indexing_29',['Array Bounds and Indexing',['../contributing.html#autotoc_md123',1,'']]],
  ['bow_20shock_203d_30',['IBM Bow Shock (3D)',['../examples.html#autotoc_md277',1,'']]],
  ['bryngelson20_31',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;b&gt;[Bryngelson20]&lt;/b&gt;)',['../equations.html#autotoc_md190',1,'']]],
  ['bub_5fpp_32',['bub_pp',['../parameters.html#autotoc_md401',1,'']]],
  ['bubble_20dynamics_33',['Strang Splitting (&lt;b&gt;[Strang68]&lt;/b&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md228',1,'']]],
  ['bubble_20dynamics_20wilfong26_20sec_204_201_34',['6. Sub-Grid Bubble Dynamics (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1)',['../equations.html#autotoc_md183',1,'']]],
  ['bubble_20model_35',['Bubble Model',['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]],
  ['bubble_20models_36',['Bubble Models',['../case_constraints.html#autotoc_md52',1,'💧 Bubble Models'],['../case.html#autotoc_md21',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#autotoc_md47',1,'Bubble Models']]],
  ['bubble_5fmodel_201_20gilmore52_37',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;b&gt;[Gilmore52]&lt;/b&gt;)',['../equations.html#autotoc_md188',1,'']]],
  ['bubble_5fmodel_202_20keller80_38',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;b&gt;[Keller80]&lt;/b&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['bubble_5fmodel_203_20rayleigh17_20plesset49_39',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;b&gt;[Rayleigh17]&lt;/b&gt;; &lt;b&gt;[Plesset49]&lt;/b&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['bubbles_20bubbles_5feuler_20true_40',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['bubbles_20bubbles_5flagrange_20true_20maeda18_41',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;b&gt;[Maeda18]&lt;/b&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['bubbles_5feuler_20true_42',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['bubbles_5flagrange_20true_20maeda18_43',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;b&gt;[Maeda18]&lt;/b&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['build_44',['build',['../cli-reference.html#autotoc_md59',1,'']]],
  ['build_20and_20test_20matrix_45',['Build and Test Matrix',['../contributing.html#autotoc_md146',1,'']]],
  ['build_20configuration_20flags_46',['Build Configuration Flags',['../cli-reference.html#autotoc_md107',1,'']]],
  ['build_20debugging_47',['Build Debugging',['../troubleshooting.html#autotoc_md498',1,'']]],
  ['build_20environment_48',['Build Environment',['../getting-started.html#autotoc_md326',1,'']]],
  ['build_20errors_49',['Common Build Errors',['../troubleshooting.html#autotoc_md523',1,'']]],
  ['build_20fails_50',['Build Fails?',['../troubleshooting.html#autotoc_md494',1,'']]],
  ['build_20fails_20with_20gpu_20openacc_20errors_51',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md527',1,'']]],
  ['build_20toolchain_52',['Build Toolchain',['../contributing.html#autotoc_md116',1,'']]],
  ['building_20mfc_53',['Building MFC',['../getting-started.html#autotoc_md327',1,'']]],
  ['building_20with_20gpu_20support_54',['Building with GPU Support',['../running.html#autotoc_md465',1,'']]],
  ['builds_55',['Debug Builds',['../troubleshooting.html#autotoc_md500',1,'']]]
];
