var searchData=
[
  ['lag_5fparams_0',['lag_params',['../parameters.html#autotoc_md403',1,'']]],
  ['lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_1',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;b&gt;[Maeda18]&lt;/b&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['lax_20shock_20tube_20problem_201d_2',['Lax shock tube problem (1D)',['../examples.html#autotoc_md244',1,'']]],
  ['layer_203d_3',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md263',1,'']]],
  ['layout_4',['Directory Layout',['../contributing.html#autotoc_md114',1,'']]],
  ['lemetayer04_20wilfong26_20sec_202_202_5',['3.1 Stiffened Gas EOS (&lt;b&gt;[Menikoff89]&lt;/b&gt;; &lt;b&gt;[LeMetayer04]&lt;/b&gt;; &lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.2)',['../equations.html#autotoc_md176',1,'']]],
  ['levels_6',['Verbosity Levels',['../troubleshooting.html#autotoc_md499',1,'']]],
  ['lid_20driven_20cavity_20problem_202d_7',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md296',1,'']]],
  ['limiting_8',['18. Flux Limiting',['../equations.html#autotoc_md239',1,'']]],
  ['line_20arguments_9',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['line_20reference_10',['Line Reference',['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md55',1,'Command Line Reference'],['../parameters.html#autotoc_md451',1,'Command Line Reference']]],
  ['linear_20theory_11',['Linear Theory',['../examples.html#autotoc_md257',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md291',1,'Final Condition and Linear Theory']]],
  ['lint_12',['lint',['../cli-reference.html#autotoc_md85',1,'']]],
  ['lint_20gate_20runs_20first_20blocks_20all_20other_20jobs_13',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['liutex_20visualization_20at_20transitional_20state_14',['Liutex visualization at transitional state',['../examples.html#autotoc_md264',1,'']]],
  ['load_15',['load',['../cli-reference.html#autotoc_md101',1,'']]],
  ['location_16',['Test Output Location',['../troubleshooting.html#autotoc_md514',1,'']]],
  ['log_17',['Debug Log',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['log_18',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md109',1,'']]],
  ['logging_20d_20debug_20log_19',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md109',1,'']]],
  ['lookup_20',['Parameter Lookup',['../getting-started.html#autotoc_md332',1,'']]],
  ['loop_21',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md134',1,'']]],
  ['low_20mach_20number_20corrections_20wilfong26_20sec_204_202_204_22',['17. Low Mach Number Corrections (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.2.4)',['../equations.html#autotoc_md237',1,'']]]
];
