var searchData=
[
  ['s_0',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['safety_1',['Precision and Type Safety',['../contributing.html#autotoc_md96',1,'']]],
  ['sanity_20transformed_20gamma_2',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md437',1,'']]],
  ['saurel08_3',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['scales_4',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['scaling_5',['Scaling',['../examples.html#autotoc_md283',1,'Strong Scaling'],['../examples.html#autotoc_md282',1,'Weak Scaling']]],
  ['scaling_6',['scaling',['../expectedPerformance.html#autotoc_md324',1,'GPU weak scaling'],['../expectedPerformance.html#autotoc_md327',1,'Strong scaling'],['../expectedPerformance.html#autotoc_md323',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_7',['Scaling and Performance test',['../examples.html#autotoc_md281',1,'']]],
  ['scheduler_20notes_8',['Scheduler Notes',['../running.html#autotoc_md510',1,'']]],
  ['schemes_9',['Numerical Schemes',['../physics_constraints.html#autotoc_md472',1,'']]],
  ['schlieren_20at_20final_20time_10',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md305',1,'']]],
  ['schlieren_5falpha_11',['schlieren_alpha',['../parameters.html#schlieren_alpha',1,'']]],
  ['schmidmayer17_20wilfong26_20sec_204_201_208_12',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md176',1,'']]],
  ['script_13',['Step 2: Customizing the script',['../visualization.html#autotoc_md596',1,'']]],
  ['sec_202_202_14',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md149',1,'']]],
  ['sec_202_203_15',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md154',1,'']]],
  ['sec_204_201_16',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md156',1,'']]],
  ['sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md208',1,'']]],
  ['sec_204_201_2010_18',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md180',1,'']]],
  ['sec_204_201_203_19',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md170',1,'']]],
  ['sec_204_201_206_20',['Sec 4 1 6',['../equations.html#autotoc_md167',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md168',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)']]],
  ['sec_204_201_207_21',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md174',1,'']]],
  ['sec_204_201_208_22',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md176',1,'']]],
  ['sec_204_201_209_23',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md179',1,'']]],
  ['sec_204_202_204_24',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md210',1,'']]],
  ['selection_25',['Model Equation Selection',['../physics_constraints.html#autotoc_md453',1,'']]],
  ['selection_26',['selection',['../visualization.html#autotoc_md587',1,'Format selection'],['../visualization.html#autotoc_md579',1,'Timestep selection']]],
  ['selection_20t_20targets_27',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['serial_20data_20output_28',['Serial data output',['../visualization.html#autotoc_md593',1,'']]],
  ['serial_20test_20execution_29',['Serial Test Execution',['../troubleshooting.html#autotoc_md544',1,'']]],
  ['server_30',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md597',1,'']]],
  ['set_20up_31',['Getting Set Up',['../contributing.html#autotoc_md83',1,'']]],
  ['setting_20up_20your_20environment_32',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md595',1,'']]],
  ['setup_33',['Setup',['../case.html#sec-velocity-field-setup',1,'10. Velocity Field Setup'],['../running.html#autotoc_md499',1,'Environment Setup']]],
  ['sh_20viz_34',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md576',1,'']]],
  ['shear_20thickening_20poiseuille_20channel_35',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md244',1,'']]],
  ['shear_20thinning_20lid_20driven_20cavity_36',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md269',1,'']]],
  ['shear_20thinning_20poiseuille_20channel_37',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md250',1,'']]],
  ['shell_38',['Interactive Shell',['../docker.html#autotoc_md130',1,'']]],
  ['shell_20completion_39',['Shell Completion',['../getting-started.html#autotoc_md345',1,'']]],
  ['shock_203d_40',['IBM Bow Shock (3D)',['../examples.html#autotoc_md260',1,'']]],
  ['shock_20droplet_202d_41',['Shock Droplet (2D)',['../examples.html#autotoc_md309',1,'']]],
  ['shock_20tube_42',['Shock Tube',['../examples.html#autotoc_md298',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md301',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_202d_43',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md235',1,'']]],
  ['shock_20tube_20problem_201d_44',['Lax shock tube problem (1D)',['../examples.html#autotoc_md306',1,'']]],
  ['shu_20osher_20problem_201d_45',['Shu-Osher problem (1D)',['../examples.html#autotoc_md223',1,'']]],
  ['silo_20hdf5_20files_46',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['silo_5fhdf5_20directory_20found_47',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md568',1,'']]],
  ['simple_20bcs_48',['16.1 Simple BCs',['../equations.html#autotoc_md206',1,'']]],
  ['simplex_5fparams_49',['simplex_params',['../parameters.html#simplex_params',1,'']]],
  ['simulation_20algorithm_50',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['simulation_20constraints_51',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md460',1,'']]],
  ['simulation_20data_20flow_52',['Simulation Data Flow',['../contributing.html#autotoc_md87',1,'']]],
  ['simulation_20loop_53',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['simulation_20parameter_54',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md105',1,'']]],
  ['singularity_55',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md129',1,'']]],
  ['six_20equation_20model_20model_5feqns_203_56',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md145',1,'']]],
  ['skeleton_57',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['slicing_58',['3D slicing',['../visualization.html#autotoc_md581',1,'']]],
  ['slurm_20job_59',['Slurm Job',['../docker.html#autotoc_md132',1,'']]],
  ['smoothing_60',['Elliptic Smoothing',['../case.html#autotoc_md23',1,'']]],
  ['soft_20guidelines_61',['Soft Guidelines',['../contributing.html#autotoc_md93',1,'']]],
  ['solution_62',['solution',['../examples.html#autotoc_md228',1,'Analytic solution'],['../examples.html#autotoc_md240',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md246',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md252',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md294',1,'Governing physics and analytic solution']]],
  ['solver_20core_63',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['solvers_64',['Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md193',1,'15.2 Riemann Solvers']]],
  ['sound_20speed_65',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['source_66',['8. Acoustic Source',['../case.html#sec-acoustic-source',1,'']]],
  ['sources_67',['Sources',['../physics_constraints.html#autotoc_md478',1,'Acoustic Sources'],['../physics_constraints.html#autotoc_md479',1,'Acoustic Sources']]],
  ['sources_20acoustic_5fsource_20true_68',['14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['spatial_20reconstruction_69',['15.1 Spatial Reconstruction',['../equations.html#autotoc_md189',1,'']]],
  ['specific_20boundary_20conditions_70',['18. Chemistry-Specific Boundary Conditions',['../case.html#autotoc_md34',1,'']]],
  ['specific_20tests_71',['Running Specific Tests',['../troubleshooting.html#autotoc_md543',1,'']]],
  ['speed_72',['Alternative Sound Speed',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['spelling_73',['spelling',['../cli-reference.html#spelling',1,'']]],
  ['splitting_20strang68_20for_20stiff_20bubble_20dynamics_74',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md201',1,'']]],
  ['src_20common_75',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md113',1,'']]],
  ['stage_76',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['standards_77',['Coding Standards',['../contributing.html#autotoc_md91',1,'']]],
  ['started_78',['Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md332',1,'Getting Started'],['../index.html#autotoc_md484',1,'Getting Started']]],
  ['startup_79',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['state_80',['State',['../equations.html#autotoc_md148',1,'3. Equations of State'],['../examples.html#autotoc_md218',1,'Evolved State'],['../examples.html#autotoc_md237',1,'Evolved State'],['../examples.html#autotoc_md276',1,'Evolved State'],['../examples.html#autotoc_md217',1,'Initial State'],['../examples.html#autotoc_md236',1,'Initial State'],['../examples.html#autotoc_md275',1,'Initial State']]],
  ['state_81',['Liutex visualization at transitional state',['../examples.html#autotoc_md257',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_82',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md595',1,'']]],
  ['step_202_3a_20customizing_20the_20script_83',['Step 2: Customizing the script',['../visualization.html#autotoc_md596',1,'']]],
  ['step_202d_84',['Step 2D',['../examples.html#autotoc_md279',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md277',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_85',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md597',1,'']]],
  ['stepping_86',['Stepping',['../case.html#autotoc_md26',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md25',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md475',1,'Time Stepping']]],
  ['stepping_20adap_5fdt_20true_87',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md200',1,'']]],
  ['stiff_20bubble_20dynamics_88',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md201',1,'']]],
  ['stiffened_20eos_20positivity_89',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md436',1,'']]],
  ['stiffened_20gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_90',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md149',1,'']]],
  ['stirred_20reactor_91',['Perfectly Stirred Reactor',['../examples.html#autotoc_md258',1,'']]],
  ['stl_5fmodels_92',['stl_models',['../parameters.html#stl_models',1,'']]],
  ['stored_20parameter_20conventions_93',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['strang_20splitting_20strang68_20for_20stiff_20bubble_20dynamics_94',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md201',1,'']]],
  ['strang68_20for_20stiff_20bubble_20dynamics_95',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md201',1,'']]],
  ['stress_20poiseuille_20channel_96',['2D Bingham (Yield-Stress) Poiseuille Channel',['../examples.html#autotoc_md238',1,'']]],
  ['stress_20tensor_20viscous_20true_97',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md152',1,'']]],
  ['strong_20scaling_98',['Strong Scaling',['../examples.html#autotoc_md283',1,'']]],
  ['strong_20scaling_99',['Strong scaling',['../expectedPerformance.html#autotoc_md327',1,'']]],
  ['structure_100',['Tag Structure',['../docker.html#autotoc_md135',1,'']]],
  ['structure_20interaction_101',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md166',1,'']]],
  ['structures_102',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['styling_103',['Plot styling',['../visualization.html#autotoc_md586',1,'']]],
  ['sub_20grid_20bubble_20dynamics_20wilfong26_20sec_204_201_104',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md156',1,'']]],
  ['sub_20grid_20bubble_20models_105',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['submitting_20a_20pull_20request_106',['Submitting a Pull Request',['../contributing.html#autotoc_md121',1,'']]],
  ['suite_107',['Running the Test Suite',['../getting-started.html#autotoc_md338',1,'']]],
  ['sum_108',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md441',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_109',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md129',1,'']]],
  ['support_110',['Support',['../docker.html#autotoc_md137',1,'Architecture Support'],['../running.html#autotoc_md496',1,'Building with GPU Support']]],
  ['supported_20compilers_111',['Supported Compilers',['../running.html#autotoc_md498',1,'']]],
  ['supports_112',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['surface_20tension_113',['Surface Tension',['../physics_constraints.html#autotoc_md465',1,'']]],
  ['surface_20tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_114',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md176',1,'']]],
  ['surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_115',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md176',1,'']]],
  ['synchronization_20macros_116',['Synchronization Macros',['../gpuParallelization.html#autotoc_md356',1,'']]],
  ['system_117',['Working with the Precision System',['../contributing.html#autotoc_md110',1,'']]]
];
