var searchData=
[
  ['mach_20number_0',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['macos_1',['macOS',['../getting-started.html#autotoc_md210',1,'Install via Homebrew (macOS)'],['../running.html#autotoc_md342',1,'Using the Homebrew package (macOS)']]],
  ['macro_20api_20documentation_2',['Macro API Documentation',['../gpuParallelization.html#autotoc_md222',1,'']]],
  ['macros_3',['Macros',['../gpuParallelization.html#autotoc_md226',1,'Computation Macros'],['../gpuParallelization.html#autotoc_md228',1,'Data Control Macros'],['../gpuParallelization.html#autotoc_md232',1,'Miscellaneous Macros'],['../gpuParallelization.html#autotoc_md230',1,'Synchronization Macros']]],
  ['magnetohydrodynamics_20mhd_4',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md28',1,'']]],
  ['material’s_5',['5. Fluid Material’s',['../case.html#autotoc_md15',1,'']]],
  ['maximum_20performance_6',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md190',1,'']]],
  ['meanings_7',['Data Type Meanings',['../gpuParallelization.html#autotoc_md223',1,'']]],
  ['merit_3a_20grind_20time_20performance_8',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md198',1,'']]],
  ['meshkov_20instability_202d_9',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md156',1,'']]],
  ['mfc_10',['MFC',['../getting-started.html#autotoc_md212',1,'Building MFC'],['../getting-started.html#autotoc_md209',1,'Fetching MFC']]],
  ['mfc_20documentation_11',['MFC Documentation',['../index.html',1,'']]],
  ['mhd_12',['14. Magnetohydrodynamics (MHD)',['../case.html#autotoc_md28',1,'']]],
  ['mi250x_20gpu_13',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md200',1,'']]],
  ['miscellaneous_20macros_14',['Miscellaneous Macros',['../gpuParallelization.html#autotoc_md232',1,'']]],
  ['mixing_20layer_203d_15',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md181',1,'']]],
  ['model_16',['Model',['../case.html#autotoc_md25',1,'11. Phase Change Model'],['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]],
  ['model_20equations_17',['🔢 Model Equations',['../case_constraints.html#autotoc_md50',1,'']]],
  ['models_18',['Models',['../case_constraints.html#autotoc_md52',1,'💧 Bubble Models'],['../case.html#autotoc_md21',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#autotoc_md47',1,'Bubble Models'],['../case_constraints.html#autotoc_md46',1,'Physics Models']]],
  ['module_20not_20found_20on_20hpc_19',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md410',1,'']]],
  ['mom_5fwrt_20',['mom_wrt',['../parameters.html#autotoc_md310',1,'']]],
  ['mpi_21',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md406',1,'']]],
  ['mpi_20errors_20or_20hangs_22',['MPI errors or hangs',['../troubleshooting.html#autotoc_md416',1,'']]],
  ['multi_20component_20inert_20shock_20tube_23',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md183',1,'']]],
  ['multi_20component_20reactive_20shock_20tube_24',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md145',1,'']]]
];
