var searchData=
[
  ['v_20verbose_0',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['v100_20gpu_1',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md291',1,'']]],
  ['v100_20gpu_20historical_2',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md288',1,'']]],
  ['validate_3',['validate',['../cli-reference.html#validate',1,'']]],
  ['validation_4',['Validation',['../troubleshooting.html#autotoc_md497',1,'Case Validation'],['../examples.html#autotoc_md213',1,'Validation']]],
  ['values_5',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['variable_6',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md110',1,'']]],
  ['variable_20x_20not_20found_7',['&quot;Variable &apos;X&apos; not found&quot;',['../troubleshooting.html#autotoc_md529',1,'']]],
  ['variables_8',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['variables_20ordering_9',['Variables Ordering',['../case.html#autotoc_md36',1,'Conservative Variables Ordering'],['../case.html#autotoc_md37',1,'Primitive Variables Ordering']]],
  ['variants_10',['2.3 Other Model Variants',['../equations.html#autotoc_md144',1,'']]],
  ['vel_5fwrt_11',['vel_wrt',['../parameters.html#vel_wrt',1,'']]],
  ['velocities_12',['Centerline Velocities',['../examples.html#autotoc_md270',1,'']]],
  ['velocity_20and_20dimensional_20consistency_13',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md410',1,'']]],
  ['velocity_20components_20in_20inactive_20dimensions_14',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md411',1,'']]],
  ['velocity_20field_20setup_15',['10. Velocity Field Setup',['../case.html#sec-velocity-field-setup',1,'']]],
  ['verbose_16',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['verbose_20runs_17',['Verbose Runs',['../troubleshooting.html#autotoc_md498',1,'']]],
  ['verbosity_20levels_18',['Verbosity Levels',['../troubleshooting.html#autotoc_md490',1,'']]],
  ['verbosity_20v_20verbose_19',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md78',1,'']]],
  ['verifying_20gpu_20detection_20',['Verifying GPU Detection',['../running.html#autotoc_md460',1,'']]],
  ['via_20apptainer_20singularity_21',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md127',1,'']]],
  ['via_20homebrew_20macos_22',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md297',1,'']]],
  ['video_20generation_23',['Video generation',['../visualization.html#autotoc_md542',1,'']]],
  ['violations_24',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md522',1,'']]],
  ['viscosity_25',['Viscosity',['../physics_constraints.html#autotoc_md436',1,'']]],
  ['viscosity_20parameters_26',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['viscous_20shock_20tube_202d_27',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md251',1,'']]],
  ['viscous_20stress_20tensor_20viscous_20true_28',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md150',1,'']]],
  ['viscous_20true_29',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md150',1,'']]],
  ['visit_30',['Visualizing with VisIt',['../visualization.html#autotoc_md552',1,'']]],
  ['visualization_31',['Examples &amp;amp; Visualization',['../index.html#autotoc_md446',1,'']]],
  ['visualization_32',['visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md534',1,'Flow visualization']]],
  ['visualization_20at_20transitional_20state_33',['Liutex visualization at transitional state',['../examples.html#autotoc_md236',1,'']]],
  ['visualization_20issues_34',['Visualization Issues',['../troubleshooting.html#autotoc_md527',1,'']]],
  ['visualization_20looks_20wrong_20or_20has_20artifacts_35',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md531',1,'']]],
  ['visualization_20on_20pace_20phoenix_36',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md554',1,'']]],
  ['visualization_20with_20mfc_20sh_20viz_37',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md536',1,'']]],
  ['visualizing_20data_20in_20cylindrical_20coordinates_38',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md551',1,'']]],
  ['visualizing_20results_39',['Visualizing Results',['../getting-started.html#autotoc_md304',1,'']]],
  ['visualizing_20with_20paraview_40',['Visualizing with ParaView',['../visualization.html#autotoc_md550',1,'']]],
  ['visualizing_20with_20visit_41',['Visualizing with VisIt',['../visualization.html#autotoc_md552',1,'']]],
  ['viz_42',['viz',['../visualization.html#autotoc_md536',1,'Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;'],['../cli-reference.html#viz',1,'viz']]],
  ['volume_20averaged_20bubble_20model_43',['9.2 Volume-Averaged Bubble Model',['../case.html#autotoc_md28',1,'']]],
  ['volume_20fraction_20sum_44',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md402',1,'']]],
  ['vortex_203d_45',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md271',1,'']]],
  ['vortex_20problem_202d_46',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md254',1,'']]],
  ['vorticity_20output_47',['Vorticity Output',['../physics_constraints.html#autotoc_md442',1,'']]],
  ['vs_20correctness_48',['Performance vs Correctness',['../troubleshooting.html#autotoc_md512',1,'']]]
];
