var searchData=
[
  ['6_0',['6',['../equations.html#autotoc_md164',1,'7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)'],['../equations.html#autotoc_md165',1,'7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)']]],
  ['6_201_201_20method_20of_20classes_20commander89_20ando11_1',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md155',1,'']]],
  ['6_201_202_20rayleigh_20plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_2',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['6_201_203_20keller_20miksis_20bubble_5fmodel_202_20keller80_3',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['6_201_204_20gilmore_20bubble_5fmodel_201_20gilmore52_4',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md158',1,'']]],
  ['6_201_205_20non_20polytropic_20thermal_20model_20polytropic_20false_20preston07_5',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['6_201_206_20qbmm_20moment_20transport_20qbmm_20true_20bryngelson20_6',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['6_201_20euler_20euler_20bubbles_20bubbles_5feuler_20true_7',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md154',1,'']]],
  ['6_202_20euler_20lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_8',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['6_20qbmm_20moment_20transport_20qbmm_20true_20bryngelson20_9',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['6_20simulation_20algorithm_10',['6. Simulation Algorithm',['../case.html#sec-simulation-algorithm',1,'']]],
  ['6_20sub_20grid_20bubble_20dynamics_20wilfong26_20sec_204_201_11',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md153',1,'']]],
  ['6_20zein10_12',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[55]&lt;/a&gt;)',['../equations.html#autotoc_md169',1,'']]],
  ['64m_20grid_20points_13',['64M Grid Points',['../expectedPerformance.html#autotoc_md291',1,'']]]
];
