var searchData=
[
  ['v_20verbose_0',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['v100_20gpu_1',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md275',1,'']]],
  ['v100_20gpu_20historical_2',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md272',1,'']]],
  ['validate_3',['validate',['../cli-reference.html#validate',1,'']]],
  ['validation_4',['Case Validation',['../troubleshooting.html#autotoc_md480',1,'']]],
  ['values_5',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['variable_6',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['variables_7',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md6',1,'']]],
  ['variables_20ordering_8',['Variables Ordering',['../case.html#autotoc_md22',1,'Conservative Variables Ordering'],['../case.html#autotoc_md23',1,'Primitive Variables Ordering']]],
  ['variants_9',['2.3 Other Model Variants',['../equations.html#autotoc_md129',1,'']]],
  ['vel_5fwrt_10',['vel_wrt',['../parameters.html#vel_wrt',1,'']]],
  ['velocities_11',['Centerline Velocities',['../examples.html#autotoc_md254',1,'']]],
  ['velocity_20and_20dimensional_20consistency_12',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md393',1,'']]],
  ['velocity_20components_20in_20inactive_20dimensions_13',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md394',1,'']]],
  ['velocity_20field_20setup_14',['10. Velocity Field Setup',['../case.html#sec-velocity-field-setup',1,'']]],
  ['verbose_15',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['verbose_20runs_16',['Verbose Runs',['../troubleshooting.html#autotoc_md481',1,'']]],
  ['verbosity_20levels_17',['Verbosity Levels',['../troubleshooting.html#autotoc_md473',1,'']]],
  ['verbosity_20v_20verbose_18',['Verbosity (&lt;span class=&quot;tt&quot;&gt;-v, --verbose&lt;/span&gt;)',['../cli-reference.html#autotoc_md63',1,'']]],
  ['verifying_20gpu_20detection_19',['Verifying GPU Detection',['../running.html#autotoc_md443',1,'']]],
  ['via_20apptainer_20singularity_20',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md112',1,'']]],
  ['via_20homebrew_20macos_21',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md281',1,'']]],
  ['violations_22',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md505',1,'']]],
  ['viscosity_23',['Viscosity',['../physics_constraints.html#autotoc_md419',1,'']]],
  ['viscosity_20parameters_24',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['viscous_20shock_20tube_202d_25',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md235',1,'']]],
  ['viscous_20stress_20tensor_20viscous_20true_26',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md135',1,'']]],
  ['viscous_20true_27',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md135',1,'']]],
  ['visit_28',['Visualizing with VisIt',['../visualization.html#autotoc_md514',1,'']]],
  ['visualization_29',['Examples &amp;amp; Visualization',['../index.html#autotoc_md429',1,'']]],
  ['visualization_30',['visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md511',1,'Flow visualization']]],
  ['visualization_20at_20transitional_20state_31',['Liutex visualization at transitional state',['../examples.html#autotoc_md220',1,'']]],
  ['visualization_20on_20pace_20phoenix_32',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md516',1,'']]],
  ['visualizing_20data_20in_20cylindrical_20coordinates_33',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md513',1,'']]],
  ['visualizing_20with_20paraview_34',['Visualizing with Paraview',['../visualization.html#autotoc_md512',1,'']]],
  ['visualizing_20with_20visit_35',['Visualizing with VisIt',['../visualization.html#autotoc_md514',1,'']]],
  ['volume_20averaged_20bubble_20model_36',['9.2 Volume-Averaged Bubble Model',['../case.html#autotoc_md14',1,'']]],
  ['volume_20fraction_20sum_37',['Volume Fraction Sum',['../physics_constraints.html#autotoc_md385',1,'']]],
  ['vortex_203d_38',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md255',1,'']]],
  ['vortex_20problem_202d_39',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md238',1,'']]],
  ['vorticity_20output_40',['Vorticity Output',['../physics_constraints.html#autotoc_md425',1,'']]],
  ['vs_20correctness_41',['Performance vs Correctness',['../troubleshooting.html#autotoc_md495',1,'']]]
];
