var searchData=
[
  ['each_20stage_0',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['elasticity_1',['15. Elasticity',['../case.html#autotoc_md32',1,'']]],
  ['elliptic_20smoothing_2',['Elliptic Smoothing',['../case.html#autotoc_md23',1,'']]],
  ['ensemble_20averaged_20bubble_20model_3',['9.1 Ensemble-Averaged Bubble Model',['../case.html#autotoc_md28',1,'']]],
  ['enumerations_4',['Enumerations',['../case.html#autotoc_md38',1,'']]],
  ['environment_5',['Environment',['../getting-started.html#autotoc_md336',1,'Build Environment'],['../visualization.html#autotoc_md622',1,'Step 1: Setting up your Environment']]],
  ['environment_20setup_6',['Environment Setup',['../running.html#autotoc_md526',1,'']]],
  ['eos_20chemistry_20chemistry_20true_7',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md152',1,'']]],
  ['eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_8',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md151',1,'']]],
  ['eos_20parameter_20sanity_20transformed_20gamma_9',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md456',1,'']]],
  ['eos_20positivity_10',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md453',1,'']]],
  ['equation_20model_20model_5feqns_202_11',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md146',1,'']]],
  ['equation_20model_20model_5feqns_203_12',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['equation_20of_20state_13',['Equation of State',['../contributing.html#autotoc_md109',1,'How to Add an Equation of State'],['../physics_constraints.html#autotoc_md454',1,'Initial States Inside a State-Dependent Equation of State']]],
  ['equation_20of_20state_20selector_14',['Equation of State Selector',['../physics_constraints.html#autotoc_md455',1,'']]],
  ['equation_20selection_15',['Model Equation Selection',['../physics_constraints.html#autotoc_md473',1,'']]],
  ['equations_16',['Equations',['../case_constraints.html#model-equations',1,'🔢 Model Equations'],['../equations.html',1,'Equations'],['../physics_constraints.html#autotoc_md472',1,'Model Equations']]],
  ['equations_20of_20state_17',['3. Equations of State',['../equations.html#autotoc_md150',1,'']]],
  ['equations_20reference_18',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md140',1,'']]],
  ['errors_19',['Errors',['../troubleshooting.html#autotoc_md581',1,'Common Build Errors'],['../troubleshooting.html#autotoc_md588',1,'Common Runtime Errors']]],
  ['errors_20',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['errors_20or_20hangs_21',['MPI errors or hangs',['../troubleshooting.html#autotoc_md592',1,'']]],
  ['euler_20bubble_20model_22',['Euler-Euler Bubble Model',['../physics_constraints.html#autotoc_md479',1,'']]],
  ['euler_20bubbles_20bubbles_5feuler_20true_23',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['euler_20euler_20bubble_20model_24',['Euler-Euler Bubble Model',['../physics_constraints.html#autotoc_md479',1,'']]],
  ['euler_20euler_20bubbles_20bubbles_5feuler_20true_25',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['euler_20lagrange_20bubble_20model_26',['Euler-Lagrange Bubble Model',['../physics_constraints.html#autotoc_md481',1,'']]],
  ['euler_20lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_27',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[31]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['evolved_20state_28',['Evolved State',['../examples.html#autotoc_md236',1,'Evolved State'],['../examples.html#autotoc_md245',1,'Evolved State'],['../examples.html#autotoc_md307',1,'Evolved State']]],
  ['exact_20riemann_5fsolver_203_29',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['example_30',['Example',['../examples.html#autotoc_md303',1,'2D Hardcodied IC Example'],['../examples.html#autotoc_md230',1,'Example']]],
  ['example_20case_31',['Running an Example Case',['../getting-started.html#autotoc_md340',1,'']]],
  ['example_20cases_32',['Example Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md214',1,'Example Cases']]],
  ['example_20runs_33',['Example Runs',['../running.html#autotoc_md541',1,'']]],
  ['example_20tags_34',['Example Tags',['../docker.html#autotoc_md138',1,'']]],
  ['example_3a_20non_20dimensionalizing_20a_20bubble_20case_35',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['examples_36',['Examples',['../case_constraints.html#autotoc_md45',1,'🔴 Advanced Examples'],['../case_constraints.html#autotoc_md44',1,'🟡 Intermediate Examples'],['../case_constraints.html#autotoc_md43',1,'🟢 Beginner Examples'],['../running.html#autotoc_md535',1,'Examples'],['../equations.html#sec-nondim-example',1,'Worked Examples']]],
  ['examples_20visualization_37',['Examples &amp;amp; Visualization',['../index.html#autotoc_md513',1,'']]],
  ['exchange_38',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md113',1,'']]],
  ['execution_39',['Execution',['../running.html#autotoc_md532',1,'Batch Execution'],['../running.html#autotoc_md520',1,'Interactive Execution'],['../troubleshooting.html#autotoc_md571',1,'Serial Test Execution']]],
  ['exploring_20available_20data_40',['Exploring available data',['../visualization.html#autotoc_md605',1,'']]],
  ['extend_20mpi_20halo_20exchange_41',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md113',1,'']]],
  ['extents_20specified_42',['Domain Extents Specified',['../physics_constraints.html#autotoc_md466',1,'']]],
  ['extrusion_43',['IC Extrusion',['../physics_constraints.html#autotoc_md509',1,'']]],
  ['extrusion_20file_20parameters_44',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md510',1,'']]]
];
