var searchData=
[
  ['facing_20step_202d_0',['Facing Step 2D',['../examples.html#autotoc_md211',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md227',1,'Forward Facing Step (2D)']]],
  ['failed_1',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md452',1,'']]],
  ['fails_2',['Fails',['../troubleshooting.html#autotoc_md420',1,'Build Fails?'],['../troubleshooting.html#autotoc_md421',1,'Run Fails?'],['../troubleshooting.html#autotoc_md422',1,'Test Fails?']]],
  ['fails_20with_20gpu_20openacc_20errors_3',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md453',1,'']]],
  ['failures_4',['Failures',['../contributing.html#autotoc_md147',1,'Common CI Failures'],['../troubleshooting.html#autotoc_md442',1,'Understanding Test Failures']]],
  ['families_5',['Parameter Families',['../parameters.html#autotoc_md289',1,'']]],
  ['feature_20compatibility_6',['Feature Compatibility',['../case_constraints.html#autotoc_md45',1,'📊 Feature Compatibility'],['../case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['fetching_20mfc_7',['Fetching MFC',['../getting-started.html#autotoc_md250',1,'']]],
  ['fewer_20ranks_8',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md435',1,'']]],
  ['field_20setup_9',['10. Velocity Field Setup',['../case.html#autotoc_md24',1,'']]],
  ['figure_20of_20merit_3a_20grind_20time_20performance_10',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md239',1,'']]],
  ['files_11',['Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md1',1,'Case Files'],['../troubleshooting.html#autotoc_md441',1,'Regenerating Golden Files']]],
  ['final_20condition_12',['Final Condition',['../examples.html#autotoc_md202',1,'Final Condition'],['../examples.html#autotoc_md204',1,'Final Condition'],['../examples.html#autotoc_md223',1,'Final Condition'],['../examples.html#autotoc_md226',1,'Final Condition']]],
  ['final_20condition_20and_20linear_20theory_13',['Final Condition and Linear Theory',['../examples.html#autotoc_md183',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md217',1,'Final Condition and Linear Theory']]],
  ['final_20condition_20density_14',['Final Condition Density',['../examples.html#autotoc_md212',1,'Final Condition (Density)'],['../examples.html#autotoc_md228',1,'Final Condition (Density)']]],
  ['final_20conditions_15',['Density Initial and Final Conditions',['../examples.html#autotoc_md188',1,'']]],
  ['final_20time_16',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md169',1,'']]],
  ['find_20a_20fortran_20compiler_17',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['find_20mpi_18',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md450',1,'']]],
  ['first_20blocks_20all_20other_20jobs_19',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['flags_20',['Flags',['../cli-reference.html#autotoc_md107',1,'Build Configuration Flags'],['../troubleshooting.html#autotoc_md415',1,'Debugging Flags'],['../expectedPerformance.html#autotoc_md234',1,'Other Optimization Flags'],['../troubleshooting.html#autotoc_md416',1,'Profiling Flags']]],
  ['flow_21',['Flow',['../gpuParallelization.html#autotoc_md265',1,'Data Flow'],['../contributing.html#autotoc_md115',1,'Simulation Data Flow']]],
  ['flow_20visualization_22',['Flow visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md463',1,'Flow visualization']]],
  ['fluid_20material’s_23',['5. Fluid Material’s',['../case.html#autotoc_md15',1,'']]],
  ['fluid_5fpp_24',['fluid_pp',['../parameters.html#autotoc_md297',1,'']]],
  ['fluid_5frho_25',['fluid_rho',['../parameters.html#autotoc_md340',1,'']]],
  ['flux_5fwrt_26',['flux_wrt',['../parameters.html#autotoc_md351',1,'']]],
  ['for_20gpus_27',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md275',1,'']]],
  ['for_20optimization_28',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md235',1,'']]],
  ['for_20portability_29',['For Portability',['../docker.html#autotoc_md159',1,'']]],
  ['forces_30',['13. Body Forces',['../case.html#autotoc_md27',1,'']]],
  ['format_31',['format',['../cli-reference.html#autotoc_md87',1,'']]],
  ['formatted_20output_32',['7. Formatted Output',['../case.html#autotoc_md20',1,'']]],
  ['fortran_20compiler_33',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['fortran_20module_34',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['forward_20facing_20step_202d_35',['Forward Facing Step (2D)',['../examples.html#autotoc_md227',1,'']]],
  ['found_20on_20hpc_36',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md454',1,'']]],
  ['fypp_20and_20gpu_37',['Fypp and GPU',['../contributing.html#autotoc_md131',1,'']]],
  ['fypp_20preprocessing_20failed_38',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md452',1,'']]]
];
