var searchData=
[
  ['pace_20paraview_20server_0',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md619',1,'']]],
  ['pace_20phoenix_1',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md616',1,'']]],
  ['pack_2',['packer pack',['../cli-reference.html#autotoc_md60',1,'']]],
  ['package_20macos_3',['Using the Homebrew package (macOS)',['../running.html#autotoc_md513',1,'']]],
  ['packer_4',['packer',['../cli-reference.html#packer',1,'']]],
  ['packer_20compare_5',['packer compare',['../cli-reference.html#autotoc_md61',1,'']]],
  ['packer_20pack_6',['packer pack',['../cli-reference.html#autotoc_md60',1,'']]],
  ['papers_7',['Papers',['../papers.html',1,'Papers'],['../papers.html#autotoc_md374',1,'Papers']]],
  ['parallel_20loop_8',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md109',1,'']]],
  ['parallelization_9',['Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md347',1,'GPU Parallelization'],['../architecture.html#autotoc_md12',1,'MPI Parallelization']]],
  ['parameter_10',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md108',1,'']]],
  ['parameter_20constraint_20violations_11',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md584',1,'']]],
  ['parameter_20conventions_12',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['parameter_20descriptions_13',['Parameter Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['parameter_20families_14',['Parameter Families',['../parameters.html#autotoc_md377',1,'']]],
  ['parameter_20lookup_15',['Parameter Lookup',['../getting-started.html#autotoc_md344',1,'']]],
  ['parameter_20reference_16',['📖 Quick Parameter Reference',['../case_constraints.html#quick-parameter-reference',1,'']]],
  ['parameter_20sanity_20transformed_20gamma_17',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md453',1,'']]],
  ['parameters_18',['Parameters',['../parameters.html',1,'Case Parameters'],['../parameters.html#autotoc_md375',1,'Case Parameters'],['../physics_constraints.html#autotoc_md505',1,'IC Extrusion File Parameters'],['../equations.html#sec-nondim-inputs',1,'Non-Dimensionalization of Input Parameters'],['../case.html#autotoc_md18',1,'Parameters'],['../equations.html#sec-two-viscosities',1,'Two Different Viscosity Parameters']]],
  ['parameters_19',['parameters',['../examples.html#autotoc_md216',1,'Geometry and parameters'],['../examples.html#autotoc_md227',1,'Regime and parameters'],['../examples.html#autotoc_md267',1,'Regime and parameters'],['../examples.html#autotoc_md272',1,'Regime and parameters'],['../examples.html#autotoc_md299',1,'Regime and parameters'],['../examples.html#autotoc_md308',1,'Regime and parameters']]],
  ['parameters_20with_20bubbles_20',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['params_21',['params',['../cli-reference.html#params',1,'']]],
  ['paraview_22',['Visualizing with ParaView',['../visualization.html#autotoc_md612',1,'']]],
  ['paraview_20server_23',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md619',1,'']]],
  ['particle_20clouds_24',['Particle Clouds',['../case.html#autotoc_md25',1,'']]],
  ['particle_5fcloud_25',['particle_cloud',['../parameters.html#particle_cloud',1,'']]],
  ['patch_20initial_20condition_20constraints_26',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md454',1,'']]],
  ['patch_20types_27',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['patch_20types_28',['Patch types',['../case.html#patch-types',1,'']]],
  ['patch_20within_20domain_29',['Patch Within Domain',['../physics_constraints.html#autotoc_md463',1,'']]],
  ['patch_5fbc_30',['patch_bc',['../parameters.html#patch_bc',1,'']]],
  ['patch_5fib_31',['patch_ib',['../parameters.html#patch_ib',1,'']]],
  ['patch_5ficpp_32',['patch_icpp',['../parameters.html#patch_icpp',1,'']]],
  ['patches_33',['Patches',['../case.html#sec-patches',1,'3. Patches'],['../case.html#sec-immersed-boundary-patches',1,'4. Immersed Boundary Patches'],['../case.html#boundary-condition-patches',1,'Boundary Condition Patches'],['../case.html#autotoc_md21',1,'Hard Coded Patches']]],
  ['patterns_34',['Patterns',['../case_constraints.html#common-configuration-patterns',1,'🚀 Common Configuration Patterns'],['../parameters.html#autotoc_md379',1,'Patterns'],['../parameters.html#autotoc_md381',1,'Patterns'],['../parameters.html#autotoc_md383',1,'Patterns'],['../parameters.html#autotoc_md385',1,'Patterns'],['../parameters.html#autotoc_md387',1,'Patterns'],['../parameters.html#autotoc_md389',1,'Patterns'],['../parameters.html#autotoc_md391',1,'Patterns'],['../parameters.html#autotoc_md393',1,'Patterns'],['../parameters.html#autotoc_md395',1,'Patterns'],['../parameters.html#autotoc_md397',1,'Patterns'],['../parameters.html#autotoc_md399',1,'Patterns'],['../parameters.html#autotoc_md401',1,'Patterns'],['../parameters.html#autotoc_md403',1,'Patterns'],['../parameters.html#autotoc_md405',1,'Patterns'],['../parameters.html#autotoc_md407',1,'Patterns'],['../parameters.html#autotoc_md409',1,'Patterns'],['../parameters.html#autotoc_md411',1,'Patterns'],['../parameters.html#autotoc_md413',1,'Patterns'],['../parameters.html#autotoc_md418',1,'Patterns'],['../parameters.html#autotoc_md420',1,'Patterns'],['../parameters.html#autotoc_md422',1,'Patterns'],['../parameters.html#autotoc_md424',1,'Patterns'],['../parameters.html#autotoc_md426',1,'Patterns'],['../parameters.html#autotoc_md428',1,'Patterns'],['../parameters.html#autotoc_md433',1,'Patterns'],['../parameters.html#autotoc_md435',1,'Patterns'],['../parameters.html#autotoc_md437',1,'Patterns'],['../parameters.html#autotoc_md439',1,'Patterns']]],
  ['pdes_35',['2. Governing PDEs',['../equations.html#autotoc_md146',1,'']]],
  ['perfectly_20stirred_20reactor_36',['Perfectly Stirred Reactor',['../examples.html#autotoc_md240',1,'']]],
  ['performance_37',['Performance',['../expectedPerformance.html#autotoc_md315',1,'Achieving Maximum Performance'],['../expectedPerformance.html',1,'Performance'],['../expectedPerformance.html#autotoc_md313',1,'Performance']]],
  ['performance_38',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md323',1,'']]],
  ['performance_20checklist_39',['Performance Checklist',['../expectedPerformance.html#autotoc_md320',1,'']]],
  ['performance_20nvidia_20uvm_40',['20. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md36',1,'']]],
  ['performance_20profiling_41',['Performance Profiling',['../troubleshooting.html#autotoc_md571',1,'']]],
  ['performance_20test_42',['Scaling and Performance test',['../examples.html#autotoc_md242',1,'']]],
  ['performance_20vs_20correctness_43',['Performance vs Correctness',['../troubleshooting.html#autotoc_md574',1,'']]],
  ['phase_20change_44',['Phase Change',['../physics_constraints.html#autotoc_md483',1,'']]],
  ['phase_20change_20model_45',['11. Phase Change Model',['../case.html#sec-phase-change',1,'']]],
  ['phase_20change_20relax_20true_20wilfong26_20sec_204_201_203_46',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md171',1,'']]],
  ['phase_20pipeline_47',['Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md87',1,'Three-Phase Pipeline']]],
  ['phase_20reactive_20burn_48',['Condensed-Phase Reactive Burn',['../physics_constraints.html#autotoc_md502',1,'']]],
  ['phoenix_49',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md616',1,'']]],
  ['physics_50',['Physics',['../architecture.html#autotoc_md13',1,'Adding New Physics'],['../physics_constraints.html#autotoc_md474',1,'Bubble Physics']]],
  ['physics_51',['Governing physics',['../examples.html#autotoc_md268',1,'']]],
  ['physics_20and_20analytic_20solution_52',['physics and analytic solution',['../examples.html#autotoc_md228',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md273',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md300',1,'Governing physics and analytic solution'],['../examples.html#autotoc_md309',1,'Governing physics and analytic solution']]],
  ['physics_20and_20model_20consistency_53',['Physics and Model Consistency',['../contributing.html#autotoc_md102',1,'']]],
  ['physics_20constraints_54',['Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'How to Document Physics Constraints'],['../physics_constraints.html',1,'Physics Constraints']]],
  ['physics_20constraints_20reference_55',['Physics Constraints Reference',['../physics_constraints.html#autotoc_md449',1,'']]],
  ['physics_20models_56',['Physics Models',['../architecture.html#autotoc_md7',1,'Physics Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['physics_20warnings_57',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['pipeline_58',['Pipeline',['../contributing.html#autotoc_md119',1,'CI Pipeline'],['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md87',1,'Three-Phase Pipeline']]],
  ['pitfalls_59',['Common Pitfalls',['../contributing.html#autotoc_md97',1,'']]],
  ['playbook_60',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_61',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[29]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['plesset49_62',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[29]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['plot_20styling_63',['Plot styling',['../visualization.html#autotoc_md608',1,'']]],
  ['point_202d_64',['2D Triple Point (2D)',['../examples.html#autotoc_md284',1,'']]],
  ['points_65',['Points',['../expectedPerformance.html#autotoc_md330',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md331',1,'64M Grid Points']]],
  ['poiseuille_20channel_66',['Poiseuille Channel',['../examples.html#autotoc_md298',1,'2D Bingham (Yield-Stress) Poiseuille Channel'],['../examples.html#autotoc_md271',1,'2D General Herschel-Bulkley Poiseuille Channel'],['../examples.html#autotoc_md215',1,'2D IBM-Walled Power-Law Poiseuille Channel'],['../examples.html#autotoc_md307',1,'2D Power-Law (Shear-Thickening) Poiseuille Channel'],['../examples.html#autotoc_md226',1,'2D Power-Law (Shear-Thinning) Poiseuille Channel']]],
  ['polytropic_20false_20preston07_67',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['polytropic_20thermal_20model_20polytropic_20false_20preston07_68',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['portability_69',['Portability',['../contributing.html#autotoc_md104',1,'Compiler Portability'],['../docker.html#autotoc_md134',1,'For Portability'],['../docker.html#autotoc_md131',1,'Portability']]],
  ['positivity_70',['Stiffened EOS Positivity',['../physics_constraints.html#autotoc_md452',1,'']]],
  ['post_20process_71',['Testing Post Process',['../testing.html#autotoc_md539',1,'']]],
  ['post_20processing_72',['Post-Processing',['../physics_constraints.html#autotoc_md497',1,'']]],
  ['post_20processing_20output_20variable_73',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['power_20law_20poiseuille_20channel_74',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md215',1,'']]],
  ['power_20law_20shear_20thickening_20poiseuille_20channel_75',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md307',1,'']]],
  ['power_20law_20shear_20thinning_20poiseuille_20channel_76',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md226',1,'']]],
  ['power9_20cpu_77',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md332',1,'']]],
  ['power9_20cpu_20historical_78',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md327',1,'']]],
  ['pre_20process_79',['Pre-Process',['../architecture.html#autotoc_md11',1,'']]],
  ['precheck_80',['precheck',['../cli-reference.html#precheck',1,'']]],
  ['precision_20and_20type_20safety_81',['Precision and Type Safety',['../contributing.html#autotoc_md99',1,'']]],
  ['precision_20system_82',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['preprocessing_20failed_83',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md579',1,'']]],
  ['preston07_84',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['primitive_20variables_85',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['primitive_20variables_20ordering_86',['Primitive Variables Ordering',['../case.html#autotoc_md41',1,'']]],
  ['probe_87',['probe',['../parameters.html#probe',1,'']]],
  ['problem_201d_88',['problem 1D',['../examples.html#autotoc_md258',1,'Lax shock tube problem (1D)'],['../examples.html#autotoc_md304',1,'Shu-Osher problem (1D)'],['../examples.html#autotoc_md223',1,'Titarev-Toro problem (1D)']]],
  ['problem_202d_89',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md251',1,'']]],
  ['problem_202d_90',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md261',1,'']]],
  ['process_91',['Process',['../architecture.html#autotoc_md11',1,'Pre-Process'],['../testing.html#autotoc_md539',1,'Testing Post Process']]],
  ['processing_92',['Post-Processing',['../physics_constraints.html#autotoc_md497',1,'']]],
  ['processing_20output_20variable_93',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['profiling_94',['Profiling',['../troubleshooting.html#autotoc_md573',1,'AMD GPU Profiling'],['../running.html#autotoc_md523',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md572',1,'NVIDIA GPU Profiling'],['../troubleshooting.html#autotoc_md571',1,'Performance Profiling']]],
  ['profiling_20flags_95',['Profiling Flags',['../troubleshooting.html#autotoc_md543',1,'']]],
  ['profiling_20for_20optimization_96',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md319',1,'']]],
  ['pt_20relaxation_20relax_5fmodel_205_20saurel08_97',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[44]&lt;/a&gt;)',['../equations.html#autotoc_md172',1,'']]],
  ['ptg_20relaxation_20relax_5fmodel_206_20zein10_98',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[60]&lt;/a&gt;)',['../equations.html#autotoc_md173',1,'']]],
  ['pull_20request_99',['Submitting a Pull Request',['../contributing.html#autotoc_md124',1,'']]],
  ['python_20toolchain_100',['Python Toolchain',['../contributing.html#autotoc_md103',1,'']]]
];
