var searchData=
[
  ['o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['of_20classes_20commander89_20ando11_1',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['of_20input_20parameters_2',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['of_20merit_3a_20grind_20time_20performance_3',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md322',1,'']]],
  ['of_20primitive_20variables_4',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['of_20state_5',['3. Equations of State',['../equations.html#autotoc_md149',1,'']]],
  ['omega_5fwrt_6',['omega_wrt',['../parameters.html#omega_wrt',1,'']]],
  ['on_20gpus_7',['on GPUs',['../running.html#autotoc_md516',1,'Running on GPUs'],['../running.html#autotoc_md518',1,'Running on GPUs']]],
  ['on_20hpc_8',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md580',1,'']]],
  ['on_20non_20conservative_20term_20implementation_9',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md197',1,'']]],
  ['on_20pace_20phoenix_10',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md615',1,'']]],
  ['on_20running_20containers_11',['Details on Running Containers',['../docker.html#autotoc_md128',1,'']]],
  ['openacc_20errors_12',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md579',1,'']]],
  ['openacc_20options_13',['OpenACC Options',['../gpuParallelization.html#autotoc_md367',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md370',1,'NVHPC OpenACC Options']]],
  ['openmp_20options_14',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md371',1,'']]],
  ['openmp_20tools_15',['OpenMP tools',['../gpuParallelization.html#autotoc_md364',1,'']]],
  ['optimization_16',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md318',1,'']]],
  ['optimization_17',['When to use case optimization',['../expectedPerformance.html#autotoc_md316',1,'']]],
  ['optimization_20flags_18',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md317',1,'']]],
  ['optimization_20recommended_19',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md315',1,'']]],
  ['option_20reference_20',['Complete option reference',['../visualization.html#autotoc_md609',1,'']]],
  ['optional_20accepting_20command_20line_20arguments_21',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['options_22',['Options',['../running.html#autotoc_md528',1,'Batch Options'],['../cli-reference.html#autotoc_md77',1,'Common Options'],['../gpuParallelization.html#autotoc_md366',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md367',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md368',1,'NVHPC Compiler Options'],['../gpuParallelization.html#autotoc_md369',1,'NVHPC General Options'],['../gpuParallelization.html#autotoc_md370',1,'NVHPC OpenACC Options'],['../gpuParallelization.html#autotoc_md371',1,'NVHPC OpenMP Options']]],
  ['options_23',['Rendering options',['../visualization.html#autotoc_md601',1,'']]],
  ['or_20hangs_24',['MPI errors or hangs',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['or_20has_20artifacts_25',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md592',1,'']]],
  ['or_20hypoelasticity_26',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md196',1,'']]],
  ['or_20silo_5fhdf5_20directory_20found_27',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md589',1,'']]],
  ['ordering_28',['Ordering',['../case.html#autotoc_md40',1,'Conservative Variables Ordering'],['../case.html#autotoc_md41',1,'Primitive Variables Ordering']]],
  ['osher_20problem_201d_29',['Shu-Osher problem (1D)',['../examples.html#autotoc_md301',1,'']]],
  ['other_20commands_30',['Other Commands',['../cli-reference.html#autotoc_md75',1,'']]],
  ['other_20jobs_31',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md118',1,'']]],
  ['other_20model_20variants_32',['2.3 Other Model Variants',['../equations.html#autotoc_md147',1,'']]],
  ['other_20optimization_20flags_33',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md317',1,'']]],
  ['out_34',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['output_35',['Output',['../case.html#sec-formatted-output',1,'7. Formatted Output'],['../physics_constraints.html#autotoc_md498',1,'FFT Output'],['../physics_constraints.html#autotoc_md497',1,'Vorticity Output']]],
  ['output_36',['Serial data output',['../visualization.html#autotoc_md614',1,'']]],
  ['output_20location_37',['Test Output Location',['../troubleshooting.html#autotoc_md566',1,'']]],
  ['output_20variable_38',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md113',1,'']]],
  ['overview_39',['Overview',['../equations.html#autotoc_md141',1,'1. Overview'],['../contributing.html#autotoc_md84',1,'Architecture Overview'],['../cli-reference.html#autotoc_md48',1,'Overview'],['../parameters.html#autotoc_md375',1,'Overview']]]
];
