var searchData=
[
  ['gamma_0',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md379',1,'']]],
  ['gas_20eos_20chemistry_20chemistry_20true_1',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md132',1,'']]],
  ['gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_2',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md131',1,'']]],
  ['gas_20jet_202d_3',['Gas Jet (2D)',['../examples.html#autotoc_md230',1,'']]],
  ['gate_20runs_20first_20blocks_20all_20other_20jobs_4',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md100',1,'']]],
  ['general_5',['general',['../parameters.html#general',1,'']]],
  ['general_20options_6',['General Options',['../gpuParallelization.html#autotoc_md308',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md311',1,'NVHPC General Options']]],
  ['generalized_20characteristic_20boundary_20conditions_7',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md21',1,'']]],
  ['generalized_20riemann_20igr_8',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md411',1,'']]],
  ['generate_9',['generate',['../cli-reference.html#generate',1,'']]],
  ['geometric_20regularization_20igr_20true_20wilfong25a_10',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['geometry_11',['Geometry',['../physics_constraints.html#autotoc_md386',1,'Domain and Geometry'],['../case_constraints.html#compat-geometry',1,'Geometry']]],
  ['getting_20help_12',['Getting Help',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['getting_20set_20up_13',['Getting Set Up',['../contributing.html#autotoc_md66',1,'']]],
  ['getting_20started_14',['Getting Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md278',1,'Getting Started'],['../index.html#autotoc_md425',1,'Getting Started']]],
  ['gilmore_20bubble_5fmodel_201_20gilmore52_15',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md143',1,'']]],
  ['gilmore52_16',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md143',1,'']]],
  ['golden_20files_17',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md487',1,'']]],
  ['gottlieb98_18',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md181',1,'']]],
  ['governing_20pdes_19',['2. Governing PDEs',['../equations.html#autotoc_md125',1,'']]],
  ['gpu_20',['GPU',['../expectedPerformance.html#autotoc_md270',1,'AMD MI250X GPU'],['../contributing.html#autotoc_md86',1,'Fypp and GPU'],['../expectedPerformance.html#autotoc_md271',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md274',1,'NVIDIA V100 GPU']]],
  ['gpu_20arrays_21',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['gpu_20detection_22',['Verifying GPU Detection',['../running.html#autotoc_md441',1,'']]],
  ['gpu_20not_20detected_23',['GPU not detected',['../troubleshooting.html#autotoc_md505',1,'']]],
  ['gpu_20openacc_20errors_24',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md499',1,'']]],
  ['gpu_20parallel_20loop_25',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['gpu_20parallelization_26',['GPU Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md290',1,'GPU Parallelization']]],
  ['gpu_20profiling_27',['GPU Profiling',['../troubleshooting.html#autotoc_md492',1,'AMD GPU Profiling'],['../running.html#autotoc_md442',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md491',1,'NVIDIA GPU Profiling']]],
  ['gpu_20support_28',['Building with GPU Support',['../running.html#autotoc_md437',1,'']]],
  ['gpus_29',['GPUs',['../running.html#autotoc_md444',1,'AMD GPUs'],['../gpuParallelization.html#autotoc_md304',1,'Debugging Tools and Tips for GPUs'],['../running.html#autotoc_md443',1,'NVIDIA GPUs'],['../running.html#autotoc_md436',1,'Running on GPUs'],['../running.html#autotoc_md438',1,'Running on GPUs']]],
  ['green_20vortex_203d_30',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md254',1,'']]],
  ['grid_20bubble_20dynamics_20wilfong26_20sec_204_201_31',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md138',1,'']]],
  ['grid_20bubble_20models_32',['9. Sub-grid Bubble Models',['../case.html#sec-bubble-models',1,'']]],
  ['grid_20points_33',['Grid Points',['../expectedPerformance.html#autotoc_md275',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md276',1,'64M Grid Points']]],
  ['grind_20time_20performance_34',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md268',1,'']]],
  ['gui_35',['Docker Desktop GUI',['../docker.html#autotoc_md108',1,'']]],
  ['guide_36',['Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md24',1,'Case Creator Guide'],['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md459',1,'Troubleshooting Guide']]],
  ['guidelines_37',['Soft Guidelines',['../contributing.html#autotoc_md76',1,'']]],
  ['guides_38',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]]
];
