var searchData=
[
  ['i_20o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_1',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['ib_5fairfoil_2',['ib_airfoil',['../parameters.html#ib_airfoil',1,'']]],
  ['ibm_20bow_20shock_203d_3',['IBM Bow Shock (3D)',['../examples.html#autotoc_md262',1,'']]],
  ['ibm_20cfl_20dt_202d_4',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md269',1,'']]],
  ['ibm_20power9_20cpu_5',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md333',1,'']]],
  ['ibm_20power9_20cpu_20historical_6',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md328',1,'']]],
  ['ibm_20walled_20power_20law_20poiseuille_20channel_7',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md228',1,'']]],
  ['ic_20example_8',['2D Hardcodied IC Example',['../examples.html#autotoc_md216',1,'']]],
  ['ic_20extrusion_9',['IC Extrusion',['../physics_constraints.html#autotoc_md487',1,'']]],
  ['ic_20extrusion_20file_20parameters_10',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md488',1,'']]],
  ['ideal_20gas_20eos_20chemistry_20chemistry_20true_11',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md152',1,'']]],
  ['ideal_20mhd_20mhd_20true_20wilfong26_20sec_204_201_209_12',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md181',1,'']]],
  ['igr_13',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md471',1,'']]],
  ['igr_20reconstruction_14',['IGR Reconstruction',['../equations.html#autotoc_md194',1,'']]],
  ['igr_20true_20wilfong25a_15',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['images_16',['Base Images',['../docker.html#autotoc_md136',1,'']]],
  ['immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_17',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['immersed_20boundary_20patch_20types_18',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['immersed_20boundary_20patches_19',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['in_20cylindrical_20coordinates_20',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md596',1,'']]],
  ['in_20dimensions_20out_21',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['in_20inactive_20dimensions_22',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md452',1,'']]],
  ['inactive_20dimensions_23',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md452',1,'']]],
  ['indexing_24',['Array Bounds and Indexing',['../contributing.html#autotoc_md97',1,'']]],
  ['inert_20shock_20tube_25',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md300',1,'']]],
  ['information_20geometric_20regularization_20igr_20true_20wilfong25a_26',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md184',1,'']]],
  ['infrastructure_27',['Infrastructure',['../architecture.html#autotoc_md10',1,'']]],
  ['initial_20and_20final_20conditions_28',['Density Initial and Final Conditions',['../examples.html#autotoc_md222',1,'']]],
  ['initial_20condition_29',['Initial Condition',['../examples.html#autotoc_md226',1,'Initial Condition'],['../examples.html#autotoc_md267',1,'Initial Condition'],['../examples.html#autotoc_md301',1,'Initial Condition'],['../examples.html#autotoc_md304',1,'Initial Condition'],['../examples.html#autotoc_md309',1,'Initial Condition'],['../examples.html#autotoc_md312',1,'Initial Condition']]],
  ['initial_20condition_20and_20result_30',['Initial Condition and Result',['../examples.html#autotoc_md217',1,'']]],
  ['initial_20condition_20constraints_31',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md440',1,'']]],
  ['initial_20state_32',['Initial State',['../examples.html#autotoc_md219',1,'Initial State'],['../examples.html#autotoc_md238',1,'Initial State'],['../examples.html#autotoc_md277',1,'Initial State']]],
  ['input_20parameters_33',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['instability_202d_34',['Instability 2D',['../examples.html#autotoc_md218',1,'Kelvin-Helmholtz Instability (2D)'],['../examples.html#autotoc_md287',1,'Rayleigh-Taylor Instability (2D)'],['../examples.html#autotoc_md276',1,'Richtmyer-Meshkov Instability (2D)']]],
  ['instability_203d_35',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md292',1,'']]],
  ['install_20via_20homebrew_20macos_36',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md336',1,'']]],
  ['integral_37',['integral',['../parameters.html#integral',1,'']]],
  ['integration_38',['15.3 Time Integration',['../equations.html#autotoc_md200',1,'']]],
  ['interaction_39',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md168',1,'']]],
  ['interactive_40',['interactive',['../cli-reference.html#interactive',1,'']]],
  ['interactive_20execution_41',['Interactive Execution',['../running.html#autotoc_md498',1,'']]],
  ['interactive_20mode_42',['Interactive mode',['../visualization.html#autotoc_md589',1,'']]],
  ['interactive_20shell_43',['Interactive Shell',['../docker.html#autotoc_md132',1,'']]],
  ['intermediate_20examples_44',['🟡 Intermediate Examples',['../case_constraints.html#autotoc_md43',1,'']]],
  ['is_20required_20to_20read_20silo_20hdf5_20files_45',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md575',1,'']]],
  ['isentropic_20vortex_20problem_202d_46',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md289',1,'']]],
  ['isolating_20issues_47',['Isolating Issues',['../troubleshooting.html#autotoc_md538',1,'']]],
  ['issues_48',['Issues',['../troubleshooting.html#autotoc_md538',1,'Isolating Issues'],['../troubleshooting.html#autotoc_md572',1,'Visualization Issues']]],
  ['iterative_20generalized_20riemann_20igr_49',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md471',1,'']]]
];
