var searchData=
[
  ['walled_20power_20law_20poiseuille_20channel_0',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md309',1,'']]],
  ['warnings_1',['⚠️ Physics Warnings',['../case_constraints.html#physics-warnings',1,'']]],
  ['weak_20scaling_2',['Weak Scaling',['../examples.html#autotoc_md245',1,'']]],
  ['weak_20scaling_3',['Weak scaling',['../expectedPerformance.html#autotoc_md363',1,'']]],
  ['weak_20scaling_4',['GPU weak scaling',['../expectedPerformance.html#autotoc_md364',1,'']]],
  ['weno_20reconstruction_5',['WENO Reconstruction',['../physics_constraints.html#autotoc_md536',1,'']]],
  ['weno_20weno_5forder_203_205_207_6',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md194',1,'']]],
  ['weno_5forder_203_205_207_7',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md194',1,'']]],
  ['what_20happens_20at_20each_20stage_8',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['what_20the_20sweep_20shows_9',['What the sweep shows',['../examples.html#autotoc_md241',1,'']]],
  ['when_20ranks_20are_20not_20cubes_10',['Automatic &lt;span class=&quot;tt&quot;&gt;ib_neighborhood_radius&lt;/span&gt; when ranks are not cubes',['../examples.html#autotoc_md338',1,'']]],
  ['when_20to_20use_20case_20optimization_11',['When to use case optimization',['../expectedPerformance.html#autotoc_md356',1,'']]],
  ['whole_20image_20device_20codegen_20instability_20worked_20around_20in_20the_20build_12',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['why_20a_20zero_20reference_20check_20is_20not_20available_20here_13',['Why a zero-reference check is not available here',['../examples.html#autotoc_md242',1,'']]],
  ['why_20it_20matters_20beyond_20tidiness_14',['Why it matters beyond tidiness',['../examples.html#autotoc_md271',1,'']]],
  ['wilfong25a_15',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['wilfong26_20sec_202_202_16',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[35]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md152',1,'']]],
  ['wilfong26_20sec_202_203_17',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md159',1,'']]],
  ['wilfong26_20sec_204_201_18',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md161',1,'']]],
  ['wilfong26_20sec_204_201_201_19',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md213',1,'']]],
  ['wilfong26_20sec_204_201_2010_20',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md184',1,'']]],
  ['wilfong26_20sec_204_201_203_21',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md174',1,'']]],
  ['wilfong26_20sec_204_201_206_22',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md172',1,'']]],
  ['wilfong26_20sec_204_201_207_23',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md178',1,'']]],
  ['wilfong26_20sec_204_201_208_24',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md180',1,'']]],
  ['wilfong26_20sec_204_201_209_25',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md183',1,'']]],
  ['wilfong26_20sec_204_202_204_26',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md215',1,'']]],
  ['with_20bubbles_27',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['with_20fewer_20ranks_28',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md613',1,'']]],
  ['with_20gpu_20openacc_20errors_29',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md631',1,'']]],
  ['with_20gpu_20support_30',['Building with GPU Support',['../running.html#autotoc_md566',1,'']]],
  ['with_20mfc_20sh_20viz_31',['Quick visualization with &lt;span class=&quot;tt&quot;&gt;./mfc.sh viz&lt;/span&gt;',['../visualization.html#autotoc_md649',1,'']]],
  ['with_20paraview_32',['Visualizing with ParaView',['../visualization.html#autotoc_md663',1,'']]],
  ['with_20the_20precision_20system_33',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['with_20visit_34',['Visualizing with VisIt',['../visualization.html#autotoc_md665',1,'']]],
  ['within_20domain_35',['Patch Within Domain',['../physics_constraints.html#autotoc_md508',1,'']]],
  ['worked_20around_20in_20the_20build_36',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['worked_20examples_37',['Worked Examples',['../equations.html#sec-nondim-example',1,'']]],
  ['workflow_38',['Workflow',['../troubleshooting.html#autotoc_md597',1,'Debugging Workflow'],['../contributing.html#autotoc_md90',1,'Development Workflow']]],
  ['working_20with_20the_20precision_20system_39',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['write_20a_20gpu_20parallel_20loop_40',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md108',1,'']]],
  ['writing_20gpu_5froutine_20device_20helpers_41',['Writing GPU_ROUTINE Device Helpers',['../gpuParallelization.html#autotoc_md400',1,'']]],
  ['wrong_20or_20has_20artifacts_42',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md644',1,'']]]
];
