var searchData=
[
  ['d_20debug_20log_0',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['data_1',['Exploring available data',['../visualization.html#autotoc_md604',1,'']]],
  ['data_20control_20macros_2',['Data Control Macros',['../gpuParallelization.html#autotoc_md355',1,'']]],
  ['data_20flow_3',['Data Flow',['../gpuParallelization.html#autotoc_md351',1,'Data Flow'],['../contributing.html#autotoc_md87',1,'Simulation Data Flow']]],
  ['data_20in_20cylindrical_20coordinates_4',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md617',1,'']]],
  ['data_20output_5',['Serial data output',['../visualization.html#autotoc_md619',1,'']]],
  ['data_20structures_6',['Key Data Structures',['../architecture.html#autotoc_md2',1,'']]],
  ['data_20type_20meanings_7',['Data Type Meanings',['../gpuParallelization.html#autotoc_md350',1,'']]],
  ['debug_20builds_8',['Debug Builds',['../troubleshooting.html#autotoc_md557',1,'']]],
  ['debug_20log_9',['Debug Log',['../troubleshooting.html#autotoc_md565',1,'']]],
  ['debug_20log_10',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['debug_20logging_20d_20debug_20log_11',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md81',1,'']]],
  ['debugging_12',['Debugging',['../troubleshooting.html#autotoc_md555',1,'Build Debugging'],['../contributing.html#autotoc_md116',1,'Debugging'],['../troubleshooting.html#autotoc_md562',1,'Runtime Debugging'],['../troubleshooting.html#autotoc_md568',1,'Test Debugging']]],
  ['debugging_20flags_13',['Debugging Flags',['../troubleshooting.html#autotoc_md546',1,'']]],
  ['debugging_20tools_20and_20tips_20for_20gpus_14',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md363',1,'']]],
  ['debugging_20workflow_15',['Debugging Workflow',['../troubleshooting.html#autotoc_md550',1,'']]],
  ['definition_20of_20primitive_20variables_16',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['density_17',['Density',['../examples.html#autotoc_md275',1,'Density'],['../examples.html#autotoc_md216',1,'Final Condition (Density)'],['../examples.html#autotoc_md252',1,'Final Condition (Density)']]],
  ['density_20initial_20and_20final_20conditions_18',['Density Initial and Final Conditions',['../examples.html#autotoc_md247',1,'']]],
  ['density_20norms_19',['Density Norms',['../examples.html#autotoc_md276',1,'']]],
  ['descriptions_20',['Descriptions',['../case.html#autotoc_md22',1,'Parameter Descriptions'],['../case.html#autotoc_md24',1,'Parameter Descriptions']]],
  ['design_20playbook_21',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['desktop_20gui_22',['Docker Desktop GUI',['../docker.html#autotoc_md127',1,'']]],
  ['details_23',['Tag Details',['../docker.html#autotoc_md135',1,'']]],
  ['details_20on_20running_20containers_24',['Details on Running Containers',['../docker.html#autotoc_md129',1,'']]],
  ['detected_25',['detected',['../troubleshooting.html#autotoc_md589',1,'&quot;NaN detected&quot;'],['../troubleshooting.html#autotoc_md590',1,'GPU not detected']]],
  ['detection_26',['Verifying GPU Detection',['../running.html#autotoc_md526',1,'']]],
  ['developer_20notes_20on_20non_20conservative_20term_20implementation_27',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md198',1,'']]],
  ['development_28',['Development',['../index.html#autotoc_md514',1,'']]],
  ['development_20commands_29',['Development Commands',['../cli-reference.html#autotoc_md65',1,'']]],
  ['development_20workflow_30',['Development Workflow',['../contributing.html#autotoc_md90',1,'']]],
  ['device_20codegen_20instability_20worked_20around_20in_20the_20build_31',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md374',1,'']]],
  ['device_20helpers_32',['Writing GPU_ROUTINE Device Helpers',['../gpuParallelization.html#autotoc_md361',1,'']]],
  ['differences_20fd_5forder_201_202_204_33',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md204',1,'']]],
  ['different_20viscosity_20parameters_34',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['dimensional_20bubble_20dynamics_35',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dimensional_20consistency_36',['Velocity and Dimensional Consistency',['../physics_constraints.html#autotoc_md468',1,'']]],
  ['dimensional_20framework_37',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['dimensional_20handling_38',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['dimensionality_39',['Dimensionality',['../physics_constraints.html#autotoc_md464',1,'']]],
  ['dimensionalization_40',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensionalization_20of_20input_20parameters_41',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['dimensionalizing_20a_20bubble_20case_42',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['dimensions_43',['Dimensions',['../getting-started.html#autotoc_md341',1,'Units and Dimensions'],['../physics_constraints.html#autotoc_md469',1,'Velocity Components in Inactive Dimensions']]],
  ['dimensions_20and_20non_20dimensionalization_44',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['dimensions_20in_20dimensions_20out_45',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['dimensions_20out_46',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['directory_20found_47',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md594',1,'']]],
  ['directory_20layout_48',['Directory Layout',['../architecture.html#autotoc_md1',1,'Directory Layout'],['../contributing.html#autotoc_md86',1,'Directory Layout']]],
  ['docker_49',['Navigating Docker',['../docker.html#autotoc_md126',1,'']]],
  ['docker_20cli_50',['Docker CLI',['../docker.html#autotoc_md128',1,'']]],
  ['docker_20desktop_20gui_51',['Docker Desktop GUI',['../docker.html#autotoc_md127',1,'']]],
  ['document_20physics_20constraints_52',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['documentation_53',['Documentation',['../gpuParallelization.html#autotoc_md376',1,'Compiler Documentation'],['../contributing.html#autotoc_md122',1,'Documentation'],['../gpuParallelization.html#autotoc_md349',1,'Macro API Documentation'],['../index.html',1,'MFC Documentation']]],
  ['domain_54',['Domain',['../case.html#sec-computational-domain',1,'2. Computational Domain'],['../physics_constraints.html#autotoc_md466',1,'Patch Within Domain']]],
  ['domain_20and_20geometry_55',['Domain and Geometry',['../physics_constraints.html#autotoc_md462',1,'']]],
  ['domain_20bounds_56',['Domain Bounds',['../physics_constraints.html#autotoc_md463',1,'']]],
  ['domain_20extents_20specified_57',['Domain Extents Specified',['../physics_constraints.html#autotoc_md465',1,'']]],
  ['driven_20cavity_58',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md294',1,'']]],
  ['driven_20cavity_20problem_202d_59',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md261',1,'']]],
  ['droplet_202d_60',['Shock Droplet (2D)',['../examples.html#autotoc_md310',1,'']]],
  ['dropped_61',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md375',1,'']]],
  ['dt_202d_62',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md225',1,'']]],
  ['dynamics_63',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['dynamics_64',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[49]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md202',1,'']]],
  ['dynamics_20wilfong26_20sec_204_201_65',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md158',1,'']]]
];
