var searchData=
[
  ['a_20fortran_20compiler_0',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md407',1,'']]],
  ['a_20new_20case_1',['Creating a New Case',['../getting-started.html#autotoc_md218',1,'']]],
  ['about_2',['About',['../index.html#autotoc_md339',1,'']]],
  ['accepting_20command_20line_20arguments_3',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['achieving_20maximum_20performance_4',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md190',1,'']]],
  ['acoustic_5',['acoustic',['../parameters.html#autotoc_md262',1,'']]],
  ['acoustic_20source_6',['8. Acoustic Source',['../case.html#acoustic-source',1,'']]],
  ['acoustic_20supports_7',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['adaptive_20time_20stepping_8',['Adaptive Time-Stepping',['../case.html#autotoc_md19',1,'']]],
  ['advanced_20examples_9',['🔴 Advanced Examples',['../case_constraints.html#autotoc_md43',1,'']]],
  ['advanced_20topics_10',['Advanced Topics',['../index.html#autotoc_md338',1,'']]],
  ['agnostic_20tools_11',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md235',1,'']]],
  ['algorithm_12',['6. Simulation Algorithm',['../case.html#autotoc_md16',1,'']]],
  ['alpha_5frho_5fe_5fwrt_13',['alpha_rho_e_wrt',['../parameters.html#autotoc_md287',1,'']]],
  ['alpha_5frho_5fwrt_14',['alpha_rho_wrt',['../parameters.html#autotoc_md290',1,'']]],
  ['alpha_5fwrt_15',['alpha_wrt',['../parameters.html#autotoc_md293',1,'']]],
  ['amd_20gpu_20profiling_16',['AMD GPU Profiling',['../troubleshooting.html#autotoc_md402',1,'']]],
  ['amd_20gpus_17',['AMD GPUs',['../running.html#autotoc_md354',1,'']]],
  ['amd_20mi250x_20gpu_18',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md200',1,'']]],
  ['an_20example_20case_19',['Running an Example Case',['../getting-started.html#autotoc_md215',1,'']]],
  ['analytical_20definition_20of_20primitive_20variables_20',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md9',1,'']]],
  ['and_20final_20conditions_21',['Density Initial and Final Conditions',['../examples.html#autotoc_md151',1,'']]],
  ['and_20linear_20theory_22',['and Linear Theory',['../examples.html#autotoc_md134',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md178',1,'Final Condition and Linear Theory']]],
  ['and_20performance_20test_23',['Scaling and Performance test',['../examples.html#autotoc_md129',1,'']]],
  ['and_20result_24',['Initial Condition and Result',['../examples.html#autotoc_md169',1,'']]],
  ['and_20tips_20for_20gpus_25',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md234',1,'']]],
  ['api_20documentation_26',['Macro API Documentation',['../gpuParallelization.html#autotoc_md222',1,'']]],
  ['apptainer_20singularity_27',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md116',1,'']]],
  ['architecture_20support_28',['Architecture Support',['../docker.html#autotoc_md124',1,'']]],
  ['arguments_29',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['artificial_20mach_20number_30',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['at_20final_20time_31',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md180',1,'']]],
  ['at_20transitional_20state_32',['Liutex visualization at transitional state',['../examples.html#autotoc_md182',1,'']]],
  ['authors_33',['Authors',['../authors.html',1,'Authors'],['../authors.html#autotoc_md0',1,'Authors']]],
  ['averaged_20bubble_20model_34',['Averaged Bubble Model',['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]]
];
