var searchData=
[
  ['nan_20detected_0',['&quot;NaN detected&quot;',['../troubleshooting.html#autotoc_md568',1,'']]],
  ['navigating_20docker_1',['Navigating Docker',['../docker.html#autotoc_md126',1,'']]],
  ['new_2',['new',['../cli-reference.html#new',1,'']]],
  ['new_20case_3',['Creating a New Case',['../getting-started.html#autotoc_md346',1,'']]],
  ['new_20fortran_20module_4',['How to Create a New Fortran Module',['../contributing.html#autotoc_md111',1,'']]],
  ['new_20physics_5',['Adding New Physics',['../architecture.html#autotoc_md13',1,'']]],
  ['new_20simulation_20parameter_6',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md107',1,'']]],
  ['newtonian_20herschel_20bulkley_20viscosity_7',['Newtonian Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md472',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['no_20binary_20or_20silo_5fhdf5_20directory_20found_8',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md573',1,'']]],
  ['non_20dimensional_20bubble_20dynamics_9',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['non_20dimensional_20framework_10',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['non_20dimensionalization_11',['1b. Units, Dimensions, and Non-Dimensionalization',['../equations.html#sec-units-dimensions',1,'']]],
  ['non_20dimensionalization_20of_20input_20parameters_12',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['non_20dimensionalizing_20a_20bubble_20case_13',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['non_20newtonian_20herschel_20bulkley_20viscosity_14',['Non Newtonian Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md472',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['non_20polytropic_20thermal_20model_20polytropic_20false_20preston07_15',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['norms_16',['Density Norms',['../examples.html#autotoc_md291',1,'']]],
  ['not_20detected_17',['GPU not detected',['../troubleshooting.html#autotoc_md569',1,'']]],
  ['not_20find_20a_20fortran_20compiler_18',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md561',1,'']]],
  ['not_20find_20mpi_19',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md560',1,'']]],
  ['not_20found_20',['&quot;Variable &apos;X&apos; not found&quot;',['../troubleshooting.html#autotoc_md574',1,'']]],
  ['not_20found_20on_20hpc_21',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md564',1,'']]],
  ['notes_22',['Notes',['../contributing.html#autotoc_md104',1,'Architecture Notes'],['../running.html#autotoc_md515',1,'Scheduler Notes']]],
  ['number_23',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['number_20corrections_20wilfong26_20sec_204_202_204_24',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md212',1,'']]],
  ['numerical_20methods_25',['15. Numerical Methods',['../equations.html#autotoc_md190',1,'']]],
  ['numerical_20schemes_26',['Numerical Schemes',['../physics_constraints.html#autotoc_md474',1,'']]],
  ['numerical_20schlieren_20at_20final_20time_27',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md307',1,'']]],
  ['numerics_28',['Numerics',['../case_constraints.html#compat-numerics',1,'']]],
  ['nvhpc_20compiler_20options_29',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md368',1,'']]],
  ['nvhpc_20general_20options_30',['NVHPC General Options',['../gpuParallelization.html#autotoc_md369',1,'']]],
  ['nvhpc_20openacc_20options_31',['NVHPC OpenACC Options',['../gpuParallelization.html#autotoc_md370',1,'']]],
  ['nvhpc_20openmp_20options_32',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md371',1,'']]],
  ['nvidia_20gpu_20profiling_33',['NVIDIA GPU Profiling',['../troubleshooting.html#autotoc_md555',1,'']]],
  ['nvidia_20gpus_34',['NVIDIA GPUs',['../running.html#autotoc_md507',1,'']]],
  ['nvidia_20uvm_35',['20. GPU Performance (NVIDIA UVM)',['../case.html#autotoc_md36',1,'']]],
  ['nvidia_20v100_20gpu_36',['NVIDIA V100 GPU',['../expectedPerformance.html#autotoc_md330',1,'']]],
  ['nvidia_20v100_20gpu_20historical_37',['NVIDIA V100 GPU (historical)',['../expectedPerformance.html#autotoc_md327',1,'']]]
];
