var searchData=
[
  ['scaling_0',['Scaling',['../examples.html#autotoc_md131',1,'Strong Scaling'],['../examples.html#autotoc_md130',1,'Weak Scaling']]],
  ['scaling_1',['scaling',['../expectedPerformance.html#autotoc_md203',1,'Strong scaling'],['../expectedPerformance.html#autotoc_md199',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_2',['Scaling and Performance test',['../examples.html#autotoc_md129',1,'']]],
  ['scheduler_20notes_3',['Scheduler Notes',['../running.html#autotoc_md361',1,'']]],
  ['schlieren_20at_20final_20time_4',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md180',1,'']]],
  ['schlieren_5falpha_5',['schlieren_alpha',['../parameters.html#autotoc_md302',1,'']]],
  ['script_6',['Step 2: Customizing the script',['../visualization.html#autotoc_md426',1,'']]],
  ['selection_20t_20targets_7',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md106',1,'']]],
  ['serial_20data_20output_8',['Serial data output',['../visualization.html#autotoc_md423',1,'']]],
  ['serial_20test_20execution_9',['Serial Test Execution',['../troubleshooting.html#autotoc_md395',1,'']]],
  ['server_10',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md427',1,'']]],
  ['setting_20up_20your_20environment_11',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md425',1,'']]],
  ['setup_12',['Setup',['../case.html#autotoc_md24',1,'10. Velocity Field Setup'],['../running.html#autotoc_md350',1,'Environment Setup']]],
  ['shell_13',['Interactive Shell',['../docker.html#autotoc_md117',1,'']]],
  ['shell_20completion_14',['Shell Completion',['../getting-started.html#autotoc_md219',1,'']]],
  ['shock_203d_15',['IBM Bow Shock (3D)',['../examples.html#autotoc_md186',1,'']]],
  ['shock_20droplet_202d_16',['Shock Droplet (2D)',['../examples.html#autotoc_md172',1,'']]],
  ['shock_20tube_17',['Shock Tube',['../examples.html#autotoc_md183',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md145',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_202d_18',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md159',1,'']]],
  ['shock_20tube_20problem_201d_19',['Lax shock tube problem (1D)',['../examples.html#autotoc_md126',1,'']]],
  ['shu_20osher_20problem_201d_20',['Shu-Osher problem (1D)',['../examples.html#autotoc_md137',1,'']]],
  ['simplex_5fparams_21',['simplex_params',['../parameters.html#autotoc_md265',1,'']]],
  ['simulation_20algorithm_22',['6. Simulation Algorithm',['../case.html#autotoc_md16',1,'']]],
  ['singularity_23',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md116',1,'']]],
  ['skeleton_24',['Basic Skeleton',['../case.html#autotoc_md2',1,'']]],
  ['slurm_20job_25',['Slurm Job',['../docker.html#autotoc_md119',1,'']]],
  ['smoothing_26',['Elliptic Smoothing',['../case.html#autotoc_md12',1,'']]],
  ['solvers_27',['⚙️ Riemann Solvers',['../case_constraints.html#autotoc_md51',1,'']]],
  ['source_28',['8. Acoustic Source',['../case.html#acoustic-source',1,'']]],
  ['specific_20tests_29',['Running Specific Tests',['../troubleshooting.html#autotoc_md394',1,'']]],
  ['spelling_30',['spelling',['../cli-reference.html#autotoc_md89',1,'']]],
  ['started_31',['Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md208',1,'Getting Started'],['../index.html#autotoc_md335',1,'Getting Started']]],
  ['state_32',['State',['../examples.html#autotoc_md142',1,'Evolved State'],['../examples.html#autotoc_md158',1,'Evolved State'],['../examples.html#autotoc_md161',1,'Evolved State'],['../examples.html#autotoc_md141',1,'Initial State'],['../examples.html#autotoc_md157',1,'Initial State'],['../examples.html#autotoc_md160',1,'Initial State']]],
  ['state_33',['Liutex visualization at transitional state',['../examples.html#autotoc_md182',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_34',['Step 1: Setting up your Environment',['../visualization.html#autotoc_md425',1,'']]],
  ['step_202_3a_20customizing_20the_20script_35',['Step 2: Customizing the script',['../visualization.html#autotoc_md426',1,'']]],
  ['step_202d_36',['Step 2D',['../examples.html#autotoc_md170',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md148',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_37',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md427',1,'']]],
  ['stepping_38',['Stepping',['../case.html#autotoc_md19',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md18',1,'Constant Time-Stepping']]],
  ['stirred_20reactor_39',['Perfectly Stirred Reactor',['../examples.html#autotoc_md152',1,'']]],
  ['strong_20scaling_40',['Strong Scaling',['../examples.html#autotoc_md131',1,'']]],
  ['strong_20scaling_41',['Strong scaling',['../expectedPerformance.html#autotoc_md203',1,'']]],
  ['structure_42',['Tag Structure',['../docker.html#autotoc_md122',1,'']]],
  ['sub_20grid_20bubble_20models_43',['9. Sub-grid Bubble Models',['../case.html#autotoc_md21',1,'']]],
  ['suite_44',['Running the Test Suite',['../getting-started.html#autotoc_md214',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_45',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md116',1,'']]],
  ['support_46',['Support',['../docker.html#autotoc_md124',1,'Architecture Support'],['../running.html#autotoc_md347',1,'Building with GPU Support']]],
  ['supported_20compilers_47',['Supported Compilers',['../running.html#autotoc_md349',1,'']]],
  ['supports_48',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['synchronization_20macros_49',['Synchronization Macros',['../gpuParallelization.html#autotoc_md230',1,'']]]
];
