var searchData=
[
  ['3_0',['3',['../equations.html#autotoc_md142',1,'2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)'],['../equations.html#autotoc_md151',1,'5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.3)'],['../equations.html#autotoc_md167',1,'8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)'],['../equations.html#autotoc_md193',1,'Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)']]],
  ['3_201_20stiffened_20gas_20eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_1',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md146',1,'']]],
  ['3_202_20ideal_20gas_20eos_20chemistry_20chemistry_20true_2',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md147',1,'']]],
  ['3_205_207_3',['WENO (&lt;span class=&quot;tt&quot;&gt;weno_order = 3, 5, 7&lt;/span&gt;)',['../equations.html#autotoc_md187',1,'']]],
  ['3_20equations_20of_20state_4',['3. Equations of State',['../equations.html#autotoc_md145',1,'']]],
  ['3_20gottlieb98_5',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['3_20immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_6',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md205',1,'']]],
  ['3_20keller_20miksis_20bubble_5fmodel_202_20keller80_7',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['3_20other_20model_20variants_8',['2.3 Other Model Variants',['../equations.html#autotoc_md143',1,'']]],
  ['3_20patches_9',['3. Patches',['../case.html#sec-patches',1,'']]],
  ['3_20rayleigh17_20plesset49_10',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['3_20time_20integration_11',['15.3 Time Integration',['../equations.html#autotoc_md195',1,'']]],
  ['3_3a_20running_20pace_20paraview_20server_12',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['3d_13',['3D',['../examples.html#autotoc_md266',1,'3D Turbulent Mixing layer (3D)'],['../examples.html#autotoc_md271',1,'IBM Bow Shock (3D)'],['../examples.html#autotoc_md218',1,'Rayleigh-Taylor Instability (3D)'],['../examples.html#autotoc_md260',1,'Taylor-Green Vortex (3D)']]],
  ['3d_20turbulent_20mixing_20layer_203d_14',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md266',1,'']]]
];
