var searchData=
[
  ['mach_20number_0',['12. Artificial Mach Number',['../case.html#sec-artificial-mach-number',1,'']]],
  ['mach_20number_20corrections_20wilfong26_20sec_204_202_204_1',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md207',1,'']]],
  ['macos_2',['macOS',['../getting-started.html#autotoc_md295',1,'Install via Homebrew (macOS)'],['../running.html#autotoc_md448',1,'Using the Homebrew package (macOS)']]],
  ['macro_20api_20documentation_3',['Macro API Documentation',['../gpuParallelization.html#autotoc_md308',1,'']]],
  ['macros_4',['Macros',['../gpuParallelization.html#autotoc_md312',1,'Computation Macros'],['../gpuParallelization.html#autotoc_md314',1,'Data Control Macros'],['../gpuParallelization.html#autotoc_md318',1,'Miscellaneous Macros'],['../gpuParallelization.html#autotoc_md316',1,'Synchronization Macros']]],
  ['maeda18_5',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['magnetohydrodynamics_6',['11. Magnetohydrodynamics',['../equations.html#autotoc_md175',1,'']]],
  ['magnetohydrodynamics_20mhd_7',['Magnetohydrodynamics MHD',['../case.html#autotoc_md30',1,'14. Magnetohydrodynamics (MHD)'],['../physics_constraints.html#autotoc_md422',1,'Magnetohydrodynamics (MHD)']]],
  ['manage_20gpu_20arrays_8',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md104',1,'']]],
  ['map_9',['Module Map',['../architecture.html#autotoc_md5',1,'']]],
  ['material_20s_10',['5. Fluid Material&apos;s',['../case.html#sec-fluid-materials',1,'']]],
  ['material_20values_11',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['matrix_12',['Build and Test Matrix',['../contributing.html#autotoc_md115',1,'']]],
  ['maximum_20performance_13',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md275',1,'']]],
  ['meanings_14',['Data Type Meanings',['../gpuParallelization.html#autotoc_md309',1,'']]],
  ['memory_20and_20allocation_15',['Memory and Allocation',['../contributing.html#autotoc_md94',1,'']]],
  ['menikoff89_20lemetayer04_20wilfong26_20sec_202_202_16',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md146',1,'']]],
  ['merge_17',['Code Review and Merge',['../contributing.html#autotoc_md119',1,'']]],
  ['merit_3a_20grind_20time_20performance_18',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md283',1,'']]],
  ['meshkov_20instability_202d_19',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md217',1,'']]],
  ['messages_20',['Commit Messages',['../contributing.html#autotoc_md87',1,'']]],
  ['method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_21',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md205',1,'']]],
  ['method_20of_20classes_20commander89_20ando11_22',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md155',1,'']]],
  ['methods_23',['15. Numerical Methods',['../equations.html#autotoc_md185',1,'']]],
  ['mfc_24',['MFC',['../getting-started.html#autotoc_md297',1,'Building MFC'],['../contributing.html#autotoc_md79',1,'Contributing to MFC'],['../getting-started.html#autotoc_md294',1,'Fetching MFC']]],
  ['mfc_20documentation_25',['MFC Documentation',['../index.html',1,'']]],
  ['mfc_3a_20comprehensive_20equations_20reference_26',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md135',1,'']]],
  ['mhd_27',['MHD',['../case.html#autotoc_md30',1,'14. Magnetohydrodynamics (MHD)'],['../physics_constraints.html#autotoc_md422',1,'Magnetohydrodynamics (MHD)']]],
  ['mhd_20mhd_20true_20wilfong26_20sec_204_201_209_28',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md176',1,'']]],
  ['mhd_20only_29',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md194',1,'']]],
  ['mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_30',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md177',1,'']]],
  ['mhd_20true_20wilfong26_20sec_204_201_209_31',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md176',1,'']]],
  ['miksis_20bubble_5fmodel_202_20keller80_32',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['miscellaneous_20macros_33',['Miscellaneous Macros',['../gpuParallelization.html#autotoc_md318',1,'']]],
  ['mittal05_20wilfong26_20sec_204_201_201_34',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[52]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md205',1,'']]],
  ['mixing_20layer_203d_35',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md233',1,'']]],
  ['mixture_20constraints_36',['Mixture Constraints',['../physics_constraints.html#autotoc_md398',1,'']]],
  ['model_37',['Model',['../case.html#sec-phase-change',1,'11. Phase Change Model'],['../case.html#autotoc_md27',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md28',1,'9.2 Volume-Averaged Bubble Model'],['../physics_constraints.html#autotoc_md417',1,'Euler-Euler Bubble Model'],['../physics_constraints.html#autotoc_md419',1,'Euler-Lagrange Bubble Model']]],
  ['model_20consistency_38',['Physics and Model Consistency',['../contributing.html#autotoc_md96',1,'']]],
  ['model_20equation_20selection_39',['Model Equation Selection',['../physics_constraints.html#autotoc_md411',1,'']]],
  ['model_20equations_40',['Model Equations',['../case_constraints.html#model-equations',1,'🔢 Model Equations'],['../physics_constraints.html#autotoc_md410',1,'Model Equations']]],
  ['model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_41',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md165',1,'']]],
  ['model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_42',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md164',1,'']]],
  ['model_20model_5feqns_202_43',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md141',1,'']]],
  ['model_20model_5feqns_203_44',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md142',1,'']]],
  ['model_20polytropic_20false_20preston07_45',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md159',1,'']]],
  ['model_20variants_46',['2.3 Other Model Variants',['../equations.html#autotoc_md143',1,'']]],
  ['model_5feqns_202_47',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md141',1,'']]],
  ['model_5feqns_203_48',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md142',1,'']]],
  ['models_49',['Models',['../case_constraints.html#bubble-models',1,'💧 Bubble Models'],['../case.html#sec-bubble-models',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#compat-bubble-models',1,'Bubble Models'],['../architecture.html#autotoc_md7',1,'Physics Models'],['../case_constraints.html#compat-physics-models',1,'Physics Models']]],
  ['modifying_20src_20common_50',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md110',1,'']]],
  ['module_51',['How to Create a New Fortran Module',['../contributing.html#autotoc_md106',1,'']]],
  ['module_20map_52',['Module Map',['../architecture.html#autotoc_md5',1,'']]],
  ['module_20not_20found_20on_20hpc_53',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md516',1,'']]],
  ['mom_5fwrt_54',['mom_wrt',['../parameters.html#mom_wrt',1,'']]],
  ['moment_20transport_20qbmm_20true_20bryngelson20_55',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['mpi_56',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md512',1,'']]],
  ['mpi_20correctness_57',['MPI Correctness',['../contributing.html#autotoc_md95',1,'']]],
  ['mpi_20errors_20or_20hangs_58',['MPI errors or hangs',['../troubleshooting.html#autotoc_md522',1,'']]],
  ['mpi_20halo_20exchange_59',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md108',1,'']]],
  ['mpi_20parallelization_60',['MPI Parallelization',['../architecture.html#autotoc_md12',1,'']]],
  ['multi_20component_20inert_20shock_20tube_61',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md257',1,'']]],
  ['multi_20component_20reactive_20shock_20tube_62',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md228',1,'']]],
  ['muscl_20muscl_5forder_202_63',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md188',1,'']]],
  ['muscl_20reconstruction_64',['MUSCL Reconstruction',['../physics_constraints.html#autotoc_md431',1,'']]],
  ['muscl_5forder_202_65',['MUSCL (&lt;span class=&quot;tt&quot;&gt;muscl_order = 2&lt;/span&gt;)',['../equations.html#autotoc_md188',1,'']]]
];
