var searchData=
[
  ['backward_20facing_20step_202d_0',['Backward Facing Step (2D)',['../examples.html#autotoc_md280',1,'']]],
  ['base_20images_1',['Base Images',['../docker.html#autotoc_md135',1,'']]],
  ['basic_20skeleton_2',['Basic Skeleton',['../case.html#autotoc_md16',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../running.html#autotoc_md507',1,'']]],
  ['basic_20usage_4',['Basic usage',['../visualization.html#autotoc_md578',1,'']]],
  ['batch_20execution_5',['Batch Execution',['../running.html#autotoc_md506',1,'']]],
  ['batch_20options_6',['Batch Options',['../running.html#autotoc_md508',1,'']]],
  ['bc_5fx_7',['bc_x',['../parameters.html#bc_x',1,'']]],
  ['bc_5fx_20beg_205_20to_2012_8',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md208',1,'']]],
  ['bc_5fy_9',['bc_y',['../parameters.html#bc_y',1,'']]],
  ['bc_5fz_10',['bc_z',['../parameters.html#bc_z',1,'']]],
  ['bcs_11',['16.1 Simple BCs',['../equations.html#autotoc_md207',1,'']]],
  ['bcs_20thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_12',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md208',1,'']]],
  ['beg_205_20to_2012_13',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md208',1,'']]],
  ['beginner_20examples_14',['🟢 Beginner Examples',['../case_constraints.html#autotoc_md41',1,'']]],
  ['bench_15',['bench',['../cli-reference.html#bench',1,'']]],
  ['bench_5fdiff_16',['bench_diff',['../cli-reference.html#bench_diff',1,'']]],
  ['benchmark_20results_17',['Benchmark Results',['../expectedPerformance.html#autotoc_md322',1,'']]],
  ['bf_5fx_20bf_5fy_20bf_5fz_18',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['bf_5fy_20bf_5fz_19',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['bf_5fz_20',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['bibliography_21',['Bibliography',['../citelist.html',1,'']]],
  ['binary_20or_20silo_5fhdf5_20directory_20found_22',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md569',1,'']]],
  ['bingham_20yield_20stress_20poiseuille_20channel_23',['2D Bingham (Yield-Stress) Poiseuille Channel',['../examples.html#autotoc_md239',1,'']]],
  ['blocks_20all_20other_20jobs_24',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md118',1,'']]],
  ['body_20forces_25',['13. Body Forces',['../case.html#autotoc_md29',1,'']]],
  ['body_20forces_20bf_5fx_20bf_5fy_20bf_5fz_26',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['boundary_20condition_20compatibility_27',['Boundary Condition Compatibility',['../physics_constraints.html#autotoc_md457',1,'']]],
  ['boundary_20condition_20patches_28',['Boundary Condition Patches',['../case.html#boundary-condition-patches',1,'']]],
  ['boundary_20conditions_29',['Boundary Conditions',['../equations.html#autotoc_md206',1,'16. Boundary Conditions'],['../case.html#autotoc_md34',1,'18. Chemistry-Specific Boundary Conditions'],['../architecture.html#autotoc_md8',1,'Boundary Conditions'],['../physics_constraints.html#autotoc_md456',1,'Boundary Conditions']]],
  ['boundary_20conditions_30',['Boundary conditions',['../case.html#boundary-conditions',1,'Boundary conditions'],['../case.html#autotoc_md37',1,'Generalized Characteristic Boundary conditions']]],
  ['boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_31',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md209',1,'']]],
  ['boundary_20patch_20types_32',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['boundary_20patches_33',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['bounds_34',['Domain Bounds',['../physics_constraints.html#autotoc_md446',1,'']]],
  ['bounds_20and_20indexing_35',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['bow_20shock_203d_36',['IBM Bow Shock (3D)',['../examples.html#autotoc_md261',1,'']]],
  ['bryngelson20_37',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md164',1,'']]],
  ['bub_5fpp_38',['bub_pp',['../parameters.html#bub_pp',1,'']]],
  ['bubble_20case_39',['Example: Non-Dimensionalizing a Bubble Case',['../equations.html#sec-bubble-example',1,'']]],
  ['bubble_20dynamics_40',['Non-Dimensional Bubble Dynamics',['../equations.html#sec-nondim-bubble-dynamics',1,'']]],
  ['bubble_20dynamics_41',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[45]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md202',1,'']]],
  ['bubble_20dynamics_20wilfong26_20sec_204_201_42',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md157',1,'']]],
  ['bubble_20model_43',['Bubble Model',['../case.html#autotoc_md27',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md28',1,'9.2 Volume-Averaged Bubble Model'],['../physics_constraints.html#autotoc_md460',1,'Euler-Euler Bubble Model'],['../physics_constraints.html#autotoc_md462',1,'Euler-Lagrange Bubble Model']]],
  ['bubble_20models_44',['Bubble Models',['../case_constraints.html#bubble-models',1,'💧 Bubble Models'],['../case.html#sec-bubble-models',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#compat-bubble-models',1,'Bubble Models']]],
  ['bubble_20physics_45',['Bubble Physics',['../physics_constraints.html#autotoc_md459',1,'']]],
  ['bubble_20simulation_20constraints_46',['Bubble Simulation Constraints',['../physics_constraints.html#autotoc_md461',1,'']]],
  ['bubble_20users_3a_20non_20dimensional_20framework_47',['Bubble Users: Non-Dimensional Framework',['../equations.html#sec-bubble-nondim',1,'']]],
  ['bubble_5fmodel_201_20gilmore52_48',['6.1.4 Gilmore (&lt;span class=&quot;tt&quot;&gt;bubble_model = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gilmore52&quot;&gt;[17]&lt;/a&gt;)',['../equations.html#autotoc_md162',1,'']]],
  ['bubble_5fmodel_202_20keller80_49',['6.1.3 Keller-Miksis (&lt;span class=&quot;tt&quot;&gt;bubble_model = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_keller80&quot;&gt;[26]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['bubble_5fmodel_203_20rayleigh17_20plesset49_50',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[38]&lt;/a&gt;)',['../equations.html#autotoc_md160',1,'']]],
  ['bubbles_51',['Flow Parameters with Bubbles',['../equations.html#sec-flow-params-bubbles',1,'']]],
  ['bubbles_20bubbles_5feuler_20true_52',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md158',1,'']]],
  ['bubbles_20bubbles_5flagrange_20true_20maeda18_53',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['bubbles_5feuler_20true_54',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md158',1,'']]],
  ['bubbles_5flagrange_20true_20maeda18_55',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['build_56',['build',['../cli-reference.html#build',1,'']]],
  ['build_20and_20test_20matrix_57',['Build and Test Matrix',['../contributing.html#autotoc_md119',1,'']]],
  ['build_20configuration_20flags_58',['Build Configuration Flags',['../cli-reference.html#autotoc_md79',1,'']]],
  ['build_20debugging_59',['Build Debugging',['../troubleshooting.html#autotoc_md530',1,'']]],
  ['build_20environment_60',['Build Environment',['../getting-started.html#autotoc_md336',1,'']]],
  ['build_20errors_61',['Common Build Errors',['../troubleshooting.html#autotoc_md555',1,'']]],
  ['build_20fails_62',['Build Fails?',['../troubleshooting.html#autotoc_md526',1,'']]],
  ['build_20fails_20with_20gpu_20openacc_20errors_63',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md559',1,'']]],
  ['build_20fits_20together_64',['How the Build Fits Together',['../contributing.html#autotoc_md89',1,'']]],
  ['build_20toolchain_65',['Build Toolchain',['../contributing.html#autotoc_md88',1,'']]],
  ['building_20mfc_66',['Building MFC',['../getting-started.html#autotoc_md337',1,'']]],
  ['building_20with_20gpu_20support_67',['Building with GPU Support',['../running.html#autotoc_md497',1,'']]],
  ['builds_68',['Debug Builds',['../troubleshooting.html#autotoc_md532',1,'']]],
  ['bulkley_20poiseuille_20channel_69',['2D General Herschel-Bulkley Poiseuille Channel',['../examples.html#autotoc_md293',1,'']]],
  ['bulkley_20viscosity_70',['Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md471',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]]
];
