var searchData=
[
  ['d_20debug_20log_0',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md64',1,'']]],
  ['data_20control_20macros_1',['Data Control Macros',['../gpuParallelization.html#autotoc_md298',1,'']]],
  ['data_20flow_2',['Data Flow',['../gpuParallelization.html#autotoc_md294',1,'Data Flow'],['../contributing.html#autotoc_md70',1,'Simulation Data Flow']]],
  ['data_20in_20cylindrical_20coordinates_3',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md461',1,'']]],
  ['data_20output_4',['Serial data output',['../visualization.html#autotoc_md463',1,'']]],
  ['data_20type_20meanings_5',['Data Type Meanings',['../gpuParallelization.html#autotoc_md293',1,'']]],
  ['debug_20builds_6',['Debug Builds',['../troubleshooting.html#autotoc_md422',1,'']]],
  ['debug_20log_7',['Debug Log',['../troubleshooting.html#autotoc_md430',1,'']]],
  ['debug_20log_8',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md64',1,'']]],
  ['debug_20logging_20d_20debug_20log_9',['Debug Logging (&lt;span class=&quot;tt&quot;&gt;-d, --debug-log&lt;/span&gt;)',['../cli-reference.html#autotoc_md64',1,'']]],
  ['debugging_10',['Debugging',['../troubleshooting.html#autotoc_md420',1,'Build Debugging'],['../contributing.html#autotoc_md97',1,'Debugging'],['../troubleshooting.html#autotoc_md427',1,'Runtime Debugging'],['../troubleshooting.html#autotoc_md433',1,'Test Debugging']]],
  ['debugging_20flags_11',['Debugging Flags',['../troubleshooting.html#autotoc_md411',1,'']]],
  ['debugging_20tools_20and_20tips_20for_20gpus_12',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md304',1,'']]],
  ['debugging_20workflow_13',['Debugging Workflow',['../troubleshooting.html#autotoc_md415',1,'']]],
  ['definition_20of_20primitive_20variables_14',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md6',1,'']]],
  ['density_15',['Density',['../examples.html#autotoc_md238',1,'Density'],['../examples.html#autotoc_md241',1,'Final Condition (Density)'],['../examples.html#autotoc_md257',1,'Final Condition (Density)']]],
  ['density_20initial_20and_20final_20conditions_16',['Density Initial and Final Conditions',['../examples.html#autotoc_md217',1,'']]],
  ['density_20norms_17',['Density Norms',['../examples.html#autotoc_md239',1,'']]],
  ['descriptions_18',['Descriptions',['../case.html#autotoc_md8',1,'Parameter Descriptions'],['../case.html#autotoc_md10',1,'Parameter Descriptions']]],
  ['design_20playbook_19',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['desktop_20gui_20',['Docker Desktop GUI',['../docker.html#autotoc_md108',1,'']]],
  ['details_21',['Tag Details',['../docker.html#autotoc_md116',1,'']]],
  ['details_20on_20running_20containers_22',['Details on Running Containers',['../docker.html#autotoc_md110',1,'']]],
  ['detected_23',['detected',['../troubleshooting.html#autotoc_md454',1,'&quot;NaN detected&quot;'],['../troubleshooting.html#autotoc_md455',1,'GPU not detected']]],
  ['detection_24',['Verifying GPU Detection',['../running.html#autotoc_md391',1,'']]],
  ['development_25',['Development',['../index.html#autotoc_md379',1,'']]],
  ['development_20commands_26',['Development Commands',['../cli-reference.html#autotoc_md47',1,'']]],
  ['development_20workflow_27',['Development Workflow',['../contributing.html#autotoc_md72',1,'']]],
  ['differences_20fd_5forder_201_202_204_28',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['directory_20layout_29',['Directory Layout',['../contributing.html#autotoc_md69',1,'']]],
  ['docker_30',['Navigating Docker',['../docker.html#autotoc_md107',1,'']]],
  ['docker_20cli_31',['Docker CLI',['../docker.html#autotoc_md109',1,'']]],
  ['docker_20desktop_20gui_32',['Docker Desktop GUI',['../docker.html#autotoc_md108',1,'']]],
  ['documentation_33',['Documentation',['../gpuParallelization.html#autotoc_md314',1,'Compiler Documentation'],['../contributing.html#autotoc_md103',1,'Documentation'],['../gpuParallelization.html#autotoc_md292',1,'Macro API Documentation'],['../index.html',1,'MFC Documentation']]],
  ['domain_34',['2. Computational Domain',['../case.html#sec-computational-domain',1,'']]],
  ['driven_20cavity_20problem_202d_35',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md251',1,'']]],
  ['droplet_202d_36',['Shock Droplet (2D)',['../examples.html#autotoc_md208',1,'']]],
  ['dt_202d_37',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md249',1,'']]],
  ['dynamics_38',['Strang Splitting (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_strang68&quot;&gt;[44]&lt;/a&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md183',1,'']]],
  ['dynamics_20wilfong26_20sec_204_201_39',['6. Sub-Grid Bubble Dynamics (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1)',['../equations.html#autotoc_md138',1,'']]]
];
