var searchData=
[
  ['case_0',['Case',['../getting-started.html#autotoc_md333',1,'Creating a New Case'],['../contributing.html#autotoc_md136',1,'How to Add a Test Case'],['../getting-started.html#autotoc_md330',1,'Running an Example Case']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../case_constraints.html#autotoc_md40',1,'']]],
  ['case_20files_3',['Case Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md1',1,'Case Files']]],
  ['case_20optimization_4',['When to use case optimization',['../expectedPerformance.html#autotoc_md307',1,'']]],
  ['case_20optimization_20recommended_5',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md306',1,'']]],
  ['case_20parameter_20constraint_20violations_6',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md531',1,'']]],
  ['case_20parameters_20reference_7',['Case Parameters Reference',['../parameters.html',1,'Case Parameters Reference'],['../parameters.html#autotoc_md361',1,'Case Parameters Reference']]],
  ['case_20validation_8',['Case Validation',['../troubleshooting.html#autotoc_md506',1,'']]],
  ['cases_9',['Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md240',1,'Example Cases'],['../running.html#autotoc_md481',1,'Restarting Cases']]],
  ['cavity_20problem_202d_10',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md296',1,'']]],
  ['centerline_20velocities_11',['Centerline Velocities',['../examples.html#autotoc_md298',1,'']]],
  ['cfl_20condition_12',['15.4 CFL Condition',['../equations.html#autotoc_md229',1,'']]],
  ['cfl_20dt_202d_13',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md294',1,'']]],
  ['change_20model_14',['11. Phase Change Model',['../case.html#autotoc_md25',1,'']]],
  ['change_20relax_20true_20wilfong26_20sec_204_201_203_15',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.3)',['../equations.html#autotoc_md197',1,'']]],
  ['characteristic_20bcs_20thompson87_20thompson90_20bc_5fxbeg_205_20to_2012_16',['16.2 Characteristic BCs (&lt;b&gt;[Thompson87]&lt;/b&gt;, &lt;b&gt;[Thompson90]&lt;/b&gt;; &lt;span class=&quot;tt&quot;&gt;bc_xbeg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md234',1,'']]],
  ['characteristic_20boundary_20conditions_17',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md34',1,'']]],
  ['checklist_18',['Performance Checklist',['../expectedPerformance.html#autotoc_md310',1,'']]],
  ['chem_5fparams_19',['chem_params',['../parameters.html#autotoc_md423',1,'']]],
  ['chem_5fwrt_5fy_20',['chem_wrt_Y',['../parameters.html#autotoc_md380',1,'']]],
  ['chemistry_21',['17. Chemistry',['../case.html#autotoc_md31',1,'']]],
  ['chemistry_20and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_22',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.7)',['../equations.html#autotoc_md201',1,'']]],
  ['chemistry_20chemistry_20true_23',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['chemistry_20true_24',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['chemistry_20true_20wilfong26_20sec_204_201_207_25',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.7)',['../equations.html#autotoc_md201',1,'']]],
  ['ci_20commands_26',['CI Commands',['../cli-reference.html#autotoc_md95',1,'']]],
  ['ci_20failures_27',['Common CI Failures',['../contributing.html#autotoc_md147',1,'']]],
  ['ci_20pipeline_28',['CI Pipeline',['../contributing.html#autotoc_md144',1,'']]],
  ['classes_20commander89_20ando11_29',['6.1.1 Method of Classes (&lt;b&gt;[Commander89]&lt;/b&gt;; &lt;b&gt;[Ando11]&lt;/b&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['clean_30',['clean',['../cli-reference.html#autotoc_md65',1,'']]],
  ['clean_20rebuild_31',['Clean Rebuild',['../troubleshooting.html#autotoc_md503',1,'']]],
  ['cli_32',['Docker CLI',['../docker.html#autotoc_md154',1,'']]],
  ['clusters_20via_20apptainer_20singularity_33',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md157',1,'']]],
  ['cmake_20could_20not_20find_20a_20fortran_20compiler_34',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['cmake_20could_20not_20find_20mpi_35',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md524',1,'']]],
  ['code_20coverage_36',['Code Coverage',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['code_20review_20and_20merge_37',['Code Review and Merge',['../contributing.html#autotoc_md150',1,'']]],
  ['coded_20patches_38',['Hard Coded Patches',['../case.html#autotoc_md10',1,'']]],
  ['coding_20standards_39',['Coding Standards',['../contributing.html#autotoc_md119',1,'']]],
  ['combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_40',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.1.7)',['../equations.html#autotoc_md201',1,'']]],
  ['command_20line_20arguments_41',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['command_20line_20reference_42',['Command Line Reference',['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md55',1,'Command Line Reference'],['../parameters.html#autotoc_md451',1,'Command Line Reference']]],
  ['commander89_20ando11_43',['6.1.1 Method of Classes (&lt;b&gt;[Commander89]&lt;/b&gt;; &lt;b&gt;[Ando11]&lt;/b&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['commands_44',['Commands',['../cli-reference.html#autotoc_md95',1,'CI Commands'],['../cli-reference.html#autotoc_md58',1,'Commands'],['../cli-reference.html#autotoc_md84',1,'Development Commands'],['../cli-reference.html#autotoc_md100',1,'Other Commands'],['../troubleshooting.html#autotoc_md491',1,'Useful Commands'],['../cli-reference.html#autotoc_md69',1,'Utility Commands']]],
  ['commit_20messages_45',['Commit Messages',['../contributing.html#autotoc_md118',1,'']]],
  ['common_46',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md141',1,'']]],
  ['common_20build_20errors_47',['Common Build Errors',['../troubleshooting.html#autotoc_md523',1,'']]],
  ['common_20ci_20failures_48',['Common CI Failures',['../contributing.html#autotoc_md147',1,'']]],
  ['common_20configuration_20patterns_49',['🚀 Common Configuration Patterns',['../case_constraints.html#autotoc_md44',1,'']]],
  ['common_20options_50',['Common Options',['../cli-reference.html#autotoc_md105',1,'']]],
  ['common_20pitfalls_51',['Common Pitfalls',['../contributing.html#autotoc_md122',1,'']]],
  ['common_20runtime_20errors_52',['Common Runtime Errors',['../troubleshooting.html#autotoc_md530',1,'']]],
  ['compare_53',['packer compare',['../cli-reference.html#autotoc_md76',1,'']]],
  ['compatibility_54',['Compatibility',['../case_constraints.html#autotoc_md45',1,'📊 Feature Compatibility'],['../case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['compiler_55',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['compiler_20agnostic_20tools_56',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md350',1,'']]],
  ['compiler_20documentation_57',['Compiler Documentation',['../gpuParallelization.html#autotoc_md359',1,'']]],
  ['compiler_20options_58',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md355',1,'']]],
  ['compiler_20portability_59',['Compiler Portability',['../contributing.html#autotoc_md129',1,'']]],
  ['compiler_20tools_60',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md352',1,'']]],
  ['compilers_61',['Supported Compilers',['../running.html#autotoc_md467',1,'']]],
  ['completion_62',['Shell Completion',['../getting-started.html#autotoc_md334',1,'']]],
  ['completion_63',['completion',['../cli-reference.html#autotoc_md78',1,'']]],
  ['component_20inert_20shock_20tube_64',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md287',1,'']]],
  ['component_20reactive_20shock_20tube_65',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md258',1,'']]],
  ['comprehensive_20equations_20reference_66',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md166',1,'']]],
  ['computation_20macros_67',['Computation Macros',['../gpuParallelization.html#autotoc_md341',1,'']]],
  ['computational_20domain_68',['2. Computational Domain',['../case.html#autotoc_md7',1,'']]],
  ['computer_20templates_69',['Computer Templates',['../running.html#autotoc_md478',1,'']]],
  ['condition_70',['Condition',['../equations.html#autotoc_md229',1,'15.4 CFL Condition'],['../examples.html#autotoc_md276',1,'Final Condition'],['../examples.html#autotoc_md278',1,'Final Condition'],['../examples.html#autotoc_md297',1,'Final Condition'],['../examples.html#autotoc_md300',1,'Final Condition'],['../examples.html#autotoc_md245',1,'Initial Condition'],['../examples.html#autotoc_md251',1,'Initial Condition'],['../examples.html#autotoc_md254',1,'Initial Condition'],['../examples.html#autotoc_md259',1,'Initial Condition'],['../examples.html#autotoc_md273',1,'Initial Condition'],['../examples.html#autotoc_md288',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_71',['Condition and Linear Theory',['../examples.html#autotoc_md257',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md291',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_72',['Initial Condition and Result',['../examples.html#autotoc_md293',1,'']]],
  ['condition_20density_73',['Condition Density',['../examples.html#autotoc_md286',1,'Final Condition (Density)'],['../examples.html#autotoc_md302',1,'Final Condition (Density)']]],
  ['condition_20patches_74',['Boundary Condition Patches',['../case.html#autotoc_md17',1,'']]],
  ['conditions_75',['Conditions',['../equations.html#autotoc_md232',1,'16. Boundary Conditions'],['../examples.html#autotoc_md262',1,'Density Initial and Final Conditions']]],
  ['conditions_76',['conditions',['../case.html#autotoc_md33',1,'Boundary conditions'],['../case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20flags_77',['Build Configuration Flags',['../cli-reference.html#autotoc_md107',1,'']]],
  ['configuration_20patterns_78',['🚀 Common Configuration Patterns',['../case_constraints.html#autotoc_md44',1,'']]],
  ['conservative_20variables_20ordering_79',['Conservative Variables Ordering',['../case.html#autotoc_md37',1,'']]],
  ['consistency_80',['Physics and Model Consistency',['../contributing.html#autotoc_md127',1,'']]],
  ['constant_20time_20stepping_81',['Constant Time-Stepping',['../case.html#autotoc_md18',1,'']]],
  ['constraint_20violations_82',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md531',1,'']]],
  ['containers_83',['Containers',['../docker.html',1,'Containers'],['../docker.html#autotoc_md151',1,'Containers'],['../docker.html#autotoc_md155',1,'Details on Running Containers'],['../getting-started.html#autotoc_md328',1,'Using Containers']]],
  ['contributing_84',['Contributing',['../contributing.html',1,'']]],
  ['contributing_20to_20mfc_85',['Contributing to MFC',['../contributing.html#autotoc_md110',1,'']]],
  ['control_20macros_86',['Data Control Macros',['../gpuParallelization.html#autotoc_md343',1,'']]],
  ['coordinates_87',['16. Cylindrical Coordinates',['../case.html#autotoc_md30',1,'']]],
  ['coordinates_88',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md539',1,'']]],
  ['coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_89',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.3)',['../equations.html#autotoc_md181',1,'']]],
  ['corrections_20wilfong26_20sec_204_202_204_90',['17. Low Mach Number Corrections (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 4.2.4)',['../equations.html#autotoc_md237',1,'']]],
  ['correctness_91',['Correctness',['../contributing.html#autotoc_md126',1,'MPI Correctness'],['../troubleshooting.html#autotoc_md521',1,'Performance vs Correctness']]],
  ['could_20not_20find_20a_20fortran_20compiler_92',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['could_20not_20find_20mpi_93',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md524',1,'']]],
  ['count_94',['count',['../cli-reference.html#autotoc_md91',1,'']]],
  ['count_5fdiff_95',['count_diff',['../cli-reference.html#autotoc_md93',1,'']]],
  ['coverage_96',['Code Coverage',['../troubleshooting.html#autotoc_md501',1,'']]],
  ['cpu_97',['CPU',['../expectedPerformance.html#autotoc_md317',1,'IBM Power9 CPU'],['../expectedPerformance.html#autotoc_md322',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_98',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md352',1,'']]],
  ['cray_20general_20options_99',['Cray General Options',['../gpuParallelization.html#autotoc_md353',1,'']]],
  ['cray_20openacc_20options_100',['Cray OpenACC Options',['../gpuParallelization.html#autotoc_md354',1,'']]],
  ['create_20a_20new_20fortran_20module_101',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['creating_20a_20new_20case_102',['Creating a New Case',['../getting-started.html#autotoc_md333',1,'']]],
  ['creating_20tests_103',['Creating Tests',['../testing.html#autotoc_md485',1,'']]],
  ['creator_20guide_104',['Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide']]],
  ['customizing_20the_20script_105',['Step 2: Customizing the script',['../visualization.html#autotoc_md544',1,'']]],
  ['cyl_5fcoord_20true_20wilfong26_20sec_202_203_106',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.3)',['../equations.html#autotoc_md181',1,'']]],
  ['cylindrical_20coordinates_107',['16. Cylindrical Coordinates',['../case.html#autotoc_md30',1,'']]],
  ['cylindrical_20coordinates_108',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md539',1,'']]],
  ['cylindrical_20coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_109',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;b&gt;[Wilfong26]&lt;/b&gt; Sec. 2.3)',['../equations.html#autotoc_md181',1,'']]]
];
