var searchData=
[
  ['ranks_0',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md391',1,'']]],
  ['rayleigh_20taylor_20instability_202d_1',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md177',1,'']]],
  ['rayleigh_20taylor_20instability_203d_2',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md133',1,'']]],
  ['reactive_20shock_20tube_3',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md145',1,'']]],
  ['reactor_4',['Perfectly Stirred Reactor',['../examples.html#autotoc_md152',1,'']]],
  ['rebuild_5',['Clean Rebuild',['../troubleshooting.html#autotoc_md385',1,'']]],
  ['recommended_6',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md191',1,'']]],
  ['reference_7',['Reference',['../case_constraints.html#autotoc_md53',1,'📖 Quick Parameter Reference'],['../parameters.html',1,'Case Parameters Reference'],['../parameters.html#autotoc_md246',1,'Case Parameters Reference'],['../cli-reference.html',1,'Command Line Reference'],['../cli-reference.html#autotoc_md55',1,'Command Line Reference'],['../parameters.html#autotoc_md334',1,'Command Line Reference'],['../cli-reference.html#autotoc_md57',1,'Quick Reference'],['../troubleshooting.html#autotoc_md370',1,'Quick Reference'],['../index.html#autotoc_md336',1,'Reference']]],
  ['references_8',['References',['../references.html',1,'References'],['../references.html#autotoc_md340',1,'References']]],
  ['regenerating_20golden_20files_9',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md397',1,'']]],
  ['remote_20visualization_20on_20pace_20phoenix_10',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md424',1,'']]],
  ['restarting_20cases_11',['Restarting Cases',['../running.html#autotoc_md363',1,'']]],
  ['result_12',['Result',['../examples.html#autotoc_md169',1,'Initial Condition and Result'],['../examples.html#autotoc_md128',1,'Result'],['../examples.html#autotoc_md136',1,'Result'],['../examples.html#autotoc_md139',1,'Result'],['../examples.html#autotoc_md167',1,'Result'],['../examples.html#autotoc_md174',1,'Result']]],
  ['results_13',['Results',['../expectedPerformance.html#autotoc_md197',1,'Benchmark Results'],['../examples.html#autotoc_md147',1,'Results'],['../examples.html#autotoc_md185',1,'Results']]],
  ['richtmyer_20meshkov_20instability_202d_14',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md156',1,'']]],
  ['riemann_20solvers_15',['⚙️ Riemann Solvers',['../case_constraints.html#autotoc_md51',1,'']]],
  ['riemann_20test_202d_16',['2D Riemann Test (2D)',['../examples.html#autotoc_md150',1,'']]],
  ['run_17',['run',['../cli-reference.html#autotoc_md61',1,'']]],
  ['run_20fails_18',['Run Fails?',['../troubleshooting.html#autotoc_md377',1,'']]],
  ['running_19',['Running',['../running.html',1,'Running'],['../running.html#autotoc_md341',1,'Running']]],
  ['running_20an_20example_20case_20',['Running an Example Case',['../getting-started.html#autotoc_md215',1,'']]],
  ['running_20containers_21',['Details on Running Containers',['../docker.html#autotoc_md114',1,'']]],
  ['running_20on_20gpus_22',['Running on GPUs',['../running.html#autotoc_md346',1,'Running on GPUs'],['../running.html#autotoc_md348',1,'Running on GPUs']]],
  ['running_20pace_20paraview_20server_23',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md427',1,'']]],
  ['running_20specific_20tests_24',['Running Specific Tests',['../troubleshooting.html#autotoc_md394',1,'']]],
  ['running_20the_20test_20suite_25',['Running the Test Suite',['../getting-started.html#autotoc_md214',1,'']]],
  ['running_20with_20fewer_20ranks_26',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md391',1,'']]],
  ['runs_27',['Runs',['../running.html#autotoc_md365',1,'Example Runs'],['../troubleshooting.html#autotoc_md389',1,'Verbose Runs']]],
  ['runtime_28',['1. Runtime',['../case.html#autotoc_md6',1,'']]],
  ['runtime_20debugging_29',['Runtime Debugging',['../troubleshooting.html#autotoc_md387',1,'']]],
  ['runtime_20errors_30',['Common Runtime Errors',['../troubleshooting.html#autotoc_md412',1,'']]]
];
