var searchData=
[
  ['facing_20step_202d_0',['Facing Step 2D',['../examples.html#autotoc_md285',1,'Backward Facing Step (2D)'],['../examples.html#autotoc_md301',1,'Forward Facing Step (2D)']]],
  ['failed_1',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md526',1,'']]],
  ['fails_2',['Fails',['../troubleshooting.html#autotoc_md494',1,'Build Fails?'],['../troubleshooting.html#autotoc_md495',1,'Run Fails?'],['../troubleshooting.html#autotoc_md496',1,'Test Fails?']]],
  ['fails_20with_20gpu_20openacc_20errors_3',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md527',1,'']]],
  ['failures_4',['Failures',['../contributing.html#autotoc_md147',1,'Common CI Failures'],['../troubleshooting.html#autotoc_md516',1,'Understanding Test Failures']]],
  ['false_20preston07_5',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;b&gt;[Preston07]&lt;/b&gt;)',['../equations.html#autotoc_md189',1,'']]],
  ['families_6',['Parameter Families',['../parameters.html#autotoc_md363',1,'']]],
  ['fd_5forder_201_202_204_7',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md230',1,'']]],
  ['feature_20compatibility_8',['Feature Compatibility',['../case_constraints.html#autotoc_md45',1,'📊 Feature Compatibility'],['../case.html#autotoc_md5',1,'Feature Compatibility']]],
  ['fetching_20mfc_9',['Fetching MFC',['../getting-started.html#autotoc_md324',1,'']]],
  ['fewer_20ranks_10',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md509',1,'']]],
  ['field_20setup_11',['10. Velocity Field Setup',['../case.html#autotoc_md24',1,'']]],
  ['figure_20of_20merit_3a_20grind_20time_20performance_12',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md313',1,'']]],
  ['files_13',['Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md1',1,'Case Files'],['../troubleshooting.html#autotoc_md515',1,'Regenerating Golden Files']]],
  ['final_20condition_14',['Final Condition',['../examples.html#autotoc_md276',1,'Final Condition'],['../examples.html#autotoc_md278',1,'Final Condition'],['../examples.html#autotoc_md297',1,'Final Condition'],['../examples.html#autotoc_md300',1,'Final Condition']]],
  ['final_20condition_20and_20linear_20theory_15',['Final Condition and Linear Theory',['../examples.html#autotoc_md257',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md291',1,'Final Condition and Linear Theory']]],
  ['final_20condition_20density_16',['Final Condition Density',['../examples.html#autotoc_md286',1,'Final Condition (Density)'],['../examples.html#autotoc_md302',1,'Final Condition (Density)']]],
  ['final_20conditions_17',['Density Initial and Final Conditions',['../examples.html#autotoc_md262',1,'']]],
  ['final_20time_18',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md243',1,'']]],
  ['find_20a_20fortran_20compiler_19',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['find_20mpi_20',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md524',1,'']]],
  ['finite_20differences_20fd_5forder_201_202_204_21',['15.5 Finite Differences (&lt;span class=&quot;tt&quot;&gt;fd_order = 1, 2, 4&lt;/span&gt;)',['../equations.html#autotoc_md230',1,'']]],
  ['first_20blocks_20all_20other_20jobs_22',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['five_20equation_20model_20model_5feqns_202_23',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md171',1,'']]],
  ['flags_24',['Flags',['../cli-reference.html#autotoc_md107',1,'Build Configuration Flags'],['../troubleshooting.html#autotoc_md489',1,'Debugging Flags'],['../expectedPerformance.html#autotoc_md308',1,'Other Optimization Flags'],['../troubleshooting.html#autotoc_md490',1,'Profiling Flags']]],
  ['flow_25',['Flow',['../gpuParallelization.html#autotoc_md339',1,'Data Flow'],['../contributing.html#autotoc_md115',1,'Simulation Data Flow']]],
  ['flow_20visualization_26',['Flow visualization',['../visualization.html',1,'Flow visualization'],['../visualization.html#autotoc_md537',1,'Flow visualization']]],
  ['fluid_20material’s_27',['5. Fluid Material’s',['../case.html#autotoc_md15',1,'']]],
  ['fluid_20structure_20interaction_28',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md193',1,'']]],
  ['fluid_5fpp_29',['fluid_pp',['../parameters.html#autotoc_md371',1,'']]],
  ['fluid_5frho_30',['fluid_rho',['../parameters.html#autotoc_md414',1,'']]],
  ['flux_20limiting_31',['18. Flux Limiting',['../equations.html#autotoc_md239',1,'']]],
  ['flux_5fwrt_32',['flux_wrt',['../parameters.html#autotoc_md425',1,'']]],
  ['for_20gpus_33',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md349',1,'']]],
  ['for_20optimization_34',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md309',1,'']]],
  ['for_20portability_35',['For Portability',['../docker.html#autotoc_md159',1,'']]],
  ['for_20stiff_20bubble_20dynamics_36',['Strang Splitting (&lt;b&gt;[Strang68]&lt;/b&gt;) (for stiff bubble dynamics)',['../equations.html#autotoc_md228',1,'']]],
  ['forces_37',['13. Body Forces',['../case.html#autotoc_md27',1,'']]],
  ['forces_20bf_5fx_20bf_5fy_20bf_5fz_38',['13. Body Forces (&lt;span class=&quot;tt&quot;&gt;bf_x&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_y&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;bf_z&lt;/span&gt;)',['../equations.html#autotoc_md211',1,'']]],
  ['format_39',['format',['../cli-reference.html#autotoc_md87',1,'']]],
  ['formatted_20output_40',['7. Formatted Output',['../case.html#autotoc_md20',1,'']]],
  ['fortran_20compiler_41',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md525',1,'']]],
  ['fortran_20module_42',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['forward_20facing_20step_202d_43',['Forward Facing Step (2D)',['../examples.html#autotoc_md301',1,'']]],
  ['found_20on_20hpc_44',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md528',1,'']]],
  ['fypp_20and_20gpu_45',['Fypp and GPU',['../contributing.html#autotoc_md131',1,'']]],
  ['fypp_20preprocessing_20failed_46',['&quot;Fypp preprocessing failed&quot;',['../troubleshooting.html#autotoc_md526',1,'']]]
];
