var searchData=
[
  ['o_20and_20startup_0',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['of_20classes_20commander89_20ando11_1',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md158',1,'']]],
  ['of_20input_20parameters_2',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['of_20merit_3a_20grind_20time_20performance_3',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md287',1,'']]],
  ['of_20primitive_20variables_4',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md20',1,'']]],
  ['of_20state_5',['3. Equations of State',['../equations.html#autotoc_md148',1,'']]],
  ['omega_5fwrt_6',['omega_wrt',['../parameters.html#omega_wrt',1,'']]],
  ['on_20gpus_7',['on GPUs',['../running.html#autotoc_md459',1,'Running on GPUs'],['../running.html#autotoc_md461',1,'Running on GPUs']]],
  ['on_20hpc_8',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md523',1,'']]],
  ['on_20pace_20phoenix_9',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md558',1,'']]],
  ['on_20running_20containers_10',['Details on Running Containers',['../docker.html#autotoc_md127',1,'']]],
  ['only_11',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md197',1,'']]],
  ['openacc_20errors_12',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md522',1,'']]],
  ['openacc_20options_13',['OpenACC Options',['../gpuParallelization.html#autotoc_md330',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md333',1,'NVHPC OpenACC Options']]],
  ['openmp_20options_14',['NVHPC OpenMP Options',['../gpuParallelization.html#autotoc_md334',1,'']]],
  ['openmp_20tools_15',['OpenMP tools',['../gpuParallelization.html#autotoc_md327',1,'']]],
  ['optimization_16',['Profiling for Optimization',['../expectedPerformance.html#autotoc_md283',1,'']]],
  ['optimization_17',['When to use case optimization',['../expectedPerformance.html#autotoc_md281',1,'']]],
  ['optimization_20flags_18',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md282',1,'']]],
  ['optimization_20recommended_19',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md280',1,'']]],
  ['option_20reference_20',['Complete option reference',['../visualization.html#autotoc_md552',1,'']]],
  ['optional_20accepting_20command_20line_20arguments_21',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['options_22',['Options',['../running.html#autotoc_md471',1,'Batch Options'],['../cli-reference.html#autotoc_md77',1,'Common Options'],['../gpuParallelization.html#autotoc_md329',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md330',1,'Cray OpenACC Options'],['../gpuParallelization.html#autotoc_md331',1,'NVHPC Compiler Options'],['../gpuParallelization.html#autotoc_md332',1,'NVHPC General Options'],['../gpuParallelization.html#autotoc_md333',1,'NVHPC OpenACC Options'],['../gpuParallelization.html#autotoc_md334',1,'NVHPC OpenMP Options']]],
  ['options_23',['Rendering options',['../visualization.html#autotoc_md544',1,'']]],
  ['or_20hangs_24',['MPI errors or hangs',['../troubleshooting.html#autotoc_md529',1,'']]],
  ['or_20has_20artifacts_25',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md535',1,'']]],
  ['or_20silo_5fhdf5_20directory_20found_26',['&quot;No &apos;binary/&apos; or &apos;silo_hdf5/&apos; directory found&quot;',['../troubleshooting.html#autotoc_md532',1,'']]],
  ['ordering_27',['Ordering',['../case.html#autotoc_md38',1,'Conservative Variables Ordering'],['../case.html#autotoc_md39',1,'Primitive Variables Ordering']]],
  ['osher_20problem_201d_28',['Shu-Osher problem (1D)',['../examples.html#autotoc_md232',1,'']]],
  ['other_20commands_29',['Other Commands',['../cli-reference.html#autotoc_md74',1,'']]],
  ['other_20jobs_30',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md117',1,'']]],
  ['other_20model_20variants_31',['2.3 Other Model Variants',['../equations.html#autotoc_md146',1,'']]],
  ['other_20optimization_20flags_32',['Other Optimization Flags',['../expectedPerformance.html#autotoc_md282',1,'']]],
  ['out_33',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['output_34',['Output',['../case.html#sec-formatted-output',1,'7. Formatted Output'],['../physics_constraints.html#autotoc_md447',1,'FFT Output'],['../physics_constraints.html#autotoc_md446',1,'Vorticity Output']]],
  ['output_35',['Serial data output',['../visualization.html#autotoc_md557',1,'']]],
  ['output_20location_36',['Test Output Location',['../troubleshooting.html#autotoc_md509',1,'']]],
  ['output_20variable_37',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md112',1,'']]],
  ['overview_38',['Overview',['../equations.html#autotoc_md140',1,'1. Overview'],['../contributing.html#autotoc_md84',1,'Architecture Overview'],['../cli-reference.html#autotoc_md46',1,'Overview'],['../parameters.html#autotoc_md338',1,'Overview']]]
];
