var searchData=
[
  ['backward_20facing_20step_202d_0',['Backward Facing Step (2D)',['../examples.html#autotoc_md170',1,'']]],
  ['base_20images_1',['Base Images',['../docker.html#autotoc_md121',1,'']]],
  ['basic_20skeleton_2',['Basic Skeleton',['../case.html#autotoc_md2',1,'']]],
  ['basic_20usage_3',['Basic Usage',['../running.html#autotoc_md357',1,'']]],
  ['batch_20execution_4',['Batch Execution',['../running.html#autotoc_md356',1,'']]],
  ['batch_20options_5',['Batch Options',['../running.html#autotoc_md358',1,'']]],
  ['bc_5fx_6',['bc_x',['../parameters.html#autotoc_md268',1,'']]],
  ['bc_5fy_7',['bc_y',['../parameters.html#autotoc_md271',1,'']]],
  ['bc_5fz_8',['bc_z',['../parameters.html#autotoc_md274',1,'']]],
  ['beginner_20examples_9',['🟢 Beginner Examples',['../case_constraints.html#autotoc_md41',1,'']]],
  ['bench_10',['bench',['../cli-reference.html#autotoc_md96',1,'']]],
  ['bench_5fdiff_11',['bench_diff',['../cli-reference.html#autotoc_md98',1,'']]],
  ['benchmark_20results_12',['Benchmark Results',['../expectedPerformance.html#autotoc_md197',1,'']]],
  ['body_20forces_13',['13. Body Forces',['../case.html#autotoc_md27',1,'']]],
  ['boundary_20condition_20patches_14',['Boundary Condition Patches',['../case.html#autotoc_md17',1,'']]],
  ['boundary_20conditions_15',['Boundary conditions',['../case.html#autotoc_md33',1,'Boundary conditions'],['../case.html#autotoc_md34',1,'Generalized Characteristic Boundary conditions']]],
  ['boundary_20patch_20types_16',['Immersed Boundary Patch Types',['../case.html#autotoc_md36',1,'']]],
  ['boundary_20patches_17',['4. Immersed Boundary Patches',['../case.html#autotoc_md13',1,'']]],
  ['bow_20shock_203d_18',['IBM Bow Shock (3D)',['../examples.html#autotoc_md186',1,'']]],
  ['bub_5fpp_19',['bub_pp',['../parameters.html#autotoc_md283',1,'']]],
  ['bubble_20model_20',['Bubble Model',['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]],
  ['bubble_20models_21',['Bubble Models',['../case_constraints.html#autotoc_md52',1,'💧 Bubble Models'],['../case.html#autotoc_md21',1,'9. Sub-grid Bubble Models'],['../case_constraints.html#autotoc_md47',1,'Bubble Models']]],
  ['build_22',['build',['../cli-reference.html#autotoc_md59',1,'']]],
  ['build_20configuration_20flags_23',['Build Configuration Flags',['../cli-reference.html#autotoc_md107',1,'']]],
  ['build_20debugging_24',['Build Debugging',['../troubleshooting.html#autotoc_md380',1,'']]],
  ['build_20environment_25',['Build Environment',['../getting-started.html#autotoc_md211',1,'']]],
  ['build_20errors_26',['Common Build Errors',['../troubleshooting.html#autotoc_md405',1,'']]],
  ['build_20fails_27',['Build Fails?',['../troubleshooting.html#autotoc_md376',1,'']]],
  ['build_20fails_20with_20gpu_20openacc_20errors_28',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md409',1,'']]],
  ['building_20mfc_29',['Building MFC',['../getting-started.html#autotoc_md212',1,'']]],
  ['building_20with_20gpu_20support_30',['Building with GPU Support',['../running.html#autotoc_md347',1,'']]],
  ['builds_31',['Debug Builds',['../troubleshooting.html#autotoc_md382',1,'']]]
];
