var searchData=
[
  ['a_20fortran_20compiler_0',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md451',1,'']]],
  ['a_20gpu_20parallel_20loop_1',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md134',1,'']]],
  ['a_20new_20case_2',['Creating a New Case',['../getting-started.html#autotoc_md259',1,'']]],
  ['a_20new_20fortran_20module_3',['How to Create a New Fortran Module',['../contributing.html#autotoc_md137',1,'']]],
  ['a_20new_20simulation_20parameter_4',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md133',1,'']]],
  ['a_20post_20processing_20output_20variable_5',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md140',1,'']]],
  ['a_20pull_20request_6',['Submitting a Pull Request',['../contributing.html#autotoc_md149',1,'']]],
  ['a_20test_20case_7',['How to Add a Test Case',['../contributing.html#autotoc_md136',1,'']]],
  ['about_8',['About',['../index.html#autotoc_md383',1,'']]],
  ['accepting_20command_20line_20arguments_9',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['achieving_20maximum_20performance_10',['Achieving Maximum Performance',['../expectedPerformance.html#autotoc_md231',1,'']]],
  ['acoustic_11',['acoustic',['../parameters.html#autotoc_md303',1,'']]],
  ['acoustic_20source_12',['8. Acoustic Source',['../case.html#acoustic-source',1,'']]],
  ['acoustic_20supports_13',['Acoustic Supports',['../case.html#acoustic-supports',1,'']]],
  ['adaptive_20time_20stepping_14',['Adaptive Time-Stepping',['../case.html#autotoc_md19',1,'']]],
  ['add_20a_20new_20simulation_20parameter_15',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md133',1,'']]],
  ['add_20a_20post_20processing_20output_20variable_16',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md140',1,'']]],
  ['add_20a_20test_20case_17',['How to Add a Test Case',['../contributing.html#autotoc_md136',1,'']]],
  ['advanced_20examples_18',['🔴 Advanced Examples',['../case_constraints.html#autotoc_md43',1,'']]],
  ['advanced_20topics_19',['Advanced Topics',['../index.html#autotoc_md381',1,'']]],
  ['agnostic_20tools_20',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md276',1,'']]],
  ['algorithm_21',['6. Simulation Algorithm',['../case.html#autotoc_md16',1,'']]],
  ['all_20other_20jobs_22',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['allocate_20and_20manage_20gpu_20arrays_23',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['allocation_24',['Memory and Allocation',['../contributing.html#autotoc_md125',1,'']]],
  ['alpha_5frho_5fe_5fwrt_25',['alpha_rho_e_wrt',['../parameters.html#autotoc_md331',1,'']]],
  ['alpha_5frho_5fwrt_26',['alpha_rho_wrt',['../parameters.html#autotoc_md334',1,'']]],
  ['alpha_5fwrt_27',['alpha_wrt',['../parameters.html#autotoc_md337',1,'']]],
  ['amd_20gpu_20profiling_28',['AMD GPU Profiling',['../troubleshooting.html#autotoc_md446',1,'']]],
  ['amd_20gpus_29',['AMD GPUs',['../running.html#autotoc_md398',1,'']]],
  ['amd_20mi250x_20gpu_30',['AMD MI250X GPU',['../expectedPerformance.html#autotoc_md241',1,'']]],
  ['an_20example_20case_31',['Running an Example Case',['../getting-started.html#autotoc_md256',1,'']]],
  ['analytical_20definition_20of_20primitive_20variables_32',['Analytical Definition of Primitive Variables',['../case.html#autotoc_md9',1,'']]],
  ['and_20allocation_33',['Memory and Allocation',['../contributing.html#autotoc_md125',1,'']]],
  ['and_20final_20conditions_34',['Density Initial and Final Conditions',['../examples.html#autotoc_md192',1,'']]],
  ['and_20gpu_35',['Fypp and GPU',['../contributing.html#autotoc_md131',1,'']]],
  ['and_20indexing_36',['Array Bounds and Indexing',['../contributing.html#autotoc_md123',1,'']]],
  ['and_20linear_20theory_37',['and Linear Theory',['../examples.html#autotoc_md175',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md219',1,'Final Condition and Linear Theory']]],
  ['and_20manage_20gpu_20arrays_38',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['and_20merge_39',['Code Review and Merge',['../contributing.html#autotoc_md150',1,'']]],
  ['and_20model_20consistency_40',['Physics and Model Consistency',['../contributing.html#autotoc_md127',1,'']]],
  ['and_20performance_20test_41',['Scaling and Performance test',['../examples.html#autotoc_md170',1,'']]],
  ['and_20result_42',['Initial Condition and Result',['../examples.html#autotoc_md210',1,'']]],
  ['and_20test_20matrix_43',['Build and Test Matrix',['../contributing.html#autotoc_md146',1,'']]],
  ['and_20tips_20for_20gpus_44',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md275',1,'']]],
  ['and_20type_20safety_45',['Precision and Type Safety',['../contributing.html#autotoc_md124',1,'']]],
  ['api_20documentation_46',['Macro API Documentation',['../gpuParallelization.html#autotoc_md263',1,'']]],
  ['apptainer_20singularity_47',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md157',1,'']]],
  ['architecture_20notes_48',['Architecture Notes',['../contributing.html#autotoc_md130',1,'']]],
  ['architecture_20overview_49',['Architecture Overview',['../contributing.html#autotoc_md112',1,'']]],
  ['architecture_20support_50',['Architecture Support',['../docker.html#autotoc_md165',1,'']]],
  ['arguments_51',['(Optional) Accepting command line arguments',['../case.html#autotoc_md3',1,'']]],
  ['array_20bounds_20and_20indexing_52',['Array Bounds and Indexing',['../contributing.html#autotoc_md123',1,'']]],
  ['arrays_53',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['artificial_20mach_20number_54',['12. Artificial Mach Number',['../case.html#autotoc_md26',1,'']]],
  ['at_20final_20time_55',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md221',1,'']]],
  ['at_20transitional_20state_56',['Liutex visualization at transitional state',['../examples.html#autotoc_md223',1,'']]],
  ['authors_57',['Authors',['../authors.html',1,'Authors'],['../authors.html#autotoc_md0',1,'Authors']]],
  ['averaged_20bubble_20model_58',['Averaged Bubble Model',['../case.html#autotoc_md22',1,'9.1 Ensemble-Averaged Bubble Model'],['../case.html#autotoc_md23',1,'9.2 Volume-Averaged Bubble Model']]]
];
