var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md136',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md138',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md139',1,'']]],
  ['target_20selection_20t_20targets_4',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['taylor_20green_20vortex_203d_6',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md265',1,'']]],
  ['taylor_20instability_202d_7',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md288',1,'']]],
  ['taylor_20instability_203d_8',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md293',1,'']]],
  ['templates_9',['Computer Templates',['../running.html#autotoc_md525',1,'']]],
  ['tension_10',['Surface Tension',['../physics_constraints.html#autotoc_md478',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_11',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md179',1,'']]],
  ['tensor_20viscous_20true_12',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md155',1,'']]],
  ['terminal_20ui_20tui_13',['Terminal UI (TUI)',['../visualization.html#autotoc_md601',1,'']]],
  ['test_14',['test',['../examples.html#autotoc_md284',1,'Scaling and Performance test'],['../cli-reference.html#test',1,'test']]],
  ['test_202d_15',['2D Riemann Test (2D)',['../examples.html#autotoc_md222',1,'']]],
  ['test_20case_16',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['test_20debugging_17',['Test Debugging',['../troubleshooting.html#autotoc_md558',1,'']]],
  ['test_20execution_18',['Serial Test Execution',['../troubleshooting.html#autotoc_md560',1,'']]],
  ['test_20fails_19',['Test Fails?',['../troubleshooting.html#autotoc_md543',1,'']]],
  ['test_20failures_20',['Understanding Test Failures',['../troubleshooting.html#autotoc_md563',1,'']]],
  ['test_20matrix_21',['Build and Test Matrix',['../contributing.html#autotoc_md121',1,'']]],
  ['test_20output_20location_22',['Test Output Location',['../troubleshooting.html#autotoc_md561',1,'']]],
  ['test_20suite_23',['Running the Test Suite',['../getting-started.html#autotoc_md341',1,'']]],
  ['testing_24',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md118',1,'Testing'],['../testing.html#autotoc_md531',1,'Testing']]],
  ['testing_20post_20process_25',['Testing Post Process',['../testing.html#autotoc_md533',1,'']]],
  ['tests_26',['Tests',['../testing.html#autotoc_md532',1,'Creating Tests'],['../troubleshooting.html#autotoc_md559',1,'Running Specific Tests']]],
  ['the_20build_20fits_20together_27',['How the Build Fits Together',['../contributing.html#autotoc_md91',1,'']]],
  ['the_20homebrew_20package_20macos_28',['Using the Homebrew package (macOS)',['../running.html#autotoc_md507',1,'']]],
  ['the_20precision_20system_29',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['the_20script_30',['Step 2: Customizing the script',['../visualization.html#autotoc_md612',1,'']]],
  ['the_20simulation_20loop_31',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['the_20test_20suite_32',['Running the Test Suite',['../getting-started.html#autotoc_md341',1,'']]],
  ['theory_33',['Theory',['../examples.html#autotoc_md289',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md294',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_34',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[39]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['thermodynamic_20constraints_35',['Thermodynamic Constraints',['../physics_constraints.html#autotoc_md448',1,'']]],
  ['thickening_20poiseuille_20channel_36',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md247',1,'']]],
  ['thinning_20lid_20driven_20cavity_37',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md272',1,'']]],
  ['thinning_20poiseuille_20channel_38',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md253',1,'']]],
  ['thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_39',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['thompson90_20bc_5fx_20beg_205_20to_2012_40',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['three_20phase_20pipeline_41',['Three Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md87',1,'Three-Phase Pipeline']]],
  ['tiled_201d_20rendering_42',['Tiled 1D rendering',['../visualization.html#autotoc_md599',1,'']]],
  ['time_43',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md308',1,'']]],
  ['time_20integration_44',['15.3 Time Integration',['../equations.html#autotoc_md201',1,'']]],
  ['time_20performance_45',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md325',1,'']]],
  ['time_20stepping_46',['Time Stepping',['../case.html#autotoc_md27',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md26',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md488',1,'Time Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_47',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md203',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_48',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['timestep_20selection_49',['Timestep selection',['../visualization.html#autotoc_md595',1,'']]],
  ['tips_20for_20gpus_50',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md363',1,'']]],
  ['titarev_20toro_20problem_201d_51',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md267',1,'']]],
  ['to_2012_52',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[48]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[49]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md210',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_53',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md108',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_54',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['to_20add_20a_20test_20case_55',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_56',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md110',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_57',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['to_20document_20physics_20constraints_58',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_59',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['to_20guides_60',['How-To Guides',['../contributing.html#autotoc_md107',1,'']]],
  ['to_20mfc_61',['Contributing to MFC',['../contributing.html#autotoc_md84',1,'']]],
  ['to_20read_20silo_20hdf5_20files_62',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['to_20run_63',['to run',['../examples.html#autotoc_md232',1,'How to run'],['../examples.html#autotoc_md244',1,'How to run'],['../examples.html#autotoc_md250',1,'How to run'],['../examples.html#autotoc_md256',1,'How to run'],['../examples.html#autotoc_md275',1,'How to run'],['../examples.html#autotoc_md298',1,'How to run']]],
  ['to_20use_20case_20optimization_64',['When to use case optimization',['../expectedPerformance.html#autotoc_md319',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_65',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md109',1,'']]],
  ['together_66',['How the Build Fits Together',['../contributing.html#autotoc_md91',1,'']]],
  ['toolchain_67',['Toolchain',['../contributing.html#autotoc_md90',1,'Build Toolchain'],['../contributing.html#autotoc_md103',1,'Python Toolchain']]],
  ['tools_68',['Tools',['../gpuParallelization.html#autotoc_md366',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md345',1,'Helpful Tools']]],
  ['tools_69',['tools',['../gpuParallelization.html#autotoc_md364',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md365',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_70',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md363',1,'']]],
  ['topics_71',['Advanced Topics',['../index.html#autotoc_md503',1,'']]],
  ['toro_20problem_201d_72',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md267',1,'']]],
  ['toro94_73',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[51]&lt;/a&gt;)',['../equations.html#autotoc_md198',1,'']]],
  ['transformed_20gamma_74',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md450',1,'']]],
  ['transitional_20state_75',['Liutex visualization at transitional state',['../examples.html#autotoc_md260',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_76',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['triple_20point_202d_77',['2D Triple Point (2D)',['../examples.html#autotoc_md307',1,'']]],
  ['troubleshooting_20guide_78',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md534',1,'Troubleshooting Guide']]],
  ['true_79',['true',['../equations.html#autotoc_md189',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md153',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md155',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md160',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md203',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_80',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['true_20kamrin12_20wilfong26_20sec_204_201_206_81',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md171',1,'']]],
  ['true_20maeda18_82',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md167',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_83',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[40]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_84',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[43]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md179',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_85',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['true_20wilfong25a_86',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[54]&lt;/a&gt;)',['../equations.html#autotoc_md185',1,'']]],
  ['true_20wilfong26_20sec_202_203_87',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_88',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md183',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_89',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md173',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_90',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md177',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_91',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md182',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_92',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[53]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[34]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[55]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md211',1,'']]],
  ['tube_93',['Tube',['../examples.html#autotoc_md301',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md304',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_94',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md238',1,'']]],
  ['tube_20problem_201d_95',['Lax shock tube problem (1D)',['../examples.html#autotoc_md309',1,'']]],
  ['tui_96',['Terminal UI (TUI)',['../visualization.html#autotoc_md601',1,'']]],
  ['turb_5fpos_97',['turb_pos',['../parameters.html#turb_pos',1,'']]],
  ['turbulence_98',['20. Synthetic Turbulence',['../case.html#autotoc_md37',1,'']]],
  ['turbulent_20mixing_20layer_203d_99',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md259',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_100',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['two_20different_20viscosity_20parameters_101',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['type_20meanings_102',['Data Type Meanings',['../gpuParallelization.html#autotoc_md352',1,'']]],
  ['type_20safety_103',['Precision and Type Safety',['../contributing.html#autotoc_md99',1,'']]],
  ['types_104',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['types_105',['Patch types',['../case.html#patch-types',1,'']]]
];
