var searchData=
[
  ['i_20k_5ftherm_0',['4a. Fourier Heat Conduction (&lt;span class=&quot;tt&quot;&gt;fluid_pp(i)%k_therm&lt;/span&gt;)',['../equations.html#autotoc_md157',1,'']]],
  ['i_20o_20and_20startup_1',['I/O and Startup',['../architecture.html#autotoc_md9',1,'']]],
  ['ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_2',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md213',1,'']]],
  ['ib_5fairfoil_3',['ib_airfoil',['../parameters.html#ib_airfoil',1,'']]],
  ['ib_5fneighborhood_5fradius_20when_20ranks_20are_20not_20cubes_4',['Automatic &lt;span class=&quot;tt&quot;&gt;ib_neighborhood_radius&lt;/span&gt; when ranks are not cubes',['../examples.html#autotoc_md338',1,'']]],
  ['ibm_20bow_20shock_203d_5',['IBM Bow Shock (3D)',['../examples.html#autotoc_md331',1,'']]],
  ['ibm_20cfl_20dt_202d_6',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md237',1,'']]],
  ['ibm_20power9_20cpu_7',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md371',1,'']]],
  ['ibm_20power9_20cpu_20historical_8',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md366',1,'']]],
  ['ibm_20walled_20power_20law_20poiseuille_20channel_9',['2D IBM-Walled Power-Law Poiseuille Channel',['../examples.html#autotoc_md309',1,'']]],
  ['ic_20example_10',['2D Hardcodied IC Example',['../examples.html#autotoc_md333',1,'']]],
  ['ic_20extrusion_11',['IC Extrusion',['../physics_constraints.html#autotoc_md552',1,'']]],
  ['ic_20extrusion_20file_20parameters_12',['IC Extrusion File Parameters',['../physics_constraints.html#autotoc_md553',1,'']]],
  ['ideal_20gas_20eos_20chemistry_20chemistry_20true_13',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['ideal_20mhd_20mhd_20true_20wilfong26_20sec_204_201_209_14',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md183',1,'']]],
  ['igr_15',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md531',1,'']]],
  ['igr_20reconstruction_16',['IGR Reconstruction',['../equations.html#autotoc_md196',1,'']]],
  ['igr_20true_20wilfong25a_17',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['image_20device_20codegen_20instability_20worked_20around_20in_20the_20build_18',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['images_19',['Base Images',['../docker.html#autotoc_md137',1,'']]],
  ['immersed_20boundary_20force_20history_20',['Immersed-boundary force history',['../case.html#sec-ib-force-history',1,'']]],
  ['immersed_20boundary_20force_20on_20a_20thin_20plate_20issue_201849_21',['Immersed-boundary force on a thin plate (issue #1849)',['../examples.html#autotoc_md239',1,'']]],
  ['immersed_20boundary_20method_20ib_20true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_22',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[58]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md213',1,'']]],
  ['immersed_20boundary_20patch_20types_23',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['immersed_20boundary_20patches_24',['4. Immersed Boundary Patches',['../case.html#sec-immersed-boundary-patches',1,'']]],
  ['implementation_25',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md202',1,'']]],
  ['implementation_26',['Thermochemistry implementation',['../thermochemistry.html',1,'']]],
  ['in_20cylindrical_20coordinates_27',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md664',1,'']]],
  ['in_20dimensions_20out_28',['Dimensions In = Dimensions Out',['../equations.html#sec-dimensions-in-out',1,'']]],
  ['in_20inactive_20dimensions_29',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md511',1,'']]],
  ['in_20the_20build_30',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['in_20the_20same_20corner_31',['A second trap in the same corner',['../examples.html#autotoc_md320',1,'']]],
  ['inactive_20dimensions_32',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md511',1,'']]],
  ['indexing_33',['Array Bounds and Indexing',['../contributing.html#autotoc_md96',1,'']]],
  ['inert_20shock_20tube_34',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md221',1,'']]],
  ['inflow_20ramp_35',['GRCBC Inflow Ramp',['../physics_constraints.html#autotoc_md517',1,'']]],
  ['information_20geometric_20regularization_20igr_20true_20wilfong25a_36',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[59]&lt;/a&gt;)',['../equations.html#autotoc_md186',1,'']]],
  ['infrastructure_37',['Infrastructure',['../architecture.html#autotoc_md10',1,'']]],
  ['initial_20and_20final_20conditions_38',['Density Initial and Final Conditions',['../examples.html#autotoc_md264',1,'']]],
  ['initial_20condition_39',['Initial Condition',['../examples.html#autotoc_md222',1,'Initial Condition'],['../examples.html#autotoc_md225',1,'Initial Condition'],['../examples.html#autotoc_md249',1,'Initial Condition'],['../examples.html#autotoc_md266',1,'Initial Condition'],['../examples.html#autotoc_md316',1,'Initial Condition'],['../examples.html#autotoc_md346',1,'Initial Condition']]],
  ['initial_20condition_40',['Initial condition',['../examples.html#autotoc_md231',1,'']]],
  ['initial_20condition_20and_20result_41',['Initial Condition and Result',['../examples.html#autotoc_md334',1,'']]],
  ['initial_20condition_20constraints_42',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md498',1,'']]],
  ['initial_20conditions_43',['Mixing-layer initial conditions',['../thermochemistry.html#autotoc_md589',1,'']]],
  ['initial_20state_44',['Initial State',['../examples.html#autotoc_md252',1,'Initial State'],['../examples.html#autotoc_md261',1,'Initial State'],['../examples.html#autotoc_md336',1,'Initial State']]],
  ['initial_20states_20inside_20a_20state_20dependent_20equation_20of_20state_45',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md495',1,'']]],
  ['inlining_46',['Module boundaries and NVHPC inlining',['../gpuParallelization.html#autotoc_md401',1,'']]],
  ['input_20parameters_47',['Non-Dimensionalization of Input Parameters',['../equations.html#sec-nondim-inputs',1,'']]],
  ['inside_20a_20state_20dependent_20equation_20of_20state_48',['Initial States Inside a State-Dependent Equation of State',['../physics_constraints.html#autotoc_md495',1,'']]],
  ['inside_20fortran_20block_20constructs_20are_20silently_20dropped_49',['Target regions inside Fortran BLOCK constructs are silently dropped',['../gpuParallelization.html#autotoc_md415',1,'']]],
  ['instability_202d_50',['Instability 2D',['../examples.html#autotoc_md251',1,'Kelvin-Helmholtz Instability (2D)'],['../examples.html#autotoc_md329',1,'Rayleigh-Taylor Instability (2D)'],['../examples.html#autotoc_md335',1,'Richtmyer-Meshkov Instability (2D)']]],
  ['instability_203d_51',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md280',1,'']]],
  ['instability_20worked_20around_20in_20the_20build_52',['Whole-image device codegen instability (worked around in the build)',['../gpuParallelization.html#autotoc_md414',1,'']]],
  ['install_20via_20homebrew_20macos_53',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md374',1,'']]],
  ['integration_54',['15.3 Time Integration',['../equations.html#autotoc_md203',1,'']]],
  ['interaction_55',['7. Fluid-Structure Interaction',['../equations.html#autotoc_md171',1,'']]],
  ['interactive_20execution_56',['Interactive Execution',['../running.html#autotoc_md563',1,'']]],
  ['interactive_20mode_57',['Interactive mode',['../visualization.html#autotoc_md657',1,'']]],
  ['interactive_20shell_58',['Interactive Shell',['../docker.html#autotoc_md133',1,'']]],
  ['intermediate_20examples_59',['🟡 Intermediate Examples',['../case_constraints.html#autotoc_md44',1,'']]],
  ['is_20not_20available_20here_60',['Why a zero-reference check is not available here',['../examples.html#autotoc_md242',1,'']]],
  ['is_20not_20only_20this_20case_61',['It is not only this case',['../examples.html#autotoc_md341',1,'']]],
  ['is_20required_20to_20read_20silo_20hdf5_20files_62',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md643',1,'']]],
  ['isentropic_20vortex_20problem_202d_63',['Isentropic vortex problem (2D)',['../examples.html#autotoc_md295',1,'']]],
  ['isolating_20issues_64',['Isolating Issues',['../troubleshooting.html#autotoc_md606',1,'']]],
  ['issue_201849_65',['Immersed-boundary force on a thin plate (issue #1849)',['../examples.html#autotoc_md239',1,'']]],
  ['issues_66',['Issues',['../gpuParallelization.html#autotoc_md413',1,'AMD flang (amdflang) Known Issues'],['../troubleshooting.html#autotoc_md606',1,'Isolating Issues'],['../troubleshooting.html#autotoc_md640',1,'Visualization Issues']]],
  ['it_67',['it',['../examples.html#autotoc_md319',1,'Running it'],['../examples.html#autotoc_md340',1,'Running it']]],
  ['it_20is_20not_20only_20this_20case_68',['It is not only this case',['../examples.html#autotoc_md341',1,'']]],
  ['it_20matters_20beyond_20tidiness_69',['Why it matters beyond tidiness',['../examples.html#autotoc_md271',1,'']]],
  ['iterative_20generalized_20riemann_20igr_70',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md531',1,'']]]
];
