var searchData=
[
  ['t_20targets_0',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['tag_20details_1',['Tag Details',['../docker.html#autotoc_md136',1,'']]],
  ['tag_20structure_2',['Tag Structure',['../docker.html#autotoc_md138',1,'']]],
  ['tags_3',['Example Tags',['../docker.html#autotoc_md139',1,'']]],
  ['target_20selection_20t_20targets_4',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['targets_5',['Target Selection (&lt;span class=&quot;tt&quot;&gt;-t, --targets&lt;/span&gt;)',['../cli-reference.html#autotoc_md80',1,'']]],
  ['taylor_20green_20vortex_203d_6',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md283',1,'']]],
  ['taylor_20instability_202d_7',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md292',1,'']]],
  ['taylor_20instability_203d_8',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md222',1,'']]],
  ['templates_9',['Computer Templates',['../running.html#autotoc_md532',1,'']]],
  ['tension_10',['Surface Tension',['../physics_constraints.html#autotoc_md482',1,'']]],
  ['tension_20surface_5ftension_20true_20schmidmayer17_20wilfong26_20sec_204_201_208_11',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['tensor_20viscous_20true_12',['4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)',['../equations.html#autotoc_md155',1,'']]],
  ['term_20implementation_13',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['terminal_20ui_20tui_14',['Terminal UI (TUI)',['../visualization.html#autotoc_md608',1,'']]],
  ['test_15',['test',['../examples.html#autotoc_md243',1,'Scaling and Performance test'],['../cli-reference.html#test',1,'test']]],
  ['test_202d_16',['2D Riemann Test (2D)',['../examples.html#autotoc_md278',1,'']]],
  ['test_20case_17',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['test_20debugging_18',['Test Debugging',['../troubleshooting.html#autotoc_md565',1,'']]],
  ['test_20execution_19',['Serial Test Execution',['../troubleshooting.html#autotoc_md567',1,'']]],
  ['test_20fails_20',['Test Fails?',['../troubleshooting.html#autotoc_md550',1,'']]],
  ['test_20failures_21',['Understanding Test Failures',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['test_20matrix_22',['Build and Test Matrix',['../contributing.html#autotoc_md121',1,'']]],
  ['test_20output_20location_23',['Test Output Location',['../troubleshooting.html#autotoc_md568',1,'']]],
  ['test_20suite_24',['Running the Test Suite',['../getting-started.html#autotoc_md340',1,'']]],
  ['testing_25',['Testing',['../testing.html',1,'Testing'],['../contributing.html#autotoc_md118',1,'Testing'],['../testing.html#autotoc_md538',1,'Testing']]],
  ['testing_20post_20process_26',['Testing Post Process',['../testing.html#autotoc_md540',1,'']]],
  ['tests_27',['Tests',['../testing.html#autotoc_md539',1,'Creating Tests'],['../troubleshooting.html#autotoc_md566',1,'Running Specific Tests']]],
  ['the_20build_20fits_20together_28',['How the Build Fits Together',['../contributing.html#autotoc_md91',1,'']]],
  ['the_20homebrew_20package_20macos_29',['Using the Homebrew package (macOS)',['../running.html#autotoc_md514',1,'']]],
  ['the_20precision_20system_30',['Working with the Precision System',['../contributing.html#autotoc_md113',1,'']]],
  ['the_20script_31',['Step 2: Customizing the script',['../visualization.html#autotoc_md619',1,'']]],
  ['the_20simulation_20loop_32',['The Simulation Loop',['../architecture.html#autotoc_md3',1,'']]],
  ['the_20test_20suite_33',['Running the Test Suite',['../getting-started.html#autotoc_md340',1,'']]],
  ['theory_34',['Theory',['../examples.html#autotoc_md223',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md293',1,'Final Condition and Linear Theory']]],
  ['thermal_20model_20polytropic_20false_20preston07_35',['6.1.5 Non-Polytropic Thermal Model (&lt;span class=&quot;tt&quot;&gt;polytropic = .false.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_preston07&quot;&gt;[41]&lt;/a&gt;)',['../equations.html#autotoc_md165',1,'']]],
  ['thermodynamic_20constraints_36',['Thermodynamic Constraints',['../physics_constraints.html#autotoc_md452',1,'']]],
  ['thickening_20poiseuille_20channel_37',['2D Power-Law (Shear-Thickening) Poiseuille Channel',['../examples.html#autotoc_md308',1,'']]],
  ['thinning_20lid_20driven_20cavity_38',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md267',1,'']]],
  ['thinning_20poiseuille_20channel_39',['2D Power-Law (Shear-Thinning) Poiseuille Channel',['../examples.html#autotoc_md227',1,'']]],
  ['thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_40',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[52]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[53]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md209',1,'']]],
  ['thompson90_20bc_5fx_20beg_205_20to_2012_41',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[52]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[53]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md209',1,'']]],
  ['three_20phase_20pipeline_42',['Three Phase Pipeline',['../architecture.html#autotoc_md0',1,'Three-Phase Pipeline'],['../contributing.html#autotoc_md87',1,'Three-Phase Pipeline']]],
  ['tiled_201d_20rendering_43',['Tiled 1D rendering',['../visualization.html#autotoc_md606',1,'']]],
  ['time_44',['Numerical Schlieren at Final Time',['../examples.html#autotoc_md286',1,'']]],
  ['time_20integration_45',['15.3 Time Integration',['../equations.html#autotoc_md200',1,'']]],
  ['time_20performance_46',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md324',1,'']]],
  ['time_20stepping_47',['Time Stepping',['../case.html#autotoc_md27',1,'Adaptive Time-Stepping'],['../case.html#autotoc_md26',1,'Constant Time-Stepping'],['../physics_constraints.html#autotoc_md492',1,'Time Stepping']]],
  ['time_20stepping_20adap_5fdt_20true_48',['Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)',['../equations.html#autotoc_md202',1,'']]],
  ['time_5fstepper_201_202_203_20gottlieb98_49',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md201',1,'']]],
  ['timestep_20selection_50',['Timestep selection',['../visualization.html#autotoc_md602',1,'']]],
  ['tips_20for_20gpus_51',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md364',1,'']]],
  ['titarev_20toro_20problem_201d_52',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md224',1,'']]],
  ['to_2012_53',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[52]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[53]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md209',1,'']]],
  ['to_20add_20a_20new_20simulation_20parameter_54',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md108',1,'']]],
  ['to_20add_20a_20post_20processing_20output_20variable_55',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['to_20add_20a_20test_20case_56',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['to_20allocate_20and_20manage_20gpu_20arrays_57',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md110',1,'']]],
  ['to_20create_20a_20new_20fortran_20module_58',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['to_20document_20physics_20constraints_59',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['to_20extend_20mpi_20halo_20exchange_60',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['to_20guides_61',['How-To Guides',['../contributing.html#autotoc_md107',1,'']]],
  ['to_20mfc_62',['Contributing to MFC',['../contributing.html#autotoc_md84',1,'']]],
  ['to_20read_20silo_20hdf5_20files_63',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md593',1,'']]],
  ['to_20run_64',['to run',['../examples.html#autotoc_md219',1,'How to run'],['../examples.html#autotoc_md230',1,'How to run'],['../examples.html#autotoc_md270',1,'How to run'],['../examples.html#autotoc_md275',1,'How to run'],['../examples.html#autotoc_md302',1,'How to run'],['../examples.html#autotoc_md311',1,'How to run']]],
  ['to_20use_20case_20optimization_65',['When to use case optimization',['../expectedPerformance.html#autotoc_md318',1,'']]],
  ['to_20write_20a_20gpu_20parallel_20loop_66',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md109',1,'']]],
  ['together_67',['How the Build Fits Together',['../contributing.html#autotoc_md91',1,'']]],
  ['toolchain_68',['Toolchain',['../contributing.html#autotoc_md90',1,'Build Toolchain'],['../contributing.html#autotoc_md103',1,'Python Toolchain']]],
  ['tools_69',['Tools',['../gpuParallelization.html#autotoc_md367',1,'Cray Compiler Tools'],['../getting-started.html#autotoc_md344',1,'Helpful Tools']]],
  ['tools_70',['tools',['../gpuParallelization.html#autotoc_md365',1,'Compiler agnostic tools'],['../gpuParallelization.html#autotoc_md366',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_71',['Debugging Tools and Tips for GPUs',['../gpuParallelization.html#autotoc_md364',1,'']]],
  ['topics_72',['Advanced Topics',['../index.html#autotoc_md510',1,'']]],
  ['toro_20problem_201d_73',['Titarev-Toro problem (1D)',['../examples.html#autotoc_md224',1,'']]],
  ['toro94_74',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[55]&lt;/a&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['transformed_20gamma_75',['EOS Parameter Sanity (Transformed Gamma)',['../physics_constraints.html#autotoc_md454',1,'']]],
  ['transitional_20state_76',['Liutex visualization at transitional state',['../examples.html#autotoc_md298',1,'']]],
  ['transport_20qbmm_20true_20bryngelson20_77',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['triple_20point_202d_78',['2D Triple Point (2D)',['../examples.html#autotoc_md285',1,'']]],
  ['troubleshooting_20guide_79',['Troubleshooting Guide',['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md541',1,'Troubleshooting Guide']]],
  ['true_80',['true',['../equations.html#autotoc_md187',1,'14. Acoustic Sources (&lt;span class=&quot;tt&quot;&gt;acoustic_source = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md153',1,'3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md155',1,'4. Viscous Stress Tensor (&lt;span class=&quot;tt&quot;&gt;viscous = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md160',1,'6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)'],['../equations.html#autotoc_md202',1,'Adaptive Time Stepping (&lt;span class=&quot;tt&quot;&gt;adap_dt = .true.&lt;/span&gt;)']]],
  ['true_20bryngelson20_81',['6.1.6 QBMM Moment Transport (&lt;span class=&quot;tt&quot;&gt;qbmm = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_bryngelson20&quot;&gt;[7]&lt;/a&gt;)',['../equations.html#autotoc_md166',1,'']]],
  ['true_20maeda18_82',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[31]&lt;/a&gt;)',['../equations.html#autotoc_md167',1,'']]],
  ['true_20rodriguez19_20wilfong26_20sec_204_201_206_83',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]],
  ['true_20schmidmayer17_20wilfong26_20sec_204_201_208_84',['10. Surface Tension (&lt;span class=&quot;tt&quot;&gt;surface_tension = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_schmidmayer17&quot;&gt;[46]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.8)',['../equations.html#autotoc_md177',1,'']]],
  ['true_20tseng03_20mittal05_20wilfong26_20sec_204_201_201_85',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['true_20wilfong25a_86',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[58]&lt;/a&gt;)',['../equations.html#autotoc_md183',1,'']]],
  ['true_20wilfong26_20sec_202_203_87',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]],
  ['true_20wilfong26_20sec_204_201_2010_88',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md181',1,'']]],
  ['true_20wilfong26_20sec_204_201_203_89',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md171',1,'']]],
  ['true_20wilfong26_20sec_204_201_207_90',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['true_20wilfong26_20sec_204_201_209_91',['11.1 Ideal MHD (&lt;span class=&quot;tt&quot;&gt;mhd = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.9)',['../equations.html#autotoc_md180',1,'']]],
  ['tseng03_20mittal05_20wilfong26_20sec_204_201_201_92',['16.3 Immersed Boundary Method (&lt;span class=&quot;tt&quot;&gt;ib = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_tseng03&quot;&gt;[57]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_mittal05&quot;&gt;[36]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.1)',['../equations.html#autotoc_md210',1,'']]],
  ['tube_93',['Tube',['../examples.html#autotoc_md247',1,'1D Multi-Component Inert Shock Tube'],['../examples.html#autotoc_md289',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_202d_94',['Viscous Shock Tube (2D)',['../examples.html#autotoc_md233',1,'']]],
  ['tube_20problem_201d_95',['Lax shock tube problem (1D)',['../examples.html#autotoc_md259',1,'']]],
  ['tui_96',['Terminal UI (TUI)',['../visualization.html#autotoc_md608',1,'']]],
  ['turb_5fpos_97',['turb_pos',['../parameters.html#turb_pos',1,'']]],
  ['turbulence_98',['20. Synthetic Turbulence',['../case.html#autotoc_md37',1,'']]],
  ['turbulent_20mixing_20layer_203d_99',['3D Turbulent Mixing layer (3D)',['../examples.html#autotoc_md297',1,'']]],
  ['tvd_20runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_100',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md201',1,'']]],
  ['two_20different_20viscosity_20parameters_101',['Two Different Viscosity Parameters',['../equations.html#sec-two-viscosities',1,'']]],
  ['type_20meanings_102',['Data Type Meanings',['../gpuParallelization.html#autotoc_md351',1,'']]],
  ['type_20safety_103',['Precision and Type Safety',['../contributing.html#autotoc_md99',1,'']]],
  ['types_104',['Immersed Boundary Patch Types',['../case.html#immersed-boundary-patch-types',1,'']]],
  ['types_105',['Patch types',['../case.html#patch-types',1,'']]]
];
