var searchData=
[
  ['case_0',['Case',['../getting-started.html#autotoc_md346',1,'Creating a New Case'],['../equations.html#sec-bubble-example',1,'Example: Non-Dimensionalizing a Bubble Case'],['../contributing.html#autotoc_md111',1,'How to Add a Test Case'],['../getting-started.html#autotoc_md341',1,'Running an Example Case']]],
  ['case_20creator_20guide_1',['Case Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md42',1,'Case Creator Guide']]],
  ['case_20design_20playbook_2',['🧩 Case Design Playbook',['../case_constraints.html#case-design-playbook',1,'']]],
  ['case_20files_3',['Case Files',['../case.html',1,'Case Files'],['../case.html#autotoc_md15',1,'Case Files']]],
  ['case_20optimization_4',['When to use case optimization',['../expectedPerformance.html#autotoc_md318',1,'']]],
  ['case_20optimization_20recommended_5',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md317',1,'']]],
  ['case_20parameter_20constraint_20violations_6',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['case_20parameters_7',['Case Parameters',['../parameters.html',1,'Case Parameters'],['../parameters.html#autotoc_md376',1,'Case Parameters']]],
  ['case_20validation_8',['Case Validation',['../troubleshooting.html#autotoc_md560',1,'']]],
  ['cases_9',['Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md215',1,'Example Cases'],['../running.html#autotoc_md535',1,'Restarting Cases']]],
  ['cavity_10',['2D Shear-Thinning Lid-Driven Cavity',['../examples.html#autotoc_md267',1,'']]],
  ['cavity_20problem_202d_11',['Lid-Driven Cavity Problem (2D)',['../examples.html#autotoc_md252',1,'']]],
  ['centerline_20velocities_12',['Centerline Velocities',['../examples.html#autotoc_md254',1,'']]],
  ['cfl_20condition_13',['15.4 CFL Condition',['../equations.html#autotoc_md204',1,'']]],
  ['cfl_20dt_202d_14',['2D IBM CFL dt (2D)',['../examples.html#autotoc_md287',1,'']]],
  ['change_15',['Phase Change',['../physics_constraints.html#autotoc_md484',1,'']]],
  ['change_20model_16',['11. Phase Change Model',['../case.html#sec-phase-change',1,'']]],
  ['change_20relax_20true_20wilfong26_20sec_204_201_203_17',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md171',1,'']]],
  ['channel_18',['Channel',['../examples.html#autotoc_md299',1,'2D Bingham (Yield-Stress) Poiseuille Channel'],['../examples.html#autotoc_md272',1,'2D General Herschel-Bulkley Poiseuille Channel'],['../examples.html#autotoc_md216',1,'2D IBM-Walled Power-Law Poiseuille Channel'],['../examples.html#autotoc_md308',1,'2D Power-Law (Shear-Thickening) Poiseuille Channel'],['../examples.html#autotoc_md227',1,'2D Power-Law (Shear-Thinning) Poiseuille Channel']]],
  ['characteristic_20bcs_20thompson87_20thompson90_20bc_5fx_20beg_205_20to_2012_19',['16.2 Characteristic BCs (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson87&quot;&gt;[52]&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_thompson90&quot;&gt;[53]&lt;/a&gt;; &lt;span class=&quot;tt&quot;&gt;bc_x%beg = -5&lt;/span&gt; to &lt;span class=&quot;tt&quot;&gt;-12&lt;/span&gt;)',['../equations.html#autotoc_md209',1,'']]],
  ['characteristic_20boundary_20conditions_20',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md39',1,'']]],
  ['checklist_21',['Performance Checklist',['../expectedPerformance.html#autotoc_md321',1,'']]],
  ['chem_5fparams_22',['chem_params',['../parameters.html#chem_params',1,'']]],
  ['chem_5fwrt_5fy_23',['chem_wrt_Y',['../parameters.html#chem_wrt_Y',1,'']]],
  ['chemistry_24',['17. Chemistry',['../case.html#autotoc_md34',1,'']]],
  ['chemistry_20and_20combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_25',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['chemistry_20chemistry_20true_26',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['chemistry_20specific_20boundary_20conditions_27',['18. Chemistry-Specific Boundary Conditions',['../case.html#autotoc_md35',1,'']]],
  ['chemistry_20true_28',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md153',1,'']]],
  ['chemistry_20true_20wilfong26_20sec_204_201_207_29',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['ci_20commands_30',['CI Commands',['../cli-reference.html#autotoc_md73',1,'']]],
  ['ci_20failures_31',['Common CI Failures',['../contributing.html#autotoc_md122',1,'']]],
  ['ci_20pipeline_32',['CI Pipeline',['../contributing.html#autotoc_md119',1,'']]],
  ['classes_20commander89_20ando11_33',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['clean_34',['clean',['../cli-reference.html#clean',1,'']]],
  ['clean_20rebuild_35',['Clean Rebuild',['../troubleshooting.html#autotoc_md557',1,'']]],
  ['cli_36',['Docker CLI',['../docker.html#autotoc_md129',1,'']]],
  ['cli_20reference_37',['CLI Reference',['../cli-reference.html',1,'CLI Reference'],['../cli-reference.html#autotoc_md47',1,'CLI Reference'],['../parameters.html#autotoc_md449',1,'CLI Reference']]],
  ['clouds_38',['Particle Clouds',['../case.html#autotoc_md25',1,'']]],
  ['clusters_20via_20apptainer_20singularity_39',['Using Supercomputers/Clusters via Apptainer/Singularity',['../docker.html#autotoc_md132',1,'']]],
  ['cmake_20could_20not_20find_20a_20fortran_20compiler_40',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md579',1,'']]],
  ['cmake_20could_20not_20find_20mpi_41',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['code_20architecture_42',['Code Architecture',['../architecture.html',1,'']]],
  ['code_20coverage_43',['Code Coverage',['../troubleshooting.html#autotoc_md555',1,'']]],
  ['code_20review_20and_20merge_44',['Code Review and Merge',['../contributing.html#autotoc_md125',1,'']]],
  ['coded_20patches_45',['Hard Coded Patches',['../case.html#autotoc_md21',1,'']]],
  ['coding_20standards_46',['Coding Standards',['../contributing.html#autotoc_md94',1,'']]],
  ['combustion_47',['Combustion',['../physics_constraints.html#autotoc_md502',1,'']]],
  ['combustion_20chemistry_20true_20wilfong26_20sec_204_201_207_48',['9. Chemistry and Combustion (&lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.1.7)',['../equations.html#autotoc_md175',1,'']]],
  ['command_20line_20arguments_49',['(Optional) Accepting command line arguments',['../case.html#autotoc_md17',1,'']]],
  ['commander89_20ando11_50',['6.1.1 Method of Classes (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_commander89&quot;&gt;[13]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_ando11&quot;&gt;[2]&lt;/a&gt;)',['../equations.html#autotoc_md161',1,'']]],
  ['commands_51',['Commands',['../cli-reference.html#autotoc_md73',1,'CI Commands'],['../cli-reference.html#autotoc_md50',1,'Commands'],['../cli-reference.html#autotoc_md66',1,'Development Commands'],['../cli-reference.html#autotoc_md76',1,'Other Commands'],['../troubleshooting.html#autotoc_md545',1,'Useful Commands'],['../cli-reference.html#autotoc_md56',1,'Utility Commands']]],
  ['commit_20messages_52',['Commit Messages',['../contributing.html#autotoc_md93',1,'']]],
  ['common_53',['Modifying &lt;span class=&quot;tt&quot;&gt;src/common/&lt;/span&gt;',['../contributing.html#autotoc_md116',1,'']]],
  ['common_20build_20errors_54',['Common Build Errors',['../troubleshooting.html#autotoc_md577',1,'']]],
  ['common_20ci_20failures_55',['Common CI Failures',['../contributing.html#autotoc_md122',1,'']]],
  ['common_20configuration_20patterns_56',['🚀 Common Configuration Patterns',['../case_constraints.html#common-configuration-patterns',1,'']]],
  ['common_20material_20values_57',['Common Material Values',['../equations.html#sec-material-values',1,'']]],
  ['common_20options_58',['Common Options',['../cli-reference.html#autotoc_md79',1,'']]],
  ['common_20pitfalls_59',['Common Pitfalls',['../contributing.html#autotoc_md97',1,'']]],
  ['common_20runtime_20errors_60',['Common Runtime Errors',['../troubleshooting.html#autotoc_md584',1,'']]],
  ['compare_61',['packer compare',['../cli-reference.html#autotoc_md61',1,'']]],
  ['compatibility_62',['Compatibility',['../case_constraints.html#feature-compatibility',1,'📊 Feature Compatibility'],['../physics_constraints.html#autotoc_md473',1,'Boundary Condition Compatibility'],['../case.html#autotoc_md19',1,'Feature Compatibility'],['../physics_constraints.html#autotoc_md480',1,'Feature Compatibility']]],
  ['compiler_63',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md579',1,'']]],
  ['compiler_20agnostic_20tools_64',['Compiler agnostic tools',['../gpuParallelization.html#autotoc_md365',1,'']]],
  ['compiler_20documentation_65',['Compiler Documentation',['../gpuParallelization.html#autotoc_md374',1,'']]],
  ['compiler_20options_66',['NVHPC Compiler Options',['../gpuParallelization.html#autotoc_md370',1,'']]],
  ['compiler_20portability_67',['Compiler Portability',['../contributing.html#autotoc_md104',1,'']]],
  ['compiler_20tools_68',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md367',1,'']]],
  ['compilers_69',['Supported Compilers',['../running.html#autotoc_md521',1,'']]],
  ['complete_20option_20reference_70',['Complete option reference',['../visualization.html#autotoc_md611',1,'']]],
  ['completion_71',['Shell Completion',['../getting-started.html#autotoc_md347',1,'']]],
  ['completion_72',['completion',['../cli-reference.html#completion',1,'']]],
  ['component_20inert_20shock_20tube_73',['1D Multi-Component Inert Shock Tube',['../examples.html#autotoc_md247',1,'']]],
  ['component_20reactive_20shock_20tube_74',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md289',1,'']]],
  ['components_20in_20inactive_20dimensions_75',['Velocity Components in Inactive Dimensions',['../physics_constraints.html#autotoc_md467',1,'']]],
  ['comprehensive_20equations_20reference_76',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md141',1,'']]],
  ['computation_20macros_77',['Computation Macros',['../gpuParallelization.html#autotoc_md354',1,'']]],
  ['computational_20domain_78',['2. Computational Domain',['../case.html#sec-computational-domain',1,'']]],
  ['computer_20templates_79',['Computer Templates',['../running.html#autotoc_md532',1,'']]],
  ['condensed_20phase_20reactive_20burn_80',['Condensed-Phase Reactive Burn',['../physics_constraints.html#autotoc_md503',1,'']]],
  ['condition_81',['Condition',['../equations.html#autotoc_md204',1,'15.4 CFL Condition'],['../examples.html#autotoc_md237',1,'Final Condition'],['../examples.html#autotoc_md253',1,'Final Condition'],['../examples.html#autotoc_md256',1,'Final Condition'],['../examples.html#autotoc_md284',1,'Final Condition'],['../examples.html#autotoc_md225',1,'Initial Condition'],['../examples.html#autotoc_md248',1,'Initial Condition'],['../examples.html#autotoc_md260',1,'Initial Condition'],['../examples.html#autotoc_md290',1,'Initial Condition'],['../examples.html#autotoc_md295',1,'Initial Condition'],['../examples.html#autotoc_md306',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_82',['Condition and Linear Theory',['../examples.html#autotoc_md223',1,'Final Condition and Linear Theory'],['../examples.html#autotoc_md293',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_83',['Initial Condition and Result',['../examples.html#autotoc_md258',1,'']]],
  ['condition_20compatibility_84',['Boundary Condition Compatibility',['../physics_constraints.html#autotoc_md473',1,'']]],
  ['condition_20constraints_85',['Patch Initial Condition Constraints',['../physics_constraints.html#autotoc_md455',1,'']]],
  ['condition_20density_86',['Condition Density',['../examples.html#autotoc_md251',1,'Final Condition (Density)'],['../examples.html#autotoc_md266',1,'Final Condition (Density)']]],
  ['condition_20patches_87',['Boundary Condition Patches',['../case.html#boundary-condition-patches',1,'']]],
  ['conditions_88',['Conditions',['../equations.html#autotoc_md207',1,'16. Boundary Conditions'],['../case.html#autotoc_md35',1,'18. Chemistry-Specific Boundary Conditions'],['../architecture.html#autotoc_md8',1,'Boundary Conditions'],['../physics_constraints.html#autotoc_md472',1,'Boundary Conditions'],['../examples.html#autotoc_md279',1,'Density Initial and Final Conditions']]],
  ['conditions_89',['conditions',['../case.html#boundary-conditions',1,'Boundary conditions'],['../case.html#autotoc_md39',1,'Generalized Characteristic Boundary conditions']]],
  ['configuration_20flags_90',['Build Configuration Flags',['../cli-reference.html#autotoc_md81',1,'']]],
  ['configuration_20patterns_91',['🚀 Common Configuration Patterns',['../case_constraints.html#common-configuration-patterns',1,'']]],
  ['conservative_20term_20implementation_92',['Developer Notes on Non-Conservative Term Implementation',['../equations.html#autotoc_md199',1,'']]],
  ['conservative_20variables_20ordering_93',['Conservative Variables Ordering',['../case.html#autotoc_md40',1,'']]],
  ['consistency_94',['Consistency',['../physics_constraints.html#autotoc_md459',1,'Alpha-Rho Consistency'],['../contributing.html#autotoc_md102',1,'Physics and Model Consistency'],['../equations.html#sec-unit-consistency',1,'Unit Consistency'],['../physics_constraints.html#autotoc_md466',1,'Velocity and Dimensional Consistency']]],
  ['constant_20time_20stepping_95',['Constant Time-Stepping',['../case.html#autotoc_md26',1,'']]],
  ['constraint_20violations_96',['&quot;Case parameter constraint violations&quot;',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['constraints_97',['Constraints',['../physics_constraints.html#autotoc_md477',1,'Bubble Simulation Constraints'],['../contributing.html#how-to-document-physics-constraints',1,'How to Document Physics Constraints'],['../physics_constraints.html#autotoc_md457',1,'Mixture Constraints'],['../physics_constraints.html#autotoc_md455',1,'Patch Initial Condition Constraints'],['../physics_constraints.html',1,'Physics Constraints'],['../physics_constraints.html#autotoc_md452',1,'Thermodynamic Constraints']]],
  ['constraints_20reference_98',['Physics Constraints Reference',['../physics_constraints.html#autotoc_md450',1,'']]],
  ['containers_99',['Containers',['../docker.html',1,'Containers'],['../docker.html#autotoc_md126',1,'Containers'],['../docker.html#autotoc_md130',1,'Details on Running Containers'],['../getting-started.html#autotoc_md339',1,'Using Containers']]],
  ['contributing_100',['Contributing',['../contributing.html',1,'']]],
  ['contributing_20to_20mfc_101',['Contributing to MFC',['../contributing.html#autotoc_md84',1,'']]],
  ['control_20macros_102',['Data Control Macros',['../gpuParallelization.html#autotoc_md356',1,'']]],
  ['conventions_103',['Stored Parameter Conventions',['../equations.html#sec-stored-forms',1,'']]],
  ['coordinates_104',['16. Cylindrical Coordinates',['../case.html#autotoc_md33',1,'']]],
  ['coordinates_105',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md614',1,'']]],
  ['coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_106',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]],
  ['core_107',['Solver Core',['../architecture.html#autotoc_md6',1,'']]],
  ['corrections_20wilfong26_20sec_204_202_204_108',['17. Low Mach Number Corrections (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 4.2.4)',['../equations.html#autotoc_md212',1,'']]],
  ['correctness_109',['Correctness',['../contributing.html#autotoc_md101',1,'MPI Correctness'],['../troubleshooting.html#autotoc_md575',1,'Performance vs Correctness']]],
  ['could_20not_20find_20a_20fortran_20compiler_110',['&quot;CMake could not find a Fortran compiler&quot;',['../troubleshooting.html#autotoc_md579',1,'']]],
  ['could_20not_20find_20mpi_111',['&quot;CMake could not find MPI&quot;',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['count_112',['count',['../cli-reference.html#count',1,'']]],
  ['count_5fdiff_113',['count_diff',['../cli-reference.html#count_diff',1,'']]],
  ['coverage_114',['Code Coverage',['../troubleshooting.html#autotoc_md555',1,'']]],
  ['cpu_115',['IBM Power9 CPU',['../expectedPerformance.html#autotoc_md333',1,'']]],
  ['cpu_20historical_116',['IBM Power9 CPU (historical)',['../expectedPerformance.html#autotoc_md328',1,'']]],
  ['cray_20compiler_20tools_117',['Cray Compiler Tools',['../gpuParallelization.html#autotoc_md367',1,'']]],
  ['cray_20general_20options_118',['Cray General Options',['../gpuParallelization.html#autotoc_md368',1,'']]],
  ['cray_20openacc_20options_119',['Cray OpenACC Options',['../gpuParallelization.html#autotoc_md369',1,'']]],
  ['create_20a_20new_20fortran_20module_120',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['creating_20a_20new_20case_121',['Creating a New Case',['../getting-started.html#autotoc_md346',1,'']]],
  ['creating_20tests_122',['Creating Tests',['../testing.html#autotoc_md539',1,'']]],
  ['creator_20guide_123',['Creator Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md42',1,'Case Creator Guide']]],
  ['customizing_20the_20script_124',['Step 2: Customizing the script',['../visualization.html#autotoc_md619',1,'']]],
  ['cyl_5fcoord_20true_20wilfong26_20sec_202_203_125',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]],
  ['cylindrical_20coordinates_126',['16. Cylindrical Coordinates',['../case.html#autotoc_md33',1,'']]],
  ['cylindrical_20coordinates_127',['Visualizing data in cylindrical coordinates',['../visualization.html#autotoc_md614',1,'']]],
  ['cylindrical_20coordinates_20cyl_5fcoord_20true_20wilfong26_20sec_202_203_128',['5. Cylindrical Coordinates (&lt;span class=&quot;tt&quot;&gt;cyl_coord = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[59]&lt;/a&gt; Sec. 2.3)',['../equations.html#autotoc_md157',1,'']]]
];
