var searchData=
[
  ['halo_20exchange_0',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['hangs_1',['MPI errors or hangs',['../troubleshooting.html#autotoc_md506',1,'']]],
  ['hard_20coded_20patches_2',['Hard Coded Patches',['../case.html#autotoc_md7',1,'']]],
  ['hard_20rules_3',['Hard Rules',['../contributing.html#autotoc_md75',1,'']]],
  ['hardcodied_20ic_20example_4',['2D Hardcodied IC Example',['../examples.html#autotoc_md247',1,'']]],
  ['harten83_5',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md176',1,'']]],
  ['helmholtz_20instability_202d_6',['Kelvin-Helmholtz Instability (2D)',['../examples.html#autotoc_md220',1,'']]],
  ['help_7',['Getting Help',['../troubleshooting.html#autotoc_md508',1,'']]],
  ['help_8',['help',['../cli-reference.html#help',1,'']]],
  ['helpful_20tools_9',['Helpful Tools',['../getting-started.html#autotoc_md286',1,'']]],
  ['hll_20riemann_5fsolver_201_20harten83_10',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md176',1,'']]],
  ['hllc_20riemann_5fsolver_202_20toro94_11',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md177',1,'']]],
  ['hlld_20riemann_5fsolver_204_20mhd_20only_12',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md179',1,'']]],
  ['homebrew_20macos_13',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md280',1,'']]],
  ['homebrew_20package_20macos_14',['Using the Homebrew package (macOS)',['../running.html#autotoc_md432',1,'']]],
  ['how_20to_20add_20a_20new_20simulation_20parameter_15',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md88',1,'']]],
  ['how_20to_20add_20a_20post_20processing_20output_20variable_16',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md95',1,'']]],
  ['how_20to_20add_20a_20test_20case_17',['How to Add a Test Case',['../contributing.html#autotoc_md91',1,'']]],
  ['how_20to_20allocate_20and_20manage_20gpu_20arrays_18',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md90',1,'']]],
  ['how_20to_20create_20a_20new_20fortran_20module_19',['How to Create a New Fortran Module',['../contributing.html#autotoc_md92',1,'']]],
  ['how_20to_20document_20physics_20constraints_20',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['how_20to_20extend_20mpi_20halo_20exchange_21',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['how_20to_20guides_22',['How-To Guides',['../contributing.html#autotoc_md87',1,'']]],
  ['how_20to_20write_20a_20gpu_20parallel_20loop_23',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md89',1,'']]],
  ['hpc_24',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md500',1,'']]],
  ['hyperelastic_20model_20hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_25',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['hyperelasticity_20true_20kamrin12_20wilfong26_20sec_204_201_206_26',['7.2 Hyperelastic Model (&lt;span class=&quot;tt&quot;&gt;hyperelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_kamrin12&quot;&gt;[24]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md150',1,'']]],
  ['hypoelastic_20model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_27',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md149',1,'']]],
  ['hypoelasticity_28',['Hypoelasticity',['../physics_constraints.html#autotoc_md408',1,'']]],
  ['hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_29',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md149',1,'']]]
];
