var searchData=
[
  ['h2_20n2_20air_20mc_201_205_0',['3D Temporal Reacting Mixing Layer (H2/N2 - air, Mc = 1.5)',['../examples.html#autotoc_md227',1,'']]],
  ['h5py_20is_20required_20to_20read_20silo_20hdf5_20files_1',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md609',1,'']]],
  ['halo_20exchange_2',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['handling_3',['General Users: Dimensional Handling',['../equations.html#sec-dimensional-handling',1,'']]],
  ['hangs_4',['MPI errors or hangs',['../troubleshooting.html#autotoc_md604',1,'']]],
  ['happens_20at_20each_20stage_5',['What happens at each stage',['../architecture.html#autotoc_md4',1,'']]],
  ['hard_20coded_20patches_6',['Hard Coded Patches',['../case.html#autotoc_md21',1,'']]],
  ['hard_20rules_7',['Hard Rules',['../contributing.html#autotoc_md93',1,'']]],
  ['hardcodied_20ic_20example_8',['2D Hardcodied IC Example',['../examples.html#autotoc_md313',1,'']]],
  ['harten83_9',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[21]&lt;/a&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['has_20artifacts_10',['Visualization looks wrong or has artifacts',['../troubleshooting.html#autotoc_md610',1,'']]],
  ['has_20to_20match_20the_20dimensionality_11',['Boundary-condition patch geometry has to match the dimensionality',['../examples.html#autotoc_md298',1,'']]],
  ['hdf5_20files_12',['&quot;h5py is required to read Silo-HDF5 files&quot;',['../troubleshooting.html#autotoc_md609',1,'']]],
  ['helmholtz_20instability_202d_13',['Kelvin-Helmholtz Instability (2D)',['../examples.html#autotoc_md240',1,'']]],
  ['help_14',['Getting Help',['../troubleshooting.html#autotoc_md612',1,'']]],
  ['helpers_15',['Writing GPU_ROUTINE Device Helpers',['../gpuParallelization.html#autotoc_md371',1,'']]],
  ['helpful_20tools_16',['Helpful Tools',['../getting-started.html#autotoc_md353',1,'']]],
  ['herschel_20bulkley_20poiseuille_20channel_17',['2D General Herschel-Bulkley Poiseuille Channel',['../examples.html#autotoc_md243',1,'']]],
  ['herschel_20bulkley_20viscosity_18',['Herschel Bulkley Viscosity',['../case.html#sec-non-newtonian',1,'19. Non-Newtonian (Herschel-Bulkley) Viscosity'],['../physics_constraints.html#autotoc_md502',1,'Non-Newtonian (Herschel-Bulkley) Viscosity']]],
  ['historical_19',['historical',['../expectedPerformance.html#autotoc_md337',1,'IBM Power9 CPU (historical)'],['../expectedPerformance.html#autotoc_md336',1,'NVIDIA V100 GPU (historical)']]],
  ['history_20',['Immersed-boundary force history',['../case.html#sec-ib-force-history',1,'']]],
  ['hll_20riemann_5fsolver_201_20harten83_21',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[21]&lt;/a&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['hllc_20riemann_5fsolver_202_20toro94_22',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[56]&lt;/a&gt;)',['../equations.html#autotoc_md197',1,'']]],
  ['hlld_20riemann_5fsolver_204_20mhd_20or_20hypoelasticity_23',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md199',1,'']]],
  ['homebrew_20macos_24',['Install via Homebrew (macOS)',['../getting-started.html#autotoc_md345',1,'']]],
  ['homebrew_20package_20macos_25',['Using the Homebrew package (macOS)',['../running.html#autotoc_md530',1,'']]],
  ['how_20the_20build_20fits_20together_26',['How the Build Fits Together',['../contributing.html#autotoc_md89',1,'']]],
  ['how_20to_20add_20a_20new_20simulation_20parameter_27',['How to Add a New Simulation Parameter',['../contributing.html#autotoc_md107',1,'']]],
  ['how_20to_20add_20a_20post_20processing_20output_20variable_28',['How to Add a Post-Processing Output Variable',['../contributing.html#autotoc_md115',1,'']]],
  ['how_20to_20add_20a_20test_20case_29',['How to Add a Test Case',['../contributing.html#autotoc_md111',1,'']]],
  ['how_20to_20add_20an_20equation_20of_20state_30',['How to Add an Equation of State',['../contributing.html#autotoc_md110',1,'']]],
  ['how_20to_20allocate_20and_20manage_20gpu_20arrays_31',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md109',1,'']]],
  ['how_20to_20create_20a_20new_20fortran_20module_32',['How to Create a New Fortran Module',['../contributing.html#autotoc_md112',1,'']]],
  ['how_20to_20document_20physics_20constraints_33',['How to Document Physics Constraints',['../contributing.html#how-to-document-physics-constraints',1,'']]],
  ['how_20to_20extend_20mpi_20halo_20exchange_34',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md114',1,'']]],
  ['how_20to_20guides_35',['How-To Guides',['../contributing.html#autotoc_md106',1,'']]],
  ['how_20to_20run_36',['How to run',['../examples.html#autotoc_md246',1,'How to run'],['../examples.html#autotoc_md262',1,'How to run'],['../examples.html#autotoc_md275',1,'How to run'],['../examples.html#autotoc_md286',1,'How to run'],['../examples.html#autotoc_md292',1,'How to run'],['../examples.html#autotoc_md307',1,'How to run']]],
  ['how_20to_20write_20a_20gpu_20parallel_20loop_37',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md108',1,'']]],
  ['hpc_38',['&quot;Module not found&quot; on HPC',['../troubleshooting.html#autotoc_md598',1,'']]],
  ['hypoelastic_20model_20hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_39',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]],
  ['hypoelasticity_40',['Hypoelasticity',['../physics_constraints.html#autotoc_md498',1,'']]],
  ['hypoelasticity_41',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD or hypoelasticity)',['../equations.html#autotoc_md199',1,'']]],
  ['hypoelasticity_20true_20rodriguez19_20wilfong26_20sec_204_201_206_42',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[42]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[60]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md170',1,'']]]
];
