var searchData=
[
  ['ranks_0',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md497',1,'']]],
  ['rayleigh_20plesset_20bubble_5fmodel_203_20rayleigh17_20plesset49_1',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['rayleigh_20taylor_20instability_202d_2',['Rayleigh-Taylor Instability (2D)',['../examples.html#autotoc_md262',1,'']]],
  ['rayleigh_20taylor_20instability_203d_3',['Rayleigh-Taylor Instability (3D)',['../examples.html#autotoc_md218',1,'']]],
  ['rayleigh17_20plesset49_4',['6.1.2 Rayleigh-Plesset (&lt;span class=&quot;tt&quot;&gt;bubble_model = 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rayleigh17&quot;&gt;[28]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_plesset49&quot;&gt;[37]&lt;/a&gt;)',['../equations.html#autotoc_md156',1,'']]],
  ['reactive_20shock_20tube_5',['1D Multi-Component Reactive Shock Tube',['../examples.html#autotoc_md230',1,'']]],
  ['reactor_6',['Perfectly Stirred Reactor',['../examples.html#autotoc_md237',1,'']]],
  ['rebuild_7',['Clean Rebuild',['../troubleshooting.html#autotoc_md491',1,'']]],
  ['recommended_8',['Case Optimization (Recommended)',['../expectedPerformance.html#autotoc_md276',1,'']]],
  ['reconstruction_9',['Reconstruction',['../equations.html#autotoc_md186',1,'15.1 Spatial Reconstruction'],['../equations.html#autotoc_md189',1,'IGR Reconstruction'],['../physics_constraints.html#autotoc_md431',1,'MUSCL Reconstruction'],['../physics_constraints.html#autotoc_md430',1,'WENO Reconstruction']]],
  ['reference_10',['Reference',['../case_constraints.html#quick-parameter-reference',1,'📖 Quick Parameter Reference'],['../cli-reference.html',1,'CLI Reference'],['../cli-reference.html#autotoc_md43',1,'CLI Reference'],['../parameters.html#autotoc_md390',1,'CLI Reference'],['../equations.html#autotoc_md135',1,'MFC: Comprehensive Equations Reference'],['../physics_constraints.html#autotoc_md391',1,'Physics Constraints Reference'],['../cli-reference.html#autotoc_md45',1,'Quick Reference'],['../troubleshooting.html#autotoc_md476',1,'Quick Reference'],['../index.html#autotoc_md442',1,'Reference']]],
  ['reference_20scales_11',['Reference Scales',['../equations.html#sec-reference-scales',1,'']]],
  ['regenerating_20golden_20files_12',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md503',1,'']]],
  ['regularization_20igr_20true_20wilfong25a_13',['12. Information Geometric Regularization (&lt;span class=&quot;tt&quot;&gt;igr = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong25a&quot;&gt;[53]&lt;/a&gt;)',['../equations.html#autotoc_md179',1,'']]],
  ['relativistic_20mhd_20relativity_20true_20wilfong26_20sec_204_201_2010_14',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md177',1,'']]],
  ['relativity_20true_20wilfong26_20sec_204_201_2010_15',['11.2 Relativistic MHD (&lt;span class=&quot;tt&quot;&gt;relativity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.10)',['../equations.html#autotoc_md177',1,'']]],
  ['relax_20true_20wilfong26_20sec_204_201_203_16',['8. Phase Change (&lt;span class=&quot;tt&quot;&gt;relax = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.3)',['../equations.html#autotoc_md167',1,'']]],
  ['relax_5fmodel_205_20saurel08_17',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['relax_5fmodel_206_20zein10_18',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[55]&lt;/a&gt;)',['../equations.html#autotoc_md169',1,'']]],
  ['relaxation_20relax_5fmodel_205_20saurel08_19',['8.1 pT-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 5&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_saurel08&quot;&gt;[40]&lt;/a&gt;)',['../equations.html#autotoc_md168',1,'']]],
  ['relaxation_20relax_5fmodel_206_20zein10_20',['8.2 pTg-Relaxation (&lt;span class=&quot;tt&quot;&gt;relax_model = 6&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_zein10&quot;&gt;[55]&lt;/a&gt;)',['../equations.html#autotoc_md169',1,'']]],
  ['remote_20visualization_20on_20pace_20phoenix_21',['Remote Visualization on PACE Phoenix',['../visualization.html#autotoc_md530',1,'']]],
  ['request_22',['Submitting a Pull Request',['../contributing.html#autotoc_md118',1,'']]],
  ['restarting_20cases_23',['Restarting Cases',['../running.html#autotoc_md469',1,'']]],
  ['result_24',['Result',['../examples.html#autotoc_md254',1,'Initial Condition and Result'],['../examples.html#autotoc_md213',1,'Result'],['../examples.html#autotoc_md221',1,'Result'],['../examples.html#autotoc_md224',1,'Result'],['../examples.html#autotoc_md252',1,'Result'],['../examples.html#autotoc_md259',1,'Result']]],
  ['results_25',['Results',['../expectedPerformance.html#autotoc_md282',1,'Benchmark Results'],['../examples.html#autotoc_md232',1,'Results'],['../examples.html#autotoc_md270',1,'Results']]],
  ['review_20and_20merge_26',['Code Review and Merge',['../contributing.html#autotoc_md119',1,'']]],
  ['rho_20consistency_27',['Alpha-Rho Consistency',['../physics_constraints.html#autotoc_md400',1,'']]],
  ['richtmyer_20meshkov_20instability_202d_28',['Richtmyer-Meshkov Instability (2D)',['../examples.html#autotoc_md241',1,'']]],
  ['riemann_20igr_29',['Iterative Generalized Riemann (IGR)',['../physics_constraints.html#autotoc_md427',1,'']]],
  ['riemann_20solvers_30',['Riemann Solvers',['../case_constraints.html#riemann-solvers',1,'⚙️ Riemann Solvers'],['../equations.html#autotoc_md190',1,'15.2 Riemann Solvers']]],
  ['riemann_20test_202d_31',['2D Riemann Test (2D)',['../examples.html#autotoc_md235',1,'']]],
  ['riemann_5fsolver_201_20harten83_32',['HLL (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 1&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_harten83&quot;&gt;[20]&lt;/a&gt;)',['../equations.html#autotoc_md191',1,'']]],
  ['riemann_5fsolver_202_20toro94_33',['HLLC (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 2&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_toro94&quot;&gt;[50]&lt;/a&gt;)',['../equations.html#autotoc_md192',1,'']]],
  ['riemann_5fsolver_203_34',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md193',1,'']]],
  ['riemann_5fsolver_204_20mhd_20only_35',['HLLD (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 4&lt;/span&gt;, MHD only)',['../equations.html#autotoc_md194',1,'']]],
  ['rodriguez19_20wilfong26_20sec_204_201_206_36',['7.1 Hypoelastic Model (&lt;span class=&quot;tt&quot;&gt;hypoelasticity = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_rodriguez19&quot;&gt;[39]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 4.1.6)',['../equations.html#autotoc_md164',1,'']]],
  ['rules_37',['Hard Rules',['../contributing.html#autotoc_md89',1,'']]],
  ['run_38',['run',['../cli-reference.html#run',1,'']]],
  ['run_20fails_39',['Run Fails?',['../troubleshooting.html#autotoc_md483',1,'']]],
  ['runge_20kutta_20time_5fstepper_201_202_203_20gottlieb98_40',['TVD Runge-Kutta (&lt;span class=&quot;tt&quot;&gt;time_stepper = 1, 2, 3&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_gottlieb98&quot;&gt;[18]&lt;/a&gt;)',['../equations.html#autotoc_md196',1,'']]],
  ['running_41',['Running',['../running.html',1,'Running'],['../running.html#autotoc_md447',1,'Running']]],
  ['running_20an_20example_20case_42',['Running an Example Case',['../getting-started.html#autotoc_md300',1,'']]],
  ['running_20containers_43',['Details on Running Containers',['../docker.html#autotoc_md124',1,'']]],
  ['running_20on_20gpus_44',['Running on GPUs',['../running.html#autotoc_md452',1,'Running on GPUs'],['../running.html#autotoc_md454',1,'Running on GPUs']]],
  ['running_20pace_20paraview_20server_45',['Step 3: Running pace-paraview-server',['../visualization.html#autotoc_md533',1,'']]],
  ['running_20specific_20tests_46',['Running Specific Tests',['../troubleshooting.html#autotoc_md500',1,'']]],
  ['running_20the_20test_20suite_47',['Running the Test Suite',['../getting-started.html#autotoc_md299',1,'']]],
  ['running_20with_20fewer_20ranks_48',['Running with Fewer Ranks',['../troubleshooting.html#autotoc_md497',1,'']]],
  ['runs_49',['Runs',['../running.html#autotoc_md471',1,'Example Runs'],['../troubleshooting.html#autotoc_md495',1,'Verbose Runs']]],
  ['runs_20first_20blocks_20all_20other_20jobs_50',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md114',1,'']]],
  ['runtime_51',['1. Runtime',['../case.html#sec-runtime',1,'']]],
  ['runtime_20debugging_52',['Runtime Debugging',['../troubleshooting.html#autotoc_md493',1,'']]],
  ['runtime_20errors_53',['Common Runtime Errors',['../troubleshooting.html#autotoc_md518',1,'']]]
];
