var searchData=
[
  ['gas_20jet_202d_0',['Gas Jet (2D)',['../examples.html#autotoc_md184',1,'']]],
  ['gate_20runs_20first_20blocks_20all_20other_20jobs_1',['Lint Gate (runs first, blocks all other jobs)',['../contributing.html#autotoc_md145',1,'']]],
  ['general_2',['general',['../parameters.html#autotoc_md375',1,'']]],
  ['general_20options_3',['General Options',['../gpuParallelization.html#autotoc_md279',1,'Cray General Options'],['../gpuParallelization.html#autotoc_md282',1,'NVHPC General Options']]],
  ['generalized_20characteristic_20boundary_20conditions_4',['Generalized Characteristic Boundary conditions',['../case.html#autotoc_md34',1,'']]],
  ['generate_5',['generate',['../cli-reference.html#autotoc_md82',1,'']]],
  ['geometry_6',['Geometry',['../case_constraints.html#autotoc_md49',1,'']]],
  ['getting_20help_7',['Getting Help',['../troubleshooting.html#autotoc_md462',1,'']]],
  ['getting_20set_20up_8',['Getting Set Up',['../contributing.html#autotoc_md111',1,'']]],
  ['getting_20started_9',['Getting Started',['../getting-started.html',1,'Getting Started'],['../getting-started.html#autotoc_md249',1,'Getting Started'],['../index.html#autotoc_md378',1,'Getting Started']]],
  ['golden_20files_10',['Regenerating Golden Files',['../troubleshooting.html#autotoc_md441',1,'']]],
  ['gpu_11',['GPU',['../expectedPerformance.html#autotoc_md241',1,'AMD MI250X GPU'],['../contributing.html#autotoc_md131',1,'Fypp and GPU'],['../expectedPerformance.html#autotoc_md242',1,'NVIDIA V100 GPU'],['../expectedPerformance.html#autotoc_md245',1,'NVIDIA V100 GPU']]],
  ['gpu_20arrays_12',['How to Allocate and Manage GPU Arrays',['../contributing.html#autotoc_md135',1,'']]],
  ['gpu_20detection_13',['Verifying GPU Detection',['../running.html#autotoc_md395',1,'']]],
  ['gpu_20not_20detected_14',['GPU not detected',['../troubleshooting.html#autotoc_md459',1,'']]],
  ['gpu_20openacc_20errors_15',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md453',1,'']]],
  ['gpu_20parallel_20loop_16',['How to Write a GPU Parallel Loop',['../contributing.html#autotoc_md134',1,'']]],
  ['gpu_20parallelization_17',['GPU Parallelization',['../gpuParallelization.html',1,'GPU Parallelization'],['../gpuParallelization.html#autotoc_md261',1,'GPU Parallelization']]],
  ['gpu_20profiling_18',['GPU Profiling',['../troubleshooting.html#autotoc_md446',1,'AMD GPU Profiling'],['../running.html#autotoc_md396',1,'GPU Profiling'],['../troubleshooting.html#autotoc_md445',1,'NVIDIA GPU Profiling']]],
  ['gpu_20support_19',['Building with GPU Support',['../running.html#autotoc_md391',1,'']]],
  ['gpus_20',['GPUs',['../running.html#autotoc_md398',1,'AMD GPUs'],['../gpuParallelization.html#autotoc_md275',1,'Debugging Tools and Tips for GPUs'],['../running.html#autotoc_md397',1,'NVIDIA GPUs'],['../running.html#autotoc_md390',1,'Running on GPUs'],['../running.html#autotoc_md392',1,'Running on GPUs']]],
  ['green_20vortex_203d_21',['Taylor-Green Vortex (3D)',['../examples.html#autotoc_md216',1,'']]],
  ['grid_20bubble_20models_22',['9. Sub-grid Bubble Models',['../case.html#autotoc_md21',1,'']]],
  ['grid_20points_23',['Grid Points',['../expectedPerformance.html#autotoc_md246',1,'16M Grid Points'],['../expectedPerformance.html#autotoc_md247',1,'64M Grid Points']]],
  ['grind_20time_20performance_24',['Figure of merit: Grind time performance',['../expectedPerformance.html#autotoc_md239',1,'']]],
  ['gui_25',['Docker Desktop GUI',['../docker.html#autotoc_md153',1,'']]],
  ['guide_26',['Guide',['../case_constraints.html',1,'Case Creator Guide'],['../case_constraints.html#autotoc_md39',1,'Case Creator Guide'],['../troubleshooting.html',1,'Troubleshooting Guide'],['../troubleshooting.html#autotoc_md413',1,'Troubleshooting Guide']]],
  ['guidelines_27',['Soft Guidelines',['../contributing.html#autotoc_md121',1,'']]],
  ['guides_28',['How-To Guides',['../contributing.html#autotoc_md132',1,'']]]
];
