var searchData=
[
  ['elasticity_0',['15. Elasticity',['../case.html#autotoc_md17',1,'']]],
  ['elliptic_20smoothing_1',['Elliptic Smoothing',['../case.html#autotoc_md9',1,'']]],
  ['ensemble_20averaged_20bubble_20model_2',['9.1 Ensemble-Averaged Bubble Model',['../case.html#autotoc_md13',1,'']]],
  ['enumerations_3',['Enumerations',['../case.html#autotoc_md20',1,'']]],
  ['environment_4',['Environment',['../getting-started.html#autotoc_md281',1,'Build Environment'],['../visualization.html#autotoc_md465',1,'Step 1: Setting up your Environment']]],
  ['environment_20setup_5',['Environment Setup',['../running.html#autotoc_md390',1,'']]],
  ['eos_20chemistry_20chemistry_20true_6',['3.2 Ideal Gas EOS (Chemistry, &lt;span class=&quot;tt&quot;&gt;chemistry = .true.&lt;/span&gt;)',['../equations.html#autotoc_md132',1,'']]],
  ['eos_20menikoff89_20lemetayer04_20wilfong26_20sec_202_202_7',['3.1 Stiffened Gas EOS (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_menikoff89&quot;&gt;[33]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_lemetayer04&quot;&gt;[27]&lt;/a&gt;; &lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_wilfong26&quot;&gt;[54]&lt;/a&gt; Sec. 2.2)',['../equations.html#autotoc_md131',1,'']]],
  ['equation_20model_20model_5feqns_202_8',['2.1 Five-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 2&lt;/span&gt;)',['../equations.html#autotoc_md126',1,'']]],
  ['equation_20model_20model_5feqns_203_9',['2.2 Six-Equation Model (&lt;span class=&quot;tt&quot;&gt;model_eqns = 3&lt;/span&gt;)',['../equations.html#autotoc_md127',1,'']]],
  ['equations_10',['Equations',['../case_constraints.html#model-equations',1,'🔢 Model Equations'],['../equations.html',1,'Equations']]],
  ['equations_20of_20state_11',['3. Equations of State',['../equations.html#autotoc_md130',1,'']]],
  ['equations_20reference_12',['MFC: Comprehensive Equations Reference',['../equations.html#autotoc_md121',1,'']]],
  ['errors_13',['Errors',['../troubleshooting.html#autotoc_md445',1,'Common Build Errors'],['../troubleshooting.html#autotoc_md452',1,'Common Runtime Errors']]],
  ['errors_14',['Build fails with GPU/OpenACC errors',['../troubleshooting.html#autotoc_md449',1,'']]],
  ['errors_20or_20hangs_15',['MPI errors or hangs',['../troubleshooting.html#autotoc_md456',1,'']]],
  ['euler_20bubbles_20bubbles_5feuler_20true_16',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md139',1,'']]],
  ['euler_20euler_20bubbles_20bubbles_5feuler_20true_17',['6.1 Euler-Euler Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_euler = .true.&lt;/span&gt;)',['../equations.html#autotoc_md139',1,'']]],
  ['euler_20lagrange_20bubbles_20bubbles_5flagrange_20true_20maeda18_18',['6.2 Euler-Lagrange Bubbles (&lt;span class=&quot;tt&quot;&gt;bubbles_lagrange = .true.&lt;/span&gt;) (&lt;a class=&quot;el&quot; href=&quot;citelist.html#CITEREF_maeda18&quot;&gt;[30]&lt;/a&gt;)',['../equations.html#autotoc_md146',1,'']]],
  ['evolved_20state_19',['Evolved State',['../examples.html#autotoc_md204',1,'Evolved State'],['../examples.html#autotoc_md222',1,'Evolved State'],['../examples.html#autotoc_md236',1,'Evolved State']]],
  ['exact_20riemann_5fsolver_203_20',['Exact (&lt;span class=&quot;tt&quot;&gt;riemann_solver = 3&lt;/span&gt;)',['../equations.html#autotoc_md178',1,'']]],
  ['example_21',['Example',['../examples.html#autotoc_md247',1,'2D Hardcodied IC Example'],['../examples.html#autotoc_md226',1,'Example']]],
  ['example_20case_22',['Running an Example Case',['../getting-started.html#autotoc_md285',1,'']]],
  ['example_20cases_23',['Example Cases',['../examples.html',1,'Example Cases'],['../examples.html#autotoc_md195',1,'Example Cases']]],
  ['example_20runs_24',['Example Runs',['../running.html#autotoc_md405',1,'']]],
  ['example_20tags_25',['Example Tags',['../docker.html#autotoc_md119',1,'']]],
  ['examples_26',['Examples',['../case_constraints.html#autotoc_md27',1,'🔴 Advanced Examples'],['../case_constraints.html#autotoc_md26',1,'🟡 Intermediate Examples'],['../case_constraints.html#autotoc_md25',1,'🟢 Beginner Examples'],['../running.html#autotoc_md399',1,'Examples']]],
  ['examples_20visualization_27',['Examples &amp;amp; Visualization',['../index.html#autotoc_md377',1,'']]],
  ['exchange_28',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]],
  ['execution_29',['Execution',['../running.html#autotoc_md396',1,'Batch Execution'],['../running.html#autotoc_md384',1,'Interactive Execution'],['../troubleshooting.html#autotoc_md435',1,'Serial Test Execution']]],
  ['extend_20mpi_20halo_20exchange_30',['How to Extend MPI Halo Exchange',['../contributing.html#autotoc_md94',1,'']]]
];
