var annotated_dup =
[
    [ "m_derived_types", "namespacem__derived__types.html", [
      [ "field_position", "structm__derived__types_1_1field__position.html", "structm__derived__types_1_1field__position" ],
      [ "scalar_field", "structm__derived__types_1_1scalar__field.html", "structm__derived__types_1_1scalar__field" ],
      [ "pres_field", "structm__derived__types_1_1pres__field.html", "structm__derived__types_1_1pres__field" ],
      [ "integer_field", "structm__derived__types_1_1integer__field.html", "structm__derived__types_1_1integer__field" ],
      [ "levelset_field", "structm__derived__types_1_1levelset__field.html", "structm__derived__types_1_1levelset__field" ],
      [ "levelset_norm_field", "structm__derived__types_1_1levelset__norm__field.html", "structm__derived__types_1_1levelset__norm__field" ],
      [ "mpi_io_var", "structm__derived__types_1_1mpi__io__var.html", "structm__derived__types_1_1mpi__io__var" ],
      [ "mpi_io_ib_var", "structm__derived__types_1_1mpi__io__ib__var.html", "structm__derived__types_1_1mpi__io__ib__var" ],
      [ "mpi_io_levelset_var", "structm__derived__types_1_1mpi__io__levelset__var.html", "structm__derived__types_1_1mpi__io__levelset__var" ],
      [ "mpi_io_levelset_norm_var", "structm__derived__types_1_1mpi__io__levelset__norm__var.html", "structm__derived__types_1_1mpi__io__levelset__norm__var" ],
      [ "vector_field", "structm__derived__types_1_1vector__field.html", "structm__derived__types_1_1vector__field" ],
      [ "vec3_dt", "structm__derived__types_1_1vec3__dt.html", "structm__derived__types_1_1vec3__dt" ],
      [ "riemann_states", "structm__derived__types_1_1riemann__states.html", "structm__derived__types_1_1riemann__states" ],
      [ "riemann_states_vec3", "structm__derived__types_1_1riemann__states__vec3.html", "structm__derived__types_1_1riemann__states__vec3" ],
      [ "int_bounds_info", "structm__derived__types_1_1int__bounds__info.html", "structm__derived__types_1_1int__bounds__info" ],
      [ "bc_patch_parameters", "structm__derived__types_1_1bc__patch__parameters.html", "structm__derived__types_1_1bc__patch__parameters" ],
      [ "bounds_info", "structm__derived__types_1_1bounds__info.html", "structm__derived__types_1_1bounds__info" ],
      [ "bub_bounds_info", "structm__derived__types_1_1bub__bounds__info.html", "structm__derived__types_1_1bub__bounds__info" ],
      [ "ic_model_parameters", "structm__derived__types_1_1ic__model__parameters.html", "structm__derived__types_1_1ic__model__parameters" ],
      [ "t_triangle", "structm__derived__types_1_1t__triangle.html", "structm__derived__types_1_1t__triangle" ],
      [ "t_ray", "structm__derived__types_1_1t__ray.html", "structm__derived__types_1_1t__ray" ],
      [ "t_bbox", "structm__derived__types_1_1t__bbox.html", "structm__derived__types_1_1t__bbox" ],
      [ "t_model", "structm__derived__types_1_1t__model.html", "structm__derived__types_1_1t__model" ],
      [ "ic_patch_parameters", "structm__derived__types_1_1ic__patch__parameters.html", "structm__derived__types_1_1ic__patch__parameters" ],
      [ "ib_patch_parameters", "structm__derived__types_1_1ib__patch__parameters.html", "structm__derived__types_1_1ib__patch__parameters" ],
      [ "physical_parameters", "structm__derived__types_1_1physical__parameters.html", "structm__derived__types_1_1physical__parameters" ],
      [ "subgrid_bubble_physical_parameters", "structm__derived__types_1_1subgrid__bubble__physical__parameters.html", "structm__derived__types_1_1subgrid__bubble__physical__parameters" ],
      [ "mpi_io_airfoil_ib_var", "structm__derived__types_1_1mpi__io__airfoil__ib__var.html", "structm__derived__types_1_1mpi__io__airfoil__ib__var" ],
      [ "integral_parameters", "structm__derived__types_1_1integral__parameters.html", "structm__derived__types_1_1integral__parameters" ],
      [ "acoustic_parameters", "structm__derived__types_1_1acoustic__parameters.html", "structm__derived__types_1_1acoustic__parameters" ],
      [ "source_spatial_type", "structm__derived__types_1_1source__spatial__type.html", "structm__derived__types_1_1source__spatial__type" ],
      [ "ghost_point", "structm__derived__types_1_1ghost__point.html", "structm__derived__types_1_1ghost__point" ],
      [ "species_parameters", "structm__derived__types_1_1species__parameters.html", "structm__derived__types_1_1species__parameters" ],
      [ "chemistry_parameters", "structm__derived__types_1_1chemistry__parameters.html", "structm__derived__types_1_1chemistry__parameters" ],
      [ "bubbles_lagrange_parameters", "structm__derived__types_1_1bubbles__lagrange__parameters.html", "structm__derived__types_1_1bubbles__lagrange__parameters" ],
      [ "cell_num_bounds", "structm__derived__types_1_1cell__num__bounds.html", "structm__derived__types_1_1cell__num__bounds" ],
      [ "simplex_noise_params", "structm__derived__types_1_1simplex__noise__params.html", "structm__derived__types_1_1simplex__noise__params" ]
    ] ],
    [ "m_nvtx", "namespacem__nvtx.html", [
      [ "nvtxeventattributes", "structm__nvtx_1_1nvtxeventattributes.html", "structm__nvtx_1_1nvtxeventattributes" ],
      [ "nvtxrangepush", "interfacem__nvtx_1_1nvtxrangepush.html", "interfacem__nvtx_1_1nvtxrangepush" ],
      [ "nvtxrangepop", "interfacem__nvtx_1_1nvtxrangepop.html", "interfacem__nvtx_1_1nvtxrangepop" ]
    ] ]
];