var annotated_dup =
[
    [ "m_data_input", "namespacem__data__input.html", [
      [ "s_read_abstract_data_files", "interfacem__data__input_1_1s__read__abstract__data__files.html", "interfacem__data__input_1_1s__read__abstract__data__files" ]
    ] ],
    [ "acoustic_parameters", "structacoustic__parameters.html", "structacoustic__parameters" ],
    [ "bounds_info", "structbounds__info.html", "structbounds__info" ],
    [ "bub_bounds_info", "structbub__bounds__info.html", "structbub__bounds__info" ],
    [ "chemistry_parameters", "structchemistry__parameters.html", "structchemistry__parameters" ],
    [ "field_position", "structfield__position.html", "structfield__position" ],
    [ "ghost_point", "structghost__point.html", "structghost__point" ],
    [ "ib_patch_parameters", "structib__patch__parameters.html", "structib__patch__parameters" ],
    [ "ic_model_parameters", "structic__model__parameters.html", "structic__model__parameters" ],
    [ "ic_patch_parameters", "structic__patch__parameters.html", "structic__patch__parameters" ],
    [ "int_bounds_info", "structint__bounds__info.html", "structint__bounds__info" ],
    [ "integer_field", "structinteger__field.html", "structinteger__field" ],
    [ "integral_parameters", "structintegral__parameters.html", "structintegral__parameters" ],
    [ "levelset_field", "structlevelset__field.html", "structlevelset__field" ],
    [ "levelset_norm_field", "structlevelset__norm__field.html", "structlevelset__norm__field" ],
    [ "mpi_io_airfoil_ib_var", "structmpi__io__airfoil__ib__var.html", "structmpi__io__airfoil__ib__var" ],
    [ "mpi_io_ib_var", "structmpi__io__ib__var.html", "structmpi__io__ib__var" ],
    [ "mpi_io_levelset_norm_var", "structmpi__io__levelset__norm__var.html", "structmpi__io__levelset__norm__var" ],
    [ "mpi_io_levelset_var", "structmpi__io__levelset__var.html", "structmpi__io__levelset__var" ],
    [ "mpi_io_var", "structmpi__io__var.html", "structmpi__io__var" ],
    [ "physical_parameters", "structphysical__parameters.html", "structphysical__parameters" ],
    [ "pres_field", "structpres__field.html", "structpres__field" ],
    [ "probe_parameters", "structprobe__parameters.html", "structprobe__parameters" ],
    [ "scalar_field", "structscalar__field.html", "structscalar__field" ],
    [ "source_spatial_type", "structsource__spatial__type.html", "structsource__spatial__type" ],
    [ "species_parameters", "structspecies__parameters.html", "structspecies__parameters" ],
    [ "t_bbox", "structt__bbox.html", null ],
    [ "t_model", "structt__model.html", "structt__model" ],
    [ "t_ray", "structt__ray.html", null ],
    [ "t_triangle", "structt__triangle.html", "structt__triangle" ],
    [ "vector_field", "structvector__field.html", "structvector__field" ]
];